### ISSUE TITLE
Feedback/enquête tool

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#102]
@maartenfv commented on [Tue Jun 11 2019](https://github.com/teamforus/development/issues/442)

We want to be able to gather feedback after an implementation. We can re-use the enquête tool?

Would like to know the cost to make this a standard part of an implementation.

---

@linda-90 commented on [Tue Jun 11 2019](https://github.com/teamforus/development/issues/442#issuecomment-500857681)

Enquete tool Kindpakket Zuidhorn: https://github.com/teamforus/implementation-westerkwartier/issues/11

"The plan is to send an email to all kindpakket users to ask for a rating of the system. The first email will just ask for feedback by clicking one of three smilies 😄 😐 and 😞. When the user clicks one, the user is sent to a webpage (first rating is already registered) where we ask them to give an extra motivation and/or to answer some (multiple choice) questions."

---

@maxvisser commented on [Tue Jun 11 2019](https://github.com/teamforus/development/issues/442#issuecomment-500858397)

Enquête tool has some limitations as mails need to be configured manually. Users need to be exported and imported manually. To make this more manageable the function of gathering feedback can be relayed to Hotjar or building this tool inside the platform.

Also the way we are sending the mails needs to be refined, we need to add a footer with unsubscibe, not meant for me, why did I get this mail kind of functions. 

---

@TomForus commented on [Thu Jun 13 2019](https://github.com/teamforus/development/issues/442#issuecomment-501672401)

@maxvisser Shall we discuss this tomorrow?

---

@jamalv commented on [Mon Jan 13 2020](https://github.com/teamforus/development/issues/442#issuecomment-573567407)

Should calculate cost. I think this is part of DigiBeter. We should discuss the right way to implement this.

**Comment by maxvisser** [comment]
@GerbenBosschieter and @MichaelForus are working on this (could you write an update or progress?)

**Comment by jamalv** [comment]
superseded by: https://github.com/teamforus/implementation/issues/657
