### ISSUE TITLE
Consistent terminology

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#106]
As a user I would like the same terms to be used everywhere so that I don't get confused and only have to learn one term for each concept.

**Some examples of conflicting terms:**
Voucher, budget, fund, 
Aanbieder, leverancier, 

## Goal
- [ ] Create a glossary of terms in the platform. 
- [ ] Indicate which terms are _not allowed_ to be used instead of the main term
- [ ] Update all the products and designs to reflect these terms and be fully consistent

**Comment by maxvisser** [comment]
Seems like a good idea for these terms. what should be in the IP is also pretty clear. As it is not something thats really critical i will label it with won't have.

**Comment by jamalv** [comment]
superseded by: https://github.com/teamforus/general/issues/313
