### ISSUE TITLE
Voucher list - Hide and reveal vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#108]
We currently implemented a shortcut on the voucher list we hide all expired and used vouchers.

I want the user to be able to hide and reveal voucher instead.

An example of a implemention I like is in Scoupy; When you long press a voucher you get a layer on top of the voucher that shows an eye icon with Hide below it (and cancel) 
When you hide it, it will be added to a section below vouchers where you can view hidden voucher and reveal them again if you want.

 ![](https://i.imgur.com/Mhd3yfP.gif)

**Comment by maxvisser** [comment]
plan:
- add hold to drag and order
- add swipe to archive ( can active voucher be archived? )

add a way to unarchive

**Comment by jknnr** [comment]
this will need backend update, so it remembers if the voucher is in archive or changed position in the list

**Comment by jamalv** [comment]
moved to productboard, due to inactivity: https://app.productboard.com/inbox/notes/17398093
