### ISSUE TITLE
Hide the voucher screen if there are no vouchers

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#111]
## Feature request: hide voucher tab if there's no vouchers:
Many of the users of the me app will be shopkeepers. For them the voucher tab is not interesting at all. (at this point) They will often open the app, the store might have a long cue and be busy. So every second counts. Therefore, for the shopkeepers its nice if they are not "confronted" with an empty and for them useless voucher page. Less is more.

## Specs:
* when user installs the app and has no vouchers, there will be two tabs: scanner and profile
* default tab is the scanner
* the app checks if there are any vouchers, if there **are** it will show the voucher tab from this moment on
    * local storage (user defaults) will be updated so the next time the user opens the app the voucher tab will just be there.

**Comment by maxvisser** [comment]
Gmail just introduced Meet into Gmail app and allows user to manually hide the tab in settings

**Comment by jamalv** [comment]
no longer relevant, we have a great screen for this now 😄
