### ISSUE TITLE
Design E-Mail digest

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#116]
I think there are four digest really needed:

fund requests 
	- Sent to Provider: denying providers, approving providers, approving some products
	- Sent to Sponsor: a new product has been added to the webshop, A provider applied 
    - Both to sponsor and provider: Product feedback from sponsor / provider communication (new product review functionality)

Forus Email user calc 
    - tom currently gets 18 mails

**Comment by maxvisser** [comment]
- [x] see which emails the platform sends
- [x] write texts for email digest
- [x] add to figma
- [ ] designer review

**Comment by danrminds** [comment]
@maxvisser - Are these all the emails we need to send via the digest?

**Comment by maxvisser** [comment]
Hi lets do a short call about this one so I can explain this abit better

**Comment by maxvisser** [comment]
I think there are three digest really needed:

fund requests (denying providers, approving providers)

Product feedback from sponsor / provider communication (new product review functionality)

Forus Email user calc ( tom currently gets 18 mails)

**Comment by maxvisser** [comment]
A good way to do them is with collecting notifications (for example a sponsor flicking switches of approving / denying products); for example you have 20 products and sponsor accepts them seperately 15 out 20. you want to get a digest.

As I wrote the digests in dutch; it would probably help to translate them aswell.

**Comment by maxvisser** [comment]
There are a few key components:
How often does each digest needs to be send?
What does each digest contain
Who is the receiver?
Can we add multiple digest into one mail

**Comment by danrminds** [comment]
Stage 1:
Building notifications on the dashboard (read / unread)

## Sponsor
- A provider applied to your fund (provider name, fund name)
- New product added to your fund (product name, provider name, fund name)
- Provider replied to your review request on a product (provider name, product name)
- Fund is too low 
- Fund got closed / status changed (fund name, old status, new status)

## Provider
- A fund status has changed
- You can sell product and scan voucher for fund X
- You can not anymore sell product for fund X
- You can not anymore scan vouchers for fund X
- A product of yours got approved for a fund
- You run out of stock of a product
- Sales / transactions

## Validator
- You have a new validation request

## Personal ones
- You have been added as an employee (organisation name, role)
- You have been assigned / unassigned a new role (organisation name, role)
- You have been removed as an employee (organisation name)
- A change on a validation/clarification request

## Requester

**Comment by danrminds** [comment]
## Provider

### A fund status has changed
Will remain sent as an individual notification, directly after this happens - to all providers that are part of that fund. 

### Digest 1: Updates on approval on funds 
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=17%3A204

**Comment by danrminds** [comment]
## Sponsor

### Digest 1. 
A provider applied to your fund (provider name, fund name)
New product added to your fund (product name, provider name, fund name)
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=75%3A205

### Digest 2. 
Provider replied to your review request on a product (provider name, product name)
Fund is too low
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=75%3A275

### Fund status changed (fund name, old status, new status)
Will remain sent as an individual notification, directly after this happens

**Comment by danrminds** [comment]
## Validator

### Digest 1: How many validation requests you have
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/Mails?node-id=77%3A121

**Comment by danrminds** [comment]
## Personal

### You have been added as an employee (organisation name, role)
Will remain sent as an individual notification, directly after this happens

**Comment by danrminds** [comment]
@maxvisser Went with Valentin yesterday again through the email design for digest. We did split it up for some roles in couple of emails, for different purposes (approval as provider, product reserved, new message). 

Valentin suggests to make it as a single email, as this is the main idea of a digest. And just stack there anything that is important and happened since the last one, so we don't send 3 emails per day in case he got approved, made sales and got a message.

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/41
