### ISSUE TITLE
Track which employee works for which office: allow filtering transcation on offices

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#118]
## Main asssignee: @

Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes
## Who requested this change?
Requested by Scapino

## Current situation
Currently there is no way for a bigger organization to filter transactions based on offices. 

Bigger organizations want answers to questions like:
- How many € did my office in Zuidhorn make this month?

## Desired situation

Track which employee works for which office, and enable filtering transactions on offices.

## Plan
On adding an employee, organization admin can select an office the employee works for. (only one) This allows the organization admin to see which transaction this employee did in the name of this office by filtering on transactions page.

**Comment by maxvisser** [comment]
as location are linked to offices; this can be needed for SDOA's financial dashboard proposal as well. Linkin employees to offices and retrieving postalcodes of offices so you can filter on offices on financial dashboard

**Comment by jamalv** [comment]
Productboard insight: https://forus.productboard.com/insights/shared-inbox/notes/17375231
