### ISSUE TITLE
CR: Directly pay providers via webshop (koop op afstand)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#120]
# Proposal

# Introduction
Payments via the platform are currently made possible by using the Me app. This method of payment is similar to a cash register at the store.

Multiple providers and stakeholders have expressed the need for this process to be expanded to support multiple payment methods without using the Me app.

# Summary
This proposal discusses how an applicant can place a reservation through the webshop that can be converted  to a transaction after accepting. In addition, we will discuss how the provider receives this and can process the reservation.

**Payment via webshop**

*   Requester uses webshop to select a product
*   Requester chooses budget to do the payment with
*   Provider receives a request to process (accept/reject) the reservation
*   Transaction will be added and kept on hold for 14 days after the provider accepts the reservation.
*   After 14 days the transaction will be paid out \

# Payment initiative from requester (requester perspective)

**User story:** As a requester I would like to do a transaction via the webshop

**Description:** steps below will describe the user flow of a requester that does a reservation by using the webshop. This will replace the current feature of doing reservations. 

The user flow below should support:

*   Funds with budget vouchers
*   Funds with action voucher

**Stappen:**

1. Requester logs in on Webshop
2. Requester chooses a product
3. Requester clicks  **Reserve**

![image](https://user-images.githubusercontent.com/10818702/120481456-6a4ca380-c3b0-11eb-85c3-437693220340.png)

4. Requester gets redirected to page to confirm budget to reserve with an clicks **Choose budget**

![image](https://user-images.githubusercontent.com/10818702/120481533-7cc6dd00-c3b0-11eb-98a0-5850a51af476.png)

5. Requester receives a pop up with information about reservation and clicks **Confirm. **After confirmation the reservation will be sent to the provider for approval.

![image](https://user-images.githubusercontent.com/10818702/120481558-83edeb00-c3b0-11eb-8f1d-63d96c63b497.png)

6. Requester gets redirected to the page with all reservations and their current statuses. 

![image](https://user-images.githubusercontent.com/10818702/120481667-9e27c900-c3b0-11eb-85e6-1589900c9158.png)

**Note:**

*   If provider rejected the reservation we show: **Geweigerd**
*   If provider accepted the reservation and transaction is done we show: **Geaccepteerd**
*   If the reservation is on hold (so not accepted or rejected by the provider) We show: **In afwachting** and a sentence: “_Reservering annuleren_” The requester can cancel the reservation just like the current situation.
*   If the provider accepted the reservation the 14 days period of transaction on hold will start. We show: **Geaccepteerd **and the sentence “_Wilt u annuleren?_”. If the requester clicks this sentence it will show a popup with the information to the contact provider. The transaction can be cancelled by the provider on the dashboard. 

![image](https://user-images.githubusercontent.com/10818702/120481693-a7189a80-c3b0-11eb-924e-75bafb72c7a4.png)

7. If there is no list of reservations, we show an empty block.

![image](https://user-images.githubusercontent.com/10818702/120481708-ac75e500-c3b0-11eb-96cc-6c0f260d699a.png)

8. The reservation can be approved or rejected by the provider. The requester will receive a notification after approval or rejection. 

![image](https://user-images.githubusercontent.com/10818702/120481731-b566b680-c3b0-11eb-848b-12cd906ef63d.png)

# Payment initiative from requester (provider perspective)

**User story:** As a provider I would like to process an incoming reservation of a requester 

**Description:** steps below will describe the user flow of a provider that processes (accept/reject) a reservation sent by a reservation.

**Stappen:**

1. Provider gets a notification / email about a reservation

![image](https://user-images.githubusercontent.com/10818702/120481778-be578800-c3b0-11eb-8f3c-e0f6cd8c08bb.png)

2. Provider opens dashboard and clicks **Reservations**
3. Provider gets a list with all reservations and the statusses 

![image](https://user-images.githubusercontent.com/10818702/120481810-c7e0f000-c3b0-11eb-8d36-8807c7f122f6.png)

4. Provider accepts or rejects the reservation, the payment will follow and will be added to the transaction list.
    - If provider **accepts** the reservation It will show the popup below 

![image](https://user-images.githubusercontent.com/10818702/120481842-d3341b80-c3b0-11eb-9555-3fb9f8ba3c68.png)

4. If provider **Rejects** the reservation it will show the popup below

![image](https://user-images.githubusercontent.com/10818702/120481876-df1fdd80-c3b0-11eb-94b8-eb905e075677.png)

5. If the provider clicks **Accept** the status of the reservation will change and a transaction will be added to the transaction list. The transaction is on hold for 14 days.

![image](https://user-images.githubusercontent.com/10818702/120481924-e941dc00-c3b0-11eb-9b09-bf03ecc2c21b.png)

6. The transaction can be cancelled by the provider within the 14 days period. Provider clicks **Bekijk** to open transaction details and clicks **Betaling annuleren** to do a “refund”. The status of the transaction is also changed in the transaction overview. 

![image](https://user-images.githubusercontent.com/10818702/120481957-f2cb4400-c3b0-11eb-8c12-a8620d16b0c1.png)

7. The provider can also automatically accept reservations by turning on the button below 

![image](https://user-images.githubusercontent.com/10818702/120481992-f8c12500-c3b0-11eb-8cee-fb23fcadac3a.png)

8. The provider has to accept some agreements before this can be done. If this option is turned on all transactions will be directly added and the 14 days period will start. Provider checks the box and clicks **Bevestig** to turn this on.

![image](https://user-images.githubusercontent.com/10818702/120482021-fe1e6f80-c3b0-11eb-8521-5b6f020bc5e7.png)

**Comment by jamalv** [comment]
related: https://github.com/teamforus/general/issues/291

**Comment by maxvisser** [comment]
I think this would be a great first step for implementing this feature #136

**Comment by jamalv** [comment]
Currently too big for internal funding, putting it on hold.

**Comment by maxvisser** [comment]
How I see this working:
User will go to webshop presses button 'Buy' 
Provider will get a new page on their dashboard called 'Order' this lists all order (users who clicked the button buy)
Provider accepts order; which initiates the payment from municipality to provider

**Comment by maxvisser** [comment]
Maarten added a new cr; #669

- Gemeente Westerkwartier

Hi Maarten,
Kan je met Potjeswijzer ook al in webshops betalen? Zo niet, dan lijkt me dat een belangrijke functionaliteit voor de nabije toekomst.
Wat jij?
Groeten,
Erwin

**Comment by jamalv** [comment]
Acties:
- Bespreken met valentin hoe groot het is om initiatie vanuit de inwoner mogelijk te maken @maxvisser 
- Voorstel aanpassen met aanpassing naar pasnummer @GerbenBosschieter 
- Update geven aan maarten van stand van zaken @GerbenBosschieter 
- Offerte opstellen op basis van ureninschatting max, en voorstel gerben @maartenfv 


## Ureninschatting
- Op reserveringen (Nijmegen en Westerkwartier) + betaling initieren op pasnummer - een sprint (~34 storypoints) (must-have)
- Voor groningen reserveringen kunnen doen (reservering systeem reactoren) - een sprint (should-have)

**Comment by jamalv** [comment]
a note from a call with stakeholders: how to deal with identification? "sometimes requesters show their identity cards when redeeming the vouchers" - (how) do we account for this?

**Comment by maxvisser** [comment]
maybe allowing providers to disable reservations?

**Comment by GerbenBosschieter** [comment]
As we discussed earlier. I have split up the Figma proposal the smaller the scope to reservation by requester on webshop and supporting plastic card number.

[- Webshop by requester ](https://www.figma.com/file/ZyMLzODQXm4nNTzqF19lny/Directly-pay%3A-Webshop?node-id=176%3A138)

[- Directly by by provider ](https://www.figma.com/file/tDbMnCbcvU0aiwxmmWvYld/Directly-pay%3A-Provider-by-using-plastic-card?node-id=1%3A1048)

**Comment by GerbenBosschieter** [comment]
Made textual proposal from what we have in Figma.

https://docs.google.com/document/d/117i9W_CyNkRq5FHSIN-h4VAwqRhZlNWo5EFm0Nul1eo/edit#

**Comment by jamalv** [comment]
Launched: https://forus.productboard.com/portal/1-forus-me-roadmap/tabs/381bddc4-3d90-4a9b-b647-ed1fc713db6b/features/6685739/portal/expanded

Currently working on phased rollout
