### ISSUE TITLE
CR: Purchase button on a provider's website

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#121]
Requested by: a sponsor

### Change description
As a provider I would like to integrate funds on Forus as a payment option on my own webshop so that I have a direct integration with the flow on my webshop.

**Comment by maxvisser** [comment]
Seems like a bit overkill for now. Probably first we need to look at a public api and a sdk for it.

**Comment by jamalv** [comment]
created as an insight: https://app.productboard.com/inbox/notes/17412879
