### ISSUE TITLE
Robin Ci: Scope bepalen van Agile SDL

### ISSUE THREAD

**Issue by RobinMeles** [teamforus/general#125]
Het is zaak om te bepalen welke stappen van de Security Development Lifecycle ik meeneem in mijn onderzoek.

**Comment by maxvisser** [comment]
welke SDL had je nu gekozen? ééntje van microsoft toch?

**Comment by maxvisser** [comment]
• Are vulnerabilities reduced to an acceptable level for release?
• How does the security quality of this product compare with
similar software products?
• Are all security test requirements being met?
• What are the major root causes of security issues?
• How numerous are security flaws compared to security bugs?
• Which security activity is most effective in finding vulnerabilities?
• Which team is more productive in fixing security defects
and vulnerabilities?

**Comment by RobinMeles** [comment]
Requirements voor SDL: Agile SDL in Background, dan requirements in requirements.
Kijken naar de gehele pipeline
Wat is automatiseerbaar?
False positives?
Microsoft sdl fuzzing?
Requirement van moet net zo functioneren als: moet duidelijker. Dus wat is functionaliteit.
Dus de focus moet toch meer liggen op de gehele CI pipeline.
Ontwerp: Welke mogelijkheden waren er? Welke oplossingsrichtingen zijn er? Hoe kan ik de requirements vervullen?
Analyse: is de gekozen in ontwerp wel logisch? Is dat mogelijk?
Hoe richt ik CI in? Tooling?

Dus de stappen zijn:
-Vind een passend raamwerk (gedaan: Microsoft Agile SDL)
-Match de SDL met de huidige situatie van Forus (nog niet gedaan)
-Kijk naar het aspect Continuous Integration en kijk wat er te automatiseren valt in de gehele CI pipeline, dus niet -alleen tooling (nog niet gedaan)
-Hieruit komen requirements die gevolgd moeten worden
-Op basis van de requirements een ontwerp maken voor de dingen die verbeterd/geautomatiseerd kunnen worden in de CI pipeline.
