### ISSUE TITLE
Investigate migration to gitlab.

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#13]
## Problem statement:
We are currently using GitHub, which is working very well but is closed source.

## Proposed solution:
Gitlab (community edition) is an open source alternative to GitHub. It seems to offer a wider range of functionality and can be deployed on our own servers (for example at code.forus.io). This topic is meant to investigate the pros and cons of a possible migration.

**Comment by maxvisser** [comment]
Maybe after august

**Comment by jamalv** [comment]
Agreed, can be a very low-key investigation if people are looking for some distraction, will only get focus after august.

**Comment by jamalv** [comment]
I did a gitlab deploy this weekend on a personal server, just to play around and see the features of the free and open source (MIT) community edition: http://149.210.168.104/

**Comment by jamalv** [comment]
there is no desire to switch, microsoft is still doing okay.

**Comment by jamalv** [comment]
(as long as they are keeping windows 10 developers away from github :))
