### ISSUE TITLE
Sponsor only subsidizes a percentage of full product price

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#130]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [x] Finances
- [x] Processes

## Current situation
A sponsor always subsidizes the full amount of a product. Lets say a provider adds an xbox for 5 euro's to the fund. The sponsor will fund the whole 5 euro's.

## Desired situation
Sponsor can set a percentage which it subsidizes. The productvoucher displays which amount the request has still pay himself.

Example: provider adds a xbox 20€ for 25 euro's. the sponsor can set a global percentage 60% discount. The xbox is now 10€ in the webshop and the discount will be 15 euro's (added on top of the discount the provider gave).

## Plan
https://docs.google.com/document/d/1NQbjuKjkA-Zyo7Ww7FuHaG3PDiIt-C_Nj033W_MEQGs/edit?usp=sharing

**Comment by jamalv** [comment]
I'm not sure that I agree with your statement that the sponsor always subsidises the full amount :) When a provider adds a discount they also subsidise, right? But yea, it's a good proposal.

As I understand it it would become possible to make a reservation even if you don't have enough budget, and then the productvoucher shows the amount that still needs to be paid to the provider?

**Comment by maxvisser** [comment]
You are correct. 

It will be a bit difficult UX wise to explain what will be deducted from the voucher, which discounts the provider gives, which discounts the sponsor gives and what the user maybe needs to pay from his pocket.

**Comment by maxvisser** [comment]
I think we need a checkout page which displays: 

Normal price:				 	100 euro
Discount provider %30  			- 30 euro
Discount sponsor %70			- 70 euro
You need to pay					0 euro's

**Comment by maxvisser** [comment]
part of actions; can maybe be closed @jamalv

**Comment by maxvisser** [comment]
Can be reopened when it becomes usefull again.
