### ISSUE TITLE
Potjeswijzer demonstration

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#132]
We have a group of stakeholders (sponsors, validators, requestors, etc) that would like to see how far we are with potjeswijzer and what the platform (Forus and Me) can do. 

Things we would like to show to the stakeholders in the demo:

## Main asssignee: @danrminds 

Task: Prepare the demo for potjeswijzer to enable showing the user stories below. Probably we need to create a seperate branch for this demo. 

## Context/goal: 
As a requester i can click the big start button on the homepage, sign in with DigiD and after logging in i get redirected to the overview of available "potjes"
As a sponsor, validator or provider, i can sign up using the sign up button on this page
As a sponsor; I can create a fund and set criteria and external validators
As a provider I can apply to participate in a fund
As a requester I can apply to a fund and fill the required info
As a validator I can validate the information that the requester provided
  * Dashboard
  * Validate (a) record trough the me app?
As a requestor I receive my voucher and pay with my voucher at a provider

Tasks:

**Comment by maxvisser** [comment]
as there are  two requester signupflows: the one nijmegen uses which has DigiD and one without, which is built from criteria. Its pretty hard to get the whole workflow working without doing some hacky stuff.

https://dev.forus.io/potjeswijzer/#!/
