### ISSUE TITLE
Frontend e2e testen - uitleg

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#134]
Sjoerd laat robin zien hoe hij lokaal e2e testen kan draaien.

**Comment by SjoerdHilhorst** [comment]
Alright ik loop even de stappen door om dit werkende te krijgen, ik ga ervanuit dat je de frontend en backend al draaiende hebt. 

## Database seeden (Alleen als je de tests lokaal wilt draaien, kun je overslaan)

1. open terminal in de backend
2. run 
`php artisan migrate:refresh`
`php artisan db:seed`
`php artisan db:seed --class=LoremDbSeeder`
bij deze laatste stap krijg je een active_account token die je nodig hebt voor een volgende stap

## Frontend testcases pullen
1. open terminal in de frontend
2. run
`git fetch`
`git checkout feature.e2e-testcases`

## Environment 
1. open `src/test/e2e/protractor.env.js`
2. vul `customerURL`, `providerURL`, `validatorURL`, `sponsorURL` in voor de omgeving die je wilt testen ie:
 `customerURL="https://staging.forus.io/requester/"`
 `providerURL="https://staging.forus.io/provider/"`
etc..
OF, voor lokaal testen
 `customerURL="https://lcoalhost:5500"`
 `providerURL="https://localhost:4000"`
etc..


3. active organization kan je op `"1"` zetten
4. voor `active_account` moet je even inloggen op de website van een URL die je hebt opgegeven in stap 2, met een account die al een fonds geconfigureerd heeft, @maxvisser weet jij een email? 
Dan kun je uit local storage in je browser de active_account key halen.
 
OF, als je lokaal draait de active_account gebruiken die je kreeg in stap 2 van Database seeden
5. De rest van de environment kan overgeslagen worden

## Testcases runnen
Er zijn meerdere manieren:
- `gulp protractor`
- `protractor test/e2e/protractor.conf.js`
als je een specifieke suite wilt runnen (requester, provider, validator, sponsor)

- `protractor test/e2e/protractor.conf.js --suite <role>`

**Comment by SjoerdHilhorst** [comment]
Als je ergens vast komt te zitten of testcases failen, laat het weten :100:

**Comment by maartenfv** [comment]
@SjoerdHilhorst Klopt het dat deze geclosed kan worden?

**Comment by SjoerdHilhorst** [comment]
Dat is aan robin denk ik, voor mij wel
