### ISSUE TITLE
CR: Choose organisation page (Currently for Potjeswijzer)

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#135]
### Requested by: @danrminds 
https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG/Potjeswijzer.nl?node-id=42%3A10567&viewport=-527%2C7517%2C0.5

### Change description
as a reviewer, Max would need a design for each of the webshops (not only potjeswijzer) or no pr should be made to develop as it will not be merged until it is finished for all webshops.

We have to decide if we want this page to be part of all webshops, or we make it for our website, and link that page on the rest of the webshops.

**Comment by maxvisser** [comment]
as the strategy is to make one dashboard for all municipalities. I would say enhance the landing pages of the general dashboards with these new pages. For potjeswijzer we could make a custom landing page. (instead of adding it to the webshop)

**Comment by maxvisser** [comment]
https://forus.io/sponsor/
https://forus.io/provider/
https://forus.io/validator/

will get all these new blocks
![image](https://user-images.githubusercontent.com/10818702/78760021-d1272600-7980-11ea-8f18-f8510a6228f9.png)

I would propose to make these landing pages white labeled; no forus logos etc.

**Comment by danrminds** [comment]
So, did we decide anything here on how we do it from here? I will unassign myself for now.

**Comment by maxvisser** [comment]
the page is currently in the codebase but the link on the home page is gone.

**Comment by jamalv** [comment]
My preference would be to make it for the website and link to that page from the webshops. It will be easier to maintain (1 page instead of one for each webshop) and it will also be a nice addition to the website (I think).

This means it will need designs and texts. The main question is if @GerbenBosschieter and @linda-90 think this page could be added to the website: 

https://www.figma.com/file/lGrd2oSiUEZ6aLYF3dirt5/%F0%9F%94%B5Forus.io%3A-Organisation-signup-page?node-id=0%3A1

**Comment by GerbenBosschieter** [comment]
@jamalv we would like to add this page to the website. But the current design doesn't really fit into our current design of the website. So adding the potjeswijzer design to the website is a bit weird

**Comment by GerbenBosschieter** [comment]
@jamalv This will also influence the landingspages of westerkwartier and Nijmegen. Don't like the idea of just changing it to a completely different design for these implementations. They already have a floating validator dashboard.

Before we even continue with this we should have a clear strategy to keep everything aligned for our customers.
Need some planning on how to implement this.

**Example**
Current Nijmegen dashboards:
1.  <img width="1091" alt="Screen Shot 2020-07-06 at 16 30 53" src="https://user-images.githubusercontent.com/38419514/86604881-3d2c2100-bfa6-11ea-8430-860a5967a3df.png">
2. <img width="1437" alt="Screen Shot 2020-07-06 at 16 31 12" src="https://user-images.githubusercontent.com/38419514/86604884-3e5d4e00-bfa6-11ea-91b5-f0a5a865d7fb.png">

**Comment by maxvisser** [comment]
Closed until this becomes relevant again
