### ISSUE TITLE
CR: Show reservations and cancelations on provider dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#136]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Max Visser

### Change description
A provider currently can see how many of his products are reserved but has no way to contact the requester. 

Also we implement cancelations on product voucher pretty hasty. 

I would add a product details page which show the reservations for a specific product and by who (emailadres? or let requester fill in first name, last name at checkout); a way to contact the requester and until the reservation is valid. Product can't be deleted until it does not have any reservations anymore.

**Comment by maxvisser** [comment]
@jamalv what do you think about this issue. I think will be the first step for no pickup location products

**Comment by maxvisser** [comment]
As we already have the product details page on product; I think it would be a small improvement to add reservations (and who reserved your product) maybe even show shared QR-codes here.

**Comment by jamalv** [comment]
How would you show "who" reserved the product? I assume you would show the provider the emailadres of the requester? I'd be interested in looking if we can have a more privacy-friendly way of doing this.

**Comment by maxvisser** [comment]
Yes mean reason to show the reservation is aswell giving a way of contacting the request if we would make it more privacy-friendly; the provider still does not have a way to do so.
