### ISSUE TITLE
CR: Show financial data of declined providers

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#140]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
@jamalv 

### Change description
When I decline a provider in the demo environment, the financial data is removed from the financial overview. I think this is unintended? When a provider is declined, the data should stay available in the financial reports.

**Comment by maxvisser** [comment]
Depends on how you see the financial dashboard (as live data) or a reporting tool.

**Comment by maxvisser** [comment]
Can be planned @danrminds

**Comment by maxvisser** [comment]
Please check if this is still the case @maxvisser

**Comment by maxvisser** [comment]
@MichaelForus Could you help me with checking if this is still the case?

**Comment by MichaelForus** [comment]
@maxvisser I have tested it again. The transactions remain visible on the transactions page. But the provider is no longer visible on the financial page and therefore the statistics and transactions are no longer visible.

**Transacties**
<img width="719" alt="Schermafbeelding 2020-10-30 om 14 51 36" src="https://user-images.githubusercontent.com/66309692/97713202-cf10ea00-1abf-11eb-812f-66140eb0fb53.png">

**Financiën**
<img width="731" alt="Schermafbeelding 2020-10-30 om 14 52 02" src="https://user-images.githubusercontent.com/66309692/97713223-d637f800-1abf-11eb-8062-64bb87b94fd3.png">

**Comment by jamalv** [comment]
@jamalv please check if this is still the case, if so it can be planned

**Comment by jamalv** [comment]
@danrminds I have verified this is still the case. It can be planned.

**Comment by jamalv** [comment]
"As a sponsor I would still like to see the financial data in the financial dashboard"
