### ISSUE TITLE
CR: Add breaks to office details

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#141]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
ANB

### Change description
Added in new signupflow, never implemented on webshop

#### Option one:

![image](https://user-images.githubusercontent.com/10818702/79439674-69eb2080-7fd5-11ea-8206-c2a773fa6d76.png)
Icon + Break in sentence before actual opening time

Pro's:
easily implementable

Cons: 
Design wise not really nice

#### Option two:

![image](https://user-images.githubusercontent.com/10818702/79439813-9141ed80-7fd5-11ea-9ee2-cfc4699e2ff9.png)

Remove breaks from the actual time

Pro's:
Looks like actual openingtimes design wise

Con's:
Need to rewrite how we store openingtimes or make a frontend script to do this (look for dependency angular plugin can also be an option)

**Comment by maxvisser** [comment]
https://www.figma.com/file/LW2UE4w1ZTiizijJYSqcNV/Provider---Office-edit---Openingtimes?node-id=15%3A3419

**Comment by jamalv** [comment]
Discussed this on friday, approved to go with option two

@danrminds could you work with alex to make designs for this to prepare development?

**Comment by danrminds** [comment]
![Screenshot 2020-04-30 at 13 32 10](https://user-images.githubusercontent.com/33207036/80705759-4650cb80-8ae7-11ea-89d9-8b08851d13f8.png)

https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs/library-webshop?node-id=640%3A215

**Comment by danrminds** [comment]
@sashooa 

We need to update also the Provider dashboard page (adding / editing location-office)

Now it is like this:
![Screenshot 2020-05-01 at 17 33 55](https://user-images.githubusercontent.com/33207036/80817685-35c94f80-8bd2-11ea-9a0e-45d026de7c54.png)

So, it does not include any information about pause times. Let's change it based on the example from the signup flows (UX)
![Screenshot 2020-05-01 at 17 35 07](https://user-images.githubusercontent.com/33207036/80817731-48438900-8bd2-11ea-9f45-2374e3ba113c.png)
