### ISSUE TITLE
Financial dashboard: Improving financial reporting

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#142]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

This IP lives in this google doc: https://docs.google.com/document/d/15J9f_fS1_gv8PZM6fRLp1R9i6LLgaaig_MSlzLpjnRg/edit

# [Figma](https://www.figma.com/file/oKXIg1YhjE4HU3kJ4G46pg/%F0%9F%A7%AAFinancial-dashboard-improvements?node-id=1%3A61)

**Comment by maxvisser** [comment]
no access to the gdoc

**Comment by maxvisser** [comment]
This issue is too vague. Could you update it?

**Comment by maartenfv** [comment]
De voorgestelde oplossing van Forus voldoet aan de volgende eisen:
1. Managementinformatie. zoals in het overzicht Bijlage A, wordt getoond in
de beheeromgeving via het nieuw te ontwikkelen dashboard.*
2. Filters worden toegevoegd voor top 10 aanbieders en postcode.
3. Het wordt mogelijk om deze informatie te exporteren vanuit de
beheeromgeving.
4. De medewerkers ontvangen een werkinstructie over de vernieuwde
werking.

**Comment by maxvisser** [comment]
Probleem:
SDOA geeft ons nu alleen een bedrag (een familiebudget).
Bij sdoa melding maken dat wij geen aantal kinderen hebben

**Comment by maartenfv** [comment]
Zie project issue: https://github.com/teamforus/projectmanagement/issues/147

**Comment by maartenfv** [comment]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/d95167d8-bdde-47fd-8a53-65e21e7a2177)

**Comment by linda-90** [comment]
Feedback:

1. Export: Geen tekst maar waardevelden voor Excel
2. Periode: Maand en jaar
3. Transactiekosten: Zegt niks
4. Afronden hele getallen in euro’s op dashboard, in detail in export.

 Wensen: In de toekomst ook kinderen kunnen exporteren

**Comment by maxvisser** [comment]
2. voor bijv kerstpakket markt of ander soort kort lopend fonds zijn de andere wel nodig :)

**Comment by maxvisser** [comment]
@danrminds could you plan in tasks for alex for this sprint?

Feedback:

Export:value fields for data for Excel (example dates should be a date excel regocnizes
Periods: Month and year is useful
Transaction costs: Does not add anything
Round off whole numbers in the euro dashboard, in detail in the export.

request: Be able to export a number of children in the future
