### ISSUE TITLE
CR: As a provider/sponsor I would like to have an option to payout/receive payments in bulk.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#143]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by: 
- One of our providers  (support)
- This feature has been requested before after Christmas market
- Nijmegen (sponsor to decrease costs)

### Change description
- Some provider would like it if they can be paid in bulk. Sometimes they keep separate administration for payment from our platform. Payment at the bulk level reduces the administrative burden. With a feature like this it would be nice to give the provider an option to choose between different periods of the bulk payments.

- This feature can also contribute to the discussion about refunds.

**Comment by maxvisser** [comment]
As this results in changing alot to the Bunq Service it will mean alot heavy testing as it is the core of the application. I rather do it with major refactoring or supporting for example more bank API, a PSD2 api. 

Aswell as there is a big organizational aspect of this as we don't host the money; we need to payout at the end date of the fund which means there should be always enough money on the bunq account to payout.

**Comment by jamalv** [comment]
Probably we also have to think about how to display the pending amount. This might have a relation with this lab issue: https://github.com/teamforus/lab/issues/46 This CR will add a lot of complexity, but the benefits are there.

**Comment by maartenfv** [comment]
#239 This is the same issue but then requested by sponsor role.
