### ISSUE TITLE
A child is born within a funds years span. A sponsor wants to create new voucher for new born for a child poverty related fund.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#145]
**Is your feature request related to a problem? Please describe.**
A child is born within a funds years span. A sponsor wants to create new voucher for new born for a child poverty related fund. The family already has a voucher for 3 children (300 euros per child = 900 euros). Currently assigned a voucher will generate a seperate budget voucher

**Describe the solution you'd like**
Sponsor wants to topup this voucher instead of assigned a seperate voucher to identity.

**Describe alternatives you've considered**
keep two voucher but transaction can be done by voucher token of the first voucher

As a sponsor I would like to top-up an existing voucher while the fund is running.

**Comment by maxvisser** [comment]
I think its best to not mimic data. if this is implemented we should probably link vouchers visually if they are fron the same budget.

**Comment by maxvisser** [comment]
> I would be interested to know how this functionality currently works. Can it be confirmed that a new voucher is generated if you already have a voucher?

Currently it creates a new voucher instead of topping up the old one.

**Comment by jamalv** [comment]
Added to productboard: https://app.productboard.com/inbox/notes/15686613
