### ISSUE TITLE
Groningen test environment

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#146]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
We don't have a way to effectively let the new stakeholders in Groningen "play around" with the platform, and to give feedback in order to achieve the best possible results. 

## Desired situation
By setting up a staging (test) environment, we enable our stakeholders to learn about the platform, and  to give feedback. It will also give context to help us discuss new developments with them.

### Technical
- [x] Create webshop in groningen style https://github.com/teamforus/general/issues/46

### Operational
- [ ] Create accounts 
- [ ] Give explanation / training

**Comment by maxvisser** [comment]
lets do it first on dev. https://github.com/teamforus/implementation/issues/343

**Comment by maxvisser** [comment]
https://dev.forus.io/groningen looks similar to figma; should decide on when to merge the shop and put it on staging for external testing

**Comment by maxvisser** [comment]
@jamalv what do yo expect from me for this IP? maybe lets plan this issue for this week to discuss it.

**Comment by GerbenBosschieter** [comment]
@maxvisser We will have a call thursday with groningen. From what I can see there is only demo content on dev and not on staging. I don't like the idea of giving them acces to dev environment. And staging is currently the same as dev. Can I just continue working on staging?

**Comment by maxvisser** [comment]
yes they can get access to staging. still waiting here on a respons from Jamal; maybe Groningen does not want demo content (basically creating the content themselves?)

**Comment by GerbenBosschieter** [comment]
They can also create demo content their self if there is already demo content

**Comment by maxvisser** [comment]
I think it would be nice for them to upload a csv, go through the signupflow as a provider. Accept provider. See how a product is displayed of that provider on webshop etc.

**Comment by jamalv** [comment]
It's probably best for some demo content to be there; not too much but to just give some context.

**Comment by jamalv** [comment]
This has been implemented
