### ISSUE TITLE
Sprint 2020Q2S3: Nothing goes above Groningen

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#147]
<img src="https://user-images.githubusercontent.com/30194799/79732837-86989880-82f4-11ea-83ca-25770bcfbd6d.png" width="200" >

## Context
This is the first sprint where the focus is mainly on the Groningen implementation! 🥳 Of course a big part of our team lives in Groningen, and therefore this implementation is extra special to us! 😄

We will go live in Groningen on: Juli 1st
All new functionality should be ready: June 1st
New users: ~20k

Quite a lot of new functionality is needed, and of-course the platform to be solid and user friendly. Any issues we have had will have 4 x the impact when add the new users in Groningen. We have little time and a lot to do! Therefore the next period will require the team to get the best out of ourselves. 💪 

## Goal
One of our top priorities is to start sharing our platform with our new stakeholders as soon as possible. This way they will be able to learn about the platform, what are the greatest strengths, and where more development is still needed for the best possible outcome. This way we will be able to work together the most effectively. Groningen already has many years of experience with this program and of course we have the platform and team to take it to the next level 🚀 

We will use both Figma and the staging (test) environment to be able to show how the platform works.

Next, from the tender we know about new functionality that is needed, we will also start with development on that this sprint; focussed on these improvement proposals: #128 and #54

## Milestones

General milestone (Proposals, epics): https://github.com/teamforus/general/milestone/16
Forus milestone (Tasks): https://github.com/teamforus/forus/milestone/70
Me milestone (Tasks): https://github.com/teamforus/me/milestone/33

**Comment by maxvisser** [comment]
There's nothing above Groningen!

**Comment by jamalv** [comment]
for @aghimpu; mobile signupflows and groningen webshop @danrminds could you create the tasks in forus and add them to the milestone?
