### ISSUE TITLE
EPIC: Project-100: IP's

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#148]
## Goal

The goal of this epic is to finish all the improvement proposals for project-100

**Comment by maxvisser** [comment]
an epic of an epic?:P

**Comment by jamalv** [comment]
jup :P i wanted to create an overview of all the IP's we're working on to see their status and if they are complete, as this epic epic is a focus for us now

**Comment by jamalv** [comment]
have now moved to using a project for the overview: https://app.zenhub.com/workspaces/public-5e79d635e969e6cdeeebb411/roadmap
