### ISSUE TITLE
Public membership

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#15]
Hi All,

Just wanted to let you know you have the choice of making your membership to this organisation Public:

<img width="835" alt="screen shot 2018-07-12 at 10 58 01" src="https://user-images.githubusercontent.com/30194799/42623237-a2a6f9c6-85c2-11e8-98ac-e9a2759c9b1e.png">

Simply go to https://github.com/orgs/teamforus/people, look yourself up and put your visibility on public:

<img width="994" alt="screen shot 2018-07-12 at 10 57 16" src="https://user-images.githubusercontent.com/30194799/42623335-e544c1b4-85c2-11e8-9dfe-4fe939cc40b3.png">

p.s. I can only assign 10 people to this issue :(

**Comment by maxvisser** [comment]
Cool feature, made my membership public :+1:

**Comment by sgort** [comment]
Done. Thanks for the reminder. I should have done this from the start

**Comment by jamalv** [comment]
Ah, don't worry, we were all unaware of this :)

**Comment by TomForus** [comment]
Done

**Comment by maartenfv** [comment]
Hurrah! 👍

**Comment by GerbenBosschieter** [comment]
Done

**Comment by jamalv** [comment]
Added this to manual: https://github.com/teamforus/general/blob/develop/manual/public-membership.md
