### ISSUE TITLE
IP: Relationship, partner and children

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#150]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [x] Finances
- [x] Processes

## Current situation
Currently an identity is independant.

## Desired situation
There should be relationships between identities. 

As a sponsor I would like a parent to recieve the voucher for their children. But I want the voucher to be given out only once. Therefore I want the system to check if the other parent has already recieved this voucher.

As a parent I would like to add my children identities to my own identity.

Also, this identity should be able to order and connect a physical card to their voucher using the "old cards" system.

## Plan
Figma: https://www.figma.com/file/rW80bGvSS7TKXovctNjjUQ/Relations?node-id=0%3A1

## Tasks
- [ ] Review [designs in figma](https://www.figma.com/file/rW80bGvSS7TKXovctNjjUQ/Relations?node-id=0%3A1) @danrminds @sashooa
- [ ] Implement :)

**Comment by maxvisser** [comment]
we should investigate why this should happen and if the proposed solution is correct. As it could be that family budgets are sufficient.

**Comment by maxvisser** [comment]
how does work with a family of 5 people who all have a stadjerspas

**Comment by maxvisser** [comment]
_bsn,children_nth
12, 4 --this one should not get a voucher

12 will login
gets prevalidation by using DigiD

gets voucher

Has no fund request


34 will login

Start fund request
fills in form


Validator 
Fund_request
34 as BSN


Prevalidation table -> Search BSN -> check if activated -> if there and not activate -> he needs to deactive prevalidation or ask to use code 'partner check modal'

25.000 -> 80% prevalidation -> 20% will be manual

prevalidation -> Prepare information (post) -> personal

redeem a prevalidation and apply for a fund using prevalidation
application will bestored as fund_request

fund_request -> Validator export here list of fund_request (request to you)

voucher

_bsn,_partner,children_nth
12,34,4 --oldest of is head of family

Requester signupflow
User 12 logs in with DigiD
Backend -> Prevalidation gets redeemed for this BSN
Gets BSN Record and prevalidated records
partner: 34 -> system type
children_nth: 4

Both parents are not familiar by municipality
Moved from different city and just got there

1 parent applied
12 applies -> validator check his database of people sees 12 has a partner which 34; validator enters 34 as partner (optional)
gets approved
gets vouchers

34 applies -> validator checks his database of people sees 34 has partner which is 12;


2 parents both applied simutamiously -> on funds page they need to activate voucher on activation we will check if partner

**Comment by maxvisser** [comment]
@danrminds lets discuss this issue briefly

**Comment by jamalv** [comment]
I have discussed the proposal about relations and the workflow in figma with the stakeholder that has to do it, and it is approved.

@danrminds could you do a design review on this? https://www.figma.com/file/rW80bGvSS7TKXovctNjjUQ/Relations?node-id=29%3A10563

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R6](https://forus.testquality.com/project/11140/testcase/255434/requirement/10814). Do not remove or edit.

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R7](https://forus.testquality.com/project/11140/testcase/255433/requirement/10815). Do not remove or edit.
