### ISSUE TITLE
Notify users about new offers

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#152]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
Currently users have to go to the webshop to learn about new offers.

## Desired situation
option 1 (depends on stakeholder approval): we automatically send periodical updates (digest)
option 2: the implementation is able to send emails to users about offers

## Plan
-

**Comment by maxvisser** [comment]
@jamalv what do you think about this mvp:
we ask users on activation of voucher if they want to share their email with the sponsor of the fund for these kind of purposes. (as well as sharing if they used their voucher) What will happen:
- we show the voucher on voucher generator
- sponsor can export emails on voucher generator

Other option:
We sent automatically generated emails to requesters (if they have set this up on notification preferences) with random product highlights.

extra: 
On new implementation dashboard we add a 'product highlight' feature. This shows all products connected to the fund and a way to highlight (6 at a maximum). Implementation manager can select some and sees when the last email was sent and when the new one will be sent.

**Comment by jamalv** [comment]
Yes, I think that's a nice way to do it. I think we can show a modal at first open of the voucher (on the webshop) - and there should then also be a setting to change this later. 

Mockup: 
![image.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/439111c7-75d8-42f3-830b-a1300488e1e2)

Figma: https://www.figma.com/file/aFDUiHyqzrn0gVFpJ3ysSd/Sharing-permission?node-id=1%3A60

**Comment by jamalv** [comment]
As I understand, this is also part of digest? Could we rate this proposed feature on scope?

**Comment by maxvisser** [comment]
I would say we do notify users for new products / services; As actions are new. these should be added to digest. Have no strong opinion about sharing info modal. If I would implement it I would add it to the signupflow of requester. We should see where the information is shown (is voucher added to voucher generator? should voucher generator show that it was added by signupflow?)

**Comment by jamalv** [comment]
Agreed: opened a CR for sharing details here: https://github.com/teamforus/general/issues/334 and added a remark to actions about the mails: https://github.com/teamforus/general/issues/209
