### ISSUE TITLE
Financial data export

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#153]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
We offer dashboards to view financial data, and we can export transactions

## Desired situation
To offer sufficient exports of the financial data

## Plan
- Check if the transaction export is sufficient
- If not sufficient, add requirements here

**Comment by maxvisser** [comment]
I switched this back to a change request as it is still to vague.

**Comment by jamalv** [comment]
related (internal): https://github.com/teamforus/lab/issues/44

**Comment by maxvisser** [comment]
Not clear to scope. Could refine this issue (whats needed)

**Comment by maxvisser** [comment]
Or close the issue.
