### ISSUE TITLE
Sprint Review (Demo)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#155]
_At Forus we follow the official scrum guide. The following text was taken from: https://scrumguides.org/scrum-guide.html#sprint-review_

**Time tracking**
This issue is used for time tracking when preparing for or attending the Sprint Review.

**Sprint Review** 
The purpose of the Sprint Review is to inspect the outcome of the Sprint and determine future adaptations. The Scrum Team presents the results of their work to key stakeholders and progress toward the Product Goal is discussed.

During the event, the Scrum Team and stakeholders review what was accomplished in the Sprint and what has changed in their environment. Based on this information, attendees collaborate on what to do next. The Product Backlog may also be adjusted to meet new opportunities. The Sprint Review is a working session and the Scrum Team should avoid limiting it to a presentation.

The Sprint Review is the second to last event of the Sprint and is timeboxed to a maximum of four hours for a one-month Sprint. For shorter Sprints, the event is usually shorter.

**The Sprint**
Sprints are the heartbeat of Scrum, where ideas are turned into value.

They are fixed length events of one month or less to create consistency. A new Sprint starts immediately after the conclusion of the previous Sprint.

All the work necessary to achieve the Product Goal, including Sprint Planning, Daily Scrums, Sprint Review, and Sprint Retrospective, happen within Sprints.

**Comment by EmielForus** [comment]
New: https://github.com/teamforus/DevOps/issues/1
