### ISSUE TITLE
Backlog Refinement

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#156]
**Time tracking**
This issue is used for time tracking when preparing for or attending the Backlog Refinement session.

**Tooling**
For Backlog Refinement, we use https://app.zenhub.com/.

**Product Backlog**
_At Forus we follow the official scrum guide. The following text was taken from: https://scrumguides.org/scrum-guide.html#product-backlog_

The Product Backlog is an emergent, ordered list of what is needed to improve the product. It is the single source of work undertaken by the Scrum Team.

Product Backlog items that can be Done by the Scrum Team within one Sprint are deemed ready for selection in a Sprint Planning event. They usually acquire this degree of transparency after refining activities. **Product Backlog refinement is the act of breaking down and further defining Product Backlog items into smaller more precise items.** This is an ongoing activity to add details, such as a description, order, and size. Attributes often vary with the domain of work.

The Developers who will be doing the work are responsible for the sizing. The Product Owner may influence the Developers by helping them understand and select trade-offs.

The following text was taken from: [Medium](https://medium.com/the-liberators/myth-refinement-is-a-required-meeting-for-the-entire-scrum-team-b17fb7bc25fa#:~:text=The%20Scrum%20Guide%20describes%20Product,items%20in%20the%20Product%20Backlog.&text=So%20the%20Scrum%20Guide%20is,done%20in%20the%20real%20world.)

Product Backlog refinement is certainly an essential part of the Scrum Framework. But more often than not, it takes the form of a team passively sitting around a meeting table while a subset of the team discusses upcoming items in excruciating detail. When doing Product Backlog refinement like this, it is understandable that teams try to spend as little time on it as possible — which is one of the key reasons holding Scrum Teams back from becoming truly awesome.

So the Scrum Guide is quite clear; refinement is not an event in Scrum. This may appear like mere wordplay. But it does have a significant impact on how it is done in the real world. The guide emphasizes that Product Backlog Refinement is something that Development Teams do as a natural part of development. It is not something that necessarily happens at a fixed moment during the Sprint where the entire Scrum Team has to attend. 

As an activity, Product Backlog refinement has the following purposes in Scrum:

- Clarifying items on the Product Backlog that are too unclear to start work on. This is preferably done directly with the people you’re building the items for (the stakeholders);

- Breaking down items that are too big to pull into a Sprint (which generally also means that they’re too unclear);

- Re-ordering the Product Backlog as needed to make the upcoming Sprints as smooth and valuable as possible;

- Adding or removing items from the Product Backlog as new insights emerge;

- Estimating the effort involved in implementing particular items. This does not have to be as ‘formal’ as assigning story points (an optional practice in Scrum), T-shirt sizes or whatever sizing technique you use. A gut feeling (“Yeah, we know well enough what needs to be done and it feels doable in a Sprint”) is fine too;

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/280

**Comment by EmielForus** [comment]
New: https://github.com/teamforus/DevOps/issues/2
