### ISSUE TITLE
CR:  As a sponsor I would like to have an overview of statistics that compare the closed/active funds.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#159]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter and one of our sponsors

### Change description
- We already offer statistic about a specific fund. Would also be nice to have some general statistics that compare funds. This would provide the sponsor with more management information so they could take action where needed.

#### Example
There are a lot of statistics we could generate. Some examples:
- How many providers joined this year in comparison to last year?
- How many and which providers did add a product to the webshop in comparison to last year?
- How many requester used there budget in comparison to last year?

**Comment by maxvisser** [comment]
If we would do this we should probably invest time first in renewing funds; as you could then make the relation of this fund is this fund but then from the previous year. 

How I see this working:
Sponsor presses renew after fund is closed. old fund will connect as a child to the new fund. When you go to financial dashboard you have an option to see all statistics in comparison of last year.

**Comment by maxvisser** [comment]
MVP of this is exporting the information so a municipality could answer these question with their own BI systems

**Comment by jamalv** [comment]
I think renewing funds is a great idea. @maxvisser could you open a separate CR for it? I think it would be pretty great to implement that before year-end.

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/252
