### ISSUE TITLE
Check voucher even if you are not allowed to scan

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#160]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
Currently when a provider scans a voucher that is expired or there is no budget: they get an error. With a new implementation, the voucher is also used to give other discounts by the provider (outside the platform); so by seeing the voucher, the provider knows that this requester is part of a certain target audience. 

## Desired situation
Instead of giving an error, we should just show show the voucher. If there is no budget, or it is expired, we can hide those fields, and then the provider just has the option to "confirm" that he saw the voucher.

## Plan
https://www.figma.com/file/PLe8YzKNgnYyezMBFX83np/Check-(expired)-voucher?node-id=1%3A2

## Tasks
@jknnr, could you create the tasks for lena to make / fix the designs and also the development tasks later? And could you add the milestone for next sprint to those tasks?

**Comment by maxvisser** [comment]
I would still like a context aswell of it being empty; As providers which expect it to be empty should now its empty;

As I see it we should still let the provider see a balance of €0 euro's or just describe as it is. "There is no balance on this voucher" / "Er staat geen tegoed op deze voucher"

**Comment by maxvisser** [comment]
@jamalv maybe only implement this on action vouchers.

**Comment by maxvisser** [comment]
Scope is medium, needs a brainstorm session

**Comment by jamalv** [comment]
I don't actually think this is needed for actions, right? As with actions it will not be possible to have no budget.

**Comment by maxvisser** [comment]
well you could have nothing to scan; as in no active actions for you as a provider.

**Comment by maxvisser** [comment]
You need to have atleast one action (as otherwise you are not approved) is this intended? @jamalv

**Comment by jamalv** [comment]
#402 is needed to allow all providers to be approved for an action (even if it doesn't have a price)

**Comment by jamalv** [comment]
so after implementing #402 this will not be needed.

**Comment by maxvisser** [comment]
Ah thats smart. Another option is to bring back an 'accept' button:
Show organization description on sponsor dashboard
show #204 on sponsor dashboard

Requester will go to provider page on webshop. See all discounts and organizational description explaining how their discount works.

If you are accepted: you can scan vouchers but no running actions will appear. We could show in Me-app overall discount you added.

**Comment by jamalv** [comment]
no longer relevant
