### ISSUE TITLE
Switch from using floating cards to tables in dashboard lists

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#161]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
Currently we have really massive cards on most dashboard pages with lists. This makes difficult the navigation UX, searching, etc. 

## Desired situation
I would suggest to modify the UI and replace all lists from floating cards to actual tables.
For the tables we could use a switcher from compact to extensive view. 

![Screenshot 2020-04-21 at 19 14 06](https://user-images.githubusercontent.com/33207036/79893393-4cb6b780-8404-11ea-9cc1-f7e33174b128.png)

Example of a changed page:
https://www.figma.com/file/hoCkRiVbvRfhqPNJYAJLP7/Tables?node-id=2%3A2&viewport=872%2C1610%2C2

Also - lists like these would not need the "Kijk" button anymore. 
![Screenshot 2020-04-21 at 19 14 58](https://user-images.githubusercontent.com/33207036/79893548-87b8eb00-8404-11ea-9d48-f4c5919a1619.png)
The table row would be clickable by default, which makes the navigation easier. We could leave the space there only for action buttons.

Example:
![Screenshot 2020-04-21 at 19 16 28](https://user-images.githubusercontent.com/33207036/79893673-ad45f480-8404-11ea-93f8-9016b73b4fda.png)

## Plan
-

**Comment by maxvisser** [comment]
Yes agree looks alot more clean

**Comment by maxvisser** [comment]
7 pages which need this. Impact does not seem that high

**Comment by jamalv** [comment]
Moved to productboard: https://app.productboard.com/inbox/notes/15568890
