### ISSUE TITLE
Study issue and figma manuals

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#164]
We created some manuals on how to create issues: https://github.com/teamforus/general/blob/develop/manuals/development/issues.md

And also about how to work in figma:
https://github.com/teamforus/general/blob/develop/manuals/design/pipeline.md

Could you please read the manuals when you have time and ask any questions you might have in the comments on this issue?

**Comment by maxvisser** [comment]
As this is open till april and only me and gerben tracked time. I will close this (you can still track time on closed issues)
