### ISSUE TITLE
IP: Approving multiple funds

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#165]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- One our implementations
- Team members

### Change description
**Current**
- The current layout of the sponsor dashboards allows the sponsor to: 
    -> Click **Providers** -> Select fund -> Get providers list -> accept or reject

**Change**
- Changing the user flow into something similar as the webshop will give a better overview and will allow the sponsor to:
    -> Click **Providers** -> Get provider list -> Select provider -> select which fund or offer should be accepted/rejected 

Using this flow will open options to give the sponsor see more relevant data at once.
I would even suggest that splitting "Providers" & "Offers" like the webshop would be something to consider. We are developing new features that will give the sponsor more options and control. Changing the UX of this part of the dashboard is something we could consider.

**Possible MVP**
- Adding more context at provider cards about which fund they are connected to.

https://www.figma.com/file/FzkMCqhlv7U3zU5evcOnz2/%F0%9F%94%B5Approving-multiple-funds

**Comment by maxvisser** [comment]
I like this CR and I think there is already a figma prototype.

I moved it to IP stage.

**Comment by jamalv** [comment]
@maxvisser @GerbenBosschieter, what's the status of this? Has this already been improved upon with updates in the meantime?

**Comment by maxvisser** [comment]
No its at the same stage as before.

**Comment by GerbenBosschieter** [comment]
There was a reason why we didn't include the overview in this proposal to the new product review feature right?

**Comment by jamalv** [comment]
@GerbenBosschieter how would you prioritise this? won't, could, should, must?

**Comment by GerbenBosschieter** [comment]
must. definitely. This is THE legacy problem for our current sponsor with multiple funds. 
Managing 15 funds while not having overview of all the funds the provider is connected to.

I would (and also did) manually create a  list to provide them with this  information

**Comment by GerbenBosschieter** [comment]
@jamalv our defintion of "Must have" = should be done in this sprint. But this is not the case. In our defintion it's more of a "should have". But it's a should have that we eventually must have and not postpone for a long time

**Comment by maxvisser** [comment]
I estimated this issue. Scope small for the MVP which is proposed

**Comment by jamalv** [comment]
Just looked at this again, I see why this is highly desire-able for multiple funds. I approve this to be worked on. Would also suggest to remove the tiles and move the filtering based on funds to the filter button.

**Comment by maxvisser** [comment]
Can I plan this in ?

**Comment by maxvisser** [comment]
I think its small/medium so it could take up a chunk of time. (as it is a should have)

**Comment by jamalv** [comment]
@maxvisser yes can be planned

**Comment by GerbenBosschieter** [comment]
I see that people create new issues for similar things.

**Comment by GerbenBosschieter** [comment]
This will help alot:

Changing the user flow into something similar as the webshop will give a better overview and will allow the sponsor to:
-> Click Providers -> Get provider list -> Select provider -> select which fund or offer should be accepted/rejected

**Comment by maxvisser** [comment]
we already planned this: whats currently on should have in figma
https://www.figma.com/file/FzkMCqhlv7U3zU5evcOnz2/%F0%9F%94%B5Approving-multiple-funds

**Comment by GerbenBosschieter** [comment]
This proposal expects the provider to apply for the fund? So if they didn't apply for a fund you can individually invite them?
