### ISSUE TITLE
CR: Fund mandatory records fields (which should exist)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#167]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Max Visser

### Change description
Some funds have criteria on income and net worth. This issue is about records that are used for the formula which do have a criteria on them. For example:

Children_nth -> you don't need to have children for the fund, but we should ask, if you have children because you get more budget on your voucher

Currently this is done by adding a criteria:
children_nt >= 0 

But this is displayed to user as:
Aantal kinderen moet gelijk of meer dan 0 zijn. 
Amount of children needs to be the same or more than 0.

Quick fix for this is to hide all >= 0 from fund criteria on requester signupflow

**Comment by jamalv** [comment]
@maxvisser is this still relevant?

**Comment by maxvisser** [comment]
Yes
