### ISSUE TITLE
Transactions: making them more flexible, scalible and robust

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#169]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

**Note:** As this IP is a sensitive topic, let's contain the discussion to the [google doc](https://docs.google.com/document/d/1eEZYSAYs9bJq2YswqtIB2BsY_RX9kUipaQyOVQ1wo-g/edit).

**Comment by maxvisser** [comment]
Can't estimate this issue.

**Comment by jamalv** [comment]
no longer relevant
