### ISSUE TITLE
How does it work infrographic

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#170]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [ ] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
![image](https://user-images.githubusercontent.com/10818702/80372453-d8609600-8893-11ea-88ba-4d8c772376a3.png)

## Desired situation
Better quality infographic which explain the process better

## Plan
-

## Change request issue:
https://github.com/teamforus/general/1 (if applicable)

**Comment by jamalv** [comment]
I believe @linda-90 is working on this :) when we have something it can be reviewed! @linda-90 if you start working on something could you link the figma file here or let us know if/how we can help?

**Comment by maxvisser** [comment]
I think these are done and this issue can be closed @linda-90
