### ISSUE TITLE
Extending API Connections

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#173]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

This IP should be created and discussed in this [google doc](https://docs.google.com/document/d/12JF6AruEOzBgEhATq7sVuYmv3X8uma7KwNL7uhA5s6Q/edit)

**Comment by maartenfv** [comment]
Hallo Maarten,

Ik begreep van Gert Jan van der Kooi van PinkRoccade dat jullie een prettig gesprek hebben gehad. Pink is enthousiast!
Binnen de gemeente Groningen wordt druk gemaild en onze i-adviseur Frits Willemsen heeft flink voor dit project gelobbied om er een pilot van te maken.

Dinsdagmiddag hebben we hierover een gesprek met Harry over hoe we dat hier intern zouden moeten regelen.

Jullie horen snel weer van ons!

Wordt vervolgd.


Met vriendelijke groet,

Henriette

**Comment by maxvisser** [comment]
Not clear what the scope is.
