### ISSUE TITLE
Me info button

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#175]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Jamal

### Change description

Figma:
https://www.figma.com/file/ARUlmFPD1ZHOu5LZEgAY6P/Me-Info-button?node-id=2%3A136

**Comment by maxvisser** [comment]
Gebruik de scanner om de QR-code op de website te scannen en in te loggen op jouw omgeving. 

Ben je een aanbieder die is aangesloten? Gebruik de scanner om QR-codes te scannen en betalingen te kunnen ontvangen.

**Comment by maxvisser** [comment]
Wrote a text for this info screen. @myshelova could you review and add the text?

**Comment by maxvisser** [comment]
Example of a different app I use which has such an info button https://photos.app.goo.gl/Jnv3rT4GHmEhBocF6

**Comment by maxvisser** [comment]
@Myshelova could you review IP

**Comment by jamalv** [comment]
@maxvisser I think maybe let's first work on making a decision about the proposals first; to go with an info button or with a tutorial: https://github.com/teamforus/general/issues/205

**Comment by maxvisser** [comment]
Yes thought we were already on an agreements as you made the initial figma proposal. :) will put it on hold for now.

**Comment by linda-90** [comment]
@jamalv I have placed this on our agenda. 
De status en planning kunnen we vanmiddag bespreken:)

**Comment by jamalv** [comment]
going with https://github.com/teamforus/general/issues/205
