### ISSUE TITLE
Incorrect date formatting at add offer page

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#176]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
jamal

### Change description
As a provider when adding an offer I might not care about the end date of an offer, so by default I did not fill one. Then the error message I get is incorrect > 

<img width="503" alt="Screenshot 2020-04-29 at 21 28 13" src="https://user-images.githubusercontent.com/30194799/80638310-891b9080-8a60-11ea-9b31-6dbfefab123b.png">

In the input field it asks for dd-mm-yy and the error says it should be Y-m-d.

Maybe we should consider making end date optional? Or setting a default?

**Comment by maxvisser** [comment]
the expire date will be used for reservation (last day it can be picked up). We don't have any context here about funds; we could auto fill it with today + 1 year

**Comment by maxvisser** [comment]
added the incorrect error to the big pile of weird errors; https://github.com/teamforus/general/issues/82

**Comment by maxvisser** [comment]
can this be closed?
