### ISSUE TITLE
As a user I would like to be able to fit my entire logo in the image cropper, without editing the image outside of Forus

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#177]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
When uploading an image, we default to zoomed in a bit, but the chance is quite big that I want to show as much as possible of the image. Therefore it would make more sense, in my opinion, to default the cropper to be zoomed out.

Current default
<img width="464" alt="Screenshot 2020-04-29 at 21 34 54" src="https://user-images.githubusercontent.com/30194799/80638894-76558b80-8a61-11ea-92fa-e1f8a35af32d.png">

Requested default
<img width="490" alt="Screenshot 2020-04-29 at 21 36 47" src="https://user-images.githubusercontent.com/30194799/80638928-88cfc500-8a61-11ea-90e6-8d8a128ba9f2.png">

## Other issue #421:
Should allow white space.
Should allow black space.
Optional colour picker.

Needs to allow to zoom out more.

## Related: https://github.com/teamforus/general/issues/763

- We need more space to place the picture.
- Make sure the cropper is actually square.

It says upload square resolution but its not square. 
![image](https://user-images.githubusercontent.com/30211022/107948510-35007f00-6f94-11eb-8889-c4b640fb0e7b.png)

**Comment by maxvisser** [comment]
Like the idea, not sure of how easy this is to implement as we did not build this cropper (its a angularjs dependency); can be moved as a task to forus and we can check it.

**Comment by maxvisser** [comment]
needs project

**Comment by jamalv** [comment]
Update: default zoomed out state is ready, adding whitespace research is done and conclusion is will take a few days. 

Currently doesn't fit schedule and is a should-have (no formal agreements about it). I have increased the estimate, added this insight to productboard, now depends on priority relative to other issues.

**Comment by maxvisser** [comment]
quickfix will be part of release v24

**Comment by jamalv** [comment]
added the whitespace to productboard: https://app.productboard.com/inbox/notes/15568555

this issue can be closed after release imo
