### ISSUE TITLE
MijnOverheid connection - Personal records

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#178]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Max Visser

### Change description
Seems like the thing we saw on the hackathon last year is in production;

https://www.logius.nl/diensten/mijnoverheid/aanvragen
Inzage persoonsgegevens: dit aansluittraject is doorgaans een maatwerktraject dat in onderling overleg tot stand komt. De projectkosten hiervoor zijn voor rekening van de aansluitende partij.

**Comment by jamalv** [comment]
we got in touch, apparently it is not production ready yet. would be very nice when it's ready, though.
