### ISSUE TITLE
Work on dashboard library (figma)

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#179]

**Comment by maxvisser** [comment]
Would be nice if we know which pages / what work.

**Comment by danrminds** [comment]
It was done more as a generic task, when work is not trackable in other specific ones, but still covers the dashboard library.

**Comment by maxvisser** [comment]
Would still be nice to see which file is worked upon; I will close this isse ( you can still use it to track time). A comment in description of time tracking is needed to describe what was done.
