### ISSUE TITLE
Open source and licensing

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#18]
## Context:
Forus is [planned](https://github.com/teamforus/forus#roadmap) be deployed on a decentralized infrastructure. But due to technical limitations (privacy, speed, costs) that is not yet feasible. Therefore, we will first build an [organizationally decentralized](https://github.com/teamforus/forus#roadmap) application on proven technology that we will deploy on a centralized infrastructure (AWS) this will allow us to provide real-world value and itterate to increase the usefullness of the platform. Then, when the technology proves itself ready, we will migrate.

## Problem statement:
When the application is running on a [decentralized infrastructure](https://github.com/teamforus/me#why-build-me). For us the open source license should be as permissive as possible. We want to encourage adoption and for it to be fully decentralized we believe it should be part of the public domain. But until we reach that point, we risk fragmentation. This can happen when other parties will deploy the platform and store user data on their (closed) systems. 

## Proposed solution:
I propose to initially use a more restrictive license that will allow third parties to inspect the code and make contributions, but disallows them from commercializing/deploying it. This way, the responsibility of deployment and executing the [migration strategy](https://github.com/teamforus/forus/tree/dev/docs#decentralisation-roadmap) to a fully decentralized infrastructure will stay with Foundation Forus. 

## Risks:
This will put Foundation Forus in a more centralized position in the short term. Users of the platform that care about decentralization have to place their trust in the Foundation that it will execute the vision. 

Please share your thoughts, proposals for licenses are very welcome.

**Comment by maxvisser** [comment]
we can differentiate between repo's. I think apache 2.0 or Mozilla public use would be a great option. Our intention should be to trademark Forus and Me (in context of our own applications). So if there are bad copy's they can't use the of Forus or Me.

````
Trademarks.
This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.
````

**Comment by jamalv** [comment]
@maxvisser, I think trademarking the names can be a good fit for the frontend repositories. I think the decentralised parts of the backend (e.g. smart contracts) should be licensed as freely as possible (e.g. unlicensed).

For the (temporary) centralised version of the backend we could even consider creating our own licence since the situation is quite specific. The message should be something like:

The Forus-backend (php) is a temporary solution that should only be deployed and taken into production by the legal entity Foundation Forus while technical decentralization is not yet feasible. This restriction is in place to avoid fragmentation/vendor lock-in with parties that don’t have the intention to decentralise their infrastructure. The centralised backend is open source purely for educational purposes.

**Comment by maxvisser** [comment]
I think it would still be wise to pickup the most restrictive one until we have set-up a custom license

**Comment by jamalv** [comment]
Maybe something like: https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by jamalv** [comment]
About the traditional (php) backend: there is no clear advantage of it being open source as far as I can see, it has no clear role in decentralisation. It is mainly there to enable us to provide real-world value to users right now, and to create a full feedback loop so that we can learn how we can shape the product to provide maximum value, while we are moving in the direction of decentralising it.

There _is_ a clear disadvantage as stated above: if other parties will deploy the system and start adding users, we risk fragmentation of data. It will make migration harder. Also, they might not have the vision of decentralisation and giving data ownership back to the end user. This creates risks that be avoided by making the traditional (centralised) backend closed source. In the meantime, the ethereum/ipfs variant backend of the system is being developed fully open source, and I am in favour of adding the "unlicense" to it. Check it out here: https://github.com/teamforus/rd-ethereum-platform

For now, I have put the php part of the system private. At least until we find good reasoning in favour of making it public.

**Comment by danrminds** [comment]
Completely agree

**Comment by sgort** [comment]
Is it ok with Forus if I ask my contact at https://oseno.nl/ for advise here?

**Comment by jamalv** [comment]
Absolutely, this is an important topic for us and a discussion we would like to have publicly. This thread is open and anyone can comment. If there's any questions we're glad to clarify. We have set up the early beginnings of a knowledge base at: https://docs.forus.io and any questions we receive can be seen as input for the FAQ we'll add there 👍

**Comment by bvhme** [comment]
Just to be sure, I would look to Trademarking more as a solution for this than licencing. This can be achieved with AGPL and similar licences but I would strongly advise against using any licence not on the [list of popular licences by the OSI](https://opensource.org/licenses). Using custom licences means the code cannot easily be reused by others since often they will need to involve 'legal' to review it.

**Comment by maxvisser** [comment]
@bvhme Yes we really should seperate trademarking and licensing. @jamal maybe we should create a seperate issue for that.

I think there are multiple 'products' that need licenses:
- **kindpakket zuidhorn mvp, built last year**
After 1 nov this application is going offline, I think we can open source the application under AGPL

- **new 'first' build of a organisational decentralized forus: that support kindpakket and other funds that are similar, php backend**
Could be open source, we need to set up a good security strategy first though.


- **first version of the me app concept, php backend**
We dont want fragmentation here, As it is written in php, i also see almost no benefit in open source, only disadventages.

- **research & development ethereum forus platform**
I think this can be unlicensend, as ethereum contract are open when deployed on a public chain anyway.

**Comment by maxvisser** [comment]
https://fair.io/#license

I think this may be a start to open up the code of the backend for audits and preproduction deployments as we can limit the amount of users within the license. We can work towards open sourcing the platform completely while currently limiting fragmentation of data (because of the limit of users)

**Comment by jamalv** [comment]
@bvhme @maxvisser @sgort, thanks for your input! I have added my thoughts below.

Repository | Licence | Reasoning
---|---|---  
me/forus-backend-**serverless** | Unlicence | To be fully decentralized and encourage adoption and standardisation, this implementation (smart contracts etc.) should be licenced as permissive as possible.
me/forus-backend-**server** | Copyrighted | To avoid the risks stated above we actually don’t want this implementation to be used exept as a reference for creating the serverless implementation, and for third parties to be able to inspect and improve the code. <br><br>I think we can make the code public but copyright it under the name of the foundation, and then challence people to “compete” with it by advancing the serverless implementation 😉 Obviously the foundation will also work on this. When the decentralized implementation is advanced enough, we will migrate the data away from our servers and to the end users (or give users the choice to do that, for example in the me app).
me/forus-**frontend** | AGPLv3? | Not yet sure of the strategy here.

**Comment by maxvisser** [comment]
https://creativecommons.org/licenses/by-nc-nd/4.0/ is maybe an option for forus-backend

**Comment by jamalv** [comment]
Yea, that one seems right. 

Considering the information troughout this thread, can we agree that this is the right call to make right now? 

To summarize: the code for the forus backend will be public and can be studied, improved and used as a reference for buidling the fully decentralized (and unlicenced) implementation, but can not be taken into use exept by the foundation. In the short term this will avoid fragmentation of data while the decentralized version is being built, this leaves the responsibiltiy of migration with the foundation only, and gives the foundation the opportunity to already bring the platform to end users, to learn from their experience and be able to invest into building the decentralized platform.

**Comment by jamalv** [comment]
Wrote the following disclaimer, with it I personally think it can be made public again: 

DISCLAIMER: Don't bring this into production. This repository is public for educational purposes, and to allow auditing and improvement of the code. The vision is for this backend to be decentralized. That means to work peer-to-peer and without servers. To achieve this we are [researching](https://github.com/teamforus/research-and-development) technologies such as Ethereum and IPFS. These technologies are still young and in our eyes not ready to be taken into production. Therefore we built this implementation of the platform to be able to provide value to and get feedback from end users. While we think decentralisation is important, building something useful is even more important for us. This implementation facilitates us in doing that. If you want to contribute you are most welcome, but we would also encourage you to invest your energies in the decentralized (and unlicenced) version of the platform: [https://github.com/teamforus/rd-ethereum-platform](https://github.com/teamforus/rd-ethereum-platform)

© 2018 Foundation Forus, All Rights Reserved

**Comment by bvhme** [comment]
Breaks my heart to see any promising codebase be closed, but great work informing everyone.

As a side note please understand that you are now explicitly forbidding people from forking and making pull requests (since they are not allowed to copy it)

Also, I can advice breaking it up into a few paragraphs, giving it a header and adding a few ⚠️ emoji :)

**Comment by jamalv** [comment]
Thanks for your input! As the codebase was previously closed, we see this as a small step in the right direction. For us it is also a difficult discussion, and one that definitely doesn’t end here. We invite everyone to think along with us and ask us questions about our reasoning. We will use it as input for the documentation we want to write over at docs.forus.io and maybe update our decisions accordingly.

**Comment by jamalv** [comment]
We discussed this further and I would like to add the following paragraph:

This limitation will be in place until user data is securely stored on the device (smartphone) of the end user or encrypted on a decentralized file storage system (e.g. IPFS) with the encryption key in control of the user (e.g. on device or at a storage service of their choice).
