### ISSUE TITLE
CR: Generate a batch of vouchers

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#180]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gerben

### Change description
- As a sponsor I would like to generate multiple vouchers at once (batch) so I don't have to repeat the same actions if I already know I want to generate 100 vouchers of € 10,-.

This change request is only related to generating the vouchers, not granting them.

**Comment by maxvisser** [comment]
seems like csv upload should be the right fit for this right?

**Comment by maxvisser** [comment]
discussed with @GerbenBosschieter csv uploader is fine for this.
