### ISSUE TITLE
CR: Add search on provider name as seperate filter on products page webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#181]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal Vleij

### Change description
I had a discussion with Jamal about this CR last week. Currently our search field is able to filter on provider name but this is not really inituitive for the user (he does not know). Making it a seperate search field which auto completes on provider name helps making it more usefull.

**Comment by maxvisser** [comment]
Can be planned

**Comment by linda-90** [comment]
@maxvisser Could you give an update? I have moved this issue to the pipeline: Make a written plan.

**Comment by jamalv** [comment]
@maxvisser I believe this was done?

**Comment by maxvisser** [comment]
Yes its done
