### ISSUE TITLE
Budget voucher reservations 

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#183]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [ ] Finances
- [x] Processes

## Current situation
* A user can add reservations to the budget voucher
* A sponsor can add reservations trough fund configuration
* A sponsor can add products trough the voucher generator

## Desired situation
A good way to manage reservations on budget vouchers for a fund (needs clearification) - I will discuss this more with stakeholders. Here we might need the ability to block / remove reservations and maybe even the budget voucher as well.

## Plan
https://docs.google.com/document/d/1v0iKgbkJQ4F6hiwJZUKf79faUgVh3jsE4b5Fw7b8US0/edit?usp=sharing

**Comment by maxvisser** [comment]
I would rather remove / add stuff to the formula and allow user to 'reactivate' fund to get more stuff on their card. 

If sponsor adds more products to the formula, user could get a mail go to the webshop to activate to following new reservations:
xx
xx

<< direct link to fund page >>

Pro's of this:
Newly generated voucher will have all current available offers. 
Requester has control over their account

**Comment by maxvisser** [comment]
@jamalv in context of other IP's maybe this one can be on hold for now?

**Comment by linda-90** [comment]
@jamalv We placed this issue in icebox. Is this correct?

**Comment by jamalv** [comment]
yes correct, can be closed
