### ISSUE TITLE
Provider can make a product unavailable for a fund

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#185]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
All offers are added to a funds when a provider is accepted by a sponsor

## Desired situation
Providers can propose offers for specific target audiences (D6). The proposal is to add a toggle to the product page of the provider where he can make certain product unavailable for specific fund which he is accepted for. This way he has control over where his products are visable.

In order to make a specific in-kind credit available to a target group (offers for parents other than for children), it must be possible for the provider to make an offer per fund. In this way, the same provider can offer different things to children than to parents. 

## Plan
https://www.figma.com/file/sfWYveCwXxeTzh1ziYUBIW/Applying-offers?node-id=1%3A2

**Comment by maxvisser** [comment]
I like the proposal

**Comment by jamalv** [comment]
Had a discussion with Max and discussed points above:
Default is available & no impact on userflow because of that. The provider has the option to turn it off.

**Comment by maxvisser** [comment]
Edge case:
Sponsor has 5 funds. A provider has made his product available for 4 of the 5 funds. A requester has a voucher for the 2 of the funds. one of these voucher is from a fund which the provider told to the sponsor his product is not available for. The sponsor has decided to allow all products of this provider for all its funds.

In this case the requester will still be able to request the product with his voucher for the fund the provider told the sponsor the product was not available for. 

This functionality should only hide the product from the webshop and sponsor dashboard for a specific fund but it is not necassary to hard limit any creation of product vouchers.

**Comment by danrminds** [comment]
@jamalv 

This should be done by Valentin. it will touch a lot of difficult queries on dashboards and webshops. 

Let me know on priority

**Comment by maxvisser** [comment]
@jamalv Because of actions (where no product will appear automatically in the webshop) I see this as less priority. A provider can or cannot decide to apply for a fund which you can define as 'doing a proposal for a specific audience'

**Comment by jamalv** [comment]
@maxvisser i agree with that applying to a fund and then adding it to it entails this action, making this less critical (even though this functionality is still a nice-to have and has been requested by national providers on our platform as well)
