### ISSUE TITLE
IP: Notification log on webshop/dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#186]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Current situation
Currently a user gets alot of email notifications. We are working on a email digest to minimize these mails to only sent a few a day. The concept of these digest mails currently contain alot of information which can't be accessed anywhere else then the mail. Which results in when a mail is lost or not sent in that the user is not correctly informed.

### Proposal
This change request is a solution to this problem. The webshop and dashboards should contain a notification log which shows which notification the user got from the system.

extra:
tracking which notifications are read
linking notifications to the right page in dashboard/webshop

**Comment by maxvisser** [comment]
@danrminds could you add some screenshot of notification log on your CRM? (as inspiration)

**Comment by maartenfv** [comment]
@maxvisser Discussed with Max needs to be language checked and tested. A Max could you give us the file to be checked?

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-backend/tree/develop/resources/lang/nl/notifications

**Comment by maartenfv** [comment]
@maxvisser Does this still need to be checked?

**Comment by maartenfv** [comment]
Language check was conducted on the following files:
- [ ] notifications_fund_providers.php
- [ ] notifications_fund_requests.php
- [ ] notifications_funds.php
- [ ] notifications_identities.php
- [ ] notifications_products.php
- [ ] notifications_vouchers.php

**Comment by maartenfv** [comment]
@maxvisser 

What is meant with:

'revoked_products' => [
        'title' => 'Aanmelding voor :fund_name is gewijzigd. U bent niet meer geaccepteerd voor al uw aanbiedingen.',
        'description' => 'Aanmelding voor :fund_name is gewijzigd. U bent niet meer geaccepteerd voor al uw aanbiedingen.',

Wat gebeurt er als revoked products wordt getriggerd?

**Comment by maartenfv** [comment]
@maxvisser are these the correct/related Figma proposals?

**Comment by maxvisser** [comment]
yes

**Comment by maxvisser** [comment]
> @maxvisser
> 
> What is meant with:
> 
> 'revoked_products' => [
> 'title' => 'Aanmelding voor :fund_name is gewijzigd. U bent niet meer geaccepteerd voor al uw aanbiedingen.',
> 'description' => 'Aanmelding voor :fund_name is gewijzigd. U bent niet meer geaccepteerd voor al uw aanbiedingen.',
> 
> Wat gebeurt er als revoked products wordt getriggerd?

this notification is trigger when a sponsor revokes acceptance for All products

![image](https://user-images.githubusercontent.com/10818702/88027005-fc501280-cb36-11ea-8716-13689bd70f40.png)

Provider receives this notification. All his products are pulled from webshop and can't be reserved anymore from webshop.

**Comment by maartenfv** [comment]
@maxvisser @jamalv Ik heb alles zo goed mogelijk gechecked. Is lastig zonder context. Kunnen we deze ook nog een keer controleren tijdens het testen?

**Comment by maartenfv** [comment]
I have placed this back to the Figma proposal phase. Will update the Figma proposal with the actual texts for consistency and so it will be easier to change them later.

**Comment by maxvisser** [comment]
On production can be communicated to users

**Comment by maartenfv** [comment]
@maxvisser Let's close this issue.
