### ISSUE TITLE
Reviewing offers: send image in chat

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#189]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
municipality

### Change description
Add the ability to add an image in the chat between sponsor and provider

**Comment by maxvisser** [comment]
What's the reason? Image suggestions?

**Comment by maxvisser** [comment]
we could allow markdown which the scope of is small. we need to host images and do a cropper for the images aswell as letting provider easily apply that image to the product. Scope gets bigger. Also I would maybe suggest doing this on the action instead of the product.

**Comment by jamalv** [comment]
moved to productboard: https://app.productboard.com/inbox/notes/15568998
