### ISSUE TITLE
Improving the rocket.chat situation

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#191]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [ ] Design
- [ ] Code
- [x] Infrastructure
- [ ] Users
- [ ] Finances
- [x] Processes

## Current situation
Rocket.chat has served us well over the last years, but sometimes it gives some troubles. Max needs to spend some time on upkeep / maintainance. Sometimes it goes down. Storage is getting full, and sometimes it is a bit buggy. Therefore it is desirable to to think about a sustainable situation.

## Desired situation
**Important note:** This proposal should not disrupt team communication; therefore it has low priority and should be handled carefully.

**Should have:** Less / no maintenance; chat is pretty crucial the team; it should be stable. Max always fixes it quickly, but this could be better.
**Could have:** More, useful and powerful features.

## Progress
Max and I played around a bit with google chat. It looks nice, but the features are a bit limited and it is less suited for a community. 

I was showed a nice implementation of discord, and was super impressed. I have, in the weekend, played around a bit and set up a server: https://discord.gg/EjqxTxW feel free to look around :) 

## Plan
Check / discuss options: 
  * Invest in optimising our own rocket.chat deploy
  * Move rocket.chat to the cloud
  * Look for other tools
    * Moving back to slack
    * Moving to something like google chat
    * Moving to discord
    * Some other, yet unknown, tool

This should all happen below the radar until we have a good proposal. Then implementation (if implementation is needed) should be done clearly and swiftly. For example everybody signs up for the new service before a sprint demo. At the end of sprint demo we ask if everybody succeeded, and stay in the call to help people who had some trouble. Then we also need to think about our current community; we have about 147 users; they are currently not very active, but we should notify them _if_ we would move; so this needs a plan as well. We could send an @all notification in general to send everybody an email.

**Comment by maxvisser** [comment]
Looked at slack pricing. Would only work if rminds also got slack otherwise it would be too expensive.

Google chat could work but it's pretty new. Probably will get alot of integrations with g suite as time goes on.

Discord is awesome but somewhat gaming oriented but that does not really matter as the core works incredible. No app installations needed, direct voice chat which is really nice. I really dig the social aspect of going into a channel and directly being able to talk to someone without sending links :)

**Comment by maxvisser** [comment]
Moving rocket.chat to aws is maybe a day of work. Where at the start of the day I will make a backup. Download the backup and restore it on a new chat. (configure proxy and dns etc)
