### ISSUE TITLE
Add a notification screen to the Me-app

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#193]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- We should add a screen to the Me-app with an overview of incoming (unread) push notifications. This could be added to the profile tab

We use push notification to inform the app users about certain actions. The push notification can only be read if the user is receiving the notifications while watching his phone and the the sentence is not to long to get cut off by the screen width.
If the user doesn't read the notification it will result in a badge on the overview of all apps with a number of unread notifications.
The user opens the app but doesn't find the notification.

**Comment by maxvisser** [comment]
Yes probably this can be fixed with the new notification log #186 Me-app is currently out-of-scope. Dashboard and webshop will be implemented first.

**Comment by jamalv** [comment]
Yes, I agree this should be added to the roadmap.

Opened a figma to start the brainstorm: https://www.figma.com/file/m4uGX6sYJSugUj1RROLQW4/Me-Notifications?node-id=0%3A1
