### ISSUE TITLE
Price (/content) changes for actions: stop action + warning

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#196]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Municipality

### User stories:
As sponsor I want an action to be stopped when a provider changes the offer so that I am in control of the actions I am running

As a sponsor I want to notified when a provider changes an offer, so that I can re-start the action

As a provider I want to be warned when I change an offer that has running actions so that I can re-start the action under the new conditions

### Context
In the current approval process, an offers price can still be adjusted by the provider after approval. It should be built in that this is no longer possible and that an adjustment must first be approved by the municipality.

### Planning

- [x] | Writen proposal | Deadline: 05-08-2020 | Can be checked when enough info in Issue or Doc.
- [x] | Figma | Deadline: 07-08-2020 | Can be checked when proposal has reached Pull request stage in Figma.
- [x] | Development | Deadline: 21-08-2020 | Can be checked when deployed to develop
- [ ] | Staging | Deadline: 31-08-2020 | Can be checked when deployed to staging
- [ ] | Production  | Deadline: 07-09-2020 | Can be checked when deployed to production

## Figma
https://www.figma.com/file/qQrRGvPswp0bk0JQVT8dxI/Price-changes

**Comment by danrminds** [comment]
@jamalv @maxvisser 

Right now - in case a discussion had been started before for approval of the product between sponsor and provider - a notification will be sent (new system message) in the chat that the product had been changed). 

Should we keep this in the pipeline still? Or this covers the usecase for now?

**Comment by maxvisser** [comment]
when the price changes the product should not be shown anymore in the webshop and not be able to be reserved anymore :) notification is nice ofcourse but it does not cover the use case.

**Comment by maxvisser** [comment]
@jamalv lets discuss this one in a brainstorm session

**Comment by jamalv** [comment]
locking would be okay; deleting the product will stop the action (need to inform the user about this - warning modal)

**Comment by maxvisser** [comment]
I would lock the field behind field 'there is a running action' with a tooltip "A sponsor has started an action based on this product. Delete the product to stop the action"

**Comment by jamalv** [comment]
Discussed during sprintplanning today that @danrminds would check in with valentin to see what he thinks about this one in the context of actions.

**Comment by danrminds** [comment]
@jamalv 

#### Discussed with Valentin. To make the scope doable in the time we have, we should make it:
- Show notification to provider that there is an action running and it will stop
- Notify via email (directly) the sponsor
- Notification in dashboard for the sponsor (lower priority)

#### Later we can 
- Add this in the digest
- Interface for actions to reactivate

**Comment by jamalv** [comment]
@danrminds could you create the task(s)?

**Comment by maxvisser** [comment]
sponsor 5 euros
25 euros
--
30 euro
