### ISSUE TITLE
Limit offers, As a sponsor I want to limit the amount of times a user can purchase an offer.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#197]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As a sponsor I want to limit the amount of times a user can purchase an offer.

With a financial fund, the expenditure per inhabitant is limited by the financial credit that can be spent per inhabitant. This is not the case with a fund in kind, and the limit must be set in a different way. This is done by setting per offer how often a resident may use it. (for example 3 times). Example: A requester can reserve a product 3 times maximum

### Figma
https://www.figma.com/file/vY0i2SpavMw9PfW1cdcQA3/Limit-offers?node-id=1%3A16

**Comment by maxvisser** [comment]
Part of Actions #209

**Comment by maxvisser** [comment]
@jamalv I think figma file can be archived and this CR can be closed

**Comment by jamalv** [comment]
agreed
