### ISSUE TITLE
Me app brainstorm!

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#198]
This issue is for writing down any idea for the me app 😄 Please add ideas in the comments! 🥳

**Comment by GerbenBosschieter** [comment]
- Transaction overview (providers and requesters)
- Log in by sms code
- notification page (for push notifications)
- Stacking product vouchers (having multiple of the same product vouchers)
- Tutorial when first using Me-app

**Comment by GerbenBosschieter** [comment]
- New confirmation modals/pages after payment to give more clarity. (just like we now have with the confirmation when you signed up)

**Comment by GerbenBosschieter** [comment]
- Transaction overview (providers and requesters)

**Comment by GerbenBosschieter** [comment]
- Log in by sms code

**Comment by GerbenBosschieter** [comment]
- notification page (for push notifications)

**Comment by GerbenBosschieter** [comment]
- Stacking product vouchers (having multiple of the same product vouchers)

**Comment by GerbenBosschieter** [comment]
- Tutorial when first using Me-app
