### ISSUE TITLE
Me app: Login by sms code

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#201]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- As a Me-app user I would like have the option to log in by sms code. This would help me to log in if I got logged out and are not able to open a link by mail.

**Comment by maxvisser** [comment]
maybe it can becombined with https://github.com/teamforus/general/issues/113 or this issue should only be with already registered users which want to recover using telephonenumber

**Comment by jamalv** [comment]
Yea, this one will need some thought. Especially going trough different scenarios;

* First time sign-up, create an account bases on phone number
* Signed-up earlier using emailadres, now wants to use phone number (recovery)

What are the user stories? Risks? Workflows?

**Comment by maxvisser** [comment]
Combined with #113
