### ISSUE TITLE
Stacking product vouchers (webshop and apps!)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#202]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- As a user I would like to stack product vouchers that I have multiple times. This will result in a clearer overview If have a lot of vouchers. This would be nice to also have in the Me app it.

**Comment by maxvisser** [comment]
probably needs to rethink on how to show the QR-codes. This is mostly a visual change. For example you have 5 tickets for a soccer game; you need to easily switch between qr-codes or use the same.

**Comment by GerbenBosschieter** [comment]
I see this mostly as a visual change for now.

**Comment by maxvisser** [comment]
Some edge cases to think about:
- different expire dates
- different amounts on product voucher

**Comment by GerbenBosschieter** [comment]
Thinking out loud:
You could decide to only stack the product voucher when al this information you referenced to is the same as the earlier product voucher the user bought.

- Is this a reservation for a product voucher from the same organization with the same title, price and expiration date? 
    - Yes? same product voucher -> stack
    - No? different product voucher -> add to list (don't stack)

**Comment by maxvisser** [comment]
Yes, thought about this abit more; Grouping QR-codes will probably result in moving more towards Master QR. I think this needs to be done after https://github.com/teamforus/general/issues/120 and #50

**Comment by GerbenBosschieter** [comment]
@maxvisser I agree partially. You want to give the user some visuals to display how many product vouchers they have without duplicating them in the list. But I do think this is something that would be covered in a different IP. But not sure.

**Comment by maxvisser** [comment]
Needs figma proposal and a project
