### ISSUE TITLE
Me-app: show confirmation/succes screen instead of modal after succesfull payment.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#203]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- I would like to see our current modals (see images below) to change to pages/screens just like we have after someone applies. (see image below)

Our current confirmation/succes doesn't grab your full attention to confirm this message. I already spoke some user who just clicked away the error while thing it was a succes page..

If we are going to add succes or failure screens. There should be a really clear visual distinction between succes and faillure screens.

### Additional information
- Current modal
![IMG_2347](https://user-images.githubusercontent.com/38419514/82032467-87c2a880-969b-11ea-9b05-d34352594fc6.JPG)

- How it coulld be (example, we shouldn't use this exact sreen)
![IMG_3738](https://user-images.githubusercontent.com/38419514/82032511-9a3ce200-969b-11ea-8263-cd73ae399c4d.JPG)

**Comment by maxvisser** [comment]
yes the payment amount confirmation I would also do the same

**Comment by maxvisser** [comment]
@jknnr could you discuss this CR with Daniel and Vasyli

**Comment by jknnr** [comment]
Hi! It is doable on iOS cause we have the similar design. On android there is much harder even with the design.
This will not be a modal screen anymore but "activity". Activity not just a screen, but a new task that appears on top of the main flow and focuses all the memory resources on itself. So the main screen will kinda go to sleep and lose its priority. Allocating so much memory on the dialog with the "ok" button seems not logical especially on our precious Nokia 1 device. 
What we can do is experiment with customising the modal we have (Material dialog) and try to just make it bigger so it will cover 80%-90% of the screen, adopting to all screen sizes.

**Comment by maxvisser** [comment]
part of release v0.4.0 of android
