### ISSUE TITLE
hiding all financial balances, transactions and prices

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#206]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
Fund spending is limited by a financial budget of the requester.

## Desired situation
Limit fund spending by the amount of times a requester can purchase a product.

## Plan
Hide all financial balances, transactions and prices

## Figma
https://www.figma.com/file/kRHYEIvUM0sXfg6OvV04A8/Funds-in-%22Kind%22?node-id=0%3A1

**Comment by maxvisser** [comment]
whats the difference between this one and #137 ?

**Comment by jamalv** [comment]
This one has been superseded by #209
