### ISSUE TITLE
Me app should show a euro symbol before each amount

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#208]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Right now we display numbers as:

5

it should be formatted nicer e.g.

€5,-

or 

€5,00

or 

€5,25

Please be aware. Here in the netherlands we **don't** use smaller numbers (superscript) to show decimals.

**Comment by jamalv** [comment]
Example: 

![82198392-89d77200-98fc-11ea-981d-6b7f79252e68](https://user-images.githubusercontent.com/30194799/82199567-251d1700-98fe-11ea-89b1-6370496e2325.jpg)

**Comment by jamalv** [comment]
Another page where this is relevant is the payment confirmation screen for providers.

**Comment by maxvisser** [comment]
@jknnr could you create a task for this in Me repo?

**Comment by maartenfv** [comment]
@maxvisser Could you give a status update?

**Comment by jknnr** [comment]
@maartenfv This was done long ago, will appear in the next release I suppose

**Comment by maxvisser** [comment]
Should be in release v0.3.1
https://github.com/teamforus/me-ios/pull/37

This is for @GerbenBosschieter to still accept and test
