### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#209]
Figma prototype: https://www.figma.com/file/3DoB8bYyVuzL1KdHXA1WNK/%F0%9F%94%8D%F0%9F%93%9D%F0%9F%A7%91%E2%80%8D%F0%9F%A6%AF%E2%9A%99%EF%B8%8F-Actions

## **Concept Proposal: Balances (Flow of funds)**

The aim of the Stadjerspas is to support residents with a low income of the municipality of Groningen by giving a citizen a credit. The purpose of this document is to coordinate the flow of funds  in the renewed situation.

## **Definition of a credit**

The municipality defines a credit as _"Balance with which a card holder can purchase an offer." _Preliminary discussions have shown that when the municipality speaks of a credit, it means a credit in kind.

The credits issued to date on Forus' software are financial credits that can be effectively spent by the resident himself on specific products, offers and providers.

## **Context**

As described above, there is a difference between the activities at the municipality and at Forus. Since it is not feasible to change the policy, the software needs to be expanded. The purpose of this is to enable credits in kind.

In this document, the two current situations are different, in order to subsequently arrive at a plan for the optimal development and implementation of this functionality. 

## **Current situation of the municipality**

Each kind of Stadjerspas has credits in kind. For example, a resident can go swimming three times a year for free. By presenting the Stadjerspas to the shopkeeper, the credit is deducted from the pass. Then the transfer from the municipality to the shopkeeper takes place. The resident has insight into which funds are on the card, but not in the underlying financial flows.

## **Current situation in Forus**

When creating a fund on the platform, the municipality makes money available. The financial resources from this fund are then distributed among the inhabitants. Each resident will receive a voucher to be spent (for example, € 25). The resident can use his voucher to make purchases from retailers approved by the municipality. These retailers placed offers on the platform that were approved by the municipality. 

## **Challenges**

Because the financial flows in the above situations are different, it is important to find a form that, on the one hand, matches the wishes and working methods of the municipality, and on the other hand, is technically possible to implement within the time available for this topic.

## **Necessary developments**

In order to enable the workflow of the municipality, a new fund setting will be created. It is the setting to make the fund give out “Actions”

1. [**No longer show financial assets.**](https://github.com/teamforus/general/issues/206) \
With a financial fund, a resident has a financial balance to spend. This is not the case with a fund in kind. A resident can only purchase specific services and products in kind. No financial credit per resident has been established. We will remove every euro symbol on the platform and the amount associated with euro’s. No more balances on vouchers, no more visual prices on products on the webshop or the app. Prices for products are only available for provider and sponsor.
2. **Set a limit to the number of products to be used per inhabitant.** \
With a financial fund, the expenditure per inhabitant is limited by the financial credit that can be spent per inhabitant. This is not the case with actions, and the limit must be set in a different way. This is done by setting per offer how often a resident may use it. (for example 3 times). Example: A requester can reserve a product 3 times maximum
3. **Make specific offers per fund**  \
**In order to make a specific in-kind credit available to a target group (offers for parents other than for children), it must be possible for the provider to make an offer per fund. In this way, the same provider can offer different things to children than to parents. 
4. **Enable price agreements between provider and municipality.** \
**With a financial fund, the price is shown to the requester and as soon as payment is made, the amount is immediately debited from the financial balance. This creates a limit on how much every requester can spend. This is not the case with a fund in kind, and another limit needs to be set, which must be able to limit how the budget is spent. This is done by having the municipality and the provider make price agreements. This is a major change for Forus and should therefore be implemented in phases. 

    _Phase 1: Appointments via chat / direct contact_

    The amount that the provider enters is reimbursed by the municipality, and not shown to the resident. For example; the provider would like to receive a € 5 contribution from the municipality for the offer for a bicycle. The provider himself already gives a € 25 discount. This was agreed via chat. The provider also wants to receive € 70 for the bicycle from the resident. This is added in the description of the offer. The municipality therefore approves an offer based on the price proposed by the provider. If the municipality wants to negotiate the price, it can be done via chat or direct contact.

    _Phase 2: Contributions directly via the platform_

    The provider first enters the product price (for example, a bicycle of € 100). The provider then registers the offer for the fund. The provider indicates how much the provider wants to contribute (for example, € 25). The municipality can then enter the amount that the municipality wants to contribute to this offer (for example € 5). The amount that is left over is shown to the resident in the webshop (€ 70). The resident must therefore pay € 70 at the time of purchase. When scanning the card, a transaction of € 5 takes place from the municipal account to the account of the provider.

5. **Price adjustments must be approved by the municipality** \
**In the current approval process, an offer can still be adjusted by the provider after approval. It should be built in that this is no longer possible and that an adjustment must first be approved by the municipality. \

6. **Replace reservations with provider showing credits in app** \
With the current operation of the system, the resident chooses which offers he wants to reserve based on the financial credit available. In order for credits in kind to work in a user-friendly manner, the provider must see for himself which offer the resident can use, without having to first reserve it in the webshop. This is important because with financial credits it was still possible for the provider to directly debit the amount if no offer was made.

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/197

**Comment by maxvisser** [comment]
phase 2 of price agreements: https://github.com/teamforus/general/issues/130

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/196

**Comment by jamalv** [comment]
Related to 3? https://github.com/teamforus/general/issues/185

**Comment by jamalv** [comment]
@maxvisser could you add acceptance criteria to this epic?

**Comment by maxvisser** [comment]
Made some additions to figma prototype and I still have some feedback.
- I added webshop front page for highlighted action (Could have: maybe let sponsor pick actions for the highlight instead of picking random actions)
- list view of actions page. (removed discounts here aswell)

feedback on figma prototype
- Me-app is still missing; will this be a seperate IP?
- I see no provider approval, when do we show a provider on the map? how do we check if sponsor has validated the provider without approving the organization (is approving the organization neccassary legally?)
- There some new inputs field, would also be nice to see some states: for example where to show the error message, do want to write error messages for each field?

**Comment by maxvisser** [comment]
I would make seperate IP's for the indicators which show if there was any new action on a fund request (grey and red dots) and for the message above pages to give an explainer (the yellow card on product page)

**Comment by maxvisser** [comment]
Important for next sprint:
https://www.figma.com/file/qQrRGvPswp0bk0JQVT8dxI/%F0%9F%94%B5-Price-changes?node-id=0%3A1&viewport=886%2C466%2C0.23462998867034912

**Comment by maxvisser** [comment]
During sprint planning Valentin had a remark that he needs to see how the 'Edit fund' page looks on sponsor dashboard (currently only creation is shown)

Jamal gave feedback on Webshop: actions list and product details; He want a easier way filter on fund/voucher on actions list. Aswell as being able to click on voucher on action detail

**Comment by jamalv** [comment]
Remark: we need to inform users about new actions (using digest) - weekly would be good, or maybe monthly? Or let the user set this themselves?

Another suggestion: to also inform user about expiring actions in digest

**Comment by maxvisser** [comment]
Digest is out of scope for this IP right? maybe move that discussion to #152 #332

**Comment by maxvisser** [comment]
released
