### ISSUE TITLE
Don't get stuck when logging in with DigiD

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#210]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Municipality

### Change description

<table>
  <tr>
   <td>
<strong>Who</strong>
   </td>
   <td>Resident / card holder
   </td>
  </tr>
  <tr>
   <td><strong>Request</strong>
   </td>
   <td>I do not want to get stuck when I choose a new e-mail address and log in with an existing DigiD account
   </td>
  </tr>
  <tr>
   <td><strong>Problem</strong>
   </td>
   <td>In the current system, card holders sometimes create a new one account, while they actually want to apply for a new pass. In addition, it sometimes happens that they get stuck when they get a certain error message.
   </td>
  </tr>
  <tr>
   <td><strong>Idea</strong>
   </td>
   <td>Clear communication on the webshops in the form of error messages and click-through options so that they end up in the right place.
   </td>
  </tr>
  <tr>
   <td><strong>To do</strong>
   </td>
   <td>Create figma prototype
   </td>
  </tr>
</table>

**Comment by maxvisser** [comment]
this one I find a bit problematic; as you user already logged in; you need to log out the user and log it back in on the right account.

So should we automatically log the user out from the wrong mail and log him in on the right account? Some scenario's to chose from:
- log user out and directly in on right account
- ask user question first if he wants to login on the DigiD associated account
- Sent a mail to the account which the digid is associated to and ask user to logout and click link in mail

**Comment by maxvisser** [comment]
should discuss this one after 19 of oct as I see this would probably happen often.

**Comment by maxvisser** [comment]
Userflow:

Login with e-mail
Login with DigiD
Your DigiD is used by another account -> Logout and login with DigiD -> Do that now!

Loges out
Popup modal to login with DigiD

**Comment by jamalv** [comment]
@maxvisser is this still an issue after .15?

**Comment by maxvisser** [comment]
Yes
