### ISSUE TITLE
Master dashboard

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#213]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

**Note:** this is a _could-have_ so priority is low, but I believe it can offer value to our users.

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
Currently we offer a few different dashboards:
* Sponsor
* Provider
* Validator

We use different dashboards to separate functionality for the different roles. With the CMS we wanted to add even another dashboard. This got us thinking about the direction to take with this.

## Desired situation
It is important to separate functionality, but looking at other dashboards there might be smarter ways to do it. Having one master dashboard with a good menu structure could be simpler.

## Plan
* Work on and iterate on the Figma prototype until we approve a good MVP: https://www.figma.com/file/mDvjiNFYd8828kneFdEqgY/%F0%9F%A7%AAMaster-dashboard?node-id=1%3A30
* Start development on a new the master dashboard that will be available at: forus.io/admin 
* We keep supporting and maintaining old dashboards
* Internally test (dogfood) the master dashboard for a while, work out the kinks
* Slowly start migrating some users over to the master dashboard and learn from results
* Keep iterating until we are happy enough. Start more actively migrating users.
* Add depreciation notice / redirect to old dashboards to actively start migrating users.
* Phase out the specific dashboards; focus fully on the master dashboard.

**Comment by GerbenBosschieter** [comment]
This would help with preventing multiple dashboards. But I do see some new challanges:

- More options for the user will be confusing. Especially if all the roles are represented in this dashboard.
- Some users are already scared to click a button sometimes because they are not sure what it does or can't undo this anymore (we should btw definitely work on deleting, undoing and adding confirmation modals before people submit) . Adding more features and options can be even more scary.
- Don't see a reason to let the provider see sponsor features at all (ever)
- The flow of using our dashboard as a sponsor or provider is not optimal yet. It gets better every time. The master dashboards has like all the user flows in one dashboard.

**Comment by maxvisser** [comment]
Merging menus is one way; we could also add a role switcher. In the code we could keep seperate dashboards. We just add for example 'validator' / 'sponsor' links to the provider dashboard. 

Slightly off topic:
If it's just a menu change I don't see a reason to internally dogfood, maintain two for a while.

If we do consider maintaining two types of dashboards for a while I would consider for example switching from angularjs to angular or doing a complete redesign (for example merging design libraries with the cms)

**Comment by maxvisser** [comment]
Thought about it a bit more.
You could make more permissions and roles. On signup you give the organization a role which he applied for (provider) and can only get sponsor role when he goes through the signupflow which opens up more menu items

**Comment by jamalv** [comment]
I really like that idea about using roles as filters for what you see 😄 

It would mean another IP about possibly restructuring roles (I'd like that). It also means this IP needs a bit more thinking before we move forward I think it's a fun issue though, It really has the potential to make our product more clearly structured (I do see a good welcome screen as a requirement though))

**Comment by GerbenBosschieter** [comment]
I also like your idea with the roles and filters.
And @jamalv I also have some thought about and IP for restructuring roles ^^

**Comment by maartenfv** [comment]
In the future, this might be something to consider. However:

I would first like to focus on our current situation before we spend any time thinking about this. Especially during our implementation (project-100) we need every hour. This has to much impact on other departments besides dev.

- v2 version of the Sign up flow of the provider needs to go live and be useable.
- We need to make sure the MVP of the CMS goes live on the sponsor dashboard.
- CSV upload for multiple funds seems to need an update for Project-100 and Geertruidenberg multiple funds.
- Make sure we have a clear understanding in regards to the flow of funds as we need this for our compliance situation with DNB and for Groningen in regards to the "korting" functionality. aka presenting the QR-code but no money transaction.

@jamalv I suggest to move this to the lab repo. As it seems that the door of the lab is ajar and things are escaping from it.
