### ISSUE TITLE
Measuring customer satisfaction: Hotjar

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#214]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [x] Finances
- [x] Processes

Google doc: https://docs.google.com/document/d/1WegKeMUjXWsCsWOgmrLUURqashtO1reVg1RLPF9gPn0/edit#heading=h.t4y88l90hsok

**Comment by maxvisser** [comment]
Scope is probably bigger on implementation side of this area. I can't really estimate that part.  Financial part is aswell not really my expertise.
