### ISSUE TITLE
CR: Improve authorize device popup modal Me-app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#218]
## Desired situation

As a user I want a clear choice if I want to login using Scanner.

![image](https://user-images.githubusercontent.com/10818702/89156706-68853a00-d56b-11ea-977f-d131de98b42b.png)

https://www.figma.com/file/3F5FyFLJF1rzgsVto5KU1D/Me---Do-you-want-to-login%3F?node-id=85%3A127&viewport=131%2C399%2C0.5083333253860474

**Comment by jamalv** [comment]
Discord example:

![IMG_E47D168C1AC8-1](https://user-images.githubusercontent.com/30194799/83014388-e7676f00-a01e-11ea-9d41-ab73707976dc.jpeg)

**Comment by maxvisser** [comment]
Security feature lets do it ! 👍
