### ISSUE TITLE
Mobile signupflow workflow update

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#219]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Figma comment: https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7?node-id=935:3212#25532489

Scanning a qr code on the mobile signup flow isn't possible. This needs another way to authenticate. 

- [ ]  Only offer email signup, and let the provider download and install the app as the very last step, and tell them to log in using the same email adres they used to sign in here. "You are almost done, now you just need to install the app. Log in using [xxxx@mail.com] to finish signup"

And the test transaction would not be possible.

**Comment by danrminds** [comment]
@jamalv Can you please check this workflow for the provider on mobile? https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-prototype-signupflows?node-id=721%3A44

**Comment by jamalv** [comment]
@danrminds it seems you haven't really thought this trough 😅 

On mobile this is much simpler, you just need to add a link to "https://forus.io/DL" - no sms / qr code etc needed at all. I updated the figma file.

**Comment by jamalv** [comment]
This one needs more review; the texts on mobile are now very weird and confusing to the end user.

**Comment by maxvisser** [comment]
Agree. Welcome texts indicates that user will be redirect to dashboard while this is not the case (last step is downloading and login on Me-app.

**Comment by maxvisser** [comment]
Do you want to put this back on the backlog or close this one and create a new CR for looking at the texts?

**Comment by maartenfv** [comment]
@jamalv We have moved this issue back to the Figma proposal stage. Do we need a support button in the mobile design? After we have added this it can move to the design phase.

**Comment by jamalv** [comment]
@maartenfv the support button is there (screenshot from production)

(![IMG_78BA81B293CB-1_24.jpg](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/5bb2b157-3978-4939-9587-38e78aecb08b)

**Comment by jamalv** [comment]
Updated screens in figma:
![image.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/a308759f-fb3c-4740-b7eb-7386d982f2cb)

Url: https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-prototype-signupflows?node-id=935%3A3147

@maxvisser it would be really nice if this can still be fixed for the next release, as the current screens are pretty shameful

**Comment by maxvisser** [comment]
Good proposal. I will create development tasks. As this is already broken on production I don't see it as a show stopper for a release on monday. (its a must have)

**Comment by maxvisser** [comment]
Created two new tasks; could you check if this is sufficient as I am not sure which other things you changed in Figma...
https://github.com/teamforus/forus/issues/1661
https://github.com/teamforus/forus/issues/1660

**Comment by jamalv** [comment]
Tasks are good, just added a remark to the first one that it is only for mobile.

**Comment by jamalv** [comment]
> Good proposal. I will create development tasks. As this is already broken on production I don't see it as a show stopper for a release on monday. (its a must have)

I'll let you judge that :) but I would prefer to let it be branched from master and added to the release if possible

**Comment by maxvisser** [comment]
This is completely fixed in release v0.14.0
