### ISSUE TITLE
Provider signup: "Pretty url"

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#220]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Implementation department (Maarten & Linda)

### User stories in relation to the requested functionality

- [x] As a _Sponsor_ (municipality) I would like to have a webshop specific link for the providers I am inviting for my webshop or fund so that, they have a trusted way to sign up.

- [x] As a _Provider_ I would like to receive a link that I recognize and trust so that, I am sure I am dealing with the municipality.

- [ ] As a _Provider_ I would like to receive a link that is short and simple so that it is easy to ready and so that I can type it in when reading it from paper.

- [x] As a _Sponsor_ I want to recognize and present the name of the fund, webshop or municipality in the sign up link instead of the name of Forus, as I see the system as an extension of my services.

- [ ] As a _Sponsor_ I would like to find this link myself without asking Forus using my own sponsor dashboard so that, I understand where to find this link without being dependant on another organisation.

- [ ] As a _Sponsor_ I would like to be able to determine this link myself using my own sponsor dashboard so that, I can decide and adjust it without the help of Forus

- [ ] As a _Sponsor_ I would like to have an easy way to share this link so that I can single click to "copy this link" from my dashboard so that I, do not have to type the link.

- [ ] As an _Implementation manager_ I would like to have a way for the municipality to adjust this themselves using a dashboard so that it takes less time during the implementation process. 

- [ ] As an _Implementation manager_ I would like to have a reusable way to achieve generating a recognizable link so that I can repeat this process and customize for every implementation. 

### Change description
- Currently we are sending links such as (https://forus.io/provider/sign-up). We need to change this to something the municipality and shopkeepers understand such as **stadjerspas.nl/aanmelden** or **potjeswijzer.nl/aanmeldenleverancier** or something similar (best is to allow the municipality to decide without our intervention as each implementation has its own context.

- The sign-up link is used in many different places. Emails, website, Social media posts and written communication such as letters or potentially even posters. Therefor it needs to be short and simple to remember and type.

- People who are not very good with computers or English language need to understand as well. Therefore Dutch is prefered.

-  In written communication to shopkeepers, coming from the municipality, it is difficult to type: https://forus.io/provider/sign-up it would be better to have a link that is in line with the style of the rest of the communication.

- People have difficulty with: **.io**, the term **provider** and typing the "**-**" bar sign. It would be best to avoid these where and if possible.

**Comment by maartenfv** [comment]
Would I be possible to make this part of the CMS?

**Comment by maartenfv** [comment]
@linda-90 :)

**Comment by GerbenBosschieter** [comment]
I don't this is a must have ;) Must have supposed to be finished in the current sprint.

https://github.com/teamforus/general/blob/develop/manuals/development/labels.md

**Comment by jamalv** [comment]
It's a nice one though! I agree that in relation to our other tasks and since it's not in any current PVE it's a "should have" (as in our system **should _really_ have** this!) I heard that there are some ideas about this also from @dev-rminds and @maxvisser so I'll approve this to be worked on. 

We can use this issue to do some brainstorming on how to proceed and I'm also curious to hear about some options @maxvisser, I agree the CMS / webshop settings menu would be a good fit :)

**Comment by maxvisser** [comment]
yes there are some ideas about it! I do agree forus.io/provider/sign-up is not a great link at all. The option you propose have a variety of IP in them.

- translating routes to dutch
this is ofcourse pretty usefull but also has a big scope. you will need to change and test alot, aswell think about supporting the old links as maybe people have reffert to the current sign up flow and if you stop support links maybe it will break certain flows of use.
- creating easy link (slugs) for sharing a form a specific form
This is really great. if you host a dashboard on forus.io; its pretty hard to make links on a specific implementation. Would it be good enough to make a referal link like:
go to stadjerspas.nl/aanmelden and it would redirect you to forus.io/provider/sign-up or do we want to host the provider signupflow on the implementation? I dont see this as feasible.

**Comment by linda-90** [comment]
https://github.com/teamforus/general/issues/54

**Comment by maxvisser** [comment]
I think if we add this to the scope of #54 it would become pretty big. I think this will be a seperate epic.

**Comment by maxvisser** [comment]
discussed this with jamal and made an initial proposal.

**Comment by maartenfv** [comment]
![image](https://user-images.githubusercontent.com/30211022/107150431-0e23c680-695e-11eb-9c2f-16035f6c72b4.png)
 This url thing is still a problem for aanmelden and for inloggen. For aanbieders it is more logical to log into the actual webshop instead of Forus.

**Comment by maartenfv** [comment]
@maxvisser This one has been fixed right?

**Comment by maxvisser** [comment]
I believe this is a pretty URL :) https://stadjerspas.gemeente.groningen.nl/aanbieders/aanmelden

**Comment by maxvisser** [comment]
I will close it as it looks like @maartenfv agrees with this :)
