### ISSUE TITLE
Improve the Signupflow of the provider by splitting up de the flow

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#222]
Learn more about change requests here: https://bit.ly/39CWeEE

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
The steps of downloading the me app (sms) and scanning the QR code are on one step: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A2652
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/dbdb71bc-6509-43cd-a79b-29f11b2037e9)

## Desired situation
Split up the steps to improve the UX: 
Step 1: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A4562
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/51aef90b-3589-4fe3-b96c-895a4cce05c6)
Step 2: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A6482
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/43b977ac-9d07-4c1f-9665-853734a6dac8)

## Plan
- [x] @maxvisser could approve this IP?
- [x] @danrminds  could you  create the tasks?

### Requested by:
- Maarten

### Change description
- Figma Link: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=1%3A4560

**Comment by jamalv** [comment]
@maartenfv great CR! I approved it and turned it into an improvement proposal.

@maxvisser I think this one is pretty much done, could you also review it and create the tasks in Forus if you approve?

**Comment by maxvisser** [comment]
I would make a seperate proposal file in figma. Also what did you guys decide on the thing with a phone without sim card? Maybe we can make a seperate IP or add it to this one.

**Comment by maxvisser** [comment]
Added my comment in figma

**Comment by maxvisser** [comment]
I approve the IP. Tasks can be made.

**Comment by maxvisser** [comment]
@danrminds can be planned

**Comment by jamalv** [comment]
@danrminds @maxvisser I don't see this one in the latest updates to signupflow v2. what happened?
