### ISSUE TITLE
Finalize chat.forus.io migration to discord.forus.io

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#223]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
There's a couple of final steps to take:

- [x] updating the website
- [ ] updating email footers
- [x] send message in chat.forus.io

**Comment by maxvisser** [comment]
@jamalv will you write the message
@GerbenBosschieter can you update the website?

email footers is something for the whole team to do. Lets discuss this tomorrow in the daily call.

**Comment by jamalv** [comment]
@all (zodat iedereen een mailtje krijgt): Somewhere in the last few years, you have joined chat.forus.io, Forus has recently moved to Discord and this chat will no longer be used. If you'd like to stay in touch, please join us at https://discord.forus.io/ See you there! NL: Ergens in de afgelopen jaren ben je aangesloten bij chat.forus.io, Forus is onlangs verhuist naar Discord en deze chat wordt niet langer gebruikt. Als je contact wil houden, ga dan naar https://discord.forus.io/ hopelijk zien we je daar!"

**Comment by jamalv** [comment]
is the rocket.chat server still running somewhere? / did we send a message? :)

**Comment by jamalv** [comment]
ah, sure! how can I reach the server? 😅 before it was available at chat.forus.io but now that links to discord. do you maybe have a direct IP adres or something like that?

**Comment by RobinMeles** [comment]
![rocketchatforus](https://user-images.githubusercontent.com/15342635/115739384-2cf6fe00-a38e-11eb-92a6-bb9b4ce1fbbc.JPG)

Ah you are right. Chat.forus.io already links to Discord. I browsed locally to the Rocketchat server. For people who for some reason end up at the Rocketchat page, now get a message that Forus moved to Discord (as shown in the picture). So I think the next step is that I will stop and remove the instance at Transip.

**Comment by jamalv** [comment]
I'd still like to send the message, as it will send an email to the users in the server :)

Could you help me log in to the server? Do you know of an IP address or something that I could visit?

**Comment by RobinMeles** [comment]
@maartenfv requested me to close the instance at Transip. The Rocketchat server will be terminated when the contract ends (12th of June).

**Comment by jamalv** [comment]
I have sent the message, just not sure it arrived 😅
