### ISSUE TITLE
Standardize login success modals: e-mail confirm text

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#224]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
We have in the Me-app, on the dashboard and webshop alot of different kind of login success messages. Some have had text review, design review but others didn't. I would like to align them all with the most ideal text and design choices.

An example:
![image](https://user-images.githubusercontent.com/10818702/83602329-a74e4200-a572-11ea-8f95-407c8a0410fb.png)

## Desired situation
This IP about creating one standardized login success message which is the same for all products.

Example of desired situation:
![image](https://user-images.githubusercontent.com/10818702/83602405-c6e56a80-a572-11ea-910b-245625cb1d3d.png)

## Plan
https://www.figma.com/file/zHYkRxuahVLodzMtzGP2Uj/Login-success-modal?node-id=2%3A4

**Comment by maxvisser** [comment]
Maybe needed: SVG of email in multiple color styles of municipalities

**Comment by maxvisser** [comment]
@jamalv could you approve this one.

**Comment by maxvisser** [comment]
Points which should be included:
- The text feels like a computer is talking to a person and it also needs to be more action based. Instead of explaining  what happend we should tell them what to do. This is less text and less confusing.
- The title should change: don't tell them about we want to know if you have acces. Just tell them, we have send you a mail, please click the link to continue your application
- Don't refer to the blue button, just the link. Some e-mail clients don't know have css included or really minimal. Or there is a another reason why they don't display the blue button.  Whatever it is, if you expect a blue button and it's not there. Really confusing

**Comment by jamalv** [comment]
@maxvisser why is this a must have in your opinion?

**Comment by maxvisser** [comment]
I see it as part of project 100 and 31 finalizing signupflows

**Comment by maxvisser** [comment]
As gerben aswell indicates in #349

**Comment by maxvisser** [comment]
@maartenfv @linda-90 needs text review

**Comment by maxvisser** [comment]
@linda-90 lets discuss this one

**Comment by linda-90** [comment]
@maxvisser Vanmiddag tijdens dev/impl overleg?

**Comment by maxvisser** [comment]
Yes

**Comment by jamalv** [comment]
@maxvisser what is the status of this?

**Comment by maxvisser** [comment]
Currently not implemented yet

**Comment by maartenfv** [comment]
Status update?

**Comment by maxvisser** [comment]
Open as a pr to develop

**Comment by jamalv** [comment]
@maxvisser does the PR need review or can it be merged?

**Comment by jamalv** [comment]
Please let us know so that @danrminds knows if he needs to do anything

**Comment by maxvisser** [comment]
Sjoerd has wrote code but still needs to be reviewed.

**Comment by jamalv** [comment]
@maxvisser who needs to review? You? Valentin?

**Comment by maxvisser** [comment]
Both. I reviewed it yesterday. Me-apps still need tasks to check alignment
