### ISSUE TITLE
A button to directly login back in after 15 minutes of inactivity

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#225]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently you can only close the modal.
![image](https://user-images.githubusercontent.com/10818702/83603058-06f91d00-a574-11ea-8130-524b1adaf9fc.png)

I would like a option to directly log back in

**Comment by jamalv** [comment]
where basically you open the modal for filling email / scanning the qr code?

**Comment by maxvisser** [comment]
Indeed :)

**Comment by jamalv** [comment]
Great CR, I think it's a nice enhancement. Related: I was testing the flow of connecting your me app this weekend, and it is really starting to get pretty smooth 🚀
