### ISSUE TITLE
As a sponsor want to see how many activation codes are generated and activated per funds

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#226]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- A sponsor

### Change description
-
As a sponsor want to see how many activation codes are generated and activated per funds

**Comment by maxvisser** [comment]
Like your change request.  Some easy fixes I see are: We could add a number to the title; a sum of all prevalidation for a specific fund. For activated per fund we could add the activated state to the export which can be used in excel to get this sum.

There are currently not statistics for validators; we could add a validator landing page with some statistics @jamalv

**Comment by jamalv** [comment]
Jup, this is a very good CR and I like your proposals, next step is to make some suggestions in a figma proposal
