### ISSUE TITLE
CR: As a provider I would like to see a list of all funds I am applied to (Me-app)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#227]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter , providers

### Change description
-  As a provider I would like to see a list of all funds I am applied to (Me-app).

There are some municipalities that provide multiple funds. Some of these providers can;t scan all vouchers because they are not accepted. But there is no way for them to. see in the app for what funs they are accepted for. This results into thinking the app doesn't work properly.

Would be nice to have overview somewhere in the app where the provider can see all the funds they are accepted for. (maybe profile page , or display it when they get an error after scanning the voucher)

**Comment by maxvisser** [comment]
As the number of funds grow; I am not sure what the best way is to implement this. @jamalv

**Comment by jamalv** [comment]
Hmm, yea, good CR. An MVP could be to make an error message (full-page) saying something like:

not approved

this is a voucher for [fund name] by [sponsor name].
you are not approved for this fund
visit your dashboard at [xxx] to apply for this fund

need help? contact support

you are approved for the following funds;
(scrollable)[list of funds you are approved for]

[close]

**Comment by maxvisser** [comment]
could be part of #160 -> link to signupflow would be nice aswell.
