### ISSUE TITLE
As a provider I would like to have contact information of requester that did reservations

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#228]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter , multiple providers

### Change description
- As a provider I would like to have contact information of requester that did reservations

**Comment by maxvisser** [comment]
Maybe a duplicate of https://github.com/teamforus/general/issues/136

**Comment by maxvisser** [comment]
I personally see this as a pretty important one. I even find it a bit shameful that we don't offer anyway to contact the requester.

**Comment by GerbenBosschieter** [comment]
It's indeed a duplicate. Closed this one
