### ISSUE TITLE
Website: Customers story page

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#229]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Multiple teammembers

### Change description
- We don't have a customer story page anymore on the website. There are multiple people who would like to see this added to the website again.

**Comment by GerbenBosschieter** [comment]
Already discussed this @jamalv and @linda-90 

Possible MVP:
- One page with multiple customers and their experiences
- List of national organizations that are applied to the platform

This MVP will give us the option to already display other people their experience and proudly present the national organisations that are are already applied to the platform.

After the MVP we could create separate pages to really go in depth of every customer story.
The MVP page can be an overview that links to the specific pages.

**Comment by GerbenBosschieter** [comment]
@linda-90 Ready to start some figma magic again for the website ^^

**Comment by jamalv** [comment]
Some reference materials: https://www.figma.com/file/zWT7008xCnS6NtjDyYa65K/Website?node-id=0%3A1328 and
