### ISSUE TITLE
Website: Onboarding page

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#230]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Team members

### Change description
- You can login on the website, but it doesn't tell you why you should and how to register.
An on boarding page could be a solution. (@jamalv already worked on something)

**Comment by maxvisser** [comment]
If you want to add this page, please do :) Its a nice page.

**Comment by jamalv** [comment]
A concept: https://www.figma.com/file/gMRV1PpqxZfw2rOOlWZXTS/Onboarding-page?node-id=1%3A670

**Comment by jamalv** [comment]
this one is related to: https://github.com/teamforus/general/issues/135

**Comment by GerbenBosschieter** [comment]
@jamalv your concept is not about the website but about the dashboards.

**Comment by jamalv** [comment]
@GerbenBosschieter ah yea, thx, I linked the wrong one 😅  https://www.figma.com/file/lGrd2oSiUEZ6aLYF3dirt5/%F0%9F%94%B5Forus.io%3A-Organisation-signup-page?node-id=0%3A1
