### ISSUE TITLE
New label: "Type: Lab" and move lab issues

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#232]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
We internally have a "lab" repository for "fun but currently unimportant" issues. I'd like to create a new label here in the general repository: **"Type: Lab"**. This way it can be made clear that some issues are not urgent in any way, but they can live happily between the other issues :)

**Reasoning:** 

* Sometimes we have some ideas that are a bit wild :) We make them just for fun in the evenings and weekend; with this label they can go into the general repo (where we now make most new dev issues) while managing expectations. After implementing this label I'd also like to see which issues can be moved from the lab to general.
* Sometimes the ideas can be useful for current projects. Right now they are a bit burried and adding them one general repo with good labels fits the strategy we'd like to take with dev issues.

**Migration:** There's currently around 60 lab issues. I'd have to individually check to see if they can be moved to this public repo; of course this has a very low priority but since I see lab issues as kinda fun, I see this a bit as a evening/weekend side-project for me ;)

@maartenfv @maxvisser what do you think?
- [x] approval by max
- [ ] approval by maarten

**Comment by jamalv** [comment]
and maybe we can also add the **status: on hold** label to be extra clear about status

**Comment by maxvisser** [comment]
I personally have no strong opinion about this. Don't really care. :) so yes I approve.

**Comment by maartenfv** [comment]
I would keep the separation clear and keep them in the lab repo. Once an issue has matured it can be marked for approval and after a go it can be transferred to general. Therefore we do not need another label.

The main purpose of the lab is to keep the separation. In the past things escaped the lab and this creates distraction and chaos.

**Comment by maxvisser** [comment]
in practice no new issues are created in lab repo and its a bit weird that its closed

**Comment by jamalv** [comment]
> I would keep the separation clear and keep them in the lab repo. Once an issue has matured it can be marked for approval and after a go it can be transferred to general. Therefore we do not need another label.
> 
> The main purpose of the lab is to keep the separation. In the past things escaped the lab and this creates distraction and chaos.

Yea I understand, this has a lot to do with expectations though. And now we have priority labels to deal with this. There are now a lot of immature issues in general as well, but by labeling them with "could have", "on hold", "approval not requested", "not planned" etc we understand that this is nothing to worry about yet :)
