### ISSUE TITLE
Sign-up v2: Form asks me to add an office while I just did.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#233]
after creating an office , the form will redirect me to a page where it tells me to add an office while I just did. Weird UX

**URL tested:** https://dev.forus.io/provider/#!/sign-up-v2

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/738e0dba6c2a929e250dd5d0b975f7a7145ba4b3/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/738e0dba6c2a929e250dd5d0b975f7a7145ba4b3/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
@jamalv needs new text / figma update

**Comment by linda-90** [comment]
@maxvisser @jamalv Figma link?

**Comment by jamalv** [comment]
To be clear the form asks you to add **_another_** office, right? @GerbenBosschieter would making the button less prominent solve this confusion? https://www.figma.com/file/KJuU1juCHKRw9XJbnXU4zZ/Form-asks-me-to-add-an-office-while-I-just-did.?node-id=172%3A1001

**Comment by GerbenBosschieter** [comment]
@jamalv I don't know what makes it clear. I just think the current state is confusing.
And the button itself is not the problem. It's more the text.

The text tells the user to create an office while the organization already has an office (not another, just create the office). But the signup flow doesn't really take that in account. 

Situations:
- Organization has an office: the text could be something like: These are the offices we already know. Do you want to add another one?
- Organization doesn't have an office: text could stay the same.
