### ISSUE TITLE
Sign-up v2: Unclear what to do after you connect the Me-app with your profile via Desktop.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#234]
Unclear what tot do after you connect the Me-app with your profile via Desktop.

The user will see a succes message, but doesn't get any information about what to do next. This information was given on the step before. But people will forget if we asked them to leave the signup form to verify mail. 

## Task
- [ ] Add sentence: 
    - English: "Go back to the sign up form to proceed your application"
    - Dutch: "Ga terug naar het aanmeldformulier om uw aanmelding te voltooien"

**URL tested:** https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22?client_type=me_app-ios&implementation_key=general&is_mobile=1

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.api.forus.io%2Fapi%2Fv1%2Fidentity%2Fproxy%2Fconfirmation%2Fredirect%2F7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22%3Fclient_type%3Dme_app-ios%26implementation_key%3Dgeneral%26is_mobile%3D1&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22?client_type=me_app-ios&implementation_key=general&is_mobile=1&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/85febf9b19a1be01f88ab71dc9b49d1d0d9332fd/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/85febf9b19a1be01f88ab71dc9b49d1d0d9332fd/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.api.forus.io%2Fapi%2Fv1%2Fidentity%2Fproxy%2Fconfirmation%2Fredirect%2F7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22%3Fclient_type%3Dme_app-ios%26implementation_key%3Dgeneral%26is_mobile%3D1&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/7098ead0f3b6a9592691e14bc7c4dbb012e07adb6e8cfad25041d1710e6e4e831307ff042670181a5f59528d10c84983a21e93f7672f825edec850ce29733bc4e8e4e4418912136a5ed8fd5ba5ac5731b68241ace6b86fd314f44c7b45793c92a7d81d22?client_type=me_app-ios&implementation_key=general&is_mobile=1&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by jamalv** [comment]
Added a figma prototype: https://www.figma.com/file/1qV7a2t0XTbFnmlXPlduJk/%F0%9F%94%8D%F0%9F%93%9D%F0%9F%A7%91%E2%80%8D%F0%9F%A6%AF%E2%9A%99%EF%B8%8FEmail-confirmation-followup?node-id=0%3A1

For most people they were not applying for something (it is the generic email confirmation).

My proposal is as follows: show the normal email confirmation page with a link: how to continue? when they click the link we give them a smal f.a.q. about how to continue. (were you just signing in? you can close this page. were you applying trough a form? please continue on the form.)

Of course it would also be nice to "remember" that people were signing up for a form, and immediately redirect back to the form :) - don't know how difficult / feasible this is. @maxvisser?

**Comment by maxvisser** [comment]
As the sign-up happens though Me-app there is no indication of if the user just downloaded the app from app store or used the signupflow (download link via SMS) to get the me-app. So I see it currently as not feasibly;

We can however show it to all Me-app users as you already indicated.

**Comment by maxvisser** [comment]
needs text review

**Comment by jamalv** [comment]
Design review done: https://github.com/teamforus/forus/issues/1814

@maxvisser can this be planned for development?

**Comment by maxvisser** [comment]
Created the task

**Comment by GerbenBosschieter** [comment]
So where is the task, who assigned to this?

**Comment by maxvisser** [comment]
added it as blocked by https://github.com/teamforus/forus/issues/1955

**Comment by maxvisser** [comment]
PR is open to develop

**Comment by jamalv** [comment]
@maxvisser will this be in the next release?
