### ISSUE TITLE
CR: Vouchers (NL) to 'Tegoeden'

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#235]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholders

### Change description
Change "Vouchers" to "Tegoeden"
Change "Voucher" to "Tegoed" / "Tegoedbon"

**Comment by maxvisser** [comment]
Het fonds de stadjerspas krijgt straks stadjerspas-vouchers met Budgetten en reserveringen.

Tegoed zou dus mooi zijn.

Wel heel ingrijpend

**Comment by jamalv** [comment]
Klopt, de scope is groot, en aangezien we het op veel plekken gebruiken (emails, websites, folders, etc etc) er zeker niet te licht over denken. We moeten hier de communicatie afdelingen van klanten in mee nemen als we dit zouden willen. 

Overwegingen: Vouchers is niet "B1", tegoeden ook niet. Maar is wel een "nederlandser" woord. 
Er zijn ook andere mogelijkheden zoals "Waardebonnen" - maar in de gesprekken met de doelgroep werd wel een duidelijke voorkeur voor tegoeden uitgesproken. Een voordeel vanuit technisch perspectief is dat "tegoed" en "voucher" ongeveer even lang zijn dus dat er ws weinig impact is op design (bijv. op de groote van buttons etc.)

**Comment by maxvisser** [comment]
Wat wel grappig is dat hierbij misschien wel sprake is van 'voor corona' niet B1 en na corona wèl :P
https://www.consumentenbond.nl/reisverzekering/reisvouchers-bij-annulering-door-coronavirus
https://www.lc.nl/binnenland/Onrust-over-vouchers-concerten-en-festivals-neemt-toe-25733068.html?harvest_referrer=https%3A%2F%2Fwww.google.com%2F

**Comment by maxvisser** [comment]
Ben sowieso wel voor om met Stadjerspas de eerste h1 op de vouchers pagina van Budgetten te veranderen naar Tegoeden

**Comment by jamalv** [comment]
Related: vraag van maarten: https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK?node-id=4:1921#31859396

**Comment by linda-90** [comment]
🙏

**Comment by jamalv** [comment]
We hebben dit net besproken, maarten en linda vinden het ook een goed idee!

Volgende stap: plannetje maken om overal deze aanpassing (zo consistent mogelijk) door te voeren; enerzijds betreft de techniek, anderzijds betreft communicatie naar onze gebruikers / stakeholders

**Comment by linda-90** [comment]
@jamalv Heb hiervoor een issue aangemaakt. Communicatie/technischplan uitwerken: https://github.com/teamforus/implementation/issues/406

**Comment by maxvisser** [comment]
Released partly for Webshop

**Comment by maxvisser** [comment]
Needs discussion what needed to do this for platform

**Comment by jamalv** [comment]
it's also done in the me app. think it should also be done with the dashboards so that everything is alligned
