### ISSUE TITLE
CR: Validaties to Beoordelingen (NL)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#236]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal & Max

### Change description
Change validaties to beoordelingen
Change validator to beoordelaar

Reasoning: beoordelaar en beoordeling is B1, making it easier for people to understand our apps.
Of course this change request can be used to propose alternatives as well.

**Comment by jamalv** [comment]
Overwegingen: 
* We gebruiken al op enorm veel plekken "validator" in geschreven communicatie, we moeten dus goed nadenken over de scope en impact van de verandering.
* We gebruiken dit nog niet op veel plekken binnen de producten, dus daar is het (relatief) eenvoudig te implementeren als we dat zouden willen.

**Comment by maxvisser** [comment]
Vaak laten we alleen de positieve beoordelingen zien op de record en doen we niks met negatieve beoordelingen. Misschien kunnen we daar nog iets mee.

**Comment by jamalv** [comment]
Ja dus een bevestiging eigenlijk? Die gedachte triggert ook wel weer mogelijkheden: https://synoniemen.net/index.php?zoekterm=bevestiging

**Comment by jamalv** [comment]
Andere kant van die gedachte is om meer te gaan doen met "negatieve" beoordelingen.

**Comment by maxvisser** [comment]
Zoiets dus:
Validator naar Beoordelaar
Validatieverzoek naar Beoordelingsverzoek
Validatie naar Bevestiging

**Comment by jamalv** [comment]
Yes I like it. Aangezien we "validator" al wel heel lang hebben gebruikt in externe communicatie ben ik wel ook heel benieuwd wat @maartenfv en @TomForus hier van vinden; in het product is nog niet veel "legacy" aangezien het hier nog niet veel gebruikt wordt. Maar in documenten (offertes, onderzoeken etc) wordt "validator" veel gebruikt. Dit veranderen naar beoordelaar heeft in die zin wel impact. 

Voordeel is m.i. wel dat "beoordelaar" B1 taalniveau is en dat men hierdoor makkelijker begrijpt wat er bedoeld word.

**Comment by jamalv** [comment]
Wat ik wel belangrijk vind:

Een validator/beoordelaar beoordeelt **niet** of je recht hebt op een fonds, maar puur de **juistheid** van jouw informatie.

Doordat validator een "nieuw" woord is hebben we meer ruimte om dit "nieuwe" concept in te vullen. Bij beoordelaar hebben mensen al wel veel associaties en kan wellicht ook verwarring ontstaan. Het lijkt misschien meer of je beoordeeld of iemand recht heeft op een fonds, maar dat is expliciet niet het geval. Validatie gaat over de herbruikbaarheid van informatie.

**Comment by linda-90** [comment]
# Voorstel
Validator naar Beoordelaar of controlerende organisatie
Validatieverzoek naar Beoordeling aanvraag (verzoek is niet B1)
Validatie naar Goedkeuring/goedkeuren (bevestiging is niet B1)

Voorbeeld validator:
Laat de QR-code scannen door een organisatie die controleert of uw gegevens kloppen.

**Comment by maxvisser** [comment]
Ik zou dan wel consistent beoordeling gebruiken dus bijv Beoordelende organisatie

Laat de QR-code scannen door een organisatie die beoordeeld of uw gegevens kloppen.

**Comment by maxvisser** [comment]
Validatie zou ik ook veranderen naar Beoordeling

**Comment by jamalv** [comment]
bij approval van @maartenfv @linda-90 @TomForus kiezen we voor beoordelaar

**Comment by maxvisser** [comment]
@jamalv could you check if they approve?

**Comment by maartenfv** [comment]
I approve

**Comment by jamalv** [comment]
onderdeel van stijlgids
