### ISSUE TITLE
CR: Make dashboards mobile ready

### ISSUE THREAD

**Issue by NelisVanWijk** [teamforus/general#237]
**Is your feature request related to a problem? Please describe.**
The Dashboards are at this moment not really optimal for mobile use.

**Describe the solution you'd like**
If it's possible to create a special mobile dashboard which allows the user to do all the tasks you can do on the desktop that would a nice solution

**Describe alternatives you've considered**
- Change the layout on the current dashboard to make it fitting and easy to use on a mobile device
- Leave the dashboards as they are if you say: 'The dashboard was never meant to be used on a mobile phone'

**Additional context**
This is the dashboard now on a mobile phone
![Screenshot_20190417-121610](https://user-images.githubusercontent.com/25053173/56281180-449aac80-610c-11e9-9c0d-eb85dd871c83.png)
![Screenshot_20190417-121602](https://user-images.githubusercontent.com/25053173/56281181-449aac80-610c-11e9-8564-81f4c70e1bb5.png)
![Screenshot_20190417-121527](https://user-images.githubusercontent.com/25053173/56281182-45334300-610c-11e9-9a33-672161eb0011.png)
![Screenshot_20190417-121517](https://user-images.githubusercontent.com/25053173/56281183-45334300-610c-11e9-95c7-44c4298748cf.png)

**Comment by maxvisser** [comment]
I am going through some old issues on Forus which were closed but probably nice to have in our general repo. I will reopen some of these and move them:)

**Comment by jamalv** [comment]
has been added to roadmap: https://roadmap.forus.io/c/31-beheeromgeving-mobiel-vriendelijk-maken
