### ISSUE TITLE
Add date to exports (date of transaction and date of bunq transaction)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#238]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Sponsor

### Change description
As a sponsor I'd like to see both the moment of the transaction and the date of the bunq transaction in the export.

**Comment by maxvisser** [comment]
As in both dates? I think we currently don't store the bunq transaction date.

**Comment by maxvisser** [comment]
There is a PR for this now

**Comment by maxvisser** [comment]
Is on production release with v0.14.0; transactions happened before this release need to be migrated to support these new dates

**Comment by maxvisser** [comment]
Checked again. Seems to be only in the database still needs to be in export

**Comment by maxvisser** [comment]
Created a task
