### ISSUE TITLE
CR: Bundled transactions for sponsor

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#239]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Providers and sponsors

### Change description
As a provider I would like to receive bundled transactions instead of receiving a separate payment each time. 
As a sponsor I would like to send bundled transactions instead of doing separate payments each time. 

[internal doc](https://docs.google.com/document/d/1E6nRdKhH3YC0jz-rneX0UYxFw33Xk_b5kJDFR7Erwoo/edit)

**Comment by maxvisser** [comment]
Hi! I think this is a duplicate of https://github.com/teamforus/general/issues/143 Could you check if this is the case and leave your feedback there?

**Comment by maartenfv** [comment]
@maxvisser #143 is indeed the same issue but requested from a different role. During a conversation with another sponsor, this was requested again.

**Comment by maxvisser** [comment]
As its the same functionility (same change) I would propose to close this one.

**Comment by jamalv** [comment]
Added it to #143, closing this one in favour of that one.
