### ISSUE TITLE
CR: Me-app align expired vouchers limitations with backend

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#240]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Me-app is currently not prepared to handle the limitations we have on backend considering expired vouchers. In the app it still possible to see the QR-code and the option to send it by mail to yourself. We should align the apps with the backend. 

#### Additional information
https://github.com/teamforus/me/issues/448

**Comment by jamalv** [comment]
Yes. Good point. I think it is related to this one: https://github.com/teamforus/general/issues/160

Basically we need a good way to handle expired vouchers in the me app, if I understand it correctly. Here I would also say we maybe should think about how to show it, and maybe add the option to archive vouchers as well.

**Comment by jamalv** [comment]
For certain use-cases (for example discounts) it can still be useful to present the voucher to the provider to show that you are eligible for the discount, even though there is no budget left. That's also what #160 is about. We should think about how to show that.

**Comment by maxvisser** [comment]
Until this is fixed, on a development issue (in me repo) we decided to hide expired vouchers for now in Me-app. @jamalv a voucher with no balance is does not need to be expired; Valid no balance voucher will just be shown. I see no issue with #160 ;

**Comment by jamalv** [comment]
Allright; I see https://github.com/teamforus/me/issues/448 is closed, does that mean that this issue can be closed as wel?

**Comment by maxvisser** [comment]
Should be released first

**Comment by maxvisser** [comment]
MVP is fixed, let make a proper screen for this (design)

**Comment by jamalv** [comment]
MVP is fixed? Then I think a proper screen is a should have?

**Comment by maxvisser** [comment]
yeah both apps dont show the buttons/qr codes
