### ISSUE TITLE
Create new logo for potjeswijzer

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#241]
Current logo:

<img width="299" alt="Screenshot 2020-06-18 at 11 06 55" src="https://user-images.githubusercontent.com/30194799/85001356-d4464b80-b153-11ea-93c7-952112276dc3.png">

In dutch "potje" means jar - as in - a jar of money you have for a special purpose. "Wijzer" means pointer or director. So the meaning behind the name is that this is a website that points you to the right money jars. 

I think we can do something nice with this and make a more visually appealing logo. 

Just some input:

![image](https://user-images.githubusercontent.com/30194799/85001643-33a45b80-b154-11ea-8c22-0be1b3f400a0.png)

**Comment by GerbenBosschieter** [comment]
@jamalv the jar with the index in it xD.

**Comment by maxvisser** [comment]
This is done by Lena; there are a few concepts. The one I liked will be added to new navbar implementation

**Comment by jamalv** [comment]
<img width="219" alt="Screenshot 2020-08-11 at 14 31 54" src="https://user-images.githubusercontent.com/30194799/89897510-695b4300-dbdf-11ea-81e4-40338f1114c5.png">

**Comment by linda-90** [comment]
Hi @Myshelova,
The past two weeks we have collected feedback on the Potjeswijzer logo and website. 
Everyone likes the piggy-bank logo very much!

<img width="249" alt="Schermafbeelding 2020-10-13 om 13 05 10" src="https://user-images.githubusercontent.com/36952230/95852846-c0eb6b80-0d54-11eb-8076-f3eb33e69b12.png">

They also shared a bit of feedback:
- Make the piggy bank a little less stock image
- Add a coin slot in the piggy-bank
- Make the QR code more recognizable (it's a bit too abstract now)
- The color is good, looks very fresh!

The next meeting with the project team is scheduled this Thursday morning. It's a bit of a short notice, but could you share a new version of the logo before Thursday?

Another question from the team. They would like to add icons to the website.
Like:
- School book
- Clothes
- Bike
- etc.

Do you have an idea? Could you design this?
If you have any questions, please let me know!

**Comment by maxvisser** [comment]
Will work on this during the weekend

**Comment by Myshelova** [comment]
<img width="478" alt="Screenshot 2020-10-26 at 11 06 25" src="https://user-images.githubusercontent.com/22478043/97159599-68b46080-177b-11eb-9793-0be7116fce02.png">

**Comment by maxvisser** [comment]
@linda-90 is the new logo approved?

**Comment by linda-90** [comment]
@maxvisser I presented the logo to the municipality. Positive reactions!
In the meeting before my vacation there was another comment / question about another logo that looks like it.

@maartenfv Did you talk to Erwin about this when I was on vacation?

**Comment by maartenfv** [comment]
Yes, not a problem. Logo does not look like it. We can proceed.

**Comment by maxvisser** [comment]
Whats the status now; can this be implemented? Are we sure this time???

**Comment by maxvisser** [comment]
Is implemented
