### ISSUE TITLE
Pipeline: Text review should be a part of the pipeline

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#242]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Our development is going and going, new screens and features are being added to our apps and platform. This results in a lot of textual additions or changes. As an acceptance tester I see a lot of texts that are grammatical incorrect, spelling mistakes or not no consistent use of words.
Would be nice if we could do text reviews during the review moment into the pipeline. 

- Good quality text (or at-least no obviously textual mistakes) will result into a higher quality user experience.
- It will save time, no new issues have to be created if this is already intercepted during review moment instead of acceptance moment.

**Comment by maxvisser** [comment]
I agree. Should be done in Figma in the improvement proposal. Aswell as error messages, success messages and any other messages.

**Comment by jamalv** [comment]
Yes, agree aswel. The prototyping phase would be most suitable @maxvisser so that would be after **accepting** the improvement proposal (the main concept) - the way I see it a figma file for an _improvement proposal_ is "low fidelity" - and the _prototype_ should be "high fidelity" so it can be handed over to the developer : 

<img width="269" alt="Screenshot 2020-06-22 at 11 28 12" src="https://user-images.githubusercontent.com/30194799/85271723-767b7180-b47b-11ea-92ce-59d815f10211.png">

**Comment by maxvisser** [comment]
Well the pages should be added somewhere in the process. if you want linda/maarten to be able to review it quicker I would say add as much to the low fidelity (IP) as possible.

**Comment by jamalv** [comment]
I agree with that, but it needs to also be clear what is the _real_ moment that review is **needed**. There are many proposals. If we make clear that every **prototype** needs a review, then it is very clear that they can just check if there's any prototypes that need to be checked (using the 📝), this way we have a clear proces, so we need less communication overhead. But of course, if they have some spare time, they can also go trough proposals and already start looking at those.

**Comment by maxvisser** [comment]
whats the DoD? :) I think this is implemented.

**Comment by jamalv** [comment]
I agree this is implemented :D
