### ISSUE TITLE
Pipeline: Impact & risk analysis four our current implementation should be part of Improvement proposal.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#244]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- We are building some nice features. But not all features are going to work with current implementations. Or even worse, it's possible that some features are going to break. 

We really need a good impact & risk analysis for some features we want to release. Mistakes are easy made and can have so much impact. We should foresee this and prevent this in the proposal phase.

Example:
Release/ v0.12.0 can't be accepted.

**Comment by jamalv** [comment]
Yes, completely agree! Same as with accessibility (https://github.com/teamforus/general/issues/243#issuecomment-646814204) I'd like to propose to add it to the prototyping phase - here I classified it as "needs technical review" - but maybe we can think about that a bit more:

<img width="253" alt="Screenshot 2020-06-22 at 11 22 49" src="https://user-images.githubusercontent.com/30194799/85271151-b5f58e00-b47a-11ea-8ac1-7b9b5e210f47.png">

**Comment by maxvisser** [comment]
As we grow this process gets harder and harder as you need someone who knows how our customers use the system, and if you change a feature (for the better) it could break their experience or use.

**Comment by maxvisser** [comment]
@jamalv I think its not feasibility or technical review what gerben is talking about (not something Dan or Valentin could answer)

**Comment by GerbenBosschieter** [comment]
@jamalv this is not about technical review. This is more about new features and current users. Our new features and the edge casus that we should take into consideration.

For example:
- Proposal of aanvraag en toekenningen for stadjerspas pas and the document I wrote. (thats my risk analysis)
- Current states of all the textual update https://github.com/teamforus/general/issues/313
