### ISSUE TITLE
CR: Google play console notice: Check app icon requirements

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#245]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Max Visser

### Change description
![image](https://user-images.githubusercontent.com/10818702/85027380-2601cc80-b17a-11ea-8260-20a9e242cb19.png)
https://developer.android.com/google-play/resources/icon-design-specifications

**Comment by maxvisser** [comment]
@jknnr could you give an update on this one? Is there anything needed?

**Comment by jknnr** [comment]
we already use uniform icon, will double-check sizes with Lena

**Comment by maxvisser** [comment]
@Myshelova sent new icons to @jknnr 
Changed icons should be uploaded to Android developer console or in app? Could we talk about this @jknnr

**Comment by maxvisser** [comment]
@jknnr could still sent me the icons?

**Comment by Myshelova** [comment]
Icons were added to a console
