### ISSUE TITLE
Improving funds page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#247]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [x] Processes

## Current situation
Fund page is currently hidden from menu and is not accessible for users.

## Desired situation
Making funds page accesible. Improving UI/UX of this page.

## Plan
I would like to change the name of the page from 'funds' to 'requests'. As well adding statuses to the fund cards if there is a fund request for the requester. This page can also contain the messages between Sponsor and requester. 

I made small figma prototype to show the improvement:
https://www.figma.com/file/JQOpMquZiDvI2WwKdw2iDC/Improving-funds-page?node-id=1%3A3653

**Comment by maxvisser** [comment]
Part of this IP is adding chat to funds page; removing criteria from list view. Showing state of fund request.

**Comment by maxvisser** [comment]
No new design elements are needed. Hopefully alot of the code of products chats can be reused.

**Comment by jamalv** [comment]
I would like to see if we can reuse the design patterns we are using for the providers and offers for the funds page as well; I think more standardization is better in this case :) as this page grows it will need search, filter and pagination just like the other pages. If we can use the same components for al pages that will be nice

I added the templates from the library to figma, let's experiment

**Comment by maxvisser** [comment]
I would make the requesting page more similar to vouchers page; maybe vouchers page can aswell look more like offers/providers; maybe even making a more prominent connection between funds page and vouchers page.

**Comment by maxvisser** [comment]
I close this issue in favor of #366
