### ISSUE TITLE
Change request: Prices: accept a comma

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#248]
**Support Ticket ID:** #1534

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @Gerbenbosschieter, provider

### Change description
- As a provider I would like to have the option to enter prices with a comma instead of a dot when adding my product to the webshop.

**Comment by danrminds** [comment]
Planned. https://github.com/teamforus/forus/issues/1609

**Comment by maxvisser** [comment]
Don't know how to fix it with native fields

**Comment by maxvisser** [comment]
Should be in release v0.13.1
