### ISSUE TITLE
Change feedback to support

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#249]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [ ] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
- feedback@forus.io is currently being used to send message to us via the Me-app. This mail should is created to receive feedback but is being used to ask questions. The mails send via the Me-app are sent to support and some team members with the intention to receive and process feedback and if a question is being asked it can be answered by support.

## Desired situation
- use support@forus.io instead of feedback@forus.io. Inform the users by telling them something like: Do you have any questions or feedback? Contact us!

My assumption is that all the people who are connected feedback@forus.io are already experiences these mails as spam cause most of it is just support.

In addition, we did some restructuring of how we process information from support so no feedback or change request from users perspective will be lost :D

## Plan
- Change mailadres and text in Me-app
- @maxvisser remove feedback@forus.io

done

**Comment by maxvisser** [comment]
@jknnr this can be planned

**Comment by jamalv** [comment]
@jknnr could you give a status update of this issue?

**Comment by maxvisser** [comment]
I will close this; I can only check it on android its done there.

**Comment by jamalv** [comment]
done on ios as wel
