### ISSUE TITLE
CR: implementation dashboard icon

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#250]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Menu item now uses a location pin which does not really resambles what the page is about.

![image](https://user-images.githubusercontent.com/10818702/85554518-453ea500-b625-11ea-9dd1-214cb72a94e7.png)

I would suggest to change the menu image to something like a shoppingcart with a cog inside.
![image](https://user-images.githubusercontent.com/10818702/85554449-33f59880-b625-11ea-936e-21c5374e0934.png)

storefront would also be a good option (if easier)
![image](https://user-images.githubusercontent.com/10818702/85554618-61dadd00-b625-11ea-982e-45eb919814db.png)

**Comment by maxvisser** [comment]
planned for this sprint

**Comment by jamalv** [comment]
no longer relevant?

**Comment by maxvisser** [comment]
It's added to the library but not implemented yet
