### ISSUE TITLE
Website: Update texts

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#251]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
We have new texts for the website. I think we should first do a design review, and then add the texts to the website 😄 

[This is the source for the texts](https://docs.google.com/document/d/1RCtNim6NqYOfHaHYWuigigqmcAl2vGiIw4f3SBtzuZk/edit), most of them have already been added to [figma](https://www.figma.com/file/KD2HGR90hiR5kDBODj7DBw/%F0%9F%94%8DWebsite?node-id=563%3A0)

@GerbenBosschieter @linda-90 what do you think as next steps on this? Would it be good to plan a design review by lena before updating the texts? Or should we first update the texts / structure, and then maybe review the designs later?

**Comment by GerbenBosschieter** [comment]
@jamalv i don’t think there are to many design differents that are to shocking. So let’s just add the new texts for now. And let lena do an review of the complete design

**Comment by GerbenBosschieter** [comment]
Not sure If I am the one that can grant an approval but I think we came to an agreement

**Comment by jamalv** [comment]
@GerbenBosschieter haha, i believe you just did ;)

**Comment by maxvisser** [comment]
Just looked at Figma. Really nice guys! Texts are great.

**Comment by maxvisser** [comment]
Not sure If I am the one that can grant an approval but I think we came to an agreement

**Comment by jamalv** [comment]
Yea, really happy with the texts as wel!

**Comment by jamalv** [comment]
Not sure If I am the one that can grant an approval but I think we came to an agreement

**Comment by GerbenBosschieter** [comment]
Not sure if I am the one I can approve this message.  But i think we came to an agreement.

**Comment by jamalv** [comment]
@GerbenBosschieter could we plan this in? we want to go towards the strategy where we use the website as login, instead of the implementation landing pages, but for this the website should be proper, and texts are a nice piece of this! 😄

**Comment by jamalv** [comment]
Texts are here: https://github.com/teamforus/forus-frontend/blob/7ade8d1446580aadd07a6d7455ce57f902df115f/src/sources/forus-platform/pug/tpl/pages/website/home.pug

**Comment by maxvisser** [comment]
@jamalv should be live right? could you check and maybe close this issue?

**Comment by jamalv** [comment]
it's live!
