### ISSUE TITLE
Text reviews Figma proposals

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#254]
# Description
Text review Figma proposals

# Meeting
Every Tuesday from 9 till 10 am

**Comment by linda-90** [comment]
## Agenda 30-06
- Beschrijving:Aanmeldformulier
- Oude passen
- Mails

**Comment by jamalv** [comment]
Hey @linda-90  en @maartenfv, you can have a look at this folder (prototypes): https://www.figma.com/files/project/6040013/%F0%9F%94%8DPrototypes

If there's an 📝 icon in the file name, it means the texts still need review. When you gave your final blessing, could you change the name of the file by removing the 📝 icon?

**Comment by maartenfv** [comment]
Closed needs to be time tracked on the individual issue.
