### ISSUE TITLE
Provider sign-upflow: Image cropper

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#257]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Needs new design for desktop
Needs new design for mobile (or leave it out)

**Comment by jamalv** [comment]
What's the status of this? Why is this needed?

**Comment by maxvisser** [comment]
We still have the old design on desktop. Mobile status is that is is usable but really sketchy

**Comment by maartenfv** [comment]
@jamalv Can we move this one to Quick Scan stage? Is it clear enough?

**Comment by maxvisser** [comment]
Desktop 
![image](https://user-images.githubusercontent.com/10818702/87652956-224f6e80-c755-11ea-9f4d-2e2f8fbbadef.png)

Mobile 
![image](https://user-images.githubusercontent.com/10818702/87653001-35623e80-c755-11ea-9570-8496be000665.png)

probably we should first fix mobile image cropper; I would just remove it on mobile

**Comment by maxvisser** [comment]
@jamalv could you check priority and see if this can be done as part of a project? As there is already a design for (which was left unfinished? not reviewed atleast) And probably #305 will also need something like this.

**Comment by jamalv** [comment]
@maxvisser said this is fixed and can be closed :)
