### ISSUE TITLE
Fund list of signupflow: add fund image

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#262]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
![image](https://user-images.githubusercontent.com/10818702/86566233-9a55b180-bf69-11ea-9df7-e7779ece9a21.png)

Would be nice to show fund image on this list; As the list can get pretty big it is a nice way to make your fund more identifiable

**Comment by jamalv** [comment]
I created a figma prototype:

https://www.figma.com/file/L7VH4Wj2LRZu5fuYi5jbAH/%F0%9F%94%8D%E2%9A%99%EF%B8%8FSignupflow-fund-image?node-id=0%3A1

- [ ] Needs design review
- [ ] Needs development issues

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1690

**Comment by maxvisser** [comment]
Should be on production on 17 of august

**Comment by maxvisser** [comment]
released
