### ISSUE TITLE
IP: Mutations in prevalidations

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#264]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [ ] Design
- [ ] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
Data shared with Forus is now shared with the condition that the person has a year's right to activate. (the data can therefore be kept for a year instead of a month). Therefore, data cannot be changed, deactivated or declared invalid at this time. When a CSV upload with known BSNs is now uploaded, the system skips these social security numbers.

## Desired situation
In some cases prevalidations become invalid, (the data  is outdated). A request came in to be able to update the list monthly.

## Plan
Instead of skipping existing BSN-number, we should replace them (update the data associated)

**Comment by danrminds** [comment]
https://github.com/teamforus/general/issues/76

**Comment by maxvisser** [comment]
https://www.figma.com/file/RolmXCeR5lPfMlnNzDU8lO/%F0%9F%93%9D%E2%9A%99%EF%B8%8FDuplicates-on-voucher-generator?node-id=3%3A1128&viewport=1041%2C662%2C1

**Comment by maxvisser** [comment]
`Are you sure you want to create extra vouchers for these ${items.length} email addresse(s)`,
"that already have a voucher?"

**Comment by linda-90** [comment]
# 1
## EN
hero_title: "Duplicate email adresses detected.",
Description: `Are you sure you want to create extra vouchers for these ${items.length} email addresse(s)`,
"that already have a voucher?"

##NL
Er zijn dubbele e-mailadressen gedetecteerd. Weet u zeker dat u extra vouchers wilt aanmaken voor deze <<amount>> e-mailadressen?


#2
## EN
hero_title: "Duplicate prevalidations detected.",
Are you sure you want to create extra prevalidations for these ${items.length} uid(s)`,
"that already have a prevalidation?"

##NL
@maxvisser Prevalidation??

**Comment by maxvisser** [comment]
Activaties (activatiecodes/bsnnummers met klaargezette gegevens/ mensen die recht hebben)

**Comment by jamalv** [comment]
@maxvisser could you give a status update of this issue? any changes?

**Comment by maxvisser** [comment]
In release v0.14.0 should be tested with cases like Westerkwartier/SDOA/Geertruidenberg (that skipping still works) aswell as Groningen (replacing)

**Comment by maxvisser** [comment]
This is released to production
