### ISSUE TITLE
CR: Disable requesting fund via signupflow

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#266]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
@maxvisser 

### Change description
As a sponsor I would like to enable/disable the signupflow for a fund.

Municipalities upload prevalidations in bulk which contain data about requester who are eligible for a fund. If a municipality decides to not use Forus its requester signupflow for a fund. 

They should be able to disable the form. https://github.com/teamforus/forus/issues/795 It should still be possible for the user to login with DigiD and redeem prevalidations (and get a voucher this way)

**Comment by jamalv** [comment]
@maxvisser do you expect anything from me in this?

**Comment by maxvisser** [comment]
needs figma proposal (where can sponsor turn off requester signupflow)
As you should still be able to 'apply' by activating by DigiD or Activation code we should see how the form shows this to the user. Probably aswell a good idea to add this to figma.

Questions I have:
Does the edit fund page change
Does the DigiD step change?

**Comment by maxvisser** [comment]
Discussed this one with @danrminds he will check create a proposal for fund settings.

**Comment by jamalv** [comment]
Ah, nice, closed this by accident trough zenhub :) 

I did create an (empty) figma file for it: https://www.figma.com/file/jwFaeDJ09fNdym7rJGHcBF/Disable-requesting-fund-via-signupflow?node-id=0%3A1

**Comment by maxvisser** [comment]
released

**Comment by maxvisser** [comment]
No frontend implementation for this yet.
