### ISSUE TITLE
Smarter (semi) manual sorting of vouchers.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#267]
# Smarter (semi) manual sorting of vouchers.

As a user I would like to sort my vouchers in the me app.

When a new voucher appears, it is automatically at the top.
So, all vouchers are "sorted" from new too old by default.
User can tap and hold on a voucher and drag it to re-order it in their list.

Optional: swipe sideways on a voucher to show context menu with option to hide voucher.
When scrolling all the way down, there can be a [view archive] button. When clicking you see the archived vouchers. You only see the button if you have archived vouchers.

**Comment by jamalv** [comment]
I think this is MVP:

[RPReplay_Final1594062031.mov.zip](https://github.com/teamforus/general/files/4880794/RPReplay_Final1594062031.mov.zip)

We could leave the other things (swipe to hide / link with backend) out of scope.

**Comment by maxvisser** [comment]
needs project label

**Comment by jamalv** [comment]
Moved to productboard due to inactivity; https://app.productboard.com/inbox/notes/15686080
