### ISSUE TITLE
Email digest needs a language check

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#268]

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-backend/tree/develop/resources/lang/nl/digests

**Comment by maxvisser** [comment]
Figma link for texts: https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/%F0%9F%A7%91%E2%80%8D%F0%9F%A6%AF%F0%9F%94%8D%F0%9F%93%9DMails?node-id=190%3A0&viewport=490%2C-231%2C0.8103119134902954

**Comment by maartenfv** [comment]
@maxvisser @jamalv The screens in Figma are not ready for the language check.

Examples:

- We need texts to be able to understand the functionality. The texts in the designs should be written out completely. ![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/244f2abe-0afb-4736-bf9a-a4af88551743)

- The text needs to make sense. Some text are just randomly placed. (Kindpakket?)
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/69750497-4702-42af-8322-7bc74f18c875)

We will place this issue back in the pipeline to the Figma step. 

Please update the Figma screens so that they display all of the needed functionality.
Please add the needed texts.

**Comment by maxvisser** [comment]
@maartenfv these are already in code
not sure if you saw the files:
https://github.com/teamforus/forus-backend/tree/develop/app/Digests

**Comment by maxvisser** [comment]
You want me to copy over the texts from the code to figma?
