### ISSUE TITLE
CRUD in Me

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#269]

**Comment by maartenfv** [comment]
Needs a language check.

Could you please add Figma link?

**Comment by maxvisser** [comment]
https://www.figma.com/file/72RtRfLFzzzLaN92EtJwxS/%F0%9F%94%B5%F0%9F%93%9DCRUD-records-Me?node-id=12%3A0&viewport=429%2C420%2C0.11416016519069672

**Comment by linda-90** [comment]
- [ ] Language and B1 check done

**Comment by maartenfv** [comment]
@jamalv What is the status of this issue? What is the priority label and what are there project labels?

**Comment by jamalv** [comment]
superseded by: https://github.com/teamforus/itsm/issues/564
