### ISSUE TITLE
Change request: Signup flow: provider already getting stuck on step 2.

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#271]
**Support Ticket ID:** #1575

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @Gerbenbosschieter

### Change description
- Signup flow: provider already getting stuck on step 2.<br>

Figma:
https://www.figma.com/file/pdUYpbnipdNFz5xnshqqst/Provider-signupflow-download-link?node-id=1%3A1048

**Comment by GerbenBosschieter** [comment]
**Problem**
A lot of providers use a tablet instead of a mobile phone to use the me-app.
The tablet doesn't have a simcard so it can't receive a sms and our signup flow forces people to use a phone number.
The option to click a link wil only be displayed if people tried to enter a phone number and click Send.

But if you already know that you not have a simcard in your device, there is no incentive to fill one in.

**Note**
- This feedback was already noted multiple times in Figma by me (in earlier phase and comment is gone)
- @maxvisser also noted this in the most recent proposal.

So why didn't we include this feedback? This was definitely a risk we did foresee

**Comment by GerbenBosschieter** [comment]
<img width="1219" alt="Screen Shot 2020-07-08 at 10 07 35" src="https://user-images.githubusercontent.com/38419514/86895112-4c28e580-c104-11ea-91c0-4c313b3a33f7.png">

**Comment by maxvisser** [comment]
Tasks I see here:
- [ ] Adjust figma @jamalv @maxvisser 
- [ ] Create development task @danrminds

**Comment by maxvisser** [comment]
> So why didn't we include this feedback? This was definitely a risk we did foresee
Not sure anymore; I see I left comment and aswell approved the IP. Probably me reviewing the IP and aswell being the one who needs to plan it results in some unintended conflict of interests

**Comment by jamalv** [comment]
@maxvisser what is the status of this? Will/can this still be fixed in the next release? As we both witnessed how painful this can be 😃

**Comment by maxvisser** [comment]
Nobody has adjusted figma yet and no development task was created.

**Comment by jamalv** [comment]
I'll get on top of that!

**Comment by maxvisser** [comment]
Task https://github.com/teamforus/forus/issues/1662

**Comment by maxvisser** [comment]
I find that having two 'alternative' links in the bottom is a bit of a mess. You can also show the download link prominent. Even if the user does not know the 06 number of the phone he will want to see the link more quickly...

I would propose to change it to this:
![image](https://user-images.githubusercontent.com/10818702/88298085-045bae00-cd01-11ea-842d-3552f9ab39af.png)

https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBSignupflow-v2-texts?node-id=304%3A1218

**Comment by maxvisser** [comment]
MVP version will be released on monday; I want to keep this in Figma proposal phase though to make a better iteration.

**Comment by maxvisser** [comment]
https://www.figma.com/file/pdUYpbnipdNFz5xnshqqst/Provider-signupflow-download-link?node-id=1%3A1048

**Comment by jamalv** [comment]
since the core issue has been solved (@GerbenBosschieter @MichaelForus could you confirm this?) and now this is mainly about optimising the solution, I've downgraded the priority.

**Comment by jamalv** [comment]
seems to be solved, please re-open or open another issue if there are still problemens
