### ISSUE TITLE
PLEASE REMOVE ALL CAPS

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#272]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Implementation (Maarten&Linda)

### Change description

We would like to remove ALL CAPS text from our websites.

- We request to update the design guideline with this standard. So it will not be used in the future.
- Update the current webshops by removing all caps.

Example: website nijmegen.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/aa253824-aa07-409a-b5ab-0d2f752a4669)

Using all caps makes it less pleasant to look at the website.

We suggest

You should (only) use a capital letter in the following situations:
- In the names of people, places, or related words.
- At the beginning of a sentence.
- In the titles of books, films, organizations, etc.
- In abbreviations.

**Comment by maartenfv** [comment]
@GerbenBosschieter @linda-90 what are other places we use ALL CAPS?

**Comment by jamalv** [comment]
Yes agreed! I think maybe sometimes ALL CAPS can be used for call to actions? And maybe (small) labels? For the rest I also think we should use it as little as possible. maybe @Myshelova also has an opinion about this? 😄

**Comment by jamalv** [comment]
Actually I just did some browsing around websites I like, and I think maybe not using it anywhere (like you proposed) is the best.

**Comment by GerbenBosschieter** [comment]
Well, I do see it beging used with small labels and specific call to actions. But for now we should just use normal text

**Comment by maxvisser** [comment]
Should make a list of all places we use ALL CAPS now and create a development task to clean up. @SjoerdHilhorst If you have time to look at this one; this likely one where creating a task takes more time then fixing it.

**Comment by GerbenBosschieter** [comment]
@maxvisser Already made a start with this on the navbar branch. I discussed this with you and Jamal. 
There a like 5 places left where there are still some Capitals. Have to do one or three commits to create PR for navbar. (today)

After merging of this PR we could do a assessment of where there are more capitals.

**Comment by GerbenBosschieter** [comment]
Will include this while developing Groningen webshop.
@maxvisser We don't need any list. We already have the lists in the i18n files ;)

**Comment by GerbenBosschieter** [comment]
Not sure if my PR's will ever see daylight. So I will unassign myself for now. The fix itself is in a branch that will probably stauy open for a while because it's probably needs endless refactoring

**Comment by maxvisser** [comment]
released
