### ISSUE TITLE
Me app release pipeline

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#274]
Task: to write out what needs to happen for a me app release (both iOS and android); who is responsible for which part of the pipeline? What needs to happen?

## Definition of done:
- [ ] Updated document: Release manual/checklist in general repository; e.g. https://github.com/teamforus/general/tree/master/manuals/development/release-me.md or something

This list should include all the tasks/steps that are needed for a release for both android and ios

Some resources: 
https://github.com/teamforus/development/issues/114

https://github.com/teamforus/general/blob/f795f631c2065ff397f09c235a462809267dc24f/manuals/development/maintainer-manual.md#step-3-accept-and-release

**Comment by GerbenBosschieter** [comment]
summary:
- Release of the app should be the same as front and backend
- It goed wrong with buildng: who builds what en when. 
- It goes wrong staging and agreements. no planning.

**Comment by maxvisser** [comment]
Would be nice to write down what we discussed @GerbenBosschieter to make a bit of a conclusion to this issue.

**Comment by maxvisser** [comment]
what the DoD?

**Comment by jamalv** [comment]
> what the DoD?

I've updated the oringal issue

**Comment by maartenfv** [comment]
Moved this issue from general to generalmanagement

**Comment by maartenfv** [comment]
old
