### ISSUE TITLE
Some of our e-mails should be configurable.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#276]
Learn more about change requests here: https://bit.ly/39CWeEE

**Support Ticket**: #1333

### Requested by:
- Sponsor

### Change description
- As a sponsor I would like to change the date of certain automatic mails that are being send via the platform.

**E-mails** (not a complete list, just an example)
- The date of when a reminder about the budget is being send (currently 3 and 6 weeks before end date fund). Some sponsor would like to send this mail on a different moment.

**Comment by maxvisser** [comment]
We changed abit on how this works. I will check what the possibilities are with the new notifications. I think there are two things here; the system 'notifications' which remind user on system level that voucher is about to expire and you have a mail/message by sponsor which is more social thing. 

From the systems perspective you want to calculate the duration of the fund; for example a year; and have on certain dates a system reminder to use the voucher.

From the sponsors perspective you want to see who did not spend their budget and aswell remind people to do so; ask them why they did not spend all

So I see multiple solutions for this problem:
- Show fund notifications on dashboard (which ones do we sent and when?) -> set a custom date?
- Set notification text for such notifications
- Being able to contact requester via Forus (custom messages)
