### ISSUE TITLE
Directly grant voucher to requester based on records

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#277]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Can we directly grant a voucher to current holders as a fund?

e.g: person has "kindpakket" and automatically gets "fund x"? - can this be done?

**Comment by maxvisser** [comment]
I would maybe add to requester digest maybe check if they are applicable for a new fund, have direct link to funds page. If they are applicable they can activate the voucher on this page.

**Comment by maxvisser** [comment]
Not sure what the proposal is; Will estimate it as big until there is a conclusion

**Comment by jamalv** [comment]
moved to productboard: https://app.productboard.com/inbox/notes/15569014
