### ISSUE TITLE
SMS SenderID

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#278]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
https://support.twilio.com/hc/en-us/articles/223181348-Getting-Started-with-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS

**Comment by maxvisser** [comment]
checked in Twilio console; this seems to be configured. Maybe we need to somehow also use it on API.

**Comment by maxvisser** [comment]
need project label and priority

**Comment by jamalv** [comment]
Could have and currently not in scope of a project

**Comment by jamalv** [comment]
Would be very nice though, so could think about internal funding it or picking it up internally? (Sjoerd?)
