### ISSUE TITLE
Using DigiD as SSO with other municipality applications

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#279]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Customer

### Change description
One of the advantages of DigiD for dutch citizens, is that they can use it as single sign on (SSO): when they log in to DigiD on one application; the session can persist when a citizen goes to a different application. 

In our application we use DigiD one-time for getting and validating the BSN, but not as a primary login mechanism. 

### Request: 
Could we make it such, that a user that is logged in using DigiD on one application has their session persist when they log in to ours?

**Comment by jamalv** [comment]
@maxvisser I assume that we at least have to migrate from CGI to SAML, is that right? And after that, is this doable? Could you share some insights?

**Comment by maxvisser** [comment]
Correct CGI does not support SSO

**Comment by maxvisser** [comment]
Maybe close this one and let it be part of #95 For now I will add to this one #95 as blocking
