### ISSUE TITLE
Make fund formula user configurable

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#280]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Right now we set the fund formula directly in the database (for each child_nth you get €300 worth of budget) - this should be configurable by the user.

Question: can we add it to the fund settings, so that it doesn't need to be changed in service window, and it is more transparant to the sponsor what is done?

@maxvisser for me this is a bit of a blackbox, could you mock something up in figma?

## Figma
https://www.figma.com/file/99YwnGU4PrgP1zCFudAxmz/Configurable-fund-formula-s?node-id=0%3A1

**Comment by maxvisser** [comment]
You have three types of 'formula': products, budget fixed, budget multiplied; each one of these can be combined

Product formula needs a ui for selecting a product; after selecting the product it will save the product ID and its price. Condition: only products which have an unlimited stock currently can be added to the formula.

Budget fixed formula needs a ui for selecting if its a fixed price (each vouchers contains a fixed amount of euro's); this can be an input field

Budget multiplied formula needs a ui for selecting a record_type (only records of the type Number; examples: children_count) and an input field for the amount. Example you have 4 children times 300 euro's is 1200 euro voucher.

**Comment by maxvisser** [comment]
Example use case where everything is combined:
- Everyone will get a bus subscription: this a non cancelable product voucher which can only be spend for the getting a bus subscription (product fomula)
- Meedoenregeling configures a fixed price of 150; everyone will get 150€ (Budget fixed)
- If you are doing any caregiving you will get an appreciation which results in €50 for each person you give care to. (Budget multiplier: €50 multiplied by the amount of persons you care for)

you can do this all with the same fund application

**Comment by maxvisser** [comment]
Does this help by creating UI?

**Comment by jamalv** [comment]
@maxvisser started a mockup here, could you please inspect and complete it? 

https://www.figma.com/file/99YwnGU4PrgP1zCFudAxmz/Configurable-fund-formula-s?node-id=0%3A1

**Comment by maxvisser** [comment]
Don't know if we want to allow it but you can add multiple fixed numbers and multiple 'vermenigvuldigingen'/multipliers.

**Comment by jamalv** [comment]
I think we can leave that out of scope for now, as nobody is using it yet. I like the proposal as it stands now!

**Comment by jamalv** [comment]
Not sure If I am the one that can grant an approval but I think we came to an agreement

**Comment by maxvisser** [comment]
Don't think this needs an design check @danrminds

**Comment by maxvisser** [comment]
Checked on feasibility

**Comment by jamalv** [comment]
@maartenfv why did you add this to 139? we will not be using this functionality for that project. It still is nice for the client, though :)

**Comment by maxvisser** [comment]
From #470:
On the sponsor dashboard, we can create a fund and add criteria.
It would be nice to add the option base the calculation of the voucher amount based on the properties added.

Example the amount of children determines the voucher amount. Kindpakket base voucher amount 250.
Total amount = amount of children * base amount.
Total amount = 0,9 (Inkomens norm 110%)  * base amount

**Comment by maartenfv** [comment]
@jamalv I have no idea. I think I miss clicked! 
я извиняюсь

**Comment by maxvisser** [comment]
Planned to discuss during refinement 7 october

**Comment by maxvisser** [comment]
Conclusing:
![image](https://user-images.githubusercontent.com/10818702/95326745-585b4500-08a3-11eb-9241-e005800d7989.png)
