### ISSUE TITLE
CR: Add forus.io/DL to platform and webshop code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#281]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently this page is still in the old Python code base of the previous website. It was never added to the new websites code. In some release the CSS and images got disrupted and now there is only text on forus.io/DL

## Desired situation
Add the JS, CSS, images and pug file to the forus-frontend code

**Comment by jamalv** [comment]
@maxvisser could you give this an estimate?

**Comment by maxvisser** [comment]
Pug file with some js and an extra route on both platform. Some images and css. All is written only need to move from old website to Forus-frontend

So I see it as very small and an easy fix.

**Comment by maxvisser** [comment]
can be planned.
