### ISSUE TITLE
Providers: "Last seen"

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#282]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Intenal

### Change description
We would like to have an actualised offering of offers in the webshops, and avoid providers that signed up a couple years ago, from still being visible while they are not active anymore. One of the ways we achieve this, is by manually renewing the fund each year, but actually this is a big hassle for the sponsor, providers and for us. Therefore we have this cr: https://github.com/teamforus/general/issues/252

The proposal of this change is to introduce "last seen" for the providers, so that the sponsor can see when the provider was last active, and so that they can take action (contact the provider / remove them from the webshop)

**Comment by jamalv** [comment]
@maxvisser could you give an estimation of scope?

**Comment by maxvisser** [comment]
We store last api calls per identity. We should define when a provider is 'active' and who's 'Last seen' counts; A provider can have multiple employees we don't store it for the organization. I can't really estimate the scope of getting the organization's status; I would first create this status 'last seen' for each organization and test if it is accurate enough before removing any of the current ways of checking if providers are active

**Comment by jamalv** [comment]
hmmm, we could also consider something like:

last transaction: 3 months ago

last seen could be for all employees of the organisation I think

**Comment by maxvisser** [comment]
this needs a brainstorm session (maybe @danrminds and @dev-rminds included

**Comment by jamalv** [comment]
Ok, for now this does not have a high priority, but it will become more relevant again towards the end of the year and when we start thinking about how to make funds more continuous (/auto renew).

**Comment by jamalv** [comment]
is in production :D
