### ISSUE TITLE
Change request: As a sponsor I would to have more information about the financial statistics

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#286]
**Support Ticket ID:** [#1603]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
@Sponsor

### Change description
As a sponsor I would to have more information about the financial statistics<br>

- Total amount of budget that is granted
- Total amount of activated budget
- Total amount of not activated vouchers
- Remaining amount budget of activated vouchers

**Comment by GerbenBosschieter** [comment]
This information is per fund

**Comment by maxvisser** [comment]
So a financial dashboard should have an screen with all your funds combined?

**Comment by GerbenBosschieter** [comment]
No. this information should be visible per fund

**Comment by maxvisser** [comment]
Discussed this CR with @GerbenBosschieter we will start on defining users needs; what kind of information should be there; We will start with manually supplying this data (itsm issue) and discuss on how to automate this / add it to their dashboard. (discuss timeline with them aswell).

**Comment by maxvisser** [comment]
@GerbenBosschieter / @MichaelForus could you enhance this issue if you get more info on what data should be included in the total amounts? As in: we need to define what is for them 'budget that is granted' and 'total amount of activated budget' etc.

**Comment by maxvisser** [comment]
Could be part of #142

**Comment by maxvisser** [comment]
I would not make any financial statistics based on prevalidations; as this will be far too difficult to make generic. I would first implement #301 and replace prevalidations (you can create a voucher and a citizen can activate said voucher)
