### ISSUE TITLE
CR: Add offers to provider page.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#288]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- SDOA

### Change description
- Add offers to provider page.

Currently, when selecting a provider page we can not see their offers. The offers of the provider need to be displayed on the offer page.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/273c2393-0ca9-4823-a466-cf877d5e9be2)

**Comment by maxvisser** [comment]
Nice CR. Same way you should be able to go from product to provider page.

**Comment by maxvisser** [comment]
Needs design though; Will label this as a Should have; small scope
