### ISSUE TITLE
CR: Add Organisation description.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#289]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- SDOA

### Change description

- As a provider or sponsor, I would like to be able to add a description of my organisation. 
- As a requester, I would like to read about the organisation on the provider page.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/9cc6770e-fc2a-4928-abd0-ab544233a9b6)

Read about the provider. ![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/c5b33b1f-ce3c-4139-b9ae-efd55ee4d31c)

Figma:
https://www.figma.com/file/tTUOPNkVu6VIChAsA1925q/Organization-description?node-id=1%3A14899

**Comment by maxvisser** [comment]
Probably we should allow markdown here aswell to do some basic styling

**Comment by maxvisser** [comment]
@danrminds This can be planned https://github.com/teamforus/forus/issues/1650

**Comment by maxvisser** [comment]
Figma link:
https://www.figma.com/file/tTUOPNkVu6VIChAsA1925q/Organization-description?node-id=1%3A14899

**Comment by jamalv** [comment]
Let's wait until we can fit more concretely this in a project. (budget coverage)

**Comment by maxvisser** [comment]
Maybe abit too late as it was already planned and built 👍 I agree with you though about budget coverage. needs to be more clear what may be worked on and which CR don't have coverage.

**Comment by maxvisser** [comment]
released
