### ISSUE TITLE
CR: As I sponsor I want to change the header photo of the webshop in the CMS.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#290]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- SDOA, Westerkwartier

### Change description
- They want to be able to adjust the style of the webshop in more detail.

Be able to change this picture: 

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/b5cb7104-f51a-4425-aee5-138c79cbe5c3)

Using the CMS

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/03fb7822-9fc2-4c2c-9776-4370f134ceff)

**Comment by GerbenBosschieter** [comment]
@maartenfv Is this currently a change request for the CMS and do they just want to have the option in the CSM. Or do they already have a desire to change the background image right now ?

**Comment by maxvisser** [comment]
As they are not able to change to color of the text on the header they don't have alot of room to do any styling. I find it a bit weird to allow changing this image without changing any other styling on the header.

**Comment by maxvisser** [comment]
Aswell as not all municipalities use a jumbotron (inkomensondersteuning.nijmegen.nl) If we can enforce the jumbotron (same styling) for all municipalities. this will be easier to make possible.

**Comment by jamalv** [comment]
@maartenfv could you specify further?

Do they want to change the picture once? (scope: small) we'll just do it for them in the next release

Do they want to change it on a high frequency or have they requested specifically to change it themselves? then it's scope:big (see max's comment about updating all webshops to use a jumbotron etc) : would definitely be very nice to make this more standardised! just a bigger scope and more effort / coordination is needed

**Comment by jamalv** [comment]
(I assumed a priority, please update if you see it otherwise)

**Comment by maartenfv** [comment]
@GerbenBosschieter Not right now as in next week. They want to this in a couple weeks/months.

My proposal is indeed focused on doing this in the CMS. So we can allow the sponsors to do this themselves. It will help with every future implementation.

@maxvisser which websites do not use Jumbotron besides Nijmegen?

In terms of the overlay we should indeed add this option as well.

- Upload image
- Allow them to scale crop and position
- Allow them to select overlay with colour and transparency.

In case of Nijmegen, we could upload an image using this new CMS feature. Put transparency to 0.

**Comment by maxvisser** [comment]
General webshop but that one is not online. Almost all webshops currently use jumbotron.

**Comment by maartenfv** [comment]
@maxvisser That is good news I think. As this a Scope: Medium Can we get at an estimate from you or if needed from @danrminds on how long this will take to add?

**Comment by maxvisser** [comment]
Probably this could be scope small if the issue would be to fix an image uploader and a cropper. The overlay/opacity part makes it much harder; probably need to find a new dependency for it. 

Aswell as the text is now hardcoded White or Black. Probably we need a color picker for the text aswell (otherwise you could never change a dark image to a brighter image.)

Probably if a better IP is made (whats is included within the scope) I could estimate it.

For this scope my estimation is 20 to 30 hours, which would include researching a dependency for the overlay:
- Upload image
- Allow them to scale, crop and position
- Allow them to select overlay with colour and transparency.

My opinion on this is an overlay / transparancy feature seems abit of over engineering better focus first on the textual colors and other stuff which is needed within the jumbotron.

**Comment by maartenfv** [comment]
This comes up again in Potjeswijzer. We are putting a lot of time in communicating this issue regarding the header. Would be best to be able to give the option to chose the header back to the municipality. 

Currently, a lot of people on the team are working on the header photo. We would be able to delegate this to the municipalities themselves.

@maxvisser What would exactly be needed to fix the scope of the issue and make the IP?

**Comment by maartenfv** [comment]
@jamalv based on our experiences during Potjeswijzer should we place this higher on the Backlog? I think it would save us a lot of time?

**Comment by maartenfv** [comment]
@maxvisser maybe we can ask @danrminds to give an estimation?

**Comment by maxvisser** [comment]
As the scope is medium / large. I would first fix all must haves for running project before starting on new stuff.

**Comment by maartenfv** [comment]
@maxvisser @danrminds What is the status of this issue? It is still requested for GRO and needs to be planned.

**Comment by maxvisser** [comment]
if dominant color is too light -> enable patern / text shadow
if dominant color is almost white -> switch text color to black

migrating some current implementation to allow header photo changing will be difficult. We should take into account:
- sprites/splashes 

we can upload these images with alot of transparancy

**Comment by maxvisser** [comment]
idea: 
keep the old header photos in a sort of 'archive' to easily switch back; good for holidays

**Comment by maxvisser** [comment]
Update: Issue is planned; scope for this issue is kept small. Just changing the header photo for now (no text adjustsment yet)

**Comment by jamalv** [comment]
Berkelland and Geertruidenberg recently requested a change of header photo; so for them it is extra important to be included :D
