### ISSUE TITLE
Make payments without scanning QR codes / needing a smartphone

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#291]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Gemeente Groningen, Gemeente Nijmegen

### Change description
As a provider I would like to receive the payment without having to scan a QR code.

Example usecase: a provider that only receives 1 or 2 customers per year, and doesn't have/want to use a smartphone. This is a question from one of our sponsors that is concerned that the QR/payment method makes people not want to join. In their previous system, they had the option for manual entry. Can we offer a solution to this?

**Comment by jamalv** [comment]
Some ideas that were mentioned here: allowing the provider to enter "part of the QR code" in their dashboard (meaning we'd have to show it to the end user) - making "direct" payments possible could also solve this (allow the requester to do this?) - I'd also like to get the perspective from support; how do we currently deal with this?

**Comment by GerbenBosschieter** [comment]
Uses cases where this could be very useful:
- Sport organisation with a "penningmeester" that does the payment of the contribution once a month and is most of time not physically on location.
- Big organisations with a lot of cashiers. These organisations don't want to invest in multiple phones for one office. Not sure if this would solve their problem, but it's already better than beging forced to use a phone.

**Comment by maxvisser** [comment]
related:
https://github.com/teamforus/lab/issues/62

**Comment by maxvisser** [comment]
thought about this before with reactivating old card we make the voucher token human readible (1001xxxxxxxxx) but this is only for one client applicable

Your suggestion of partly entering the voucher token does not seem feasible. I would require the citizen to use Me-app/webshop to generate a temporary token which is only active for a short amount of time. For all old cards this is not applicable. 

As we want to add more and more resources to one single QR-code (password) I would suggest to maybe even rethink on how paper vouchers work and their security.

**Comment by GerbenBosschieter** [comment]
Not sure why I am assgined to this.

**Comment by maxvisser** [comment]
As this probably is mostly not feasible because of security; I would like to propose a solution:

On paper vouchers print a human readible number for example 8 digits: 0000 0000
Generate a CVC (4-digits) which is not printed. 
- CVC is shown on webpage of voucher and in Me-app. 

Provider will fill in 8 digit number and CVC on their dashboard.
Requester has the ability to change CVC (regenerate a new number).

We could also allow user to disable/enable CVC on their token; Maybe even let Sponsor decide to this in bulk for all vouchers (for example for Stadjerspas a CVC is maybe not necassary)

**Comment by jamalv** [comment]
Thx for the input! I think for this issue it is also very important to ask **why** this functionality is requested (should be added to this CR if there's other cases). Because I am also curious about the direction of "direct" payments by the requester. For example directly from the webshop. 

Scenario:

Provider does not have/want a phone, or is not physically near the requester
Requester chooses offer / provider and what they want in the webshop
Requester clicks "pay" > payment is done, provider gets money, does not need to scan anything.

If possible I would prefer this to what you mentioned, as I expect it will be much more simple for involved parties. The target audience for these interactions is probably not willing to do much 😄

**Comment by maxvisser** [comment]
That one is much bigger but yes would also be a solution :) Probably move your scenario to the right issue. https://github.com/teamforus/general/issues/120

I think its still nice if you only have a physical card/paper voucher and walk into a store you don't need to go home to go to the webshop to perform a transaction first.

**Comment by GerbenBosschieter** [comment]
FYI got a new support ticket that asked for this.

**Comment by jamalv** [comment]
Figma brainstorm: https://www.figma.com/file/1sJ0Q9eEKkSY5UezruPJhw/Payment-via-dashboard?node-id=176%3A138

**Comment by maartenfv** [comment]
Gerben zegt we kunnen het sluiten!!!
