### ISSUE TITLE
Actions: allow sponsor to override action details for their webshop (picture / text)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#292]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
For actions the sponsor is the "owner/sponsor" of the action. It might make sense to allow the sponsor to perform some "editorial" operations on the actions in the webshop: 

examples: 
* when they approve an action add an image that is shown by default (probably also keep the provider image and allow the user to go trough them
* allow the sponsor to add some editorial text to the offer (would suggest to clearly split it **note from sponsor** and **description by provider**

**Comment by maxvisser** [comment]
See only UX issues with this no technical challenges.

**Comment by maxvisser** [comment]
Seems like somewhat the same as #189
