### ISSUE TITLE
Ben u dit? of Ben u dit misschien? Nodig om in te loggen op **het** website

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#293]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/41ea8e21-3ac5-4229-b623-392106719501)

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/2695bf8c-b271-438c-8845-aa7415db777f)

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/c5a42754-32ff-4614-9816-f1925efda4b6)

Should be: 

Is deze mail wel aan u gericht maar wilt u zich afmelden voor dit soort berichten? U kunt dit aangeven in uw e-mailvoorkeuren.

De website.

**Comment by maxvisser** [comment]
het website is already changed to de website on develop branch

**Comment by maartenfv** [comment]
@maxvisser Great :) let's inform our users.

**Comment by maxvisser** [comment]
still need to be put on production :) We can keep track of it on this CR

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1651 task

**Comment by maartenfv** [comment]
@maxvisser I have updated the text.

**Comment by jamalv** [comment]
Part of release 0.13 (planned for next monday)

**Comment by maxvisser** [comment]
Its on production
