### ISSUE TITLE
CR: Dashboards to XXX [NL]

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#294]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholders

### Change description
We gebruiken nu de term "dashboards" > er wordt gesproken over "beheeromgeving" "website" etc. etc. Deze CR is bedoeld om hier over na te denken en met een alternatief voorstel te komen. 

Meeste impact is bijvoorbeeld in login mails

**Comment by maxvisser** [comment]
cockpit 😎

**Comment by maxvisser** [comment]
Term wordt voor gebruikt op knoppen en als verwijzing:
GA NAAR HET DASHBOARD

Keuze kan ook zijn om alle verwijzingen weg te halen.

**Comment by maxvisser** [comment]
Knop wordt dan 'Login'

**Comment by maxvisser** [comment]
Gerben's suggestion is Portaal

**Comment by maxvisser** [comment]
Could you approve 'Portaal' discuss with stakeholders?

**Comment by maartenfv** [comment]
Denk niet dat protaal de beste term is. Portaal (informatica)
Een portaal is een webpagina die uit diverse bronnen geselecteerde informatie biedt en/of toegang geeft tot verschillende informatiebronnen en/of services (apps). Een (openbaar) portaal op internet doet diens als "toegangspoort" tot een reeks andere websites, die over hetzelfde onderwerp gaan; soms dus synoniem van start- of hoofdpagina, maar meestal ook als vertrekpunt en overzichtstabel voor verdere navigatie binnen een onderwerp.

De Engelse naam, die ook veel in Nederlandse teksten gebruikt wordt, is portal.

Een portaal op het interne netwerk van een bedrijf kan informatie en digitale middelen aanbieden afgestemd op een medewerker en zijn taken: een gepersonaliseerd medewerkersportaal. Een algemeen bedrijfsportaal en een gemeenschapsportaal bieden een startpagina met nuttige links en informatie voor de medewerkers van het bedrijf of de leden van de gemeenschap.

**Comment by maartenfv** [comment]
Ik zou gaan voor Gebruikersomgeving
https://nl.wikipedia.org/wiki/Gebruikersomgeving

**Comment by maxvisser** [comment]
Login op de beheeromgeving van de beoordelaar
Login op de beheeromgeving van de sponsor
Login op de beheeromgeving van de aanbieder

Ga naar uw beheeromgeving om de aanvraag goed te keuren
Ga naar uw beheeromgeving om de status van uw aanmelding in te zien.

**Comment by maartenfv** [comment]
Wat is de status van deze issue?

**Comment by maxvisser** [comment]
Wordt maandag doorgevoerd.
