### ISSUE TITLE
CR: Design webshops designs based on our minimal breakpoint (1024px;)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#295]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Currently al our webshops are designed on pages on 1920px or 1440px width. Bringing this to development could result into some problems. Since we only have desktop designs instead of mobile / tablet / dektop it's really hard to decide what should happend on smaller screens. Because there is no design for it. 

If a developer wants to exactly build it as it's designed on Figma, it wil cause problems for smaller screens.
For our newest implementation we already have this problem.

Other reasons:
- Less css tricks to get the same results. Less css files and css tricks is what we want.
- If every implementation is designed on the breakpoint of 1024px we can prevent using more css because of differences from each other.
- The width of 1024px is most of the time visually not the best. Designing on 1024px will give us a impression on how it will look on smalles screen size fort desktop. Does it look good on 1024? Than it will definitely look good on screens that has more width.
- Developer should not do any designer stuff (we already had an example of NOP where I had to change the design because it smaller screen broke the design and text was not readable anymore) 
- In addition to the last point, if we would have started the design on 1024px. I didn't neeed to change any design and it would save time! And we all know, time is .....

**Examples**
Take a look at the current examples:
**Example 1: This image is on a browser width of 1440px and meets the design in Figma**
<img width="1349" alt="Screen Shot 2020-07-20 at 15 35 52" src="https://user-images.githubusercontent.com/38419514/87945812-8c437d00-caa1-11ea-9ec6-006b1275f66f.png">

**Example 2: This image is on a browser width of 1024px and meets the design in Figma. Text is not readable and the design is broken now.**
<img width="1007" alt="Screen Shot 2020-07-20 at 15 36 34" src="https://user-images.githubusercontent.com/38419514/87946012-cad93780-caa1-11ea-943e-d2298bef1f19.png">

**Comment by maxvisser** [comment]
Nice CR; Also to point out: If you don't write the css with scaling it will not look good on larger screens 
Some guide about this topic: https://css-tricks.com/optimizing-large-scale-displays/

**Comment by jamalv** [comment]
I approve; can be added to the styleguide: https://github.com/teamforus/general/blob/master/manuals/design/styleguide.md when somebody has time to do it :)

**Comment by maxvisser** [comment]
I would aswell say that DoD for this issue is aswell changing the templates to 1024? If so I think the scope is medium/big. If DoD is just adding it to the styleguide for all new designs to take account its much smaller.

**Comment by GerbenBosschieter** [comment]
Why is this scope big? Just start figma designing on 1024

**Comment by maxvisser** [comment]
Its my task to esitmate scope if its just starting new templates based on 1024 I see no problem. But maybe its a bit weird that some pages are 1024 and some are bigger.

**Comment by GerbenBosschieter** [comment]
bump
