### ISSUE TITLE
CR: Make better UX by adding checkboxes and selection.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#296]
This is going to be used for thousands of vouchers needs to have a better and safer UX.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/bce9ccb4-4fd4-4885-97a0-6d874b698c79)

Also add pop-up with Are you sure after clicking bevestig

**Comment by jamalv** [comment]
Figma file: https://www.figma.com/file/Uy3BsLneRBEFHA3nRXxNQ3/Improve-voucher-generator-duplicates?node-id=0%3A1

**Comment by maxvisser** [comment]
@maartenfv I already added to a few of your issues all labels manually; Could you use a template next time?

**Comment by maxvisser** [comment]
needs a project and priority

**Comment by jamalv** [comment]
please check the current state and see if this is still relevant

**Comment by jamalv** [comment]
Changes have been made to this, assuming this is no longer relevant; please reopen if it is.
