### ISSUE TITLE
CR: Upload example product voucher generator select product

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#297]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Select product before download upload example CSV; TO GET THE PRODUCT_ID

@maartenfv
As a Sponsor I would like to be able to select the product-id from the dropdown in de Excell sheet instead of asking for it. https://github.com/teamforus/general/issues/303

**Comment by maxvisser** [comment]
Seems it auto selects a product_id from approved provider when exporting CSV @maartenfv Probably fixes the CR. What do you think?

**Comment by maartenfv** [comment]
@maxvisser Not sure how that works maybe you can explain to me in person?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/89546722-32fb7d80-d805-11ea-8b65-aa9c151c5875.png)

**Comment by maxvisser** [comment]
upload example has an example row, with a real product_id

**Comment by maxvisser** [comment]
If  you choose product before uploading CSV you should be able to only upload a BSN

**Comment by maartenfv** [comment]
This is still unclear to me. How would a user be able to understand?
