### ISSUE TITLE
CR: Voucher generator: Assign to UID and add field

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#298]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor Nijmegen.

### Change description
- As a sponsor I would like to be able to assign vouchers to different UID's (e.g., email adres or BSN).
- As a sponsor, I want to be able to add a unique ID number to the CSV upload when generating QR-codes.
- As a sponsor, **I do not** want to use the "note" field to keep track of whom I have given a code or to write down BSN or customer number.
- As a sponsor, I want to be able to search through these new numbers.

*Note* The voucher generators are going to be used to generate thousands of codes. This means that it will not just be a feature for edge cases. The design needs to take into account these demands in terms of search-ability etc.

For the busregeling this is a must-do issue.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/460fd94a-9480-4140-b98e-94201bfa50e3)

As a sponsor I would like to be able to assign vouchers to different UID's (e.g., email adres or BSN).

Some funds use UID, Some BSN. Alot of vouchers are now generated with these UIDs in the note field. It would be better to set these UID as a seperate field on the voucher.

**Comment by jamalv** [comment]
Discussed this in the context of an upcoming project, if the project becomes official, this will be upgraded to must-have

**Comment by maxvisser** [comment]
I will unassign myself

**Comment by maartenfv** [comment]
@jamalv @maxvisser Can we get an estimate?

**Comment by maxvisser** [comment]
@danrminds could you help with an estimate?

**Comment by jamalv** [comment]
@maxvisser I see you overwrote the original user story from this issue: 

- As a sponsor I would like to be able to assign vouchers to different UID's (e.g., email adres or BSN).

This one was also in the original issue that you closed: https://github.com/teamforus/general/issues/299 - I already moved it to this issue myself. 

@maxvisser could you make sure that this user story is part of the estimate?

**Comment by maxvisser** [comment]
Currently planned for design

**Comment by maxvisser** [comment]
released
