### ISSUE TITLE
Assign vouchers to UID

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#299]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal & sponsors

### Change description
As a sponsor I would like to be able to assign vouchers to different UID's (e.g., email adres or BSN).

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/298

**Comment by jamalv** [comment]
thx, for finding the duplicate and closing! could you add my change description (user story) to the duplicate or as a comment next time, if this is relevant? - for now i've done it as I think it helps give the other issue a bit more context :)
