### ISSUE TITLE
CR:Duplicate pop-up preventing doublings in aanbiedingvouchergenerator.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#302]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor Nijmegen

### Change description
- As a sponsor I want to be sure that I do not generate multiple vouchers for the same person.
- As a sponsor I want to be sure that I do not overrule a previous voucher.

**Comment by maxvisser** [comment]
This is already built. Current status: a pr to develop

**Comment by maxvisser** [comment]
Current state is part of release v0.14.0

**Comment by jamalv** [comment]
Release v0.14.0 went live last monday. This can be closed? @maartenfv @maxvisser 🚀

**Comment by jamalv** [comment]
@maxvisser no release notes for v0.14.0? yet? :) https://github.com/teamforus/forus/tags

**Comment by jamalv** [comment]
Release notes :D https://github.com/teamforus/forus/releases/tag/v0.14.0
