### ISSUE TITLE
CR: Add Export function to product voucher generator.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#304]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor Nijmegen + Implemenation

### Change description
- Add export function die aanbiedingsvoucher generator.

As a sponsor, I want to be able to export the qr-codes as without this it is useless.

**Comment by maxvisser** [comment]
@danrminds Fuctionality is there on budget voucher generator. Can be planned.

**Comment by maxvisser** [comment]
@maartenfv what should be inside the export? which data is needed.

**Comment by maartenfv** [comment]
The following needs to be part of the export:
**Deze kolommen zijn er al en moeten in de export worden meegenomen**
- Notitie
- Aanbieding
- Aangemaakt op
- Geldig tot
- Fonds
- Toegekend
- Ingebruik
- QR-code

**Deze kolommen moeten worden toegevoegd zoals gevraagd in [issue298](https://github.com/teamforus/general/issues/298) en moeten ook in de export worden meegenomen**

- BSN
- Klantnummer
- Email address

**Comment by maxvisser** [comment]
Probably should create two exports as you probably don't want to mix assigned / unassigned voucher in the export. This probably makes it more difficult for the guy who creates the letters with QR-codes.

**Comment by maxvisser** [comment]
Currently only unassigned vouchers are in the export

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1799

**Comment by jamalv** [comment]
@maxvisser this was in .15?
