### ISSUE TITLE
Requester signupflow: support different filetypes (jpg, jpeg, png, etc) (now only pdf)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#305]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Now when a user uploads a file, it has to be a pdf; in practice often users will take a picture with their phone; we should support all major image fileformats for the uploader. It will be used by (tens of) thousands of people so it should be solid. People will be using their iOS/Android devices, and maybe their scanners with their computers to create these files.

Acceptance criteria:
- [ ] must work on mobile phones

**Comment by jamalv** [comment]
Also could we do some research into what files we need to support by major operating systems and frequently used scanners / camera's etc?

**Comment by jamalv** [comment]
And if there are still files that we don't support, the errors should be clear and useful

**Comment by maxvisser** [comment]
For other signupflows we also need this; mobile cropper is terrible. Should see how some native things work and if we can use them in browser.

**Comment by maxvisser** [comment]
As we preview PDF's we need to look into if images can also be previewed.

**Comment by maxvisser** [comment]
@danrminds could you check whats needed for the uploader to be able to allow images / preview images on validator dashboard.

**Comment by GerbenBosschieter** [comment]
@aghimpu we would like to support the following file types.

- jpg
- jpeg
- png
- pdf (already done)
- xls
- doc

It's also important that these filetypes are displayed on the preview option of the validator dashbaord.

**Comment by maxvisser** [comment]
If xls and doc need to be supported by preview option I would increase the scope to medium/big

**Comment by aghimpu** [comment]
xls and doc won't have a preview for now, that would make things more difficult (most likely would have to setup and use some sort of converter from those file types to pdf)

**Comment by maxvisser** [comment]
Lets create a seperate CR forthat with lower priority.

**Comment by maxvisser** [comment]
Made a task for this one: https://github.com/teamforus/forus/issues/1713
