### ISSUE TITLE
Clean figma 🧼🧹🧽

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#307]
Many people are working in Figma, and it's starting to get a bit messy! Let's work on that!

![tenor](https://user-images.githubusercontent.com/30194799/89007922-05489d00-d30a-11ea-8c2c-79cf3880d109.gif)

**Comment by jamalv** [comment]
Suggestion: align all page covers with the template:

![image](https://user-images.githubusercontent.com/30194799/89008033-36c16880-d30a-11ea-81e6-3ca9108959ac.png)

**Comment by bodivleij** [comment]
Hi everyone, my name is Bodi and I will be cleaning Figma. Over the past few days I have mainly worked on renaming all the component files in Libraries>Dashboard>Templates to make them easily searchable.

The structure as of now is pretty straight-forward, I've taken the URL structure of the forus.io environment and based the structure on that, for instance: 
https://forus.io/sponsor/#!/organizations/1/transactions
would be
![Screenshot 2020-07-31 at 08 52 33](https://user-images.githubusercontent.com/68469222/89008572-34134300-d30b-11ea-9a87-e507a0ea5c21.png)
(Emoticon template is a tool made by Max, which will easily identify the components in Figma, more info on that here: https://github.com/teamforus/general/blob/master/manuals/design/file-structure.md#figma-files)

**Comment by jamalv** [comment]
## Update page titles in figma files

In figma, every file has page names; sometimes this is not really clean: 

<img width="348" alt="Screenshot 2020-07-31 at 08 52 43" src="https://user-images.githubusercontent.com/30194799/89008578-36759d00-d30b-11ea-9cb1-c1c1b8eb3847.png">

this creates a lot of confusion for the team! Which page is the newest that needs to be developed etc? 

Max made a nice proposal for naming the pages;

https://github.com/teamforus/general/blob/master/manuals/design/file-structure.md#figma-files

- [ ] Done

**Comment by maxvisser** [comment]
Not sure if this is the topic to do write this down; maybe can become a seperate issue.

## Mails

Mails are pretty tedious to get into figma but when they are in we can finally do more easily text review and CR upon mails. 

### Progress
- [x] Template (design) is made for the mails.
- [x] screenshots are made for all mails (done by Myself, Me and I)
- [ ] Creating figma frames for each mail and naming the frames 
- [ ] Adding texts to mails from https://github.com/teamforus/forus-backend/tree/master/resources/lang/nl/mails/implementations/general (copy pasting it from each PHP file to figma) -> look into posibility to use sheet sync. (to make this less of a drag to do)
- [ ] Move frames to library, make component of each mail frame. 
- [ ] Publish library, big success

**Comment by jamalv** [comment]
Hey @maxvisser nice comment! For now we will not split it up in seperate issues :) makes time tracking easier for bodi (just one time metric :))

**Comment by jamalv** [comment]
so yea! this is definitely the place to add all the ideas!

**Comment by jamalv** [comment]
reminder to self: dashboard menu's

**Comment by jamalv** [comment]
no longer actively worked on
