### ISSUE TITLE
IP: Upgrade the notification module to show progress

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#309]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
Currently - the notification module we are using is just showing a one-time update of the status

## Desired situation
Would be nice to be able to show the progress bar, updates in the same notification

Example: 
![notifications](https://user-images.githubusercontent.com/33207036/88510366-81ca3b80-cfeb-11ea-8acd-c5ed521b95e7.png)

## Plan
-

**Comment by maxvisser** [comment]
Good idea. Discussed it with Valentin. Seems usefull for uploading things and other mechanics where a progress bar is usefull.

**Comment by jamalv** [comment]
How big is the scope of this change? Could you add an estimation to help with this decision? Currently don't see any projects to cover this, so will put it on hold for now.

**Comment by maxvisser** [comment]
Scope is small; such a component has multiple purposes and can be used in different use cases.

**Comment by jamalv** [comment]
since it's small and a nice UX feature; I think it can be planned. @danrminds could you plan this for dimitri?
