### ISSUE TITLE
Update Language guidelines voor text review

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#313]
- Aanbod of aanbiedingen?
- beoordelaars of validators

**Comment by maxvisser** [comment]
Vouchers of tegoed?

**Comment by maxvisser** [comment]
Dashboard of portaal? https://github.com/teamforus/general/issues/294

**Comment by maartenfv** [comment]
@maxvisser tegoed, omgeving :)

**Comment by maxvisser** [comment]
Relevant issues: #294 #235 #236

**Comment by maxvisser** [comment]
Maybe make a quick internal poll and ask some external party to double check our choices as it is a big thing to change these terms lets not play whack-a-mole and only change it once.

**Comment by linda-90** [comment]
### Wijzigingen
Hierbij een overzicht van de verschillende keuzes. Graag aanvullen indien er meer woorden zijn waarin we een keuze moeten maken.

- Aanbod of aanbiedingen  
✅ aanbiedingen
- beoordelaar of validator
✅ beoordelaar (beoordelende organisatie)
- vouchers of tegoed
✅  tegoed (hoe zit het met: passen?)
- dashboard, portaal of beheeromgeving
✅  beheeromgeving
- validatieverzoek of beoordeling aanvraag (verzoek is niet B1)
✅ beoordeling aanvraag
- validatie of goedkeuring/goedkeuren (bevestiging is niet B1)
✅ goedkeuren

**Comment by maxvisser** [comment]
maybe we can discuss this one briefly with sprint demo @jamalv

**Comment by jamalv** [comment]
https://www.accessibility.nl/tools/leesniveau

**Comment by jamalv** [comment]
https://dekrachtvancontent.nl/webredactie/zin-en-onzin-van-schrijven-op-b1-niveau/

**Comment by jamalv** [comment]
@max Ik zou criteria of criterium nog veranderen in voorwaarde of voorwaarden @linda-90 @maartenfv, what do you think?

**Comment by maxvisser** [comment]
Valideer eigenschap -> Eigenschap laten goedkeuren

**Comment by maxvisser** [comment]
Het bedrag van de aanbieding wordt van uw Meedoenpakket-voucher afgehaald en er wordt een nieuwe voucher aangemaakt
->
Het bedrag van het aanbod wordt van uw Meedoenpakket-tegoed afgehaald en er wordt een nieuw aanbod tegoed aangemaakt.

**Comment by maxvisser** [comment]
Het bedrag van het aanbod wordt van uw Meedoenpakket-tegoed afgehaald en er wordt een reservering aangemaakt.

**Comment by maxvisser** [comment]
Verstuur een validatieverzoek -> Verstuur een goedkeuringsverzoek

**Comment by linda-90** [comment]
@maxvisser 
✅ Het bedrag van het aanbod wordt van uw Meedoenpakket-tegoed afgehaald en er wordt een reservering aangemaakt.

Verstuur een validatieverzoek -> Verstuur een beoordelingsaanvraag
Waar komt deze tekst terug? Het woord verzoek is niet B1, aanvraag wel.
Kan deze tekst simpeler? Bijv. Versturen ter beoordeling of aanvraag laten beoordelen.

**Comment by maxvisser** [comment]
volgensmij de stap bij stap gids op de uitlegpagina

**Comment by maxvisser** [comment]
Aanbiedingsvouchers op het sponsor dashboard. Bij de webshop en provider dashboard kom ik wel weg met dit vervangen door 'Reserveringen' maar in het menu is Tegoeden en Reserveringen gek.
Opties:
Tegoed in natura
Product tegoed
Aanbod tegoed
Tegoed in aanbod
Aanbiedingstegoed

**Comment by maxvisser** [comment]
Niet-toegekende voucher -> dit is een voucher die door de sponsor is aangemaakt maar nog niet aan een gebruikersprofiel gekoppelt is.

**Comment by maxvisser** [comment]
Meeste heb ik nu veranderd. Heb de PR voor de teksten op dev gezet. Daarmee staat hij ook gelijk op test.potjeswijzer.nl @jamalv

**Comment by jamalv** [comment]
@maxvisser @linda-90 

![F5408D6B-9C56-4ECD-A4DD-E0E13EBC4FC0](https://user-images.githubusercontent.com/30194799/90217173-dd286600-de00-11ea-9d89-19968d6d124e.jpeg)

**Comment by jamalv** [comment]
Wat mij betreft mag die hele tekst ook weg trouwens, vind het nogal nietszeggend

**Comment by jamalv** [comment]
Er staat al een 8 linksboven, en klikken voor meer informatie is uitleggen hoe het internet werkt, niet onze rol :p

**Comment by jamalv** [comment]
Daarbij, de zoekfunctie is veel belangrijker, door die gelijk linksboven te hebben valt hij meer op; bij de usertests misten mensen nog verbazingwekkend vaak de zoekfunctie.

**Comment by maxvisser** [comment]
ik zou voor de zoekfunctie en weghalen tekst even een IP aanmaken Jamal. Ik zie niet in waarom dat deel is van het veranderen van de termen. (behalve dat 8 aanbod beetje gek is)  maar zo zullen er wel meer gekke dingen zijn (die al gek waren maar nu meer opvallen omdat je de tekst veranderd)

**Comment by maxvisser** [comment]
We kunnen er eerst wel 'Aanbod (8)', van maken

**Comment by jamalv** [comment]
https://github.com/teamforus/general/issues/362

**Comment by jamalv** [comment]
Aanbod (8) is w.m.t. heel gek, aangezien dat er ook al pal naast staat :P (zie #362)

**Comment by jamalv** [comment]
@maartenfv what is the definition of done for this issue?

**Comment by linda-90** [comment]
@jamalv @maxvisser Dit een idee?
<img width="488" alt="Schermafbeelding 2020-08-18 om 13 30 44" src="https://user-images.githubusercontent.com/36952230/90507963-15101000-e157-11ea-9e85-c15edab1e2ff.png">

**Comment by GerbenBosschieter** [comment]
bump

**Comment by maxvisser** [comment]
Also saw the same risks @GerbenBosschieter in the discussion I had with @linda-90  @maartenfv @jamalv everyone saw these risk but we decided to just implement all the changes to keywords once and don't change it back. Aswell I ask to start introducing this change (make it vocal) to all clients so it is not a 'suprise' change.

Maybe we can also start with writing a blog post and do a direct mailing to sponsor employees of the keyword change.

> - Everybody understands why certain words are chosen, so we can also internally use these words.

Internally we should indeed also implement this but I see no reason to stop using Voucher, Validator, dashboard on github as they are still the keywords in code and how developers see and understand that part of the application.

> - Texts are not only used in our products but also in our helpcenter, communication, presentation and trainings. If words change we need to change it everywhere and get used to it.

Indeed it should be changed everywhere, basically each old document or newly created one should be checked on the keywords and be edited if necessary.

> - Users are already used to certain words, for example: Nijmegen knows the voucher generator and also use the word voucher. If they want to use the voucher generator and its called: Tegoeden it will cause for a lot of confusion

I think a mailing to all users with @rivn.nl / @nijmgen.nl could help. Maybe even before implementing this change to production.

> - If we going to make a choice for certain words, we should stick to it and not change it anymore for a certain time. Because changing it and than changing it back really comes across as amateurish

Yeah don't want to play whack-a-mole with this one.. too big of a scope to do that 👍

**Comment by maxvisser** [comment]
@jamalv could you also respond on gerbens risks? How to proceed?

**Comment by maxvisser** [comment]
@jamalv could you still respond; how can we implement this without making users confused

**Comment by jamalv** [comment]
Currently @linda-90 is working on a language guide: https://roadmap.forus.io/c/24-forus-taalgids

1. Please have a look and let's use the linked (public) document to discussed proposed terms and definitions @GerbenBosschieter @jamalv @maxvisser @linda-90 @maartenfv @MichaelForus 
2. We will share the list with stakeholders to get feedback and improve @linda-90 @jamalv 
3. We will update and finalise the list @linda-90 
4. The language guide will become the leading document, and we'll need to update our products accordingly, where needed, and also make a plan on how to implement where needed @GerbenBosschieter @linda-90  

4 is the critical step in not making users confused. For the dashboard maybe we should e-mail the users of the dashboards with changes before the release? I don't expect very big changes for requesters.
