### ISSUE TITLE
Products page should have same 'organization' block as vestigingen

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#315]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/72236315-9c504080-35d6-11ea-885d-542cc8e069e0.png)

- this makes user being able to go from product to organization or office details page

**Comment by maxvisser** [comment]
@jamalv Could check priority

**Comment by maxvisser** [comment]
Needs an project to be planned

**Comment by maxvisser** [comment]
Maybe better to redesign the whole product page as it is pretty messy

**Comment by jamalv** [comment]
@maxvisser i believe this was done in the redesign, so closing this issue. please re-open if it's still relevant
