### ISSUE TITLE
Financial dashboard improvements

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#316]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

# [Figma](https://www.figma.com/file/oKXIg1YhjE4HU3kJ4G46pg/%F0%9F%A7%AAFinancial-dashboard-improvements?node-id=1%3A61)

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
It is not good yet.

## Desired situation
Better financial dashboards.

## Plan
Start with some brainstorming in figma:

**Comment by maxvisser** [comment]
I will close this one in favor of #142
