### ISSUE TITLE
IP: financial statistic: sum amount vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#318]
### User Story
As a sponsor
I want to see a financial statistics
So that I can retrieve the sum of amount of vouchers of my fund

## Prototype
https://www.figma.com/file/5HZA8BBlZAaimKZbqs8un1/Financial-statistic%3A-sum-of-amount-on-funds-its-vouchers?node-id=66%3A413

**Comment by linda-90** [comment]
04-08-2020 📝Text review in Figma
I have made a few comments in the Figma design. @jamalv @maxvisser

**Comment by maxvisser** [comment]
This is released to production
