### ISSUE TITLE
Add an unique identifier to export of fund requests

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#320]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter @maxvisser 

### Change description
- Would be nice to add an identifier to the export of fund request. This could be a simple as adding the number of the row to the export.

#### Reason
One our implementation is using the feature of fund request and they do create a sample of all the request to check if someone met the criteria for the fund. If they find any users who are not meeting the requirement they will send them a bill. 

Before doing any actions they will ask us to confirm if the information is correct and if the granted vouchers are used.
Adding a unique identifier would prevent sending any personal information by mail.

**Comment by maxvisser** [comment]
A id number of fund request would already a nice solution

**Comment by maxvisser** [comment]
Probably also an issue for project-100
