### ISSUE TITLE
IP: Finalize changing email

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#323]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently we still do not allow users to change their mail. This issue is to indicate what still needs to be done and whats needed to finalize it.

## Current situation
Hidden on production, user can change e-mail without consent of old primary email address owner

## Desired situation
Make a mail which allows old primary email address owner to verify e-mail change.
Aswell as maybe letting user login with DigiD change mail with DigiD as authentication method.

**Comment by jamalv** [comment]
i believe this is deployed
