### ISSUE TITLE
Me-app: On voucher list we should show clearly that voucher is expired.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#324]
## Context/goal: 
<details>
<summary>Second voucher is expired</summary>

![image](https://user-images.githubusercontent.com/10818702/89160224-04657480-d571-11ea-9b6b-a96872c03c23.png)
</details>

**Comment by maxvisser** [comment]
@jamalv @Myshelova I don't see the voucher list in android libary; Can we add it and so we can make an IP?

**Comment by jamalv** [comment]
@maxvisser just curious why would you rate this must have? has this been a problem in the past (of course I see it's important ;) -- just trying to understand priority :)))

**Comment by maxvisser** [comment]
Well seems like a no brainer and pretty shameful as it's so small in scope

**Comment by Myshelova** [comment]
@maxvisser I told you and Jamal about the problems with Sketch export to Figma with Android App. I'm adding all screens according to our priorities. I will add all other screens as soon as it will be possible)

**Comment by Myshelova** [comment]
But we also have a voucher list with a new concept with Actions at the Android Library <img width="205" alt="Screenshot 2020-08-12 at 22 56 43" src="https://user-images.githubusercontent.com/22478043/90067256-1f618280-dcef-11ea-88fe-a3c9830437d3.png">

**Comment by maxvisser** [comment]
Nice thanks

**Comment by maxvisser** [comment]
I think daniel has put this yellow text on the right side in iOS
![image](https://user-images.githubusercontent.com/10818702/90235246-44561280-de21-11ea-9e7b-4dae4469db1c.png)

**Comment by maxvisser** [comment]
@GerbenBosschieter could you make a screenshot of iOS?

**Comment by jamalv** [comment]
I believe this is good now?

**Comment by maxvisser** [comment]
On Android it isn't

**Comment by maxvisser** [comment]
Still waiting on a screenshot of iOS

**Comment by Myshelova** [comment]
https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/Me-iOS?node-id=1285%3A0 
<img width="414" alt="Screenshot 2020-11-19 at 09 32 35" src="https://user-images.githubusercontent.com/22478043/99641229-41834300-2a4a-11eb-98fa-23ec02db16aa.png">

**Comment by maxvisser** [comment]
This is how it looks now on production on android:

![image](https://user-images.githubusercontent.com/10818702/99642271-9a9fa680-2a4b-11eb-80cf-62bdfb6f9533.png)

![image](https://user-images.githubusercontent.com/10818702/99642337-aee3a380-2a4b-11eb-9a84-f7c7662cf681.png)

**Comment by maxvisser** [comment]
On android:
- you can't see on the list that a voucher is expired
- voucher details page looks not nice without QR-code (maybe show fund image?)
- The red text where the button were have alot of free space between it and the dividing line.
