### ISSUE TITLE
Finalize requester sign-upflow

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#325]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:
 
- [x] Design
- [x] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
...

## Desired situation
As a requester I would like to sign up to the fund so that I can get access to my budgets.

## Plan
-

https://www.figma.com/file/6mW06zt7214LgwZIoY2VVF/Requester-signupflow%3A-Project-%F0%9F%92%AF?node-id=0%3A1

**Comment by jamalv** [comment]
notes: needs funds page; 

about child fund; how do we do this?

**Comment by maxvisser** [comment]
Should list all development tasks to estimate scope

**Comment by jamalv** [comment]
@maxvisser in order to deal with multiple funds I propose to add a step where the user selects what funds they want to apply for. This way we only need one signupflow for the requester: https://github.com/teamforus/general/issues/339

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/347

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/348

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/349

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/350

**Comment by maxvisser** [comment]
Closed 2 issues @GerbenBosschieter, as these were too similar to some already on the backlog. Tried to reuse your comments in the older ones.

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/351

**Comment by GerbenBosschieter** [comment]
@maxvisser we should add these issue you refer to to this epic. There is not really a good way for me to know what is already on the backlog expect going through the backlog.

**Comment by maxvisser** [comment]
I will combine and close if needed; dont worry about it; I rather have duplicates then no issues at all 👍

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/352

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/353

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/355

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/357

**Comment by maxvisser** [comment]
Please note errors:
![image](https://user-images.githubusercontent.com/10818702/91999133-577f4280-ed3c-11ea-8e73-3bc97e901c3d.png)
How should these look?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/91999318-8ac1d180-ed3c-11ea-898a-235840975946.png)
should be adjusted towards the new titles

**Comment by maxvisser** [comment]
stap 1:
- email pagina
Size input field
border radius
textual changes
Vul uw e-mailadres in om een account aan te maken
U kunt tussentijds afbreken en op een ander moment verder gaan.

Stap 1: bevestigen

Text only

Stap 2: login with DigiD

Text only

Overview:
One has criteria other has overview of steps
circles look like inputs

**Comment by jamalv** [comment]
@maxvisser I believe your are now reviewing this :)

**Comment by maxvisser** [comment]
The flow is still in prototypes right? Not all checkmarks have been set to start development. I already planned some smaller stuff to already start on this (before approval). We should still make task for alot of smaller stuff. I am currently testing #150 not this one.

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R5](https://forus.testquality.com/project/11140/testcase/255430/requirement/10813). Do not remove or edit.

**Comment by maxvisser** [comment]
released
