### ISSUE TITLE
CR: Dead end downloading Me app from PC.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#326]
When on pc, clicking on the link in the log in mail to download me app:

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/fcc44dcc-4241-4615-8d63-cf4d04688923)

It shows the following sceen.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/bf5241ea-e7f5-4bab-ac05-079a2a698dc2)

This is a dead end on pc. 

It says "Gebeurd dit niet?" but gives no clue on what to do next.

Can we make this step have a logical conclusion on pc as well?

I understand it should not be pressed on pc. But people will do this anyways. It makes more sense to give more info about me app. or Link to the apps store on pc aswell.

Somethink like: https://play.google.com/store/apps/details?id=io.forus.me&gl=NL

**Comment by maxvisser** [comment]
#281
