### ISSUE TITLE
Adding more explicit dates to validation process

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#329]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Validators

### Change description
As a validator I would like to clearly see the dates of certain actions so that I know if I'm responding within the appropriate timeframe.

figma: https://www.figma.com/file/cHEYJrdU5hGz76pZNgsDkP/Adding-more-explicit-dates-to-validation-process?node-id=0%3A1

**Comment by maxvisser** [comment]
Which dates?

fund request creation date?

**Comment by jamalv** [comment]
Yes, I think that is the most important one, but also for the messages I think.

**Comment by maartenfv** [comment]
@jamalv I agree. Every message needs a date and time.

**Comment by maxvisser** [comment]
Made an initial scope estimation. added project-100 label

**Comment by maxvisser** [comment]
Seems to be a duplicate of https://github.com/teamforus/general/issues/319
