### ISSUE TITLE
POT | External validation

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#33]
## Change request

Requested by: Customer

### Change description

As a sponsor I would like to assign an external organisation as a validator so that there is an efficiency gain for me and all involved parties by leveraging my trust in external organisations.

On the fund page, for each record, appoint one or more possible validators. create workflow in figma > approve > implement

**Comment by jamalv** [comment]
## Notes from refinement call (analysis):

How do you know which organisations you can assign as a validator? : Similar interaction as with providers?

What happens if you deny a validator?

Note: Existing customer has a validator; if it is removed, the activation codes become invalid. (remark: not currently relevant, they are not using activation codes)

By default a sponsor should be a validator for their own funds.

Sponsor might needs some overview of requests and statistics etc.

Automatically unassign fund requests should also work with external organisations (old ones should stay valid?)

Set time period in criteria; should be newer than xxx

What happens with mistakes? With fraud?

Should think about confirmation process

Should track who assigned which records (which organisation & which employee)

What happens with a conflict? One organisation approves / one organisation denies

Two organisations can send clarification requests: this can be weird for the user

Municipality will use digid

Forus should manually add validators

User should be verified to be able to create funds, should be a review proces by forus

Scope:
Validator applies to fund
External organisation can approve fund request

Pages;

Criteria on fund (have mvp)
Sponsor: accept

**Comment by jamalv** [comment]
Concept from figma: https://www.figma.com/file/8Xc9yR3qpe0C26AfdaZnxH/prototype-ANB?node-id=914%3A2538


![image](https://user-images.githubusercontent.com/30194799/75887756-8cace580-5e2a-11ea-95ba-6a0c8c29186e.png)


![image](https://user-images.githubusercontent.com/30194799/75887734-8454aa80-5e2a-11ea-981b-f8f467161a28.png)

**Comment by jamalv** [comment]
Risk:
Should not impact current funds, since they are only using internal validation. This will be added as an extra. @dev-rminds @maxvisser, could you verify this?

**Comment by jamalv** [comment]
## informing users
Current workflows with prevalidations / activation codes and automatic validation with digid will not be impacted. This is purely extra functionally.

**Comment by maxvisser** [comment]
@maartenfv @linda-90 https://www.figma.com/file/ak9pjSwJsgwOdpPjadL26Q/%F0%9F%9B%91Prototype-external-validation could you check this for language?

**Comment by linda-90** [comment]
@jamalv I have moved this issue back to the Figma design stage for a final design check.

**Comment by maartenfv** [comment]
@maxvisser Can we fix the pop up so we can translate it?

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1680

**Comment by maxvisser** [comment]
should be on production on 17 Augustus 2020
