### ISSUE TITLE
Change all our e-mails to text align left.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#330]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Some of our new e-mails (like digest e-mails) have the text aligned left. I've already received a couple of them and it looks much better than all the e-mails we send with text aligned center.

- It's more friendly to read
- It looks cleaner and more structured. Some of the mails we send with text align center look a bit messy (as the example below)

#### Note
This does look like a easy and small change, and it is. But there are some e-mails (like login e-mails) that use images. Not sure if the design of these e-mails would look good if the text and image are left aligned.

<img width="443" alt="Screen Shot 2020-08-05 at 10 49 53" src="https://user-images.githubusercontent.com/38419514/89393940-bc2e8980-d70b-11ea-8207-feb7902e43af.png">

<img width="538" alt="Screen Shot 2020-08-05 at 10 49 46" src="https://user-images.githubusercontent.com/38419514/89393935-ba64c600-d70b-11ea-9149-9a309780c8c1.png">

**Comment by maartenfv** [comment]
@GerbenBosschieter I like this one

**Comment by maxvisser** [comment]
I think we should atleast make it consistent.
