### ISSUE TITLE
CR: Informing users when they receive a voucher from voucher generator or aanbiedingsvoucher generator

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#331]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Nijmegen

### Change description
Currently, they receive an undigested email? @maxvisser is this correct?

We should have the option to send a mail from the system when toekennen, @maxvisser maybe the sponsor should be able to switch this on or off? What happens if you receive 5 times the same voucher like what happened at Nienoord?

We should have a notification in the Me app when a new voucher has been added.

**Comment by maxvisser** [comment]
We currently have a mail which is sent by Voucher generator. 'toekenningsmail' which is sent at each voucher generator. For the product voucher generator we do not sent any mails. For nienoord I sent this mail manually to all users via Gmail.

I see two new functionality and something we already have but can be optimized

Two new requests:
- Add digest for new vouchers (notification digest?)
- Enable/disable direct mail to user with QR-code

What can be optimized:
- Add notification in Me-app when new voucehr is added -> Current there is no list of all new notification in the Me-app. If you click notification it will not open the voucher. Notification can be optimized.

**Comment by maxvisser** [comment]
if planned, estimation should be checked by Dan.
