### ISSUE TITLE
CR: which flags on frontend and backend are there?

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#337]
## Context/goal: 
On release-v0.14.0 its not needed anymore. 

## Task
- [ ] remove fund criteria edit by user flag
- [ ] list all flags

**Comment by maxvisser** [comment]
I want an index of which flags are in forus-backend and forus-frontend; Currently its a bit chaotic. Last friday me and valentin spent both 1h 30m looking for an issue while a flag was enabled. This can save precious time if we can have a list. (and be carefull about creating any kind of flag and explain when it can be removed.)

**Comment by maxvisser** [comment]
Removing fund criteria edit by user flag (was the flag of last friday) this one can be removed

**Comment by maxvisser** [comment]
estimated scope on 8h probably less.

**Comment by maartenfv** [comment]
Has this been released?

**Comment by jamalv** [comment]
I believe this is an ITSM issue
