### ISSUE TITLE
Organisation signup from the homepage

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#338]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholders

### Change description
As an organisation I would like a link to sign up on the webshop

Proposed task:

Add the following url structure to the menu (potjeswijzer webshop)

Organisatie aanmelden
- Aanbieder aanmelden (link to https://forus.io/provider/sign-up)
- Sponsor aanmelden (link to https://forus.io/sponsor/sign-up)
- Beoordelaar aanmelden (link to https://forus.io/validator/sign-up)

Add the following to all other webshops:
- Organisatie aanmelden (link to https://forus.io/provider/sign-up)

Figma: https://www.figma.com/file/1uq7AwH9QPi0NzeE3PpPQf/Organisation-signup-URL-s-in-menu-bar

**Comment by maxvisser** [comment]
I would not add it prominent to menu actually. Why is this a must have? If you look at competitors (like [metgezondboerenverstand](https://meedoeninmontferland.info/) or [Rotterdampas](https://www.rotterdampas.nl/)) they all take the footer approach.

**Comment by maxvisser** [comment]
Also can only be done for all webshop or we need to make menu configurable via CMS (which increases scope) or add another flag (which we can add to the mess #337)

**Comment by jamalv** [comment]
The requirement is "[rol] kan zich zelfstandig aanmelden in het platform vanaf de homepagina" ; [role] can independently sign up for the platform from the homepage - so we need a good way to allow this.

Another solution would be to add another item to the menu with a seperate page for providers:

"Voor organisaties" - then make this a page like the "uitleg" page, so that on that page a custom explanation can be added, depending on the usecase. From there we can link to the Signupflows for the different roles. 

@maxvisser If the scope of adding that seperate page is smaller (/about equal to adding the other menu items to the CMS), that would have preference, since it will be a much more customizable / scalable solution for other webshops as well. Having both the "uitleg" page for requesters and for organisations is highly desirable I think 😄 and we'll have to do something for project-31 - and I think the footer will not be sufficient.

**Comment by maxvisser** [comment]
Well the footer is part of the homepage so still not sure why this is a must have ;) I like the idea about adding more pages; I personally dont care about the direction; I just find it weird to add anything to the menu (as this is not important for the requester and yes they will click on it if its there and yes some will get confused and think the signupflow for provider is applying for a fund)

**Comment by jamalv** [comment]
Okay, agreed that it can be in the footer to fit the requirement of adding it to the homepage. And then I would also utilize the "uitleg" page for this, as that would make sense for a provider as well. 

And then I think we have to also check with usertesting if this is suffcient; If we give a provider the task "sign up for this website" from the homepage.
