### ISSUE TITLE
Requester: single signupflow

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#339]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Users during usertesting

### Change description
As a requester I'd like a single signup-flow when I apply for multiple funds so that I have a clear UX.

## Current situation
When a requester wants to apply for multiple funds, they have to go trough each signup flow for each fund start-to finish. During usertesting they got lost in this flow: Go to website > go to funds page > apply to a fund > application recieved (for the first fund they applied to) > now they are lost :( - what they should do is go to another fund but they don't really understand this so no fun!

## Desired situation
When a requester wants to apply for multiple funds, allow the requester to select which funds they want to apply to, and display the criteria for the combined funds. This way they will have a singular experience to go trough.

Figma: https://www.figma.com/file/FxqYmHGMqiYLa6LAq3UkCB/Improve-signup?node-id=0%3A1

## Related: application status page
https://www.figma.com/file/FxqYmHGMqiYLa6LAq3UkCB/Improve-signup?node-id=4%3A13

**Comment by jamalv** [comment]
@maxvisser could you rate this one on scope? I think it would be beneficial for both project 100 and 31

**Comment by maxvisser** [comment]
As the signupflow is based on criteria of the fund. It's probably a big challenge to think up a system to allow this. Probably rewriting alot of what's currently there.

**Comment by GerbenBosschieter** [comment]
https://github.com/teamforus/general/issues/347

**Comment by maxvisser** [comment]
To give more context around the big challenge:
A fund has criteria for example income. If we allow a requester to apply for multiple funds at once. We need to apply the user to multiple funds. (there will be no single fund request). One validator can deny; another can approve. Aswell as if criteria differs per fund you can have multiple 'income' related steps within a flow. which gives weird UX.

My proposal would be to at the end of the flow ask the user 'Do you want to apply for another fund' and somehow check if we can strip the parts of the form which the user just filled in (maybe save all already as records?)

**Comment by jamalv** [comment]
Okay, marking this as a could have; the mvp to solving this problem is redirecting to the funds page, optionally adding a friendly modal that you can request another fund. Later we can work on making this more smart.

**Comment by maxvisser** [comment]
#370 I also proposed that here; I would redirect users to funds page if they do not have vouchers. If they do we should think about the flow of getting them there

**Comment by jamalv** [comment]
moved to productboard: https://app.productboard.com/inbox/notes/15568830
