### ISSUE TITLE
Webshop email and notification settings

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#340]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
As a requester I would like to have email and notification settings in the webshop.

**Comment by jamalv** [comment]
For project 100 it is a must-have for the user to be able to change their e-mailadres. @maxvisser @danrminds I saw the figma prototype (linked in issue) but no issue; did I miss it or was there none?

Also, what's the status of this? can this be planned or are there still dependancies?

**Comment by maxvisser** [comment]
All are done. Changing email is a unreleased feature still. Notification settings are done

**Comment by maxvisser** [comment]
Decided to release e-mail settings; this is done after configuring on next release qdt-env to enable these pages.

**Comment by maxvisser** [comment]
a bug on email settings should be fixed before releasing on 12 oct.
