### ISSUE TITLE
Show fund description on funds page

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#343]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Erwin

### Change description
As a requester I would like to see more info about the fund on the funds page: what can I spend it on? How big is the budget? What are the criteria?

Original Figma comment: https://www.figma.com/file/8Xc9yR3qpe0C26AfdaZnxH?node-id=889:8253#29567776

**Comment by maxvisser** [comment]
Currently the fund description is not shown anywhere, correct? As their are two target audiences for this text I would let the fund description mainly focus on Requester?

**Comment by maxvisser** [comment]
released
