### ISSUE TITLE
Requester signup; refine step 1: welcome

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#345]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- The requester signup flow feels a bit incoherent for some scenario's. The expectation you get from applying for a specific fund and then land on the signupflow feels a bit weird.

Example:
1. Go to Stadjerspas webshop
2. Want to apply for stadjerspas so click on **Start aanvraag** (expectation to apply for stadjerspas)
3. Land on the sign up flow and it tells me I can apply for all kind of funds. (No context about Stadjerspas)

![request](https://user-images.githubusercontent.com/38419514/89991706-7c741e80-dc84-11ea-94e2-cdcda4f66261.jpg)

Have a close look again at image and text. It is generic for all signupflows. We got some feedback about the image and text; would be nice to see if we can improve it.

Figma: https://www.figma.com/file/NMwHKDE711LsG488kywDpC/Requester-signup%3A-step-1?node-id=1%3A129

**Comment by maxvisser** [comment]
I have no strong opinion about this one. Maybe @linda-90 @maartenfv could look at this one.

**Comment by maartenfv** [comment]
@jamalv @GerbenBosschieter I agree with Gerben I think this flow would benefit from adding a more logical step or adding text.

@jamalv Could we give this a priority label?
