### ISSUE TITLE
Requester signup info step: Can we make text more based on the fund of the implementation instead of always generic?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#347]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- The requester signup flow feels a bit incoherent for some scenario's. The expectation you get from applying for a specific fund and then land on the signupflow feels a bit weird.

Example:
1. Go to Stadjerspas webshop
2. Want to apply for stadjerspas so click on **Start aanvraag** (expectation to apply for stadjerspas)
3. Land on the sign up flow and it tells me I can apply for all kind of funds. (No context about Stadjerspas)

![request](https://user-images.githubusercontent.com/38419514/89991706-7c741e80-dc84-11ea-94e2-cdcda4f66261.jpg)

**Comment by maxvisser** [comment]
Seems like somewhat the same as https://github.com/teamforus/general/issues/345

**Comment by maxvisser** [comment]
Maybe combine these? @jamalv

**Comment by maxvisser** [comment]
Combined them
