### ISSUE TITLE
Requester signup step 1: textual change

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#348]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Step one has the following text and needs to be changed imo.

**Title:** Vul uw email adres in om verder te gaan
**Description**: Er wordt gekeken of u al aan voorwaarden voldoet, en u kan tussentijds afbreken en op een ander moment verder gaan.
**Link to me-app**: Ik wil inloggen met de me app

**Notes**
- Title: Email adres is wrong, should be e-mailadres (dutch way)
-  Description: The step of verifying e-mail is informing about the conditions/criteria of the fund. This step should be focused on just creating a profile / verifying e-mail and not mentions the conditions/criteria. This is confusing, because the requester doesn't have an easy and quick way to see what the criteria's are.
- Description: I don't think that the sentence is grammerly correct (this part: voldoet, en u kan). After a comma you shouldn't use **en**?
- We link to the Me-app in this step, but I can imagine that this could be confusing if they have never seen aa mentioning of the me-app before.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/89995415-b72c8580-dc89-11ea-9b6b-0cfe058e1164.png)
this is in figma

**Comment by maxvisser** [comment]
released
