### ISSUE TITLE
Requester signup step two: Textual changes and comments

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#349]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
We need some changes to this step:
- The text feels like a computer is talking to a person and it also needs to be more action based. Instead of explaining  what happend we should tell them what to do. This is less text and less confusing.
- The title should change: don't tell them about we want to know if you have acces. Just tell them, we have send you a mail, please click the link to continue your application
- Don't refer to the blue button, just the link. Some e-mail clients don't know have css included or really minimal. Or there is a another reason why they don't display the blue button.  Whatever it is, if you expect a blue button and it's not there. Really confusing

Example: We have send you a link, please click this link to verify. (mand)

- Title gets cut off
- Do not mention the subject of the mail to refer to the e-mail,  this is not scalable at all. And can be really confusing if the e-mail subject is different that what is being said in the e-mail (this is currenlty already the case)

<img width="951" alt="Screen Shot 2020-08-12 at 10 31 07" src="https://user-images.githubusercontent.com/38419514/89993405-f4dbdf00-dc86-11ea-83e3-cacbacf58f4c.png">

**Comment by maxvisser** [comment]
This text is also not standard. We should just write this text once and use it everywhere. There is already an IP to improve this. https://github.com/teamforus/general/issues/224

**Comment by maxvisser** [comment]
I will close this in favor of https://github.com/teamforus/general/issues/224 And will add https://github.com/teamforus/general/issues/224 to finalize requester signupflow.

**Comment by jamalv** [comment]
Mand!
