### ISSUE TITLE
Requester signup step indicator: Where am I, How did I get here, What year is it?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#350]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Step indicator is weird. Doesn't really make sense. We had the same problems with the provider sign up flow. Maybe there are too many scenario's of how people can land on a certain step to get  the step indicator really clear. If this will take to much time to fix, I would just hide the steps and keep the loading/indication bar.

Example: 
![flowww](https://user-images.githubusercontent.com/38419514/89995318-9cf2a780-dc89-11ea-8eb3-a1b10f41159f.jpg)

![whereami](https://user-images.githubusercontent.com/38419514/89995363-a7ad3c80-dc89-11ea-9ad9-43a2e5998c27.jpeg)

**Comment by maxvisser** [comment]
Login and Acitivation steps are not part of the stepper anymore.
