### ISSUE TITLE
Requester signup step three: use bulletpoints instead of checkboxes

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#351]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- We should use bullet points instead of checkboxes (checkcirkels). It gives an impressions you can check the circles while you can't.

<img width="780" alt="Screen Shot 2020-08-12 at 11 04 47" src="https://user-images.githubusercontent.com/38419514/89996918-b5fc5800-dc8b-11ea-9a39-e4a75a2d4522.png">

**Comment by maxvisser** [comment]
In user tests someone did try to press it 👍

**Comment by maxvisser** [comment]
released
