### ISSUE TITLE
Requester signup flow step three textual style changes, the signup flow will be used by people not computers.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#352]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- The way we display criteria is like we are talking to a computer.

Critera's:
<img width="780" alt="Screen Shot 2020-08-12 at 11 04 47" src="https://user-images.githubusercontent.com/38419514/89997421-69fde300-dc8c-11ea-9c29-22f739499af1.png">

Could be:
- U bent woonachtig in de gemeente Groningen
- Uw toetsinkomen mag maximaal 20000 zijn
- U heeft minimaal één kind.

**Comment by maxvisser** [comment]
This is fixed on new PR to develop; Sponsor can now fill in a title which will replace the default text.

**Comment by maxvisser** [comment]
I see this is already in release/v0.14.0 we can improve the flow on staging.

**Comment by maxvisser** [comment]
released
