### ISSUE TITLE
Requester signup flow step three: A wild DigiD has appeared

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#353]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
The user gets confronted by a random and wild DigiD logo If a user gets to the step of all the criteria's of the fund.
There is no context about DigiD at all and there is still the possibility to go the next step.

Not sure if this is a configuration thing or whatever. But it's weird.

<img width="1920" alt="Screen Shot 2020-08-12 at 11 07 32 (2)" src="https://user-images.githubusercontent.com/38419514/89997807-f1e3ed00-dc8c-11ea-8f29-61fc9fa11cd7.png">

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1695

**Comment by maxvisser** [comment]
released
