### ISSUE TITLE
Requester signup step one (not really step one): tell the user what to do, not just stating the criteria.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#355]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
The title of this step is the criteria. It should inform the user what to do, the description and text area where the explanation is should inform the user what it is.

Current title: **Uw inkomen is lager dan 120% van de bijstandsnorm**

I can't even think of a correct sentence cause I have no idea what this step is for. 
I assume it's explaining the specific criteria and an option for the user to provide the sponsor of the proof if the user meets the criteria. Is this the case? If so, we should:

- Tell them if it's mandatory to provide proof.
- Explain what this step is for
- Also give explanation what will happened if they do go to the next page and didn't upload any proof (something like: **note** We can request request you to provide us with a proof on a later moment)

<img width="788" alt="Screen Shot 2020-08-12 at 11 26 00" src="https://user-images.githubusercontent.com/38419514/89999626-54d68380-dc8f-11ea-829a-cfde2dfe4f35.png">

**Comment by maxvisser** [comment]
I see the change here as add an option to make uploading proof mandatory @jamalv

**Comment by maxvisser** [comment]
released
