### ISSUE TITLE
Requester signup step two (not really) agree with the criteria needs textual and design changes

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#357]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
This step is really confusing for a user and it triggers some reactions (I am easily triggered btw ;) )

**Title:** You accepted the criteria (Says who? I did not, I am here to agree with it not because I already did) 
**Could be**: Please confirm that you agree with the criteria to continue your application

**Input field / placeholder:** Uw Andere voorwaarden stadjerspas (whut does this even mean). Also it's not clear this is a input field or a selection field. Only if you click on it, the placeholder itself says something about the criteria but the form request the user to fill something in. But What? Also the point about talking to humans instead of computers.

**Area with all the criteria summed up**
Add bullet points, it now looks like a bunch of random text.

<img width="854" alt="Screen Shot 2020-08-12 at 11 40 13" src="https://user-images.githubusercontent.com/38419514/90001678-070f4a80-dc92-11ea-8b33-b9b75ef10716.png">

**Comment by maxvisser** [comment]
Title has been filled in from sponsor dashboard. I see this as fixed in Figma but we should check that.

**Comment by jamalv** [comment]
quite sure all of this has been fixed
