### ISSUE TITLE
Sponsor dashboard: Fund configuration unclear what the clicking the checkbox does

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#358]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
The sponsor has an option to click the checkbox at: **Bijlage uploaden**.
But what does this do, will this display a possibility to upload proof? Or will this make uploading proof mandatory?

We should add more context to this option. And depending of what it really does we maybe also should a warning to the requester signup flow that it's mandatory

**Comment by GerbenBosschieter** [comment]
<img width="1008" alt="Screen Shot 2020-08-12 at 12 03 15" src="https://user-images.githubusercontent.com/38419514/90003601-9ae21600-dc94-11ea-8c72-0ff07dcc94b4.png">

**Comment by maxvisser** [comment]
I would maybe move this to the modal
