### ISSUE TITLE
Activate voucher using digid

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#359]
## Context
For multiple upcoming projects we need to be able to activate vouchers using DigiD. 

The prevalidations will be added by CSV file. The BSN numbers will be in the CSV file.

## User stories
As a requester I want my vouchers to be automatically added to my account if I have the required prevalidations. If I **don't** have the right prevalidations linked to my BSN number, I would like to be redirected to the signupflow.

Figma link:
https://www.figma.com/file/o6niDcOCCRGbrt0GyM2Xfr?node-id=2%3A46&viewport=-2866%2C440%2C0.42657166719436646

**Comment by maxvisser** [comment]
This needs to be reviewed. As currently this is already done but when a user already has a BSN number assigned. In requester signupflow there is no way to retrieve new prevalidations

**Comment by maxvisser** [comment]
@jamalv Maybe lets do a quick refinement session about this; I will plan it in agenda.

**Comment by maxvisser** [comment]
@danrminds  is in the loop on this issue.

**Comment by maxvisser** [comment]
Did a brainstorm session with jamal and created a figma prototype for this issue. It contains some other CR aswell #370 #448 #434 #266 https://github.com/teamforus/general/issues/300

**Comment by jamalv** [comment]
@maxvisser was in .15?
