### ISSUE TITLE
CR: Enhance Budget voucher transaction mail

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#361]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

The requester gets a mail that contains:
## Er is een bedrag van uw :fund_name-tegoed afgeschreven
Er is met uw tegoed een aankoop gedaan. Hierdoor is er een bedrag afgeschreven.
Het huidige bedrag van uw \':fund_name\'-tegoed is €:current_budget

## Proposal
Add what was deducted from saldo 
enhance text.

**Comment by maxvisser** [comment]
@jamalv maybe rewrite current transaction mail + write a new one for actions? 

I see this as a must have

**Comment by jamalv** [comment]
Yes agreed this is a Must-Have, what do you need from me? Text suggestion:

## Financieel fonds
Er is een bedrag van uw :fund_name-tegoed afgeschreven
Er is met uw tegoed een aankoop gedaan. Hierdoor is er een bedrag afgeschreven.
Het huidige bedrag van uw \':fund_name\'-tegoed is €:current_budget

## Acties fonds
U heeft gebruik gemaakt van een actie met uw :fund_name-tegoed.
Uw resterende tegoed voor {actie naam} is {aantal}

**Comment by maxvisser** [comment]
Created a new issue for actions voucher transaction mail.

**Comment by linda-90** [comment]
Text review:

## Financieel fonds
- Er is een bedrag van uw :fund_name-tegoed afgeschreven
Er is met uw tegoed een aankoop gedaan. Hierdoor is er een bedrag afgeschreven.
Het huidige bedrag van uw \':fund_name\'-tegoed is €:current_budget
- Er is een bedrag van je :fund_name afgeschreven
Met je :fund_name is een aankoop gedaan. Hierdoor is er een bedrag afgeschreven.
Het huidige bedrag van je \':fund_name\' is €:current_budget.

@maxvisser We hadden -tegoed overal weggehaald toch?

## Acties fonds
- U heeft uw :fund_name gebruikt voor het aanbod: {actie naam}. Uw resterende tegoed voor {actie naam} is {aantal}.
- Je hebt jouw :fund_name gebruikt voor het aanbod: {actie naam}. Je resterende tegoed voor {actie naam} is {aantal}.

**Comment by maxvisser** [comment]
geen idee @linda-90

**Comment by maxvisser** [comment]
voor budget transactie willen we het bedrag dat in mindering is gebracht van het budget in de mail zetten

**Comment by linda-90** [comment]
@maxvisser Ja lijkt me goed!

**Comment by jamalv** [comment]
@maxvisser could you plan this in itsm?
