### ISSUE TITLE
Offers / Providers page: replace text with breadcrumbs

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#362]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Current situation
On the offers and providers page we are displaying some text which is pretty pointless:

<img width="409" alt="Screenshot 2020-08-14 at 08 28 51" src="https://user-images.githubusercontent.com/30194799/90220297-38aa2200-de08-11ea-8f6b-bec12abd8c9c.png">
and 
<img width="409" alt="Screenshot 2020-08-14 at 08 29 35" src="https://user-images.githubusercontent.com/30194799/90220333-4bbcf200-de08-11ea-8cdc-22371f543dbc.png">

Right next to it we are already displaying the info from the same text:

<img width="153" alt="Screenshot 2020-08-14 at 08 30 06" src="https://user-images.githubusercontent.com/30194799/90220373-5d9e9500-de08-11ea-9d6e-5e2db676d967.png">

And "click the card for more information" is also redundant; it's how the internet works, we don't have to explain it 😄 It's what this indicator is for:

<img width="199" alt="Screenshot 2020-08-14 at 08 31 11" src="https://user-images.githubusercontent.com/30194799/90220445-83c43500-de08-11ea-92c3-1e3684d5f80d.png">

## Task
Replace that text with breadcrumbs, to make the page easier to digest:

https://www.figma.com/file/JzN5CbEcgeRNARVv86hLiY/Untitled?node-id=0%3A1

Before
<img width="1679" alt="Screenshot 2020-08-14 at 08 51 21" src="https://user-images.githubusercontent.com/30194799/90221931-5f1d8c80-de0b-11ea-895c-5eed44d3f2d1.png">

After
![image](https://user-images.githubusercontent.com/30194799/90221024-a99e0980-de09-11ea-973e-591656df1690.png)

**Comment by jamalv** [comment]
@GerbenBosschieter @maxvisser @linda-90 @maartenfv what do you think?

**Comment by maxvisser** [comment]
Looks much more clean I like it 👍

**Comment by linda-90** [comment]
@jamalv Like it! 
'8 aanbod' is alleen een beetje gek. Stel voor om het op deze manier op te lossen: Aanbod 8
En dan de tekst aanbod wellicht iets groter omdat het een titel is.

<img width="674" alt="Schermafbeelding 2020-08-18 om 13 44 36" src="https://user-images.githubusercontent.com/36952230/90509022-fca0f500-e158-11ea-943a-9da9673ed65a.png">

**Comment by maxvisser** [comment]
This seems to be fixed already :D
