### ISSUE TITLE
Fund request on product page

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#363]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholders

### Change description
As a requester I would like to request a fund from the product page

Note: this page is already in actions; but we'd also like to have it on the normal product pages 😄 - It is modified a bit to be relevant to normal product pages; and it is highly desirable for project-31

Figma: https://www.figma.com/file/t65CXu3QbVG2aJrgdu8dvS/Untitled?node-id=2%3A0

**Comment by danrminds** [comment]
@jamalv 

We had 3 instances there:

- When you are logged in and have the voucher
- When you are logged in and have still to apply for a fund
- When you are not logged in

Should we add all 3 instances?

**Comment by jamalv** [comment]
@danrminds yes please!

**Comment by maxvisser** [comment]
A action is fund specific so there is no list of multiple funds (where user can apply for)
A product has can be bought with multiple funds. If a product is applicable for more three; what would happen? I would only show a max of three and maybe a link to the full list.

**Comment by maxvisser** [comment]
potjeswijzer-demo branch -> @maxvisser should check if it can be merged.

**Comment by maxvisser** [comment]
Is removed from the code. Probably the action one needs to be adjust to be reusable for other types of funds.

**Comment by jamalv** [comment]
afaik this has been done 🚀
