### ISSUE TITLE
Link to fund page at the end of signupflow

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#364]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
As a requester I would like to be redirected to the funds page at the end of a fund signup if there are more funds I can apply to.

**Comment by jamalv** [comment]
todo (gerbs) - update text on button

**Comment by maxvisser** [comment]
potjeswijzer-demo branch -> Should check if can be merged to develop @maxvisser

**Comment by maxvisser** [comment]
This is done.

**Comment by maxvisser** [comment]
released
