### ISSUE TITLE
Funds page: add filters, pagination and search

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#366]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Update the funds page to match the styling of the other webshop pages

Note: in the dutch translation we changed "funds" to "aanvragen"

Figma: https://www.figma.com/file/JQOpMquZiDvI2WwKdw2iDC/Improving-funds-page?node-id=52%3A0

**Comment by danrminds** [comment]
@jamalv I see there are filters on the Figma link you sent. Is anything else left now?

**Comment by jamalv** [comment]
I think it is good like this, it is already in pull requests. @maxvisser, what's the dev status of this? Will it be included in v0.15? - I think it can be merged into the design library.

**Comment by maxvisser** [comment]
There is still a bug in the filter I noticed. Will create an issue for it. Yes it will be included for release v0.15.0

**Comment by maxvisser** [comment]
released
