### ISSUE TITLE
Webshop me-app page needs new sreenshots/design

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#367]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter , others

### Change description
There are some desires to quick-fix the me-app page on the webshop. 

1. Update images (screenshots)
2. remove the scheme image (the weird twirl thats connects the me-app screenshots)

Removal of the twirl isn't the problem.
But updatnig the screenshots is difficult, we need a Figma design for this and the images itself.

**Comment by maxvisser** [comment]
Close this one in favor of #496
