### ISSUE TITLE
Experiment: Change products to be the homepage

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#368]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Ingrid, and as a result of usertesting

### Change description
As a requestor I would like to first find what I am looking for (for example swimming lessons, or something else) before I apply to a fund.

This change request is to test how people respond to this change. We will use it to get stakeholder feedback and to do usertesting.

**Comment by maxvisser** [comment]
Amazon does it well I feel, a tooltip is open when you enter logged out.
![image](https://user-images.githubusercontent.com/10818702/91222307-483a3c80-e71f-11ea-945c-1c1c3d850e3c.png)
