### ISSUE TITLE
CR:As a new customer I would like to have an testing environment to learn and give feedback before the official release

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#37]
## Change

Requested by: @requester

### Change description

As a new customer I would like to have an acceptance environment to learn and give feedback before the official release

**Comment by maxvisser** [comment]
Depends on the strategy but I would not like customer feedback each release; As we will get more and more customer who decides which customer do acceptance testing.

I do like the idea of having staging aswell as a test environment where municipalities can play around with and have aswell service windows for staging.

**Comment by jamalv** [comment]
Yes, this is not about feedback/acceptance but more about training :)

And also checking fund config (e-mailadresses), voucher amounts, and other such things

**Comment by maxvisser** [comment]
Well title and description is wrong. Do you mind changing it Gerben? or shall we create new CR.

**Comment by maxvisser** [comment]
We are trying this out with Groningen and see if this works in everyones favor!

**Comment by maxvisser** [comment]
This needs a DoD @GerbenBosschieter Whats needed to close it?

**Comment by GerbenBosschieter** [comment]
@maxvisser for the specific use case of Groningen it's done. Two employees are already onboard and more will follow. That being said, would be nice to have a testing environment / proces for our new clients.

**Comment by maxvisser** [comment]
Allright; As we did not receive any complaints yet I see this as fixed. Maybe lets reopen it when new use cases arise. (or create new proposals for improvement) as MVP is there.
