### ISSUE TITLE
POT | Logo feedback (Dutch)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#371]
Logo Potjeswijzer.
- Eerste indruk Medicatie potje (geneeskunde).
- Ander vorm potje er van maken.
- QR-code is goed
- Deksel moet er af.
- Spaarvarken.
- Taalhuis, pictogrammen  zijn belangrijk (vuistje: schoolboek, Kleding etc).
- Stripverhaal in logo (van potje naar product of dienst)
- Door meerdere iconen toe te voegen kan je deze ook los verder gebruiken.

**Comment by maxvisser** [comment]
if needed could ask jiske to make a logo @jamalv

**Comment by maxvisser** [comment]
@maartenfv English would help :D

**Comment by maxvisser** [comment]
A new logo is on test.potjeswijzer.nl; As I see there is already lot of time being tracked on the logo. Whats our DoD on this?

**Comment by linda-90** [comment]
Issue over aanpassingen logo: https://github.com/teamforus/general/issues/241
