### ISSUE TITLE
POT | CMS Webshop: Style links as links (underline)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#373]
Edit (Jamal): in potjeswijzer when adding a link on the homepage, it does not give an underline (styling); should be fixed.

**Comment by jamalv** [comment]
That was quick! Thx!

**Comment by maxvisser** [comment]
Scope: small but could be that the CSS is overwritten by certain implementations

**Comment by jamalv** [comment]
@maxvisser could this be planned?

**Comment by jamalv** [comment]
in .15
