### ISSUE TITLE
We should move to Mercury

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#376]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @dev-rminds 

### Change description
- Since we only have 24 hours on this planet but need much more than 24 hours in one day we should move to Mercury. A day on Mercury has 58 hours

**Comment by GerbenBosschieter** [comment]
# Tasks
 - [ ] Contact Elon Musk about the possibilities

**Comment by maxvisser** [comment]
I am already there. Base camp is up and running.

**Comment by maxvisser** [comment]
I will now fly back and be back on earth on Wednesday :grinning:

**Comment by jamalv** [comment]
Ah, thats great! Did you bring beer there? 🍻

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/91213014-4e292100-e711-11ea-80c8-c78346f3bc4f.png)
