### ISSUE TITLE
Check resolution size of jumbotrons

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#378]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
I coincidentally checked some header image for a webshop and it's 10mb, which is way too big! 😱 

<img width="219" alt="Screenshot 2020-08-23 at 11 49 40" src="https://user-images.githubusercontent.com/30194799/90975699-ec14c400-e536-11ea-9650-b54b0ed9a1e9.png">

Figma:
https://www.figma.com/file/sHS5eTHl3S0GEpURdrLRmm/Check-resolution-size-of-jumbotrons?node-id=66%3A412

**Comment by maxvisser** [comment]
But otherwise there is no way you can see the name of the ship 😆 
![image](https://user-images.githubusercontent.com/10818702/91213636-300ff080-e712-11ea-8c92-dd16236602f4.png)

**Comment by maxvisser** [comment]
Its compressed though just really high res

**Comment by maxvisser** [comment]
This one is 2000x800: (1.2mb)
![jumbotron (1)](https://user-images.githubusercontent.com/10818702/91215118-59318080-e714-11ea-868e-b40ddccc27dd.png)

**Comment by maxvisser** [comment]
Seems like it was mostly the jumbotrons of SDOA. If you approve above images we could make as task for it @jamalv

**Comment by jamalv** [comment]
Not sure If I am the one that can grant an approval but I think we came to an agreement

**Comment by maxvisser** [comment]
Currently on develop: part of release v0.15.0

**Comment by maxvisser** [comment]
released
