### ISSUE TITLE
Login button on provider signup page

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#379]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a provider I would like the option to login from the signup page

Figma: https://www.figma.com/file/LQB7ZCP8PWDyIQFaaOdz4D/Update-provider-signup-pages?node-id=1%3A94

**Comment by maartenfv** [comment]
@jamalv We have done the text review and added some text to make it more clear.

**Comment by maxvisser** [comment]
released
