### ISSUE TITLE
CR: Support tickets / chat integrated with github

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#38]
## Change request

Requested by: @danrminds 

### Change description

Would be interesting to have a support channel like support tickets, on certain topics, online - so we can receive and create change requests automatically using the API of Github.

**Comment by maxvisser** [comment]
I think gerben is doing already a pretty good job. Maybe could check which stuff could be automated.

**Comment by maxvisser** [comment]
Gerben can now create CR from Zoho with a flow
