### ISSUE TITLE
Footer add link to open modal for choosing Login / Signup as provider

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#382]
During the text review, we found that the sign-up flow for the requester is unclear.

It is difficult to know where to start the journey. Links it the footer are not sufficient as people are not going to find it. We found the Figma proposal adding the sign up to the menu. This is a very good idea.

We have improved the texts and added suggestion on how to improve the flow.
https://www.figma.com/file/1uq7AwH9QPi0NzeE3PpPQf/338%3A-Organisation-signup-URL's-in-menu-bar?node-id=7%3A134

- Clicking the menu item leads to a pop up giving a choice to providers. Do you want to log in (you have an account for your org) or do you want to sign up to create a new one.
  - Clikcking "Login" leads to login pop-up using mail or scan QR-code.
  - "Aanvraag" leads to provider sign up flow.

Futhermore.

- We restructured the footer to make it more clear.
- A separation between login in and signing up.
- A link for every role.
- Added a sentence as context about the Me app. So people know why.

Is this possible?

**Comment by maxvisser** [comment]
I would keep the menu for pages and not let some links open modals. I would see if there are better ways to get providers to signupflow and look on how competitors do this.

**Comment by maxvisser** [comment]
As this will now open a page; I see this as 'fixed'
