### ISSUE TITLE
Information about conflicting roles

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#384]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholder

### Change description
As a system administrator I would like to be informed about conflicting roles

[doc](https://docs.google.com/document/d/1q1XYs50ns92gHkmrfRWq4sZspui6RkR6W8CvLFoCft4/edit)

**Comment by maxvisser** [comment]
Validator should not be a manager
Manager should not be able to manage vouchers or create vouchers

Create a table for this.
