### ISSUE TITLE
Add "how it works" in header to CMS

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#386]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Linda

### Change description
As an implementation manager I would like the "how it works" (dutch: Hoe het werkt") link to be part of the header text in the CMS so that the webshop owner has the freedom to remove / edit it themselves

This issue is dependant on #373

**Comment by maxvisser** [comment]
the step-by-step guide or FAQ? I would just remove these blocks completely

**Comment by jamalv** [comment]
Nooo, on the homepage there is a link as well :)

**Comment by jamalv** [comment]
<img width="181" alt="Screenshot 2020-08-28 at 10 00 55" src="https://user-images.githubusercontent.com/30194799/91536689-5e115280-e915-11ea-84f3-fd5b067851d0.png">

**Comment by jamalv** [comment]
Probably small scope?

**Comment by jamalv** [comment]
Context: one of the customers would like to remove the link on the homepage header text, if we add this part to the CMS, they can choose themselves if/how they want to link to the "uitleg" page

**Comment by maxvisser** [comment]
Ah this has some issues with older implementation which do not use the CMS. You cannot just remove this link as its used by Nijmegen, Westerkwartier and others

**Comment by jamalv** [comment]
Another way to comply to this CR is to hide it for that specific customer (using CSS for example)

**Comment by maxvisser** [comment]
I would copy past the text which is currently in i18n into the database and basically migrate all client to CMS. After this is done; remove the link.

**Comment by jamalv** [comment]
Yea, we could migrate them without them noticing if we put the same text there, right?

**Comment by maxvisser** [comment]
Yeah its just some work to do. Login on each account which has CMS access copy paste the text.

**Comment by jamalv** [comment]
I believe there's multiple issues on this. @maxvisser what's the status?

**Comment by maxvisser** [comment]
Code is there as a pr to develop. Just need testing on each webshop on staging first. As when i tried this on Noordoostpolder webshop the text was misaligned and bigger (different CSS was used for the CMS text)

**Comment by maxvisser** [comment]
Created a task for it: https://github.com/teamforus/forus/issues/1903
