### ISSUE TITLE
CR: Fix the allignment of the buttons

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#387]
On the fondsen pagina a sponsor sees:

![image](https://user-images.githubusercontent.com/30211022/91560953-fff76600-e93a-11ea-93ff-b79a80838020.png)

**Comment by maxvisser** [comment]
This card will change on monday in release v0.14.0

![image](https://user-images.githubusercontent.com/10818702/91563944-1227d300-e940-11ea-81cc-918e6664c115.png)

**Comment by jamalv** [comment]
afaik this has been fixed
