### ISSUE TITLE
CR: Redesign top of transaction view.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#389]
Currently it looks unclear.  Amount on the left. Transaction on the right. Not very clear.

![image](https://user-images.githubusercontent.com/30211022/91561753-65982200-e93c-11ea-8d27-af99800bee53.png)

**Comment by maxvisser** [comment]
Needs a proposal, no estimate can be made; aswell as a project and priority label.

**Comment by maxvisser** [comment]
this is fixed for bulk transaction page
