### ISSUE TITLE
CR; Positioning of buttons

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#390]
Needs more space and is not clear that by pressing these the year, week or month changes.

![image](https://user-images.githubusercontent.com/30211022/91562372-654c5680-e93d-11ea-8a91-1d8073a28eec.png)

**Comment by maxvisser** [comment]
if the fund has product with a category which is a long string; this happens

Example of how it looks with short strings in dropdown:
![image](https://user-images.githubusercontent.com/10818702/91563225-d04a5d00-e93e-11ea-9f13-b606ef58b8d4.png)

**Comment by maxvisser** [comment]
needs design change to allow long strings or strings should be shortend within the dropdown (you loose content)

**Comment by maxvisser** [comment]
@maartenfv Could you use a issue template for making change requests?

**Comment by maxvisser** [comment]
needs priority and a project.

**Comment by jamalv** [comment]
Yea, the dropdown can probably be smaller, right? And we could truncate content of the dropdown if needed. When you click it you will see the full content?

**Comment by jamalv** [comment]
Doesn't reproduce on chrome BTW:

<img width="1104" alt="Screenshot 2020-12-08 at 09 57 55" src="https://user-images.githubusercontent.com/30194799/101461940-dab3c400-393b-11eb-93b1-8c513daa834a.png">

**Comment by maartenfv** [comment]
@maxvisser Is this one fixed? The main problem was the position of the button it looked bugged.
