### ISSUE TITLE
CR: Improve ux by adding "There is no data to display" message

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#391]
When watching these graphs it is not clear it is not loading or there is no data.

We could add a subtle message. (Better than the one I drew below) It needs to look good :)

![image](https://user-images.githubusercontent.com/30211022/91562580-b3f9f080-e93d-11ea-8264-c3d6c9a85442.png)

**Comment by maxvisser** [comment]
we use chartJS we could also add a progress bar https://www.chartjs.org/samples/latest/advanced/progress-bar.html

**Comment by maxvisser** [comment]
Not sure about the scope of adding the text in the graph; It seems small should be checked by a developer.

**Comment by maxvisser** [comment]
#316 @jamalv maybe add all these visual improvement to this epic maybe do a bit of a design of the page.
