### ISSUE TITLE
CR: Improve positioning shops finance

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#392]
Needs to be on one line. ![image](https://user-images.githubusercontent.com/30211022/91562728-f7ecf580-e93d-11ea-81cb-44998f20e9e5.png)

**Comment by maxvisser** [comment]
If you swith context the strings shown will be ever longer; How would you want to fix it?

We could move everything down.
![image](https://user-images.githubusercontent.com/10818702/91563534-54044980-e93f-11ea-917c-788e84a6f742.png)

**Comment by maxvisser** [comment]
Needs priority and project label
