### ISSUE TITLE
Aanvraagflow DigiD: stappen kloppen niet

### ISSUE THREAD

**Issue by mmjvdlinden** [teamforus/general#395]
### Requested by:
- Martijn van der Linden, gemeente Nijmegen

### Change description
- De stappen in de aanmeldflow gaan verkeerd, in plaats van stap 1 t/m 4 te doorlopen blijft de inwoner hangen bij stap 1 en wordt het: stap 1 van 4, stap 1 van 3, stap 1 van 2 
- Zie hiervoor [deze screenshots](https://irvn-my.sharepoint.com/:f:/g/personal/m6_van_der_linden_nijmegen_nl/Essttg8ybR5FvdlmmxTRRHcBXKfMhSQBIg1fJYw8R9dDkQ?e=NYy6Ti)
- Kan dit worden aangepast naar een reguliere flow?

**Comment by maxvisser** [comment]
Gereproduceerd. 

Wanneer gebruiker al een keer heeft ingelogd met DigiD (formulier verlaat, website sluit) na inloggen met DigiD en weer terug gaat om de aanvraag (van maar 4 stappen) af te maken. Zijn er natuurlijk ook nog maar twee stappen om af te maken. Dit is enorm gek voor iemand die de stappen in één keer doorloopt.

Gewenste situatie:
Inlog stap en DigiD stap blijven deel van de stappen.

<details>
<summary>Stap 3: bevestig uw inkomen</summary>

![image](https://user-images.githubusercontent.com/10818702/91944596-9ee6de00-ecfe-11ea-93ec-257570e846c2.png)

*waar nu stap 1 staat.
</details>

**Comment by mmjvdlinden** [comment]
Eens, maar het is voor de gebruiker vreemd om te starten met vier stappen en het aantal stappen wijzigt in plaats van dat je een stap vooruit komt. 
Dus vandaar de suggestie om dit te maken zoals ik als inwoner verwacht:
1/4
2/4
3/4
4/4
Ik kwam hem tegen bij het maken van een instructie. En hij viel me zo op dat ik dacht: hebben we hier nooit een vraag over gehad?

**Comment by maxvisser** [comment]
We hebben wel vaker problemen met de stappen indicato. Het formulier is zo 'slim' dat hij soms stappen overslaat of dat er stappen bij komen. Waardoor die stappen indicator heel gek is. 

De oplossing is 'onthouden' dat de stappen er waren en dat de gebruiker ze heeft volbracht en ze dus alsnog tonen, ook als de gebruiker tijdelijk de site heeft verlaten (bijv om met digid in te loggen). We hebben hem toevallig net met backlog refinement besproken en de scope van deze issue lijkt vrij klein (weinig moeite) maar is toch iets groter dan gedacht. Een tijdelijke oplossing zou kunnen zijn om de tekst niet meer te laten. 

Concreet zou het dan betekenen dat je dan alleen een proces balk zit zonder nummer indicatie:
![image](https://user-images.githubusercontent.com/10818702/91987177-023c3480-ed2e-11ea-9e6e-bd92fd08432c.png)

De echte oplossing is dus duidelijk, scope hiervan lijkt toch groter dan initieel gedacht. Snel te implementeren 'quickfix' is de tekst niet te laten zien waar in ieder geval verwarring door verkomen wordt.

**Comment by jamalv** [comment]
@mmjvdlinden, bedankt voor het aanmaken de issue! ik sluit me er volledig bij aan dat dit inderdaad vreemd is en niet aansluit bij de verwachting van de inwoner. 

We hebben deze issue met het team besproken en kwamen zoals Max noemt tot de conclusie dat er wat technische uitdagingen zijn omdat het aantal stappen dynamisch is. In het uitgebreidere aanvraag proces van Forus wordt namelijk niet opnieuw gevraagd om attributen die al bekend en goedgekeurd zijn, en dat weten we pas nadat iemand inlogt. Daarom hebben we ook gesproken over een visuele oplossing:

**Optie A:** Dit is een mockup (ruwe vormgeving) van hoe je het verwacht: https://www.figma.com/proto/buNhwrhiuG23hrxWZRGkrC/Nijmegen?node-id=1%3A2&viewport=418%2C334%2C0.15057606995105743&scaling=scale-down-width

**Optie B:** Dit is een mockup van hoe het zou zijn als we het visueel oplossen door de woorden weg te halen: https://www.figma.com/proto/buNhwrhiuG23hrxWZRGkrC/Nijmegen?node-id=218%3A929&viewport=12%2C323%2C0.1713329255580902&scaling=min-zoom

Als we kijken naar [WCAG](https://www.w3.org/WAI/tutorials/forms/multi-page/#using-the-html5-progress-element); dan wordt aangegeven dat als het aantal stappen onbekend is, er een progress balk gebruikt kan worden:  Bij _optie B_ is dat dus feitelijk wat er gebeurt.

Ik stel daarom voor om in de eerste instantie _optie B_ te implementeren; en om daarnaast verder onderzoek te doen naar hoe haalbaar het is om de stappen wel weer op een goede manier weer te geven. Hierin kunnen we gelijk de relevante WCAG richtlijnen meenemen (bijvoorbeeld het [gebruiken van de pagina titel](https://www.w3.org/WAI/tutorials/forms/multi-page/#using-the-page-title))

Bij toekomstige gebruikerstesten kunnen we hier ook aandacht aan besteden. Bijvoorbeeld door de 2 bovenstaande prototypes voor te leggen en te kijken hoe eindgebruikers de verschillen ervaren.

**Comment by mmjvdlinden** [comment]
Mooie oplossingen. Beide zijn voor mij acceptabel. Het mooie van B is ook dat je ziet hoever je in een stap zit. Jet volgen van de WCAG richtlijnen lijkt me een vereiste.

Wat betreft de gebruikerstesten deel ik je mening ook. Volgens mij kunnen we hier binnen Nijmegen voldoende aandacht aan besteden.

**Comment by maartenfv** [comment]
@jamalv @maxvisser  Wat is de status van deze issue?

**Comment by jamalv** [comment]
@maxvisser dit was inbegrepen bij het aanpakken en harmoniseren van de signupflows in release .15, klopt dat?

**Comment by maxvisser** [comment]
Dat klopt. De stappenteller begint nu pas bij het aanvraagproces. Bij nijmegen resulteert dit in 1 stap. Inloggen / DigiD wordt dus niet meegerekend. Hierdoor kunnen we beter garanderen dat de teller/stappen accuraat zijn omdat het aantal stappen kan verschillen per gebruiker en context.
