### ISSUE TITLE
Text review: aanvullingsverzoek "het question veld is verplicht"

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#399]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Max Visser

### Change description

![image](https://user-images.githubusercontent.com/10818702/91999459-af1dae00-ed3c-11ea-8c29-f4e44bf2d49f.png)

**Comment by maxvisser** [comment]
Needs better texts

**Comment by maxvisser** [comment]
error is probably still there. Thats why I left this open

**Comment by maartenfv** [comment]
Is er een link naar FIGMA voor text check? @maxvisser

**Comment by linda-90** [comment]
1. Bericht to requester = Bericht naar aanvrager
2. Het question veld is verplicht = Vul een bericht in
3. Wanneer een aanvraag incompleet of onduidelijk is, kunt u aan de aanvrager extra informatie vragen. Een bericht bijvoegen is daarom niet optioneel. = Stuur een bericht naar de aanvrager als de aanvraag onvolledig is of als er aanvullende vragen zijn. Vul een bericht in.

**Comment by maxvisser** [comment]
Could some reproduce this @maxvisser

**Comment by maxvisser** [comment]
Still an issue 
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/4cbe74f2-8de2-40c4-9a8d-70bf98398080)

**Comment by maxvisser** [comment]
Planned in for @SjoerdHilhorst to fix https://github.com/teamforus/forus/issues/2143
