### ISSUE TITLE
Set email headers and update from address

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#40]
We currently don't have our email headers set up so people only see noreply@forus.io as the sender.

<img width="360" alt="screenshot 2018-10-31 at 15 12 00" src="https://user-images.githubusercontent.com/30194799/47794124-183ad180-dd20-11e8-9565-b42440434c44.png">

We should set our headers appropriately: https://stackoverflow.com/questions/4728393/should-i-use-the-reply-to-header-when-sending-emails-as-a-service-to-others

```
from:  Gemeente Westerkwartier <info@westerkwartier.nl>
sender:  do-reply@forus.io
```

**notes:**
* We should get the **from** address from the sponsor account
* Most people probably won't see the **sender** address, but for those who do and manually send an email there, we can forward those mails to support@forus.io. But by default replies will go to the **from** address (I believe, we should test this).

**Comment by jamalv** [comment]
Current status: there is a pull request: https://github.com/teamforus/forus-backend/pull/676/files

But, all emails need to be checked. The scope is therefore pretty big.

**Comment by maxvisser** [comment]
This is in production
