### ISSUE TITLE
Add sentence to image uploader (very small and subtle)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#401]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholders

### Change description
As a an implementation owner I would like to warn users that upload images that images have to be licence-free.

"Gebruik rechtenvrije afbeeldingen of afbeeldingen waartoe u de rechten heeft" (needs review)

**Comment by maxvisser** [comment]
Needs figma proposal

**Comment by maxvisser** [comment]
added a text to image uploader in actions branch.

**Comment by maxvisser** [comment]
released
