### ISSUE TITLE
Allow provider to hide price for actions

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#402]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Client

### Change description
As a provider I would like to option to hide the price for an action so that I can offer an action on the actions page that has _no price_ but where I can put discount in the title or image: "25 percent discount on all my products and services" - to do this the label "free" or the price on the card should be hidden.

Tasks
- [x] Define concept / figma @jamalv : https://www.figma.com/file/k0wPBtzyDlD9qRj2vmRed8/Allow-provider-to-hide-price-for-actions?node-id=1%3A8641
- [ ] Review concept / design and create task @danrminds
- [ ] Development

**Comment by maxvisser** [comment]
#204 relevant

**Comment by jamalv** [comment]
@danrminds could you create the task(s)?

**Comment by danrminds** [comment]
@jamalv Discussed with Valentin. This influences a lot of things, it's a different type of interaction - on the Webshop, me app as well. Let's discuss it tomorrow at the sprint planning together.

**Comment by maxvisser** [comment]
Scope seems Medium

**Comment by maxvisser** [comment]
As I see the benefit of doing it this way #204 seems a much faster solution. If the user story is "A provider I want to only offer a discount for a product or service" I see adding a overall discount on organization level and a discount on product level as a good solution

**Comment by maxvisser** [comment]
released; needs a fix to hide gratis @jamalv could you create a seperate issue for that? (if not already done)
