### ISSUE TITLE
Webshop activation modal: input field creates double numbers NUMPAD

### ISSUE THREAD

**Issue by demylubbers** [teamforus/general#404]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Demy Lubbers

### Change description
- If I want to enter my activation code using the numbers on the right side of the keyboard. They get filled in with dubbel the digits. Example: Activation code is 1814. Becomes -> 11881144.

**Comment by maxvisser** [comment]
Need priority and project label before it can be planned.

**Comment by maxvisser** [comment]
Can't reproduce the issue will close it
