### ISSUE TITLE
Improve the titles 'Tegoeden (?)' and 'Reserveringen (?)'

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#405]
Learn more about change requests here: https://bit.ly/39CWeEE

### Change description

Improve the page 'Tegoeden'
- Titles
- Text update

Current situation
<img width="1440" alt="Schermafbeelding 2020-09-04 om 14 08 39" src="https://user-images.githubusercontent.com/36952230/92237809-4ce9b800-eeb8-11ea-8ac5-649bf1d02765.png">

New situation on 'Aanbieders' page
<img width="1437" alt="Schermafbeelding 2020-09-04 om 14 10 04" src="https://user-images.githubusercontent.com/36952230/92237844-5b37d400-eeb8-11ea-92a3-f87c3935effc.png">

Proposal in Figma:
https://www.figma.com/file/LOei9CO8mj4lshcCHQvTBz/Webshop%3A-Groningen?node-id=697%3A14112&viewport=-3583%2C634%2C0.33422181010246277

<img width="526" alt="Schermafbeelding 2020-09-04 om 14 21 22" src="https://user-images.githubusercontent.com/36952230/92238689-039a6800-eeba-11ea-825d-4df3162d20d0.png">

**Comment by jamalv** [comment]
## Improving the titles
@linda-90 thanks for the CR! I have made a separate proposal in Figma with the change you proposed, from my side this change is ✅ approved: https://www.figma.com/file/4D7DEAkBeKggZsLObCWqX2/Improve-vouchers-page?node-id=0%3A1

Just one question: in the current state there is a #zinnetjeerbij, and in your proposal you removed the zinnetje :P was this on purpose? (I like it by the way, but we should check with @GerbenBosschieter if he thinks the #zinnetjeerbij is still needed)

## Other changes to the page
Next to the change you proposed, I think this page can probably use some more improvements and discussion / suggestions :) - we can use the Figma proposal file and this change request for that 👍 

I personally would like to align all pages with the same template "standards" - if you look at test.potjeswijzer, we have already aligned the "Potjes" "Aanbod" and "Aanbieders" pages. It would be nice if the vouchers page uses the same standards. This has multiple purposes IMO:
1. Re-using design templates encourages us to make the components design / user experience better everywhere at once when we improve them, with less effort - not re-inventing the wheel every time :)
2. Re-using elements can also decrease the amount of code we have to write and maintain, also expect it will be easier to comply with WCAG for example
3. It's nice for the user! When they understand how to use 1 page, they understand how to use them all :D

Anyway, long story long, I made a proposal for that in the same figma file as well: https://www.figma.com/file/4D7DEAkBeKggZsLObCWqX2/Improve-vouchers-page?node-id=2%3A508

**Comment by jamalv** [comment]
@linda-90 could you let us know what you'd like to do with the #zinnetjeerbij?

**Comment by linda-90** [comment]
@jamalv @maxvisser 
Ah ja, dat klopt! Heb het #zinnetjeerbij weggehaald omdat het denk ik niet veel toevoegt. 
@GerbenBosschieter Ben benieuwd hoe jij hier naar kijkt en of je verwacht dat er vanuit de gebruikers vragen over komen. 

-------------

<details>
<summary>Huidig situatie</summary>
<img width="1435" alt="Schermafbeelding 2020-09-29 om 11 09 27" src="https://user-images.githubusercontent.com/36952230/94538515-61656a00-0244-11eb-8651-49df840a98ba.png">
</details>

<details>
<summary>Nieuwe situatie</summary>
<img width="1435" alt="Schermafbeelding 2020-09-29 om 11 09 27" src="https://user-images.githubusercontent.com/36952230/92238689-039a6800-eeba-11ea-825d-4df3162d20d0.png">
</details>

-------------

Waarom ik het zinnetje: 
_"Met deze tegoeden kan u naar de aangesloten aanbieders. Open het tegoed om te zien bij welke aanbieders u het saldo op het tegoed kan uitgeven."_ 
heb weggehaald.

1. De uitleg dat ze met het tegoed naar de aanbieder kunnen staat ook op de pagina wanneer je het tegoed opent. Op deze pagina staat ook meteen de kaart met aanbieders waar ze het kunnen uitgeven. De melding hier neerzetten lijkt me daarom het meest logisch.
2. De knop 'Open' valt goed op, dit wijst naar mijn inziens voor zich.
3. Daarnaast vind ik de tekst in het geheel rommelig ogen. Als de lay-out voor zich wijst, is de tekst niet nodig lijkt me:)

---------------

Indien @GerbenBosschieter hier in het kader van gebruikersvriendelijkheid anders over denkt stel ik voor om de zin te veranderen in:

_"Open het tegoed om te zien hoeveel u nog over heeft en bij welke aanbieders u het kunt uitgeven."_

@maxvisser 
Wat gebeurt er als een tegoed is verlopen en er geen transacties zijn gedaan?

**Comment by maxvisser** [comment]
dan is er geen knop bekijk transacties.

**Comment by maxvisser** [comment]
This is done and in release 15

**Comment by maxvisser** [comment]
released
