### ISSUE TITLE
Provider signupflow: Editing an organization

### ISSUE THREAD

**Issue by demylubbers** [teamforus/general#406]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Demy

### Change description
- Made a typo in the registration form while signing up as a company. For example: incorrect IBAN or email. I want to return to my registration form, but that's not possible. 

Solution: Editing button.

**Comment by maxvisser** [comment]
Proposal to add a sentence 'Do you want to edit this organization you can do this after you succesfully registrerd.

**Comment by jamalv** [comment]
moved to productboard: https://app.productboard.com/inbox/notes/15568851
