### ISSUE TITLE
Provider dashboard funds page: Lost my filter!

### ISSUE THREAD

**Issue by demylubbers** [teamforus/general#407]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Demy

### Change description
- When I am logged in as a Company and I register for a fund for (example:) 'Gemeente Berkeland', I lose the filter for which 'Gemeente'.
![lost filter](https://user-images.githubusercontent.com/70149827/92242557-40695d80-eec0-11ea-897c-9d9ffd2014df.png)

**Comment by maxvisser** [comment]
Needs priority and project label

**Comment by maxvisser** [comment]
released
