### ISSUE TITLE
Email digest

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#41]
## Change

Requested by: @requester

### Change description
Sometimes we send many mails. For a user this can flood their mailbox, leading to a bad user experience.

## Goal
The ability to cue emails, and if there is, for example 10 mails in 10 minutes, to send one mail with a digest. This issue is about making a digest

**Comment by maartenfv** [comment]
Discussed with Max. Need text check. Could you please add Figma link?

**Comment by maartenfv** [comment]
Discussed with Max as well its not just Figma needs another language check as well to make sure the emails do not "sound" like robot. Check/adjust email templates in the back-end code.

**Comment by maxvisser** [comment]
https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/%F0%9F%A7%91%E2%80%8D%F0%9F%A6%AF%F0%9F%94%8D%F0%9F%93%9DMails?node-id=3%3A108&viewport=1041%2C646%2C1

**Comment by maxvisser** [comment]
@maartenfv @linda-90 Could you check this figma prototype; I see some dutch translations and some great ideas but what is what?

**Comment by maartenfv** [comment]
@maxvisser What is the interval of the digest? Is it different for the kind of notification?
Some notifications like new offers for the citizens can be send daily?
But maybe some things are needed multiple times per day?
Is there a written proposal for these things?

**Comment by maxvisser** [comment]
It are all daily digest except the one for citizens about offers which is monthly

**Comment by maxvisser** [comment]
Configuring the interval was out of scope but ofcourse really nice to have

**Comment by maxvisser** [comment]
On production. can be communicated to users @maartenfv
