### ISSUE TITLE
Implement feedback Noordoostpolder webshop

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#410]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop-Noordoostpolder?node-id=658%3A88

**Comment by jamalv** [comment]
@linda-90 please add feedback

**Comment by linda-90** [comment]
@jamalv @maxvisser 
Feedback website design Noordoostpolder:
- https://github.com/teamforus/general/issues/413
- https://github.com/teamforus/general/issues/412
- https://github.com/teamforus/general/issues/411

**Comment by maxvisser** [comment]
As feedback issues are now created I will close this one.
