### ISSUE TITLE
CR: Dropshadows below white menu headers.

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#412]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
- headers staging are not equal

<img width="1437" alt="Schermafbeelding 2020-09-07 om 14 38 46" src="https://user-images.githubusercontent.com/36952230/92389715-e5cb3e00-f119-11ea-9049-9df48b11c140.png">
<img width="1437" alt="Schermafbeelding 2020-09-07 om 14 38 29" src="https://user-images.githubusercontent.com/36952230/92389718-e6fc6b00-f119-11ea-8afb-ea524ce20576.png">

Figma design is leidend:
https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=658%3A88&viewport=-270%2C685%2C0.36613044142723083

<img width="537" alt="Schermafbeelding 2020-09-07 om 14 54 35" src="https://user-images.githubusercontent.com/36952230/92389826-127f5580-f11a-11ea-8359-7f8cd66d20a0.png">

- [ ] Add shadow

**Comment by maxvisser** [comment]
This is about the shadow or aswell about the color change?

**Comment by linda-90** [comment]
This issue is about the shadow. What color change do you mean?

**Comment by maxvisser** [comment]
In figma the navbar is white and on staging it is grey

**Comment by maxvisser** [comment]
Background color and text color are different:
![image](https://user-images.githubusercontent.com/10818702/92444486-4064a880-f1b3-11ea-9e4b-33239b036927.png)
![image](https://user-images.githubusercontent.com/10818702/92444501-435f9900-f1b3-11ea-8aaf-33bc5d792ae7.png)

**Comment by maxvisser** [comment]
Adding dropshadows is planned.

**Comment by GerbenBosschieter** [comment]
<img width="1014" alt="Screen Shot 2020-09-14 at 11 45 58" src="https://user-images.githubusercontent.com/38419514/93071083-efa3f280-f67f-11ea-8f30-4c726eb04c6a.png">

**Comment by GerbenBosschieter** [comment]
There are two issues about this So screens hotted my comment in this one

**Comment by maxvisser** [comment]
Did you already ask @linda-90 (or lets wait until shes back from holiday) put the task on hold.

**Comment by GerbenBosschieter** [comment]
@linda-90 are you sure that Figma is leading?
As you can see, the image below has different dropshadows on different pages

<img width="1250" alt="Screen Shot 2020-09-14 at 12 07 45" src="https://user-images.githubusercontent.com/38419514/93073391-26c7d300-f683-11ea-865b-298118d677a3.png">

**Comment by linda-90** [comment]
@GerbenBosschieter Het gaat erom dat de headers op alle pagina's gelijk zijn. Nu was het zo dat de ene pagina een shadow had en de andere pagina niks en weer een andere een lijn. Zoals het nu op staging staat vind ik het prima, https://noordoostpolder.staging.forus.io/. Nu is het tenminste 1 geheel.

De shadow vind ik subtieler, maar laat het maar voor nu.
https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=658%3A88&viewport=-89%2C1836%2C1.3276869058609009

**Comment by maxvisser** [comment]
This issue about dropshadows on the navbar; if these shadows are really needed I would suggest to add these to the common aswell @GerbenBosschieter 

As I saw you already introduced them on Geertruidenberg; with merge conflicts I removed those shadows.
https://geertruidenberg.staging.forus.io/

**Comment by maxvisser** [comment]
I changed this CR to a more general issue about these shadows (if we want them for any other webshops)

**Comment by maxvisser** [comment]
I see none of our webshops have these dropshadows. I will close this issue @linda-90 if you think its still relevant you can reopen it.
