### ISSUE TITLE
CR | NOP - Improve the hover design of links and buttons on the website

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#413]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
- Now several hovers are used on the website (staging environment)
<img width="147" alt="Schermafbeelding 2020-09-07 om 15 03 07" src="https://user-images.githubusercontent.com/36952230/92403304-795c3900-f131-11ea-8d3f-a50ff9cfc056.png"><img width="221" alt="Schermafbeelding 2020-09-07 om 14 57 51" src="https://user-images.githubusercontent.com/36952230/92403305-79f4cf80-f131-11ea-9636-618b2b9850ce.png"><img width="179" alt="Schermafbeelding 2020-09-07 om 14 57 46" src="https://user-images.githubusercontent.com/36952230/92403308-7a8d6600-f131-11ea-9b51-f1c4cec66f37.png">

    - Shadow
    - Color change
    - Underlined text

Style guide is in Figma: https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=742%3A0&viewport=240%2C662%2C0.8783382773399353

### Tasks
- [ ] Update hovers as shown in the Figma design

**Comment by jamalv** [comment]
@maxvisser @linda-90 is this in production now? can this be closed?

**Comment by maxvisser** [comment]
Its not. Buttons need to be refactored complete for it  to be done (currently the CSS is a mess) or you will just fix it for this specific webshop

**Comment by maxvisser** [comment]
design proposal needs to be made for general webshop and each implementation

**Comment by jamalv** [comment]
@danrminds could you work with @sashooa to include button states in the webshop library?

**Comment by jamalv** [comment]
@danrminds expects that this has already been done for general, could you please check and add link?

**Comment by maxvisser** [comment]
in the library its not atleast.
can only find these:
![image](https://user-images.githubusercontent.com/10818702/104736589-7eff0680-5743-11eb-8ce7-191a6c6c3ed8.png)

Please look here:
https://webshop.staging.forus.io/#!/
![image](https://user-images.githubusercontent.com/10818702/104736673-9938e480-5743-11eb-9a7e-6b9359e0426e.png)

**Comment by maxvisser** [comment]
@jamalv could you check with @linda-90 whats the priority, is this done? What should we plan in.

**Comment by linda-90** [comment]
It is also part of WCAG.

> WCAG 2.0 stelt dat links zichtbaar moeten zijn voor iedereen. Dit kan u bekomen door uw link te onderlijnen, of door kleurcontrast en hover- en focuseffecten toe te passen.
