### ISSUE TITLE
Convert youtube links in Markdown editor to iframe

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#418]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
There is an extension for the markdown dependency we use to allow youtube iframe to be pasted

https://github.com/zoonru/commonmark-ext-youtube-iframe

**Comment by jamalv** [comment]
This is also relevant for potjeswijzer, they would like to add a video to the homepage.

**Comment by danrminds** [comment]
@dev-rminds still needs to review the pull-request https://github.com/teamforus/forus-backend/pull/877
