### ISSUE TITLE
CR: Auth pin code should allow pressing enter to continue

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#420]
Now I have to click the button with my mouse. I would like to press enter.
![image](https://user-images.githubusercontent.com/10818702/96423422-9b011380-11f9-11eb-80a9-a9d2217f1da6.png)

**Comment by jamalv** [comment]
@maxvisser small but nice, was requested by Bas (project leader groningen :)) - can this be planned?

**Comment by maxvisser** [comment]
Probably Valentin would do this on reusable way. Maybe aswell adding 'enter' in the button?

**Comment by maxvisser** [comment]
I remember we even had button designed with this feature in mind.

**Comment by maxvisser** [comment]
I think Valentin would not allow me to create a task to fix this on this specific modal. He probably would create a module which can be implemented on multiple modals and cases where submit can be trigger by pressing enter. I will estimate it on 10/12 hours.

**Comment by maxvisser** [comment]
This seems to be already implemented @maartenfv Where did you test this?

**Comment by jamalv** [comment]
it is the page you end up at if you login on your me app but open the mail on desktop

**Comment by maxvisser** [comment]
added screenshot to make it clear which page.
