### ISSUE TITLE
CR: Invite to employee 'Glazuur' email instead of e-mail.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#422]
During sign up flow, when adding employee, there is a spelling mistake.

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/b2506e4e-61ac-4b99-b23c-f5c5f9b13816)

**Comment by maxvisser** [comment]
There are multiple places where this mistake are made. Better to try fix all at once.

**Comment by maxvisser** [comment]
added some labels and screenshot
