### ISSUE TITLE
CR: When action is sold out (reachers 0), keep it visible in the webshop for 2 weeks with the message sold out.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#426]
## Description
Actions will go directly out of the webshop. Sponsor would like to keep them for two weeks in the webshop with a sold out message.

**Comment by jamalv** [comment]
Discussed this with the stakeholder, most actions like this are expected to be added by the municipality themselves, so they can add it from their own account. It might not be a very big problem.

**Comment by jamalv** [comment]
@danrminds could you estimate, then we can decide what to do with this :)
