### ISSUE TITLE
DOB | How are we going to proceed into 2021?

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#431]
We have several current funds. 2021 is coming. How are we going to make the transition smooth for all of our users?

- Sponsors
- Requesters
  - Do they need to sign up again?
- Providers
  - Do they need to sign up again?

Wat are potential risks and considerations? Please list them here!

**Comment by maartenfv** [comment]
This issue was discussed during retro. @jamalv are there more issues we can add to this epic?

**Comment by jamalv** [comment]
Yes, very important issue, It is a very big one but I think with a very high priority. We have a lot of new users in 2020 and a lot of existing users. In order to do this well with support and quality assurance, this is indeed a must-have.

I would say we need to dedicate at least 1 development sprint in q4 to this, and I think this issue is a very important one: https://github.com/teamforus/general/issues/252

**Comment by maartenfv** [comment]
@jamalv Could you specify which sprint would be dedicated?

**Comment by maartenfv** [comment]
@maxvisser is er een coulance periode? Margrieta herinnerde ons aan de situatie dat een fonds afliep op 31 oktober ipv 1 november. Mensen hadden nog wel recht wouden het op de laatste dag gebruiken. Mensen stonden in de winkel maar konden niet betalen. Is dit een issue voor de overgang van de jaren?

**Comment by maxvisser** [comment]
Probably not the issue for this question. I will sent you a DM on discord 👍

**Comment by maartenfv** [comment]
How do we inform the providers to proceed into the next year?

**Comment by maartenfv** [comment]
@jamalv @maxvisser Are we on track with this issue? Please plan a check with stakeholder (@linda and @GerbenBosschieter ) to see if they agree and are informed.

Are there any risks we need to act on?

**Comment by maartenfv** [comment]
@jamalv @maxvisser Do we know the major issues? What issues need to be worked on? Do Linda and Gerben agree?

**Comment by maartenfv** [comment]
Max states 4 problems:
- Providers need to re-apply
- Criteria op het fonds (meedoen reliable = ja) Max zet er een jaartal in. (er zit geen tijd in criteria) (oplossing: geef houdbaarheid aan)
- Vernieuwen fondsen
- Niet opnieuw aanvragen?

Are these all? @jamalv @maxvisser 

@linda-90 @GerbenBosschieter could you please add and state your priorities?

**Comment by GerbenBosschieter** [comment]
All my priorities are in this issue and from what I know you already added them tho this issue: https://github.com/teamforus/support/issues/5 

My biggest problem is from old to new year. So much things that need to be fixed. It's almost like a new implementation. But the biggest one of all is definitely the fact that providers need to apply for a fund again. This has always resulted in a peak of questions. Not only their applying for a fund but also changing the end date of an offer

**Comment by linda-90** [comment]
1. Providers need to re-apply for a fund (new year, same fund)
2. Citizens need to re-apply for a fund 

Should be easier / automatic for users

**Comment by maartenfv** [comment]
@jamalv no response in this issue and now we are having trouble with Nijmegen etc.  https://github.com/teamforus/implementation/issues/605

**Comment by jamalv** [comment]
Gerben: SDOA wil graag kunnen filteren in de voucher generator: https://github.com/teamforus/general/issues/728

**Comment by jamalv** [comment]
figma: https://www.figma.com/file/sV4R20czCqWrqshMoyRxJE/?node-id=43%3A235

**Comment by maxvisser** [comment]
This seems really out dated. I close this issue
