### ISSUE TITLE
CR: NOP | Make logo bigger on homepage

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#432]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
- Make logo bigger on homepage

Current situation
<img width="877" alt="Schermafbeelding 2020-09-09 om 13 52 44" src="https://user-images.githubusercontent.com/36952230/92594878-c52eef80-f2a3-11ea-981c-d645de7da9fc.png">

Desired situation
<img width="880" alt="Schermafbeelding 2020-09-09 om 13 52 28" src="https://user-images.githubusercontent.com/36952230/92594899-cf50ee00-f2a3-11ea-8e37-7fbc8556d8da.png">

**Comment by maxvisser** [comment]
On smaller screens this will look great but on larger screen maybe a bit weird?
![image](https://user-images.githubusercontent.com/10818702/92603159-46d84a80-f2af-11ea-9594-d8b9c99e6e3d.png)

**Comment by maxvisser** [comment]
Is this only on homepage or on all pages? What should the size be?

**Comment by linda-90** [comment]
@maxvisser I agree it looks a bit weird on larger screens. Would this be a possible solution? The white area with the logo is higher now.
<img width="550" alt="Schermafbeelding 2020-09-09 om 17 23 15" src="https://user-images.githubusercontent.com/36952230/92619065-56608f00-f2c1-11ea-8023-d1bef675bb01.png">

**Comment by maxvisser** [comment]
As in only on the homepage or all pages? imho it still looks abit weird 😅

**Comment by maxvisser** [comment]
I think if you make everything slightly bigger It will help aswell
old:
![image](https://user-images.githubusercontent.com/10818702/92694951-0d075280-f348-11ea-875d-c039ef051883.png)

new:
![image](https://user-images.githubusercontent.com/10818702/92694887-f9f48280-f347-11ea-909b-b668cb37584d.png)

**Comment by maxvisser** [comment]
maybe let an designer check it out? I see the problem mainly as the logo not being completely readible right ?

**Comment by maxvisser** [comment]
Logo height is btw same as in figma (105px) so there is no difference in sizes between them ;)

**Comment by maxvisser** [comment]
If I would make a task:
lets change size of logo to 165px height
button text from 16px to 18px
and padding-top/bottom from 12px to 16px

Results in:
![image](https://user-images.githubusercontent.com/10818702/92696732-9881e300-f34a-11ea-977c-83ce5576f325.png)

**Comment by maxvisser** [comment]
Gerben fixed this by moving the logo to the right and making it bigger.

**Comment by maxvisser** [comment]
released
