### ISSUE TITLE
Validator dashboard - deny all: warning and message

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#433]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
On the validator dashboard, when you "deny all" - it denies instantly without any warning and without possiblility to undo. There should be a warning just like when you deny a single record. Also being able to send a message when a municipality denies a request is important for legal reasons.

**Comment by maxvisser** [comment]
same with approve all I think

**Comment by maxvisser** [comment]
need priority and project label

**Comment by jamalv** [comment]
@maxvisser, [link](https://docs.google.com/document/d/14n3u-d9oc3e3YRdS3H09OAR73TLiQBaMZuoiosmzwjA/edit) to our brainstorm

**Comment by maxvisser** [comment]
Created a task

**Comment by maxvisser** [comment]
released
