### ISSUE TITLE
API: connect to back office (on-premise)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#435]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Nijmegen
 	
### Change description
Sponsors often have back office system built by Centric or Pink Roccade.

**Automated checks**
In automated checking there are two steps. First step was DigiD and this is now working properly. The second step is to make it possible to carry out checks with the applicant's BSN.

We want to check with the BSN number if a requester is known in the back office system of the spopnsor (in the first use case  this will be a Centric application or ESB facility / common ground implementation). We will check in the backoffice if requester already has a current benefit or is entitled to other funds.
This way we retrieve the most up-to-date information (in yes / no form) via SUWI / intelligence agency and thus also be able to assign it automatically for "unknown" residents.

**Comment by jamalv** [comment]
Thx for opening the CR: My initial proposal would be to offer something to the client that they can run on their infrastructure. For example a .NET SDK: we can offer it open source on our github, and they can implement what is relevant to their situation (for example a custom database, pink, centric etc.) - This could fit the situation for multiple clients. We should research a bit what would be the most favoured implementation for something like this. (Java? .NET? something else?)

Also it will help with versioning etc if we update our API's we can also offer new versions of the SDK. Curious to hear opinions of the technical team on this approach.

**Comment by maxvisser** [comment]
idea:
create api scheme for external api which can be used to built an application which runs on their network. This application will have logic to interpret all applications on their network and answer questions about certain requesters (we will sent BSN and maybe a criteria check to this API and they will answer if the criteria is true, false or unknown.

**Comment by jamalv** [comment]
Just a bit of brainstorming, but I was thinking of something in this direction:

![Infra](https://user-images.githubusercontent.com/30194799/92727592-a5fd9400-f36f-11ea-90e7-af71a749602f.png)

**Comment by jamalv** [comment]
I'm very curious if such a connector would be a good idea. Would like to hear what clients and their technical partners would think about this. Some of the reasons I think it could be beneficial:
* Versioning the connector will help with support, documentation, maintainance etc.
* Offering the connector with a clear functional scope, leaves the implementation and integration with existing systems free to the user; reducing complexity from our side.
* We can help with the implementation of the connector, or enlist help of trusted partners?

Depending on the scope of functionality that is needed, maybe it would be enough to make (parts of) our API public, and leave the implementation completely to the client, this probably also has pro's and cons. Let's discuss those 😄

**Comment by jamalv** [comment]
Standard schema: scalable by design
Endpoints in english

**Comment by maxvisser** [comment]
Some points from a meeting we had:
add service similar to bunq
 - Should we gracefully handle the request for example 5 attempts etc
	
add to fund a api link
authorization to api -> Two way SSL
dev time 1.5
Sandbox?

reusability

GET REQUEST send BSN NUMBER
request list of funds which they are approved

**Comment by maxvisser** [comment]
https://docs.google.com/document/d/1CJIzLuhm9Zz_URL4wuT_sed-ddoRZxzYZj7zCQV64MI/edit

**Comment by maartenfv** [comment]
Needs offerte: https://github.com/teamforus/deals/issues/121

**Comment by maxvisser** [comment]
Superseded by https://github.com/teamforus/general/issues/784
