### ISSUE TITLE
Sponsor dashboard: fund settings product formula should not be changable after fund start

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#436]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Product formula is currently a unreleased feature. Would be nice to enable this on production.

What should change is that currently you can aswell add products to the formula after the fund has started. Would be nice this can only be done when you configure the fund and while its still in the pending/waiting state. On active and closed funds user should not be able to change it.

**Comment by maxvisser** [comment]
I think this is a nice thing to add for project-139

**Comment by maxvisser** [comment]
Another one to cross of the list of unreleased features 👍 
https://github.com/teamforus/itsm/issues/228

**Comment by jamalv** [comment]
Yes, please bring this to production :)
