### ISSUE TITLE
Productvouchers activated by form should sent different mail

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#439]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

Three use cases for this mail:
- product voucher sending to mail address
- product voucher generator assigning to mail address
- activating voucher after applying for it on webshop

Current mail being sent is the one which user gets while reserving product in webshop
![image](https://user-images.githubusercontent.com/10818702/92894865-40ff7800-f41b-11ea-8a2f-7026e216733d.png)

## Tasks
- [ ] write new mail text @linda-90

**Comment by maxvisser** [comment]
@linda-90 Product voucher generator verstuurd nu geen mail (bij Nienoord hadden anders mensen 5 mails gehad) Willen we voor Busregeling wel een mail sturen?

@jamalv Maybe its better to make a 'digest' for retrieving vouchers/qr-codes by mail

**Comment by linda-90** [comment]
@maxvisser Door de mail weten ze dat ze een busregeling voucher hebben gekregen toch? Anders moet er een bericht buiten het systeem om worden verstuurd? Ik zal een tekst opstellen!

**Comment by maxvisser** [comment]
released
