### ISSUE TITLE
Fund with only a product formula gives should not generate a 0 euro voucher.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#442]
@maxvisser commented on [Fri Sep 11 2020](https://github.com/teamforus/forus/issues/1759)

## Context/goal: 
A fund with only a product formula should be able to be activated. User should get only the product voucher.

---

@maxvisser commented on [Fri Sep 11 2020](https://github.com/teamforus/forus/issues/1759#issuecomment-690956151)

Not sure if this worked in the past (if this is even a bug or intended)

---

@dev-rminds commented on [Mon Sep 14 2020](https://github.com/teamforus/forus/issues/1759#issuecomment-691879063)

@maxvisser This was intended (in the past as well)

**Comment by jamalv** [comment]
@maxvisser what's the statusof this? was it in .15?

**Comment by maxvisser** [comment]
Its done
