### ISSUE TITLE
CR: Webshop - remove "Hoe het werkt" below header description

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#445]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Geertruidenberg

### Change description
I don't think such a button really fits there if there is a menu at the top of the page. 
The button 'how it works' and 'explanation' in the menu link to the same page. 

I would delete "How It Works".

**Comment by maxvisser** [comment]
This would be removed from all webshops.

**Comment by GerbenBosschieter** [comment]
@maxvisser WCAG dissagrees with you. There should always be multiple options to get to a certain page.

**Comment by maxvisser** [comment]
Well you can add it back via CMS

**Comment by maxvisser** [comment]
> @maxvisser WCAG dissagrees with you. There should always be multiple options to get to a certain page.
It was requested by Geertruidenberg; They found it weird that they can change the whole header description but not change the text of 'hoe werkt het'

**Comment by linda-90** [comment]
Can the link 'How it works' be added to the cms?

**Comment by linda-90** [comment]
Please can the 'how it works' link be removed?
If the municipality does want the link in the header, they can add it themselves in the CMS.

It has been requested several times now. When will it be implemented?

**Comment by danrminds** [comment]
@maxvisser What is the status here? Should we do anything?

**Comment by jamalv** [comment]
@maxvisser this is on production right? needs to also go on staging? - i believe no action needed except for that

**Comment by maxvisser** [comment]
Duplicate of https://github.com/teamforus/general/issues/386
