### ISSUE TITLE
POT | Redirect to funds page after login

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#447]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
User testing: "Na het inloggen kom je direct op de pagina aanvragen kindpakket, dat is vreemd want niet iedereen heeft een kindpakket nodig, of wil een kindpakket aanvragen."

### Change description
As a user I would like to be redirected to the "potjes" pagina after login, instead of starting an application for the first fund (kindpakket) so that I understand that this website is for more than just kindpakket.

**Comment by maxvisser** [comment]
This will be the case for all implementations aswell for Nijmegen / Groningen. This cannot be done for a specific implementation; I would propose to finish the new requesting page and just start with implementing it better in the workflow.

**Comment by maxvisser** [comment]
I am not sure but you currently get redirected to vouchers page which is empty?

**Comment by jamalv** [comment]
I added the original remark from usertesting to the CR

**Comment by jamalv** [comment]
Usertesting right now is a bit messed up because of this configuration:

## Current userflow:

* user logs in
* user goes into the signupflow for the first fund
* user thinks "I don't need this kindpakket fund"

## Proposed userflow:

* User logs in
* User lands on funds page
* User thinks, oh nice all these, I will apply for the ones I need :)

**Comment by jamalv** [comment]
For potjeswijzer this is a must-have since otherwise it is not really usable

**Comment by jamalv** [comment]
> I am not sure but you currently get redirected to vouchers page which is empty?

nope, you get redirected to the first fund

**Comment by jamalv** [comment]
> For potjeswijzer this is a must-have since otherwise it is not really usable

would it be possible to do this with a flag? since potjeswijzer is the only implementation that has the funds page turned on; "if the fund page is turned on, redirect to the fund page after signup"

**Comment by maxvisser** [comment]
Ah user is already on signupflow of kindpakket when they press 'start aanvraag'

**Comment by maxvisser** [comment]
I would just finish the funds page before 1st of januari and implement all flows into the signupflows of requester. (get rid of flags) currently we already have three flags on the button:
- activation code flag
- DigiD flag to first fund
- Digid flag + automatic validation to fund with automatic validation

Adding more to the list is something we could do but I rather decrease it then pile on.

**Comment by jamalv** [comment]
Understood but I would like this to be fixed for the next round of usertesting, as it gives a very wrong impression of the website to the testers. After finishing the funds page we can still get rid of the flag.

**Comment by jamalv** [comment]
Could this be planned?

**Comment by maxvisser** [comment]
So we will fix the whole thing before next user testing? When is this?

**Comment by jamalv** [comment]
I just got an email a few minutes ago that the next round of testing is planned for friday. 😳 

Of course user testing is done from dev, so if changing this redirect for Potjeswijzer specifically is possible before friday, the impact on the tests would really be very high (you will understand if you watch the video's / read the reports :))

**Comment by jamalv** [comment]
That would be nice :)

**Comment by jamalv** [comment]
so than the flow would be; click 'aanvragen' > go to funds page > choose a fund > sign up ; that would be a fix IMO

btw; originally I meant it as click 'aanvragen' > log in > get redirected to funds page when you are logged in > pick a fund to apply to, but if the option above is an easier fix, that would be nice aswell :)

**Comment by maxvisser** [comment]
Fixed this for the demo. A real task should be created to do this correctly.
