### ISSUE TITLE
POT | Update testing demo content

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#450]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Right now the funds that are connected to the products don't really make much sense (only yoga lessons have a bunch of funds you can use, for example). Adding a few more products (swimming lessons, for example) and connecting the funds in a logical manner, will have a high impact on the way that the site is experienced :)

- [x] Share the accounts that are used for the organisations in this issue @maxvisser
- [x] Add some extra products to that are nice for the target audience (uitje to nienoord, pannekoekenschip, some sports like judo, swimming lessons, winterjas, etc) @maxvisser @jamalv @GerbenBosschieter 
- [x] Link multiple funds to each product / provider @maxvisser @jamalv @GerbenBosschieter

**Comment by maxvisser** [comment]
@jamalv Do you still need help with this?

**Comment by jamalv** [comment]
nope; got the help I needed! thx! maybe help with a small checkup? all the polishing we can do is nice, but already this is a big improvement :D
