### ISSUE TITLE
Requester sign-upflow: Default text label is missing.

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#453]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
This textbox should show the correct text
<img width="785" alt="Screenshot 2020-09-16 at 17 00 21" src="https://user-images.githubusercontent.com/30194799/93355334-3a6b6900-f83e-11ea-82f2-bd87a1f05ab2.png">

**Comment by maxvisser** [comment]
Merged with develop. Probably will be released in v0.16.0 planed on 12 oktober.

**Comment by maxvisser** [comment]
released
