### ISSUE TITLE
Actions voucher: transaction mail

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#454]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

Create a new transaction mail for actions

Subject of mail: U heeft gebruik gemaakt van een actie met uw :fund_name-tegoed.
H1: U heeft gebruik gemaakt van een actie met uw :fund_name-tegoed.

Text for mail:
U heeft gebruik gemaakt van een actie met uw :fund_name-tegoed.
Uw resterende tegoed voor {actie naam} is {aantal}

**Comment by maxvisser** [comment]
Needs figma proposal

**Comment by jamalv** [comment]
Figma proposal:

https://www.figma.com/file/2psjQ1NX4oFj7W3eZXMF40/Actions-voucher-transaction-mail?node-id=1%3A107

**Comment by maxvisser** [comment]
@maartenfv @linda-90 could you do a text review on proposal?

**Comment by maxvisser** [comment]
Linda did text review.

**Comment by maxvisser** [comment]
released
