### ISSUE TITLE
PSD | 90 days renewal of permission to use banking API

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#455]
ING describes it pretty well (Dutch): https://www.ing.nl/particulier/digitaal-bankieren/psd2/zo-werkt-toestemming-geven.html

We need to provide the functionality to allow sponsors to give permission every 90 days to us for using the banking API.

**requirements**
- Pop-up (every 90 days) on the provider dashboard that states that you need to renew the permission. (only for an employee that has these rights).
- In the menu of the organisation, you need to be able to see when you gave your last permission and when the next one needs to be given.
-  Giving permission
   - They need to Accept privacy policy by checking checkbox. (states our rules in regards to how we deal with the info we get from using the API)
   -  They need to Accept Algemene voorwaarden (general terms and conditions). checking checkbox 
   - They need to given permission to use the API checking checkbox 
- Further requirements will follow when we have more info from DNB.

**Comment by maxvisser** [comment]
Questions I have:
What is the question on the popup?
What happens after the 90 days?
Is it 'tot' or 'tot en met' -> 90 x 24h or 89x24h
- What is the first date between each 90 days when the permission can be granted? Example: sponsor employee gives permission on 1 of jan until 30th of march. Can he again give permission on the 2nd of januari to extend the authorization to 31th of march? 
  - if yes, he can extend, can this even be on time level? as in you give permission until 30th of march 15:01. Next hour you extend again until 30th of march 16:01.

**Comment by maxvisser** [comment]
Needs figma proposal and relevant legal documents.

**Comment by maartenfv** [comment]
Grip app by ABN gives a good example of what is needed. https://www.abnamro.nl/nl/prive/internet-en-mobiel/apps/grip/index.html

This app helps you track your income and expenses. It reads bank account information. You have to connect it to your bank accounts, the permission needs to be renewed every 90 days.

The user flow to provide permission is very clear in the app.

**Comment by jamalv** [comment]
closing because issue is stale/outdated
