### ISSUE TITLE
Our website still says we are using rocket chat (should be discord)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#456]
![image](https://user-images.githubusercontent.com/30211022/93604081-33229780-f9c5-11ea-98ac-1bf454ee51b4.png)

**Comment by maxvisser** [comment]
probably should take it down aswell. and message people

**Comment by maartenfv** [comment]
@maxvisser we can start here right?

**Comment by maxvisser** [comment]
This is fixed
