### ISSUE TITLE
Support dashboard: Implementation backend & frontend repositories

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#457]
## Description

@maxvisser commented on [Thu Dec 13 2018](https://github.com/teamforus/lab/issues/26)

Idea is to create a specific backend for forus for the roles we fulfill as administrators, implementators and support.

I made implementation private as we did not use it for anything the last few months. I want to use this repository to make user stories of stuff we want to be able to do with this implementation application.

---

@maxvisser commented on [Thu Dec 13 2018](https://github.com/teamforus/lab/issues/26#issuecomment-446986547)

@GerbenBosschieter could you add user stories for support role to this repository. things you want to be able to add, edit and view?

---

@GerbenBosschieter commented on [Thu Dec 13 2018](https://github.com/teamforus/lab/issues/26#issuecomment-447007571)

@maxvisser I will think about what I want as support :)

**Comment by jamalv** [comment]
stale issue - added as an insight to productboard: https://app.productboard.com/inbox/notes/18631987
