### ISSUE TITLE
Groningen webshop

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#46]
Tasks:
- [ ] Develop webshop: https://www.figma.com/file/LOei9CO8mj4lshcCHQvTBz/%F0%9F%8C%8D-Webshop-Groningen?node-id=0%3A1

**Comment by jamalv** [comment]
@GerbenBosschieter I think you already have some branch somewhere for a demo we once gave? Could you share the status of that?

**Comment by GerbenBosschieter** [comment]
@jamalv We can't use it. Max and I already tried. But there are too may new features and there has been a lot of changes in structure (css files). Fixing this will cost you more time than starting over

**Comment by jamalv** [comment]
@maxvisser could you pick this one up? @linda-90 is working on the designs (will be in the style of "Gemeente Groningen") and @aghimpu can do development :)

**Comment by maxvisser** [comment]
I made an initial version. Lets work on Figma a bit more and make a new version in a few weeks

**Comment by maxvisser** [comment]
@jamalv How can we make progress on this webshop. the initial version is deployed on staging.

**Comment by maxvisser** [comment]
@jamalv lets plan a meeting to discuss what needs to be done.

**Comment by maartenfv** [comment]
@jamalv Could you specify this issue?

What are the Sub-Issues of this Epic?

**Comment by jamalv** [comment]
The task now is to convert the design into code and bring it to production; progress is being discussed over at: https://github.com/teamforus/implementation/issues/345

**Comment by GerbenBosschieter** [comment]
- [ ] footer links
- [ ] App icons
- [ ] Me pagina
- [ ] Mobile friendliness

**Comment by maxvisser** [comment]
Final implementation will be in release v0.15.0; released on monday

**Comment by maxvisser** [comment]
released
