### ISSUE TITLE
Signupflow: Overview page "radio's"; to bullets

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#466]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
During usertesting we found out that people (every time) try to click the circles (to check radio's), and think that they don't work. We should change it to bullets to make it a bullet list.

Current state:
<img width="691" alt="Screenshot 2020-09-23 at 10 00 01" src="https://user-images.githubusercontent.com/30194799/93984298-eacbf680-fd83-11ea-91b7-4afb34b8dcef.png">

Should be:

<img width="680" alt="Screenshot 2020-09-23 at 09 59 21" src="https://user-images.githubusercontent.com/30194799/93983928-7729e980-fd83-11ea-891c-2c48d0b2524e.png">

**Comment by maartenfv** [comment]
This came up during session with Westerkwartier they want this changed as well.

**Comment by maartenfv** [comment]
Bump up!

**Comment by maxvisser** [comment]
In de library staat dit als desgin aangegeven.

![image](https://user-images.githubusercontent.com/10818702/94146724-a704ea00-fe74-11ea-977a-24e12c85f6a9.png)

**Comment by maxvisser** [comment]
Currently on PR to develop

**Comment by jamalv** [comment]
done
