### ISSUE TITLE
Requester signupflow: Remove / hide condition block

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#468]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Current state
![](https://cdn.discordapp.com/attachments/708688825014288434/758232692562329660/Screenshot_2020-09-23_at_09.45.54.png)

Should be
<img width="785" alt="Screenshot_2020-09-23_at_09 45 54" src="https://user-images.githubusercontent.com/30194799/93985460-65494600-fd85-11ea-807f-f8cab275c029.png">

**Comment by maxvisser** [comment]
if value does not meet criteria do you still want to check this on the form. If so how would you display what the user needs  to fill in.

**Comment by maxvisser** [comment]
released
