### ISSUE TITLE
CR: Heigth should be the same.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#469]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Implementation

### Change description
- Height of the aanbieding blocks should be the same. Now it is messy.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/6c633dc7-1a60-44c4-9b95-ecb878d776fa)

**Comment by maxvisser** [comment]
@GerbenBosschieter Think you fixed this on develop
![image](https://user-images.githubusercontent.com/10818702/94027445-2209ca00-fdbb-11ea-913c-fd02931d1c73.png)

Should be included on release v0.15.0

**Comment by GerbenBosschieter** [comment]
I did.

**Comment by maartenfv** [comment]
So we good? Will this be in next release?

**Comment by maxvisser** [comment]
Correct.

**Comment by maxvisser** [comment]
released
