### ISSUE TITLE
CR: Add an option to fund criteria set-up to determine the voucher amount of the fund based on properties.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#470]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Margrieta en Maarten

### Change description
On the sponsor dashboard, we can create a fund and add criteria.
It would be nice to add the option base the calculation of the voucher amount based on the properties added.

Example the amount of children determines the voucher amount. Kindpakket base voucher amount 250.
Total amount = amount of children * base amount.
Total amount = 0,9 (Inkomens norm 110%)  * base amount

![image](https://user-images.githubusercontent.com/30211022/94148151-8b024800-fe76-11ea-9ea9-63c5d6b00226.png)

**Comment by maxvisser** [comment]
#280 there is already an issue about this topic; Will add this feedback to it.

Will close this issue as it is a duplicate.
