### ISSUE TITLE
CR: Add search location to list view providers

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#471]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Margrieta Westerkwartier

### Change description

Should be able to search by location

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/1cf4d910-ed77-467a-9b8a-d0ee8a14ac84)

**Comment by maxvisser** [comment]
As in a distance filter (<1KM <5KM) and location sharing?

**Comment by maxvisser** [comment]
This also came up during user testing; "Geef bij de zoekfunctie een mogelijkheid om te zoeken op locatie"

**Comment by maxvisser** [comment]
Design has been made for this.

**Comment by maxvisser** [comment]
https://www.figma.com/file/ehttVgO6MKVZD9feDYMsa7/Sort-by...
