### ISSUE TITLE
CR: "release" all approved providers and offers in one go.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#477]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen

### Change description
- Currently starting an action needs to be done for each action individually and then it appears in the webshop one by one.
- Request is to be able to publish in one go instead of one by one.
- So they verify them one by one and keep them pending for publishing on the webshop.
- When ready they appear in one go.

**Comment by maxvisser** [comment]
From one provider its products or all providers?

**Comment by maartenfv** [comment]
@maxvisser They want to review all of them but publish in one go.

**Comment by maartenfv** [comment]
@maxvisser They can add more providers during the year right?

**Comment by maxvisser** [comment]
yes ofcourse. But just with renewal for next year.

**Comment by maxvisser** [comment]
We need to atleast the default settings (what should we fill in for data)

whats the standard limit
whats the standard price groningen pays to provider
etc.

**Comment by maxvisser** [comment]
Probably need multiple brainstorm sessions and backend adjustments. Don't see this as feasible short term. Therefor probably a big scope. Should check where the main struggles are and maybe check if we can improve their experience with some quick fixes. (if necassary)

**Comment by jamalv** [comment]
I think adding a "start" date for an action that can be in the future (but not after the end date of this fund) would be the most desirable feature. Have no idea about feasibility and scope, would save a lot of work before januari though:

![Screenshot 2020-09-25 at 18.36.48.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/c9405097-7b74-4653-bacd-7c0af5306776)

**Sidenote:** the modal feels very cluttered already, adding more to it without spending some (more) time on the UX is in that sense not very desirable IMO.

**Comment by maxvisser** [comment]
Ah nice I think I read the whole feature request wrong. I thought they wanted to approve all products at once

**Comment by maartenfv** [comment]
We could maybe add a Approve per date X option. This allows them to not have to do all these action the night before the release.|

**Comment by jamalv** [comment]
Agreed! I have updated the proposal here in figma: https://www.figma.com/file/1wtD8IclpZ6OLJzduOHpit/?node-id=88%3A4341

**Comment by jamalv** [comment]
@maxvisser, could you rate scope?

<img width="836" alt="Screenshot 2020-11-15 at 08 33 33" src="https://user-images.githubusercontent.com/30194799/99179365-429c3380-271d-11eb-995d-3406d6b15952.png">

**Comment by jamalv** [comment]
(btw, I think both checkboxes should be checked by default and unchecked if you pick a date, saves the user a couple clicks in most cases :))

**Comment by maxvisser** [comment]
Still think this is medium/big as we need to check if voucher is being able to be scanned based on this date resulting in adjusted the core functionality of scanning QR-codes. (which is already pretty complex) this adds more complexity. Should check with developers.

**Comment by jamalv** [comment]
Since early birds is not a thing anymore, the sponsor can just start starting the actions and adding them to the webshop during this month.

**Comment by jamalv** [comment]
since this is no longer relevant, added it as an insight: https://app.productboard.com/inbox/notes/15569195
