### ISSUE TITLE
Add records after filling signupflow

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#478]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Currently records are being added to your identity after a validation. This change request is about adding the records after you first fill them.

As a requester I would like records to be added to my identity after I submit them (maybe show confirmation modal).

**Comment by maxvisser** [comment]
what would happen if user adjust or remove records while they are still up for validation?

**Comment by maxvisser** [comment]
Adding the records seems fine but aswell add the validation upon the same records that were created seems like a horror story to adjust; I will add scope big. A developer can check if scope can be smaller.

**Comment by nikhilbugaliya** [comment]
Sir, you should use PHP for that. so that you can change the data and add the data and show the pop-up message with the conformation message.

**Comment by maxvisser** [comment]
Lets not fix what is broken 👍 

Discussed: adding records (adds alot of complexity)
Local storage could be an option (need a good way to clean this after logout)

**Comment by maxvisser** [comment]
Would not be an easy fix
