### ISSUE TITLE
Webshop: Sort offers, products by price

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#479]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Potjeswijzer

### Change description
Products are now sorted by creation date. For a requester it makes more sense to be able to sort the list by price. Especially sort by lowest price.

**Comment by maxvisser** [comment]
This is planned to do a design for

**Comment by maxvisser** [comment]
https://www.figma.com/file/ehttVgO6MKVZD9feDYMsa7/Sort-by...?node-id=2%3A573&viewport=1232%2C625%2C0.9104166626930237

**Comment by maxvisser** [comment]
removed from release; moved to a different one

**Comment by jamalv** [comment]
Should also be done for actions:
- Free on top
- Then discounts prices: high to low
- Then then discount percentage: high to low

**Comment by jamalv** [comment]
Add filters for: free, discounts € / discounts %
