### ISSUE TITLE
CR: Add field with info on Potjes website

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#481]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Ingrid Humanitas

### Change description
- We need to make sure people understand there are more potjes than on the website. Example I have costs for the dentist. Where can I go? Now potjeswijzer gives the impression this is all but there is more.

**Comment by maxvisser** [comment]
The explanation page could be used for this?

**Comment by jamalv** [comment]
Yes, CMS has been implemented since this issue was opened, assuming this is no longer relevant.
