### ISSUE TITLE
CR: Add external fund which does not run on Forus

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#482]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Ingrid Humanitas

### Change description
- I have a list of 54 potjes. Please add these to the list of potjes. They can link to other pages or to contactperson

**Comment by maxvisser** [comment]
I think we spoke abit about this issue. As it is pretty abstract; I think you are meaning to ask for a change to allow adding funds which do not need a application form or voucher system. I see the scope as medium. Depends on priority to plan it in.

**Comment by jamalv** [comment]
Would suggest to see this as CMS functionality, and to either add this as a separate page or on the current explanation page and to show it as a nicely formatted table view. But not use the core platform for this, as that would probably become confusing.

**Comment by maxvisser** [comment]
This is released
