### ISSUE TITLE
CR: Give pop up or other notification when creating a fund.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#483]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Potjeswijzer / Implementation

### Change description
- Let sponsor know they have created a fund.

**Comment by maxvisser** [comment]
As the fund is currently easily deletable; Why would this be desirable? Did you not get redirected to the list?

**Comment by maartenfv** [comment]
Weet u zeker dat u dit fonds wil aanmaken.
