### ISSUE TITLE
... Funds

### ISSUE THREAD

**Issue by nikhilbugaliya** [teamforus/general#484]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-Nikhil Bugaliya

### Change description
-You should add some images to your page.
Add Security for the donators.
make it easy to access for the people.

**Comment by nikhilbugaliya** [comment]
Sir, you have to make it with your name. So that people will get to know to whom they are donating. And add a description also for what purpose you need donation...

**Comment by maxvisser** [comment]
Currently sponsor can't yet ask other sponsors to donate to their funds. Not sure what you mean with donators. 👍  But ofcourse we are building a platform to make everything easy to be accessed.
