### ISSUE TITLE
CR: E-mail settings menu item textual change

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#486]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Paul en Leonie

### Change description
"E-mail adres wijzigen" to "E-mail instellingen", same as in drop down menu

**Comment by maxvisser** [comment]
Which one? E-mailadres wijzigen or E-mail instelling

**Comment by SjoerdHilhorst** [comment]
We'll make CR's grouped per page and/or subject, and close these small ones
