### ISSUE TITLE
Webshop improvement

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#49]
## Current situation
We currently have many webshops with (slightly) different stylings and content. 
The codebases are fragmented and the UX & Design need improvement.

### Production webshops:
These webshops are currently in use by thousands of people. We would like to improve them, but we have to be careful not to confuse our current users.

* https://westerkwartier.forus.io/
* https://inkomensondersteuning.nijmegen.nl/
* https://winterswijk.forus.io/
* https://berkelland.forus.io/
* https://oostgelre.forus.io/
* https://kerstpakket.forus.io/ (inactive)
* https://noordoostpolder.staging.forus.io/ (preproduction)

### Planned webshops:
These webshops are currently in development, this means they have no users and there is a bit more flexibility in making improvements. But, if we make them too different from the other webshops, this might make offering support harder.

* Potjeswijzer.nl: https://github.com/teamforus/general/issues/45
* Groningen: https://github.com/teamforus/general/issues/46
* Internal (for dogfooding): https://webshop.staging.forus.io/#!/

### Redesign in progress:
* Figma [updated screens](https://www.figma.com/file/jeym9l4owKdoCUTluAjQFm/prototype-webshop-vision?node-id=138%3A0)

### Status of codebases:
@maxvisser @GerbenBosschieter could you maybe briefly explain the current status of the codebases?

We are noticing it is becoming harder to make updates, without causing bugs in other webshops. What is the cause of this? (please state the problem here, and optionally describe a solution or multiple options for solutions below)

## Goal
To improve the user experience of the webshops, while increasing maintainability.

## Proposal(s)
-

### Describe the solution
-

### Describe alternatives you've considered
-

**Comment by maxvisser** [comment]
There are two webshop implementation which should be the base of all other implementations:
common (all common css files)
general (which contains all funds: the forus vision webshop)


Currently Common and General are the same; General just uses all CSS/images from common and dont adjust anything.

How this webshop currently looks:
https://webshop.staging.forus.io/#!/

Codebase:
- I would remove the splash from common and just add it for Nijmegen only.
- I think we should focus on making the CSS of the common more close to https://berkelland.forus.io/ as this webshop is really clean; So berkelland webshop does not need any new CSS. only some images and color changes.
- I would look into fixing the language files; We currently overwrite alot of texts with a client_key hack, mostly on the front page. And now the accessibility page; Suggestion I have:
- Add a i18n folder to implementation resources. which overwrites certain texts.
- Make a implementation admin panel for the webshop https://github.com/teamforus/lab/issues/68

**Comment by GerbenBosschieter** [comment]
- List all elements, attributes, resources, translations files etc etc (I will do this. Pretty clear for me what changes everytime)

**Comment by GerbenBosschieter** [comment]
Made a start of a list off all elements on the front end that mostly change every implementation

### Webshop
**Resources:**
- Favicon
- Navbar logo
- Header image (splash-top-b)
- Icons step by step guide (icon-steps)
- Map (colors) on home page (sprite-map)

**CSS**
- Page styling
    - General
        - border-radius
        - 
    - Body
        - background-color
    - Navbar
        - font color
        - font weight
        -  test formatting
        - background-color
    - Header
        - background-image (no-repeat and size)
        - header content (aligned center or left)
- Font styling:
    - general
        - color
        - font type
        - font weight
    - Links
        - text decoration (underline)
        - hover effects
    - Breadcrumbs
        - text decoration (underline)
        - active & hover color
    - Buttons
        - text formatting (upper lowercase)

**i18n**

**Comment by maxvisser** [comment]
I would start by fixing the markup to be the common webshop.
General will be Forus brand identity; common will be Gemeente +1 (markup)

**Comment by maxvisser** [comment]
@danrminds alot of what you have done in Extend the menu could be moved here. As it probably takes some more time to finalize.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/81561723-e9c99800-9393-11ea-957b-ddee184db46a.png)

**Comment by jamalv** [comment]
Brainstorming is being done [here in figma](https://www.figma.com/file/sEenqvErGSaTEfwqhsGfmQ/%F0%9F%A7%AAWebshop-improvements?node-id=93%3A986)

There were some comments that turned into a conversation, that I think is better suited for github:

Feedback from Jamal:
> I like that we are looking at the homepage and brainstorming improvements. But we are not there yet: 
> 
> This version feels  overwhelming. We have to be mindful that our users are low-income people; this means they might have a lower level of eductation or be elderly. This page presents to many options and next to that the call to actions are not clear. I would like a simpler menu structure, where maybe you follow a much more linear UX (get options, make a choice, get more options) instead of this version where you get all options at once.
> 
> We also had a discussion about using the signupflow as the starting point for requesters (just like with shopkeepers) this might help with a clearer UX. A design goal for this page should be that at first glance it should be clear what is expected of you (sign up or sign in) - all the other options are secondary.
> 
> So, needs a couple itterations but it’s a good start

Feedback from Gerben on Jamal’s feedback:

> I am not sure if I agree with you.  Low-income people maybe have a lower level of education and are eledery. But this doesn’t mean they don’t know how to use websites.  In fact, from what I know is that these people are active users of websites and stuff (not the elderly ofcourse)  In addition, I would to see the feedback more on guidelines than vision.  And maybe you are right about how people experience this. Who knows. 
> WCAG tells how to make our webshops inclusive for everybidy. Not sure if Linear UX is the best for screen readers and other accesibilty tools . Exmaple, there should always be a page where all the pages are accesible. And also it’s adviced to use navigiton that people are used to. You would like to have the navigation different so it not nescassary to have it all one one page. But this is contradicting to WCAG. All the items should also be visible every time the menu is displayed (so the home page should have the sime items ans the page where you have all the produts). WCAG does it even extremer, they say you should atleast 2 referennces to get to a page. (Example: Navbar: Inloggen voor aanbieders, footer: Ben je aanbieder en wil je meer informatie?)
> 
> And how does linear UX helps with getting to the offers or providers page? I do understand it for the onboarding part.  I do like it for the user to have a starting point as the signupflow.   We should consider WCAG more into these proposals. I have listed a couple of websites that need to comply to the WCAG , are definitly are  being visisted by lower income people and use comparable menu structure. (no I dont like this these website myself, but they do comply)
> 
> The website about Toegankelijkheid self does it also: https://www.logius.nl/diensten/digitoegankelijk  - https://www.nibud.nl/
> - https://www.uwv.nl/
> - https://www.werk.nl/ 
> What about your favo’s ;)
> - https://www.apple.com/music/
> - https://waitbutwhy.com/  

Feedback from Jamal on Gerbens feedback on Jamal’s feedback.

> I understand your point’s and I didn’t mean it as “black and white” it should be fully linear. Of course there is a balance, and I fully agree that a home page should offer ways to get around the website.
> 
> I set out a direction where I would like it to go here: https://www.figma.com/file/sEenqvErGSaTEfwqhsGfmQ/%F0%9F%A7%AAWebshop-improvements?node-id=259%3A4078
> 
> I am curious to here your thoughts on that page, as I hope that it complies to both our feedback (also, it is meant as a direction, implementation of the suggestions can of course be incremental) - if there’s things we like, we can implement them step by step to improve the UX.

**Comment by jamalv** [comment]
@maartenfv placed a question in figma: How do we proceed? Needs to be closed :)

@maartenfv: I think this issue is too big to close (yet) I think many smaller issues need to come out of it that can indeed be fixed and closed, but improving the webshops without disrupting current users, is a pretty big project, and I think that this issue is a good more "abstract" issue to keep an overview of the total progress. So yes, making smaller more concrete issues to make real progress is surely needed, but not sure that this issue needs to be closed, what do you think?

**Comment by maartenfv** [comment]
@jamalv I missed this issue. Could you give an update?

@jamal could you link the question, I can not find it?

@jamalv I think the Epic, Issue, Subtasks in markdown lists structure is the way to go. See: https://help.zenhub.com/support/solutions/articles/43000010341-an-intro-to-zenhub-epics

This means that this issue should go from discussion to concrete tasks so we know what to do.

Example:
What exactly needs to be decided upon?
What needs to be designed?
What needs to be developed? 

Who will do these things above?

**Comment by maxvisser** [comment]
I just want the menu part on production asap

Example of the problem:
![image](https://user-images.githubusercontent.com/10818702/88272606-453fcc80-ccd9-11ea-891d-57e79935d9c5.png)

**Comment by jamalv** [comment]
Yes I agree, lets make a task for that.

I like this: 

<img width="532" alt="Screenshot 2020-07-23 at 11 40 59" src="https://user-images.githubusercontent.com/30194799/88272744-7c15e280-ccd9-11ea-840d-945ca85fc8cc.png">

**Comment by jamalv** [comment]
Had some discussions about this the plan should be to take this step by step: we have made some good steps with the mobile menu #194 and menu bar (above) - we'll have to go trough each one step by step with the goals of:

- refactoring for maintainability and scalability
- #253 WCAG complience
- improving the designs and user experience of the webshops

The way we are doing this with the menu is a great start.

Next I propose to also update:

- [ ] Product cards
- [ ] Footer
- [ ] todo: [add all other pages and components]

Of course each of these tasks will need a seperate issue that is linked to this epic.

Let's give the webshop some love; page by page, component by component ❤️

**Comment by maxvisser** [comment]
Lets create seperate CR for footer and product cards. I will close this one and create those
