### ISSUE TITLE
CR: Webshop Provider details: being able to go back to map

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#493]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Paul en Leonie

Note: This change was requested after acceptance testing with stakeholders of project 100
### Change description
- Need to be able to go back to map overview of providers from the provider details page:
from here:
![image](https://user-images.githubusercontent.com/48722300/95090284-61bea300-0725-11eb-979e-2a181229685b.png)
To here:
![image](https://user-images.githubusercontent.com/48722300/95090394-8286f880-0725-11eb-917a-32ce259b2695.png)

**Comment by maxvisser** [comment]
Created aswell one for potjeswijzer. Nice to have I think but both parties requested it. #485

**Comment by maxvisser** [comment]
Proposal:
https://www.figma.com/file/z2g3QirHVY2gNtrkm6MJA1/?node-id=176%3A137

**Comment by maxvisser** [comment]
Created a task
