### ISSUE TITLE
Webshop: voucher overview page in profile should give more context like a welcoming text.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#494]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Sponsor

**Note:** This change was requested after acceptance testing with stakeholders of project 100

### Change description
- As a user who has a voucher I would like to be welcomed and give more context on the page I got redirected to after logging in.

**Comment by maxvisser** [comment]
I understand but to keep the page functional aswell its a pretty hard task to think about; If there is a clear proposal I can scope this issue.

**Comment by jamalv** [comment]
Yeah, I understand why this was requested. I think maybe a better alternative is a confirmation after a succesful application, maybe right now it is a bit "too magical" :)

Something like:

# 🎉 

_Success! You are eligible for the Stadjerspas! Here it is!_

[Continue]

**Comment by maxvisser** [comment]
We do have this page already in Figma and lena already started refining it more (the success page with checkboxes to activate funds)

**Comment by jamalv** [comment]
Understood from @GerbenBosschieter that he means a different page (the one in your profile)

**Comment by maxvisser** [comment]
Not sure probably this needs a proposal. Currently to vague to see whats needed.

**Comment by maxvisser** [comment]
@GerbenBosschieter also does not know; He knows we refined something but as this is from 6 months; its probably already implemented / not needed.
