### ISSUE TITLE
CR: Webshop Me page

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#496]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Paul en Leonie
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
As an implementation holder I would like to have a page about the Me app in my brand identity.

- Me page needs to be in the context of the webshop, i.e. do not link to https://forus.io/me but have a page in the webshop: https://stadjerspas.forus.io/me
  * Redesign Me page in context of webshop

**Comment by maxvisser** [comment]
We have a page for the webshop but this one was decided to get removed. As the Me-app is a generic app; I think its not that weird that you leave the site to read info about it.

I see a few options here; I do not really have any strong opinion:
1. change the content of the page and keep it updated https://stadjerspas-acc.gemeente.groningen.nl/me
2. Remove the page and all links to it.
3. Keep as is and explain decision about why making copies is aswell bad for the user.

I see the scope as small. As content is there; its just a business decision to go for either choice.

**Comment by jamalv** [comment]
Figma proposal: https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/Untitled?node-id=1%3A107

**Comment by maxvisser** [comment]
Seems fine by me; scope is still small.

**Comment by maartenfv** [comment]
What is the status of this issue?

**Comment by maartenfv** [comment]
Updated de Figma prototype. Dit is een must-have en ingeplanned voor komende sprint.

**Comment by jamalv** [comment]
Discussed in discord to leave out the link to our site, and just link to the app store. There's more info and screenshots there as well 👍

**Comment by maartenfv** [comment]
this issue is crucial.  Stated as big problem. needs to be made as in proposal by Demy.

**Comment by maxvisser** [comment]
Its already there as a PR to develop.

**Comment by maxvisser** [comment]
I see jamal reopened the design review. Not sure whats happening there.
