### ISSUE TITLE
Webshop voucher page: Hide my reservations If I don't have any

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#497]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor 

**Note:** This change was requested after acceptance testing with stakeholders of project 100

### Change description
- Don't show any information about reservations (product vouchers) if I don't have any. If my product voucher = 0, hide html block

### Example
![product](https://user-images.githubusercontent.com/38419514/95091601-efe75900-0726-11eb-8279-0c416c420d0d.jpg)

**Comment by maxvisser** [comment]
Ah I forgot that Stadjerpas never will use product vouchers. Will plan in this.

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/514

**Comment by maartenfv** [comment]
Update?

**Comment by maxvisser** [comment]
This has been hidden. I think this is already on production
