### ISSUE TITLE
Webshop voucher page: profile menu sync texts

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#499]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

**Note:** This change was requested after acceptance testing with stakeholders of project 100

### Change description
The page that we recently showed again could use some improvements:

1. The names of menu items shown when clicking profile menu (the carrot) should be aligned with sidebar menu
2. Don't show any information about activation code if they will never use it (remove activation code html for project 100)
3. Consider hiding sessions for citizens completely. It feels to techy and could result in a lot of questions.
4.  Reconsider what text / words we use

**URL tested:** https://groningen.staging.forus.io/vouchers

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fgroningen.staging.forus.io%2Fvouchers&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://groningen.staging.forus.io/vouchers&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6b4f3427d76db845abbbdcf630e96a4ace8fcf81/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/6b4f3427d76db845abbbdcf630e96a4ace8fcf81/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fgroningen.staging.forus.io%2Fvouchers&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://groningen.staging.forus.io/vouchers&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
Can be adjusted here:
https://www.figma.com/file/k8Yjwct18gJYlykIHuqMF9/Webhop-Settings?node-id=60%3A9047&viewport=-2802%2C1515%2C0.32634228467941284

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/509

**Comment by jamalv** [comment]
1. Would also consider completely removing the dropdown menu, and changing the dropdown carrot to > and go to the "profile" page.
2. 👍 
3. related: https://github.com/teamforus/general/issues/529#issuecomment-708981041
4. This is always good :)
