### ISSUE TITLE
Master QR

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#50]
## Current situation
We currently are using multple QR-codes in the platform, for reservations, and (multiple) budgets.

## Problem statement:
Users get confused by different QR codes. And to offer "city-pass" like functionality we need to be able to print a QR code on a card.

### Describe the solution
Link: [Google Doc](https://docs.google.com/document/d/1MpQ1_OVewK2vNKV96ZyYBLKU5UigH1XxUVS-WIA4sSA/edit#) (ask @jamalv or @maxvisser if you would like access)

**Comment by maxvisser** [comment]
I would suggest a second authentication method when we print QR-codes on plastic as the qrcodes are access tokens to budget/products. As it is easily copied (as the password is really visible and meant to be scant)

Why?
Printables are currently 1 year valid (which is already pretty long) you want a plastic card to go be usefull for multiple years. 

Options
Like creditcards we can add a 4 digit cvc printed on the card. Which is maybe user changeable in the webshop and for voucher generated by voucher generator for the sponsor to be able to change it ( not assigned vouchers)

**Comment by maxvisser** [comment]
Other option is to not fully comply with you change request and make the card a discount card. The qr-code a record instead of a voucher, which can be scanned and seen which parties validated the record.

Meedoenpas
Ja

Validated by
gemeente Groningen

Which results that the card is basically just an identifier and does not contain any budgets/product reservations.

**Comment by jamalv** [comment]
I think the main thing we need to consider here, is that the users of these cards are probably not digitally skilled, so our options of offering extra security features without losing usability are limited. For security, I would prefer to focus on directing users to primarily using the app, where the QR code is secured (using a second factor and/or biometrics) and can be more dynamic.

Since having this card will be optional. I would provide a warning that having it physically is less secure than having it digitally, and letting users make a conscious choice between accessibility  and security.

**Comment by jamalv** [comment]
Second option might also be possible, but it depends on the exact use case and if it is future proof.

**Comment by maxvisser** [comment]
I think the CVC is the minimum thing we should ask if the qr-code is printed on plastic and valid for multiple years; 

Warning users about it being less secure is a terrible idea. Software with big ass warning makes Forus really less trust worthy.

**Comment by maxvisser** [comment]
added my proposal to the gdoc

**Comment by jamalv** [comment]
We have learned that for project-100 we need to (at minimum) need to be able to print a budget voucher with reservations. For the first iteration a master-qr might not be nesasary. 

It is still a **should have** in order to be better prepared for the future and for increasing the user experience for a user with multiple budget vouchers.

**Comment by jamalv** [comment]
Opened a new IP about physical cards: https://github.com/teamforus/general/issues/182

**Comment by maartenfv** [comment]
@jamalv @maxvisser Could you give a status update? Is this still relevant for Groningen or has it been solved?

**Comment by jamalv** [comment]
For the current scope of discussions has not appeared to be relevant. 

As long as people are actively using the Me app (for example at SDOA) and with the UX improvements we have made so far, this seems to be going quite well. If it becomes a concrete requirement to put multiple funds/records on **one** physical card 💳 , this issue becomes a requirement. And then the label is accurate; scope big, I would expect one or two sprints at least.

**Comment by jamalv** [comment]
Replaced with item on the roadmap: https://roadmap.forus.io/c/66-generieke-pas
