### ISSUE TITLE
CR: Product details: Move product info card to above provider info card

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#500]
Learn more about change requests here: https://bit.ly/39CWeEE
### Requested by:
Paul en Leonie
Note: This change was requested after acceptance testing with stakeholders of project 100
### Change description
- Move product info card to above provider info card
- ~~The page should contain a clear UX on how to redeem the product/service with stadjerspas, it is currently not very clear on what steps the user needs to take to do this.~~
- ~~Update text "Beschikbaar aantal" as it is unclear what it references, total amount or amount available for inwoner~~

**Comment by maxvisser** [comment]
Not sure how to scope this one. Moving the product info card above the provider info is a good suggestion; Will plan that one in. The other stuff probably need a seperate issue. To discuss that further.

**Comment by maxvisser** [comment]
Lets create some different CR for the other two. As I also see maybe a whole redesign is needed scope for the other points could become pretty big.

**Comment by maartenfv** [comment]
What is the status?

**Comment by maartenfv** [comment]
The other points that have a line trough them are the most important in this issue?

**Comment by jamalv** [comment]
Current status is that 2/3 are fixed and the page got general design improvements:

<img width="1333" alt="Screenshot 2020-11-14 at 14 11 20" src="https://user-images.githubusercontent.com/30194799/99147696-47aca480-2683-11eb-822c-a54cebfca4ed.png">

not yet fixed: The page should contain a clear UX on how to redeem the product/service with stadjerspas, it is currently not very clear on what steps the user needs to take to do this. > this also came out during user testing, what happened is that the user started clicking on stadjerspas but nothing happed, so a link should be created from this page to your stadjerspas https://github.com/teamforus/general/issues/575 this way people at least have a "call to action" > and on the voucher page it shows a clear explanation "take this QR code to the provider"


Just for reference, this is the old layout:
![image](https://user-images.githubusercontent.com/30194799/99147845-652e3e00-2684-11eb-9b91-0d2f4bf6504d.png)

**Comment by maxvisser** [comment]
not relevant anymore
