### ISSUE TITLE
Change e-mailadres user flow improvements

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#501]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

**Note:** This change was requested after acceptance testing with stakeholders of project 100

### Change description
Stakeholder gaves us the feedback that it's not clear for users to change e-mailadres
1. Missing explanatory notes to tell the user what they can do here and what really happens.
2. Herstuur??? This should be something like : Verificatie e-mail opnieuw versturen.
3. Don't use words like *Maak Primair* but something: Instelling als hoofd e-mailadres
4. Add a popup after adding new e-mailadres to tell user that some actions (and tell them what action) is needed to finish this task

**URL tested:** https://groningen.staging.forus.io/preferences/emails

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fgroningen.staging.forus.io%2Fpreferences%2Femails&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://groningen.staging.forus.io/preferences/emails&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/fb5bfde14899723b41d0854e59c5e941adf951a7/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/fb5bfde14899723b41d0854e59c5e941adf951a7/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fgroningen.staging.forus.io%2Fpreferences%2Femails&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://groningen.staging.forus.io/preferences/emails&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment]
Can be adjusted here:
https://www.figma.com/file/k8Yjwct18gJYlykIHuqMF9/Webhop-Settings?node-id=60%3A9047&viewport=-2802%2C1515%2C0.32634228467941284

**Comment by maxvisser** [comment]
@linda-90 Could you do a check for this page and add good texts?

**Comment by maxvisser** [comment]
Proposal:
![image](https://user-images.githubusercontent.com/10818702/95558463-8f059c80-0a16-11eb-8f7b-43e388fc5d34.png)

**Comment by maxvisser** [comment]
On point 4 that seems to be a bug. There is currently a message in the code which has an explanation of what user needs to do. (it currently does not popup.)

**Comment by linda-90** [comment]
@maxvisser 
- [x] Text check
https://www.figma.com/file/k8Yjwct18gJYlykIHuqMF9/Webhop-Settings?node-id=60%3A9047&viewport=-2802%2C1515%2C0.32634228467941284

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/510

**Comment by maartenfv** [comment]
Status?

**Comment by maxvisser** [comment]
Points stated in the issue are fixed
