### ISSUE TITLE
CR: Product details page

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#503]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description

- Change text "Aantal beschikbaar" as it is not descriptive, is it referencing total amount? or amount available for this account?

- The page should contain a clear UX on how to redeem the product/service with stadjerspas.
 ![image](https://user-images.githubusercontent.com/48722300/95180579-756c1700-07c2-11eb-90d9-89db58c51d70.png)
 There is currently no information on the page that explains how to achieve this

**Comment by maxvisser** [comment]
> The page should contain a clear UX on how to redeem the product/service with stadjerspas.
Nice CR. I think we could link to the explanation page from here (where can be described how to retrieve actions how the system works?)

> Change text "Aantal beschikbaar" as it is not descriptive, is it referencing total amount? or amount available for this account?
Maybe change it to 'Jouw saldo:' ?

**Comment by SjoerdHilhorst** [comment]
"Jouw saldo" maybe wouldnt make sense in this context, "Aantal voor u beschikbaar" would already be an improvement

**Comment by maxvisser** [comment]
This would be weird with multiple vouchers / tegoeden

You could get:
Stadjerspas - Aantal voor u beschikbaar 1
Stadjerspas Jongeren - Aantal voor u beschikbaar 5

**Comment by maxvisser** [comment]
We could also introduce a tooltip; just show the word 'Saldo' and a little i symbol which pops open on hover; describing what a saldo is 'aantal voor u beschikbaar, ga langs bij aanbieders om gebruik te maken vaan uw saldo'

**Comment by maxvisser** [comment]
Proposal: https://www.figma.com/file/VvubQOugtWD50iJ0B955vl/Product-page?node-id=66%3A412&viewport=277%2C858%2C0.5264466404914856

**Comment by maxvisser** [comment]
Showed proposal to Gerben; He seems to agree with the proposal (a solution for the problem)

**Comment by maxvisser** [comment]
Will plan a design review for Alex

**Comment by maxvisser** [comment]
Planned: https://github.com/teamforus/forus/issues/1821

**Comment by maartenfv** [comment]
Status?
