### ISSUE TITLE
Fund specific contact e-mailadres

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#505]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
When a municipality has multiple funds, contact information can differ per fund. As a municipality is quite big you have multiply departments who can utilize funds. It would be a good feature to let the sponsor configure contact details per fund (instead of using that from the organization)

**Comment by jamalv** [comment]
Is this still relevant? Assuming could-have. Curious about your proposal :)

**Comment by maxvisser** [comment]
Yes currently we have done this pretty hacky at Bus fund for nijmegen. (we use providers mail contact); would be nice that the sponsor could set contact details per fund
