### ISSUE TITLE
When there are no offices for a product, hide map on product voucher

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#506]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently when there are no offices for a product voucher; the map is still visible.

![image](https://user-images.githubusercontent.com/10818702/95431715-eab82300-094d-11eb-94b3-a7b749ffc447.png)

**Comment by jamalv** [comment]
@maxvisser I think this was in .15?

**Comment by maxvisser** [comment]
Its not. Currently on a PR to a new release (hopefully can be released tomorrow morning)

**Comment by jamalv** [comment]
i'm assuming this has been released
