### ISSUE TITLE
Add a way to make the description 'empty' criteria description

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#508]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Dev team

### Change description
Discussed during a call with development team. Its nice to keep the criteria on the step visually if no description.

Default text is for example:
'Aantal kinderen' moet meer dan 1 zijn.

Only way to change this is add a space into description field.

**Comment by jamalv** [comment]
Not sure I understand this issue :)

**Comment by maxvisser** [comment]
maybe this one is already fixed but before we had 'aantal kinderen groter dan 1' in the list view if you didnt supply a title. which is just computer language.;  Would be nice if we could thing of some different way of managing empty titles / descriptions
