### ISSUE TITLE
CR: Create Product checkbox image rights 

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#509]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
- On the add product page: Add a checkbox to the image stating that you have rights/ownership to the image 
![image](https://user-images.githubusercontent.com/48722300/95195590-0d73fb80-07d7-11eb-9d08-f860238fef89.png)

**Comment by maxvisser** [comment]
@GerbenBosschieter What did they think about the implemented 'zinnetje erbij'?

![image](https://user-images.githubusercontent.com/10818702/95430960-cb6cc600-094c-11eb-9db2-07c8c772e544.png)

**Comment by maxvisser** [comment]
We could do this. Personally I find this pretty weird UX. The checkbox is probably aswell not legally binding just annoying.

**Comment by maxvisser** [comment]
Aswell do we need to show this checkbox somewhere? or is it just a frontend thing what enables the upload button?

**Comment by maxvisser** [comment]
Jamals proposal:
For checkbox implement I see 2 ways:

Frontend: someone has to put it, and cannot continue unless it has been set. Advantage: easy to implement. Downside: has no legal value, and someone has to put it every time you upload an image (we don't remember anything).

Backend: we store that someone has put it. This increases the scope, but I am in favor of it. For GDPR and PSD2 compliance, we have to keep a record of these types of consents anyway - for example, also that someone has given permission to receive newsletters, or has agreed to our terms of use. I imagine that you then, for example, have to keep track of when a user has set which checkbox, and what the explanation was, something in the direction of:

recieve_newsletter | true | timestamp
image_licences | true | timestamp
general_conditions | true | timestamp

In the long run it would be dope to add this as self validations to the user's profile, but in the short term we might just have to do this in a separate table?

**Comment by jamalv** [comment]
https://www.figma.com/file/1wtD8IclpZ6OLJzduOHpit/Sponsor-dashboard-Improve-start-action-modal

**Comment by maxvisser** [comment]
Checked some other sites which allows users to upload images. They all add a link to their terms of service 'Gebruiksvoorwaarden' on the page where you can upload.

For example github
![image](https://user-images.githubusercontent.com/10818702/98346180-e7c85500-2015-11eb-8f01-b033732fb5dd.png)

![image](https://user-images.githubusercontent.com/10818702/98346213-f1ea5380-2015-11eb-8ddf-58466b1f9aeb.png)

Probably better to save that user has agreed to the condition within such an agreement instead of asking for each thing if user knows the terms he can use the system.

**Comment by maartenfv** [comment]
What is the status of the issue? 

The requirement of the Municipality stays the same. They have accepted this solution (with the checkbox) as a compromise to having the municipal employee be able to change the image themselves. The municipal employee changing the image was a hard requirement. C5 _Medewerker heeft de mogelijkheid om afbeeldingen bij de aanbiedingen te plaatsen._  and C9 Medewerker heeft de mogelijkheid om de content van het systeem te beheren, dat wil zeggen het plaatsen en wijzigen van teksten, afbeeldingen en video's.

This means just adding gebruikersvoorwaarden is not a solution and the initial CR: "Change description
On the add product page: Add a checkbox to the image stating that you have rights/ownership to the image" stays the same.

**Comment by maxvisser** [comment]
![Uploading image.png…]()

**Comment by maartenfv** [comment]
Perfect 👍

**Comment by maxvisser** [comment]
The new design of the cropper is implemented + a checkbox

**Comment by maartenfv** [comment]
https://www.youtube.com/watch?v=MYrXK5ek_PQ

**Comment by danrminds** [comment]
Merged and done.
