### ISSUE TITLE
Add Contact page to webshop with a form and contact details

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#510]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Usertesting

### Change description
During user testing there was a idea which was indexed which says 'State all criteria clearly and give information about the fund before you ask to login with DigiD'; A good thing would be to add a contact item in the menu so people have a clear route to get help when they get stuck on this step. Most of the testers said that they first want to sent a mail.

**Comment by jamalv** [comment]
@maxvisser sjoerd will have a look at this, if you want to continue, please check in with sjoerd

**Comment by SjoerdHilhorst** [comment]
Jamal explained this to me that there needs to be a page similar to the privacy page, which has all the contact details which are in the footer. is this basically pasting the cms from https://github.com/teamforus/forus-frontend/pull/1619 on a new page?

**Comment by maxvisser** [comment]
explained my thoughts here:
https://github.com/teamforus/general/issues/498
