### ISSUE TITLE
Webshop: Fund details page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#511]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently we have a fund list. During usertesting we saw that the requester does not have a easy way to retrieve information about the fund (what are its criteria and what can I get with said voucher?). A detail page for said fund can help with this information distribution 

Figma: https://www.figma.com/file/TPzlh3I3RrAT7m5p9u7WRT/Fund-details-page

**Comment by maxvisser** [comment]
- Aanvraag pakketen stappen: verwijs steeds door naar een informatiepagina over de aan te vragen potje (kindpakket of iets anders). Doe dit ook bij ieder pagina in het stappenplan. 

Opties voor de should have:
Quickfix: Een fonds heeft een informatiepagina link; gebruiker kan naar een externe website gaan met informatie over het fonds

Doel: Elk fonds heeft een 'detail' pagina. Hier staat duidelijk van wie het fonds is en de beschrijving.

**Comment by jamalv** [comment]
![Screenshot 2021-01-25 at 11.27.19.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/6223ae71-8ef7-43bb-8b8b-39df42266433)

criteria details as filled by the municipality
![Screenshot 2021-01-25 at 11.30.37.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/8f236199-de73-4426-afb8-581cb3874573)

**Comment by maxvisser** [comment]
update: should be planned for alex to designed for webshop

**Comment by jamalv** [comment]
update from @danrminds alex can probably do it this weekend, will be planned when he is available.

**Comment by jamalv** [comment]
Got some feedback from Erwin: https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs?node-id=1220:25259#66640090 "Erwin: Kunnen we hier ook meer informatie laten zien? Hoeveel geld zit er in? Wat zijn de voorwaarden?" 

https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs?node-id=1220:26304#66639593 : Erwin: Kunnen we hier ook meer informatie laten zien? Hoeveel geld zit er in? Wat zijn de voorwaarden?

**Comment by jamalv** [comment]
@maxvisser I see this was added to a release but no development task, is this right?

**Comment by jamalv** [comment]
@linda-90 could you review the design and erwin's comments?

**Comment by jamalv** [comment]
some inspiration: https://www.figma.com/file/jeym9l4owKdoCUTluAjQFm/%F0%9F%A7%AAwebshop-vision?node-id=138%3A0

**Comment by linda-90** [comment]
Design (+ comments van Erwin): https://www.figma.com/file/LryGgoQSl0rPu41hbIqFEI/Webshop---Fund-details-page?node-id=1220%3A25259&viewport=701%2C363%2C0.09573645889759064

**Comment by maxvisser** [comment]
Write down some user stories; technical proposal
Recheck design when creating Generic search proposal @linda-90
