### ISSUE TITLE
Voucher page information and options are to overwhelming

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#516]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100

### Change description
The voucher page is a bit to overwhelming with information and options. Groningen requested to make the information on the page more clear. And also the banner thats being used for physical cards needs some textual changes.

1. Text is only about the scenario of old cards. Should also relate to other scenario's. 

**Example: (proposal)** 
- Title: Heeft u een pas ontvangen of was u al in bezit van één?
- Description: Om uw pas te kunnen gebruik dient u de pas te koppelen, dit geldt ook voor passen van afgelopen jaren.
- CTA button: Pas activeren

2. **The cards**
- We got the feedback: less is more
- QR code needs to be the center of attention on this page.
- The cta (print, open in me, send by mail, phsyical card shouldn't be in the voucher card. These CTA's need their own section and more context.
- They requested to remove the print button.
- Is the right card (hoe werkt het?) really necessary? Can;t we remove this and add the important information like contact information somewhere else

**URL tested:** https://stadjerspas-acc.gemeente.groningen.nl/voucher/0x2dcfb134c76a837b1770fb7fefd4fcdfeafe376b

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstadjerspas-acc.gemeente.groningen.nl%2Fvoucher%2F0x2dcfb134c76a837b1770fb7fefd4fcdfeafe376b&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://stadjerspas-acc.gemeente.groningen.nl/voucher/0x2dcfb134c76a837b1770fb7fefd4fcdfeafe376b&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/2f665bfc39df0d3db82f6fd79692db3e38c5a91e/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/2f665bfc39df0d3db82f6fd79692db3e38c5a91e/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstadjerspas-acc.gemeente.groningen.nl%2Fvoucher%2F0x2dcfb134c76a837b1770fb7fefd4fcdfeafe376b&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://stadjerspas-acc.gemeente.groningen.nl/voucher/0x2dcfb134c76a837b1770fb7fefd4fcdfeafe376b&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by GerbenBosschieter** [comment]
@Myshelova Could you review this page and give your opinion about the bullet points I added?

**Comment by GerbenBosschieter** [comment]
@maxvisser I know this CR could be to big and maybe we should split it up.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/95587627-95117280-0a42-11eb-8518-f105a3d282de.png)

**Comment by maxvisser** [comment]
Page needs to be redesigned

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/513

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/95957714-57c13200-0e00-11eb-98bd-0df4195e4915.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/95958764-e2eef780-0e01-11eb-9587-d4f72767530c.png)

**Comment by maxvisser** [comment]
Jamal's suggestion is to switch around the card about physical cards

**Comment by jamalv** [comment]
Did some "inspect element" editing during testsession (texts and order of elements):

![Screenshot 2020-10-13 at 15 44 11](https://user-images.githubusercontent.com/30194799/96096139-cf11c700-0ecf-11eb-8568-4b058031a2fd.png)

**Comment by jamalv** [comment]
https://www.figma.com/file/vWtj9Ro6j6T2EnPgvboAnh/Physical-cards-feedback?node-id=0%3A1
