### ISSUE TITLE
We should improve physical card user flow. Not clear for users. 

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#517]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
There are too many option behind the physical card button, this makes it unclear for the users.
From what I understand there are 3 scenario's for users to use this button. 

<img width="149" alt="Screen Shot 2020-10-09 at 16 03 39" src="https://user-images.githubusercontent.com/38419514/95592507-07855100-0a49-11eb-8d07-f194aef6d6cc.png">

**Scenario's**
1. User wants to activate the card that they already have
2. Users wants to order a new card though the post
3. Users lost their card, ant to block the card and order a new one.

I am not sure how we can improve this right away but I will add some examples below to give more context of why they didn't like it.

**Examples**
Scenario: Users wants to order a new card though the post.
1. User click ons **Plastic pass** (no information that you order a card by clicking this button)
2. User gets a popup that doesn't fit their needs at all. First thing they see is all the options they have to NOT order a card. This is weird. I understand we have to desire to discourage people to order a physical card. But the way we present is just confusing. Maybe we should remove these options that is not about the physical card and add text with an explanation of why you can better use the digital option (better for climate, it will be phased out eventually, etc etc)

<img width="808" alt="Screen Shot 2020-10-09 at 16 08 44" src="https://user-images.githubusercontent.com/38419514/95593316-d22d3300-0a49-11eb-8e6d-89595d1351d5.png">

3. After Clicking on **Per post bestellen** the user will get a form to fill in their address information.
4. After confirming the information a new popup opens with the confirmation. This confirmation is missing the following information: 
        - Summary of the information where the card is sent to (if the user is not sure they filled in the right address than there is a change that they going to order a new one)
        - How long will it take before a receive my card?

<img width="803" alt="Screen Shot 2020-10-09 at 16 08 58" src="https://user-images.githubusercontent.com/38419514/95594420-2edd1d80-0a4b-11eb-87ff-c0296dc10499.png">

**Comment by GerbenBosschieter** [comment]
Only covered one scenario, will add more context about other scenarios

**Comment by maxvisser** [comment]
proposal:
remove all screens which gives user a choice for example:
![image](https://user-images.githubusercontent.com/10818702/95828419-4101d900-0d35-11eb-9efe-e9d23cb238e7.png)
This screen can directly show the form

same with the other model where all options are; remove that modal aswell. Only have button on voucher card to go redirect to the actions behind these modals

So you will get:
- Request card (maybe check if there is already request and show this to user)
- Link card
- Block card (if already linked)

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/513

**Comment by jamalv** [comment]
Yea, great CR; I think making the reasoning about showing alternatives when ordering a physical card explicit is a very good idea; "you can use your digital card right now, always have it with you in the app or on the site, or email it.. environment etc"

Also like the other suggestions 👍 

Slightly related: I also liked the idea of switching the order: https://github.com/teamforus/general/issues/516#issuecomment-708984791

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/vWtj9Ro6j6T2EnPgvboAnh/Physical-cards-feedback?node-id=0%3A1

**Comment by jamalv** [comment]
@maxvisser text review is done, I think maybe the icons need to be checked by a designer (I've added a blur layer to blur what has not changed, it is locked - you can unlock/hide it, the layer name is "Focus example (detach instance)")

@maxvisser could you do a feasibility check and create the implementation tasks for the developers? https://www.figma.com/file/vWtj9Ro6j6T2EnPgvboAnh/?node-id=0%3A1

We'd also like to update the notification bar, but kept that as a seperate page, since it changes the design: https://www.figma.com/file/vWtj9Ro6j6T2EnPgvboAnh/?node-id=61%3A2566
