### ISSUE TITLE
Connection with retail kassa systems like SumUp or CCV

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#518]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

Did some research; there are two big payment terminal providers Sumup and CCV which accept Maestro, VISA etc.

It would be a nice feature to allow providers to fill in an amount on said terminal, show a QR-code on terminal which Me-app scans and let user do a payment. Their websites do not have any information about how a payment method could apply to connect to their terminals. 

Sumup seems to be the more develop friendly one, CCV seems to have a bigger market share.

## Aditional information
https://sumup.nl/
https://www.ccv.eu/

https://github.com/sumup/sumup-android-sdk

**Comment by jamalv** [comment]
Roadmap: https://roadmap.forus.io/c/79-kassa-systemen
