### ISSUE TITLE
Provider sign-up flow: Test payment and confirmation of applying to fund is confusing.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#520]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** D1

### Change description
Last step of provider sign up flows gives the user a confirmation that they applied for the funds and they can do a test payment.

We got the feedback that it's confusing:
1. You get an confirmation you applied to a fund even if you didn't apply to a fund the step before. Gives a wrong impression to the provider.

2. Doing a test payment buttons feels randomly positioned on this page. More context on why they should do a test payment is needed. Groningen told us it can scare people if there is a random to do a test payment. 

Possible solution:
- More textual context about test payment (why do you need to do a test payment)
- Tell the provider something like this: "You've successfully applied for a fund! You almost there, to do a last check and give you an impression on how it would work if you have a customer. Pleas do a test payment!"

**Comment by maxvisser** [comment]
I aswell think the current implementation of the test transaction does more bad then good; It shows a completely different interaction

**Comment by maxvisser** [comment]
Changing some texts seems as a small scope.

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/530
