### ISSUE TITLE
Adding a product: Do we still need an separation between products or services?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#521]
### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** D2

### Change description
We got a question form Groningen if it's really needed for the provider to check a checkbox to for Product / Service. Can't we just combine the categories?

**Comment by maxvisser** [comment]
Currently this data is not used. We don't show it anywhere or allow sponsor to set anything based on it. It is a legacy feature ;) So yes indeed this could be removed or used on financial dashboard #316

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/531

**Comment by jamalv** [comment]
@maxvisser if it's not used let's remove it! I was under the impression that this was used on the financial dashboard?

Less is more!

**Comment by jamalv** [comment]
It's also not used in the webshop?

**Comment by maxvisser** [comment]
Would like to use it. We never really made any good features with the data we collect. :sweat_smile:

**Comment by jamalv** [comment]
Okay, well if we're not using it and don't have any strong case for using it on the roadmap, let's kill it and save the providers the trouble.

If we ever want to use this kind of data, we should come up with the full use case and proposal when building out the scope. I'm not much in favor of collecting data just "in case we might someday use it".

What is needed to delete this? Are there any risks we should be aware of?

**Comment by jamalv** [comment]
The other direction is building out the proposal of using it; but we'd need (at the very minimal) a low fidelity figma prototype in order to get support for building it. This right now feels like a loose end without a plan, which only creates a speed bump for all the providers that sign up.

**Comment by maxvisser** [comment]
its probably harder to find the categories for services though if put them in one list

**Comment by jamalv** [comment]
@maxvisser regarding the comments above, could you validate that this feature can indeed be removed? or otherwise specify the user stories that can be filled by using this data so that we can add it to the roadmap on productboard?

**Comment by maxvisser** [comment]
I believe we built it cause Nijmegen wanted more data on their financial dashboard. I also think you misunderstood. We do not use the seperation between services and products but we do use the categories.
