### ISSUE TITLE
Product change requests (chat) improvements

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#522]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen 
**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** D2

### Change description
- There is no e-mail being send after a sponsor requested a change to the product.
- Could we add the organisation name of the sender and receiver to the chat?
- Some of the messages are automaticaaly send after a certain action is done (like rejecting the product). For the receiver it's not clear that it's an automatic message.

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/525

**Comment by maxvisser** [comment]
I think we do sent mails for chat messages. This is in the Digest (i believe). 
Adding organization names to the chat seems like a quickfix
for the automatic message maybe adding a label? like 'Systeembericht: '

**Comment by jamalv** [comment]
@maxvisser 

1. With what frequency do we send the mail? And can we verify that this is included in digest?
2. Agreed! Very good idea! @maxvisser could you plan this in?
3. Yes, I think that's a good idea, maybe mock something up in figma?

@maxvisser what do you think? should we split this one up into 3 cr's?

**Comment by maxvisser** [comment]
yes would help with tracking them

**Comment by maxvisser** [comment]
Planned showing organization name in product chat messages modal

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/96221701-48babb00-0f8b-11eb-955e-726a41697e27.png)
zoiets?

**Comment by maxvisser** [comment]
> @maxvisser
> 
> 1. With what frequency do we send the mail? And can we verify that this is included in digest?
> 2. Agreed! Very good idea! @maxvisser could you plan this in?
> 3. Yes, I think that's a good idea, maybe mock something up in figma?
> 
> @maxvisser what do you think? should we split this one up into 3 cr's?

Every day we sent the digest.

**Comment by jamalv** [comment]
> ![image](https://user-images.githubusercontent.com/10818702/96221701-48babb00-0f8b-11eb-955e-726a41697e27.png)
> zoiets?

Yeaa, that's fine, could still add it in figma and let Alex / lena look at it and add like a "bot" icon or something.
