### ISSUE TITLE
Sponsor wants to inform users about offers/actions.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#526]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** C1

### Change description
Sponsor wants to have a possibility to inform their citizens about offers and funds.
Currently the platform sends information to the user by email digest and automatic emails. The desire of the sponsor is that they can inform the user pro actively. So they need the users their mail addresses to make this possible.

**Additional information**
From what I understand their was something being said about they can call Support to get a list of all the e-mails? This was not option for Groningen (and shouldn't be For Us <- see what I did there). Groningen wants a solution in the platform self and not be depended of us, they said this was already mentioned before that the option that we create an export for e-mails was not a option

**Comment by maxvisser** [comment]
Implementing a way to show all vouchers in generator where e-mailadresses can be exported

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/521

**Comment by jamalv** [comment]
@maxvisser as discussed on monday the plan is to include this in release .15 by adding to the voucher generator. Is this still the plan?

**Comment by maxvisser** [comment]
Yes

**Comment by maxvisser** [comment]
Also discussed this with Gerben he sees no problems with current implementations only benefits

**Comment by jamalv** [comment]
released in .15

**Comment by maartenfv** [comment]
@jamalv @maxvisser Could you add the Figma link?
