### ISSUE TITLE
Sponsor dashboard: Improve start action modal

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#527]
Learn more about change requests here: https://bit.ly/39CWeEE

Figma: https://www.figma.com/file/1wtD8IclpZ6OLJzduOHpit/Sponsor-dashboard-Improve-start-action-modal?node-id=1%3A80

### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** E5

### Change description
The modal of starting an action is way to confusing. During acceptance testing we couldn't even explain what all the things meant and how to use it.

1. Way to much information in the modal, to overwhelming.
2. Labels above the input fields are unclear (example: **bijdrage**: unclear whose contribution it's about)
3. The prices that are displayed are also confusing (example: **Prijs vanuit aanbieders**: we should not display the price after the contribution of the provider. We should display how much the provider is contributing)
4.  Maak gratis: this is effectively just a full contribution of the remaining price. That's not clear in this modal.

**Possible solutions for the labels above the input fields**:
Don't use words as labels but use sentences and questions.

**Current:**
<img width="999" alt="Screen Shot 2020-10-12 at 11 13 37" src="https://user-images.githubusercontent.com/38419514/95729617-69c69780-0c7d-11eb-93dc-2c6a82dbfa38.png">

**Proposal** (just an idea/ proposal of how it could be more clear.)
<img width="754" alt="Screen Shot 2020-10-12 at 11 40 22" src="https://user-images.githubusercontent.com/38419514/95731572-fc683600-0c7f-11eb-8fa1-2c21f134a5ae.png">

**Comment by GerbenBosschieter** [comment]
I think it also better to show the inputs fields a first and the prices as last.  Because the prices are the result/concussion of what the things you give up on the input fields.

**Comment by maxvisser** [comment]
Should be added as a proposal in Figma.

**Comment by maxvisser** [comment]
Like your proposal gerben; I would maybe move the product title and organization_name and some of the product details to the left column

![image](https://user-images.githubusercontent.com/10818702/95736641-c67a8000-0c86-11eb-8b17-c2fd49a5bd55.png)

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/531

**Comment by jamalv** [comment]
@maxvisser I have added this to figma: https://www.figma.com/file/1wtD8IclpZ6OLJzduOHpit/Sponsor-dashboard-Improve-start-action-modal?node-id=2%3A172

Could you plan a design review by alex / dan, I think they'll be able to improve it further :)

**Comment by maxvisser** [comment]
Could you add this to the proposal issue?; For viewing the action details of a running action and one which was stopped should also be changed.

**Comment by jamalv** [comment]
done

**Comment by maxvisser** [comment]
Were did you put it?
Current modal looks like:
![image](https://user-images.githubusercontent.com/10818702/97018636-acc31d80-154f-11eb-8bb5-86af2b7005aa.png)

**Comment by maartenfv** [comment]
What is the status of this issue? When will it be released?

**Comment by jamalv** [comment]
## New status (will be released in .16 on monday):
<img width="1006" alt="Screenshot 2020-11-14 at 13 59 35" src="https://user-images.githubusercontent.com/30194799/99147490-a4a75b00-2681-11eb-982f-bb334dedd9c9.png">

There's still an issue with it though: https://github.com/teamforus/general/issues/573

**Comment by maartenfv** [comment]
What is the status on this issue? Have we considered @danrminds comment? "This is a wrong approach on the photo. Not all images can be zoomed in like this - and nothing will be visible on the image if you zoom it. Most of images are landscaped, preview here is verticalВведите сообщение""

Further more the input fields are super wide and it seems people are nog gonna create a trillion "acties"

**Comment by jamalv** [comment]
Yea, that comment from dan was on an older design that still had a very tall image, this design has been reviewed by sashoa

**Comment by jamalv** [comment]
haha, and about super wide input fields, that's true, could be made smaller, not sure how @danrminds looks at that?

**Comment by maartenfv** [comment]
Placed this in sprint 47+48 to be rechecked.

**Comment by jamalv** [comment]
Note, Included in that check needs to be #573
