### ISSUE TITLE
Product and provider name are switch around if you switch the view, we should align them.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#528]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** B2

### Change description
This is about the products page:
- List view: product name is above the organization name
- Image view: organization name is above the product name

 We should align this. My proposal is:
Organization name above product name (so image view)

**Example**
<img width="713" alt="Screen Shot 2020-10-12 at 11 56 24" src="https://user-images.githubusercontent.com/38419514/95733439-6bdf2500-0c82-11eb-919c-1e457e54a405.png">
<img width="717" alt="Screen Shot 2020-10-12 at 11 56 16" src="https://user-images.githubusercontent.com/38419514/95733443-6e417f00-0c82-11eb-9c37-aba582236a2c.png">

**Comment by maxvisser** [comment]
Hah nice find 👍 Easy fix

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/515

**Comment by jamalv** [comment]
@maxvisser could you create the task (for @SjoerdHilhorst?) - branch from master?

**Comment by maxvisser** [comment]
this is already as a PR to develop; needs refactoring from alex

**Comment by jamalv** [comment]
fixed, will be released monday
