### ISSUE TITLE
CR: Move button destroy sessions to top of page

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#529]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
~~- Sessions page is too difficult for inwoner, suggestion is to remove the page entirely.~~
If this is not feasible we can do some other things to improve the page
- Move beeindig alle sessies to top of page
- Add warning modal when clicking beeindig alle sessies: "Je wordt nu uitgelogd op alle apparaten, wil je doorgaan?"

**Comment by maxvisser** [comment]
currently removed from menu. I think for support it will be nice to have it still in the smaller menu.

**Comment by SjoerdHilhorst** [comment]
https://github.com/teamforus/implementation/issues/509

**Comment by maxvisser** [comment]
adding a warning modal is pretty smart.

**Comment by jamalv** [comment]
I would opt to keep the page as this is a useful security feature, I fully agree with the UX improvements though. Approval is on:
- [ ] Move beëindig alle sessies to top of page
- [ ] Add warning modal when clicking beëindig alle sessies: "Je wordt nu uitgelogd op alle apparaten, wil je doorgaan?"

I edited the original issue to strike-trough the suggestion to remove the page.

**Comment by maxvisser** [comment]
The modal is already planned and being worked on. For moving the button I would like to change the figma prototype first.

**Comment by maxvisser** [comment]
Just a remark: I think during the demo we showed a account with alot of sessions. Most accounts will have one or two.

**Comment by maxvisser** [comment]
[Uploading... image.png ]

**Comment by maxvisser** [comment]
Conclusion popup has been added. Pagination is overkill as not alot of users will have 20 sessions; If would introduce pagination we should probably do still 15 or 20 per page. Moving the button to the top would result in more people clicking it. If they do it unintentionally it will log them out from all devices. (which can result in bad UX)
