### ISSUE TITLE
Change request: Transaction details are hidden

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#530]
**Support Ticket ID:** [#1912]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Provider

### Change description
- Transaction details are hidden<br>
Could we add some visual element that shows us that we can click on the transaction for more details?

**Comment by GerbenBosschieter** [comment]
Adding a carrot (arrow) or a just the details on the right side of the card should do the job.

<img width="915" alt="Screen Shot 2020-10-12 at 15 40 57" src="https://user-images.githubusercontent.com/38419514/95753106-647b4400-0ca1-11eb-92a2-bad741802e02.png">

**Comment by jamalv** [comment]
@SjoerdHilhorst, maybe this is a nice one for you?
