### ISSUE TITLE
CR: Notifications on Dashboard should link to pages

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#531]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
- When receiving a notification on the dashboard, a user should be able to click on the notification to link him to the product/employee/fund/etc

**Comment by maxvisser** [comment]
Added scope big. Not an easy fix

**Comment by jamalv** [comment]
Yea, this is an awesome feature request! Putting this on hold since the scope is too big though, issue needs to be funded to be able to proceed. @maxvisser I would be interested in an hour-estimation for this scope, could you discuss this with the team?
