### ISSUE TITLE
CR: "Uitschrijven voor notificaties" to "Notificaties beheren"

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#532]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
- change "Uitschrijven voor notificaties" to "Notificaties beheren"

**Comment by maxvisser** [comment]
Currently changed to same text as in dropdown 'Notificatievoorkeuren'

**Comment by maartenfv** [comment]
Has this issue been processed?

**Comment by maxvisser** [comment]
its like I commented?
