### ISSUE TITLE
Stadjerspas webshop: Hardcoded link in footer for Bezoekadressen en openingstijden

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#535]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Seems like a hardcoded link to old website of stadjerspas is added to the footer.

To this page:
https://stadjerspas.nl/pagina/bezoekadressen-en-openingstijden

Probably should add this to our website or implement something else?

**Comment by jamalv** [comment]
Let's update the link to: https://wij.groningen.nl/
