### ISSUE TITLE
Discord profile picture: Demy

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#536]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a Jamal I would like a Demy to have a profile picture so that I feel a more personal connection.

**Comment by jamalv** [comment]
Oh, and while we're at it, let's also go for github 🚀

**Comment by jamalv** [comment]
@maxvisser could you rate this on scope?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/95979249-a4663680-0e1b-11eb-9fa7-da26fde81bbf.png)

**Comment by maxvisser** [comment]
added a profile picture on google

**Comment by maxvisser** [comment]
seems pretty doable. as it was pretty easy for me to do on Google

**Comment by demylubbers** [comment]
Issue has been solved. Added a filter

**Comment by jamalv** [comment]
great job guys! happy stakeholder here!

**Comment by jamalv** [comment]
I think this was the quickest solved issue so far btw
