### ISSUE TITLE
New label - [Status: Question]

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#537]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Add a new label:

## Status
label | color |  description
-- | -- | --
Status: Question | Color: #0e616b | The issue is blocked by one or more questions

I'm not sure about the current status of labeling policies, but I understand there is some weight about adding new labels 😄 

I would like to add the "question" label as it is very useful during refinement and when going trough issues to plan them (picked this up at the lungfund project). This way it's easy to see for what issues there are open questions and where it's necessary to hunt for answers :)

**Comment by maxvisser** [comment]
With the new Github function called 'Discussions' probably all questions/discussion can utilize this (issues can be tasks)

**Comment by jamalv** [comment]
The main reason for adding this is that issues can often not be planned since there are still questions; having an overview of issues that are blocked for that reason can be very useful IMO

**Comment by maxvisser** [comment]
Ah I read it as 'Type: Question'; Maybe rename it to 'Status: Needs clarification' or 'Status: Needs brainstorm'; I find 'Status: Question' not really descriptive.

**Comment by jamalv** [comment]
I do like to focus on the question status; the clearification / brainstorm is to answer the question(s). So I would say that the status is: There is currently a question, and yea, the way to solve the question is with a brainstorm or clearification from the stakeholder :)

**Comment by maxvisser** [comment]
Maybe add blocked? Status: Blocked by questions

**Comment by jamalv** [comment]
Yea that would be good for me 👍

**Comment by maxvisser** [comment]
seems to be added; will close this one
