### ISSUE TITLE
Opt-in to sharing your personal info with sponsors

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#539]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a requester I would like to opt-in to sharing my e-mailadres/voucher with the sponsor of a fund.
As a requester I would like an overview of which sponsors (/organisations) can see my e-mailadres.

If this setting is turned on, your e-mailadres will be in the list of vouchers on the voucher generator, if this setting is turned off, your e-mailadres will be hidden (like before).

**Comment by jamalv** [comment]
Related to: https://github.com/teamforus/general/issues/538

**Comment by jamalv** [comment]
## Add step to signupflow:

### Share your e-mailadres

You can choose to share your e-mailadres with [organisation name], this allows the organisation to send you newsletters, to contact you and to offer you better support. You can opt-out of this at any time via your preferences.

- [ ] I would like to share my e-mailadres with [organisation name]

**Comment by maxvisser** [comment]
Seems to be a duplicate of #334
