### ISSUE TITLE
CMS: editing texts, adding images/videos to webshop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#54]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Current situation
Every webshop implementation requires customisation. This has different perspectives: technical, and content-wise. This CMS is about trying to solve implementation bottlenecks while being able to fulfil customers need more quickly and flexible by allowing them to edit content themselves.

### Texts and images:
Right now, texts and images are not adjustable by the customer. We need to do a release for each textual update, requiring a lot of coordination. 

### Configuration:
Right now, configuration needs to happen manually in the database, therefore it needs to always happen on a monday morning, requiring a lot of coordination and creating some risks.

## Desired situation
The most important elements of the implementation; text, images, video's and configuration, should be editable from a dashboard. We will start with a small and desired scope, and work from there to make the CMS fit the customer needs, starting with the possibility to add their own texts images and video's

## Plan
We will implement the CMS in two itterations.

### First itteration
[View the explainer video](https://drive.google.com/a/forus.io/file/d/1QHlK88VMi9mkk4AygRArdCQEPW9aIceD/view?usp=sharing) | [ View the figma prototype](https://www.figma.com/file/N3p59HvuJoKr7RgT5AYAVW/CMS?node-id=1731%3A67856)

### First iteration: 
[View the explainer video](https://drive.google.com/a/forus.io/file/d/1ANYsr_Ma2ps_DRb59kXeUTgKlLJ1y7z5/view?usp=sharing) | [ View the figma prototype](https://www.figma.com/file/N3p59HvuJoKr7RgT5AYAVW/CMS?node-id=1732%3A71922)

Dependancy: #87

**Comment by maartenfv** [comment]
https://www.figma.com/file/N3p59HvuJoKr7RgT5AYAVW/CMS?node-id=751%3A794

**Comment by maxvisser** [comment]
21 april call with dan:
- Dan showed me some CMS systems RMinds has built and his vision on what a CMS should contain.
- I explained the process of setting up an implementation, difficulties with it and what steps I take to set a implementation live.
- Talked about how an CMS could be implemented on Forus. As alot of the resources and content is on github everything needs to be ported to the database. As we need to port everything this will be a big epic.
- Talked with Dan about an MVP of an CMS where only the homepage is changable. He agreed this should be doable with current code:
	- a homepage changer where you can drag & drop blocks
	- a page where you can add new FAQ questions

- As we don't know what municipalities want to change after an implementation is live; As you don't want to build a CMS for one time use.

Concluding:
decided on a small mvp to get the ball roling on this IP development wise; scope is currently really small: just changing the title and subtitle. 

Concrete tasks:
- Dan will check MVP with valentin
- Alex will build MVP

**Comment by GerbenBosschieter** [comment]
- A homepage changer where you can drag & drop blocks (I don't like this idea at all, editing content, images, some basic css as color or border-radius ). Don't let them change the structure of the page. This will not help for WCAG stuff (for example tex to speech reads html, not css, it think).

- There are some municipalities who want this, I think we should discuss this with them before weven starting development. So we can manage expectations.

**Comment by GerbenBosschieter** [comment]
Discussed CSM with Dan during refinement.

**MVP**
- Keep it really simple by starting with the proposal in figma (title and header and some configuration stuff)
- Iterate on the MVP by adding elements that municipalities will probably change over time (so this mean we should exclude CSS elements for now)
    - Example: faq, credentitals, other text element 

Figma also has some proposals from Linda with a bigger scope.
I think we should keep the discussion for the bigger scope on hold and include all feedback and wishes we will get from implementing the MVP to this discussion so we can slowly work and refine the bigger scope.

**Comment by maxvisser** [comment]
Agree on all points with gerben/dan. Lets just start with an mvp and refine the bigger scope.

**Comment by jamalv** [comment]
Update; I've had discussions about this with many stakeholders at this point and think we've come to a good scope. I will work on improving the IP until it can be turned into an epic.

**Comment by maxvisser** [comment]
I think the scope was already defined? and talked through with multiple people; do you want to do that all again?

**Comment by jamalv** [comment]
Ah nice! Yea, i just wanted to help finalize it and add it in two iterations. I've added a video to the original issue about the first itteration, working on a video for the second itteration now :) 

Let me know if it fits the picture you had or if we need to adjust course 👍

**Comment by maxvisser** [comment]
Yes I see  you added a new page to the webshop menu but there is of course no room for more menu items: https://github.com/teamforus/general/issues/87

**Comment by jamalv** [comment]
@danrminds @maxvisser I have updated the original issue with figma prototypes and explainer video's. Could you look at that and #87 see if you can approve the IP like this? If it is approved that means the next step is to change the type to epic and create and plan the tasks in Forus.

Who of you can create the tasks after approval? @maxvisser or @danrminds?

**Comment by jamalv** [comment]
After approval I think the first step is to move the figma file from proposals to prototypes. Then A designer should review it. When the final design is approved, it can be moved to pull requests and handed off to the developers.

**Comment by maxvisser** [comment]
I would first work on #87 if you want to add more to the menu of the webshop or just leave the explanation page out of this IP; as their is no room for it in the menu I suspect it would be hard to merge it with develop;

No go

**Comment by jamalv** [comment]
Some nice work has been done on #87. I think the next step is designer review (move from proposal to prototype in figma) and then it can be converted into an epic an move into the development pipeline.

@maxvisser what do you think?

**Comment by maxvisser** [comment]
Discussed #87 and dan did not like it. He said he will make some proposals with alex soon.

Also I see dan reviewed this IP with alex. I am not sure about landing the user on a edit page. Also you can't see anymore which funds are attached to the implementation. Comment in figma: https://www.figma.com/file/N3p59HvuJoKr7RgT5AYAVW?node-id=1731:68019#25668769

**Comment by maxvisser** [comment]
Jamal and me had a discussing about #87 we decided to extend the breakpoint to 1280 (instead of 1024) as a quick fix.

we will add 'info' to all menu's

**Comment by maartenfv** [comment]
@jamalv @maxvisser @linda-90 @danrminds Could we include this issue in the CMS? https://github.com/teamforus/general/issues/220

**Comment by jamalv** [comment]
Yea, I think that would be a great addition; let's first keep the discussion about it focussed on issue #220: It will be nice to first finish and release the scope of the MVP to production, and to then add #220 as a seperate update, since that one still needs prototyping etc, and this is already in code. 🚀

**Comment by maxvisser** [comment]
Yes this epic will be closed if https://github.com/teamforus/forus-frontend/pull/1157 is on production (as I see it) so Pretty URLS will not be included (maybe later as it is a good idea)

**Comment by maartenfv** [comment]
@maxvisser Oke, but how will we proceed? What are we going to do with the issue besides closing it?

**Comment by linda-90** [comment]
Wat is de status van deze issue?
@jamalv @maxvisser

**Comment by maxvisser** [comment]
Its on production https://blog.forus.io/2020/06/webshop-instellingen.html So we can close this issue.

**Comment by maartenfv** [comment]
@linda-90 Staat ook op staging. Kunnen we dit laten zien aan Leonie en Paul?

**Comment by maxvisser** [comment]
can be communicated to users. please close when done.

**Comment by jamalv** [comment]
This is live with end users: https://blog.forus.io/2020/06/webshop-instellingen.html

**Comment by jamalv** [comment]
@maartenfv @linda-90 this is stuck in the step "tell our users" when can we close this?

**Comment by maxvisser** [comment]
Had a discussion with @maartenfv about tell our users. If it is on the blog we can mark these now as closed.
