### ISSUE TITLE
Actions (mobile ready)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#552]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
As some screens are not mobile ready. We already did some design work for actions:
https://www.figma.com/file/muiPmndPxYtpv8iFnqKXsL/?node-id=0%3A1

**Comment by jamalv** [comment]
@maxvisser what is the status of this? Can it be planned?

**Comment by jamalv** [comment]
A design was made, was not implemented yet

Frontpage still looks weird, and details page on product

@danrminds could you create a task for this in forus (you can use the "move issue" command in github :))

**Comment by maxvisser** [comment]
product page and block on frontpage are adjusted. product page is already approved. Action block on frontpage needs some refactoring
