### ISSUE TITLE
We need a Thank you page for surveys

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#554]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- We are making some progress met our surveys. We currenlty setup all surveys for the stakeholders and can already host it on our own domain. If a user is done with a survey they will be redirected to a thank you page of a third party. We can redirect this to or own thank you page on the website but we don't have one.

<img width="641" alt="Screen Shot 2020-10-23 at 15 36 35" src="https://user-images.githubusercontent.com/38419514/97013529-71bdeb80-1549-11eb-9380-9ead7691994c.png">

Figma: https://www.figma.com/file/neEidaBeA5hA8u5Nkj2YC9/Website---Thank-you-page?node-id=0%3A1

**Comment by maxvisser** [comment]
I  suggest a check mark as SVG

**Comment by GerbenBosschieter** [comment]
What about this @maxvisser 

<img width="1016" alt="Screen Shot 2020-10-23 at 16 45 21" src="https://user-images.githubusercontent.com/38419514/97018297-463dff80-154f-11eb-8cb0-bfd8b4529481.png">

**Comment by maxvisser** [comment]
Thank you

**Comment by maxvisser** [comment]
Lets add it to the website as a page?

**Comment by GerbenBosschieter** [comment]
@maxvisser thats what I also thought. It is only text and  a CSV. So easy to maintain and fix with variables per implementation. We could also create like a widget on the webshop itself so people can start the survey from the webshop itself

**Comment by maxvisser** [comment]
@MichaelForus is this stil needed?
