### ISSUE TITLE
Flexible linking of funds to webshops

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#557]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Not yet requested, but I expect it will be relevant (maybe critical) for at least 2 projects

### Change description
As an implementation holder I would like to flexibly be able to turn on / off funds for my webshop.

E.g. Municipality Y has funds Y and Z on "Webshop 1", they want to create a new fund X > it does not make sense on "webshop 1" > so they want to make a new webshop "Webshop 2" > where they would like **all** the funds on this new webshop, while also keeping the old webshop online. 

This is relevant in situations where there is a consideration for "moving" from one webshop to another (project-31 and -100) - the goal is to be able to have the same fund on multiple implementations / webshops.

**Comment by maxvisser** [comment]
current state:
webshops do not have an owner
funds can be configured to one webshop only.
