### ISSUE TITLE
CR: Add possibility to require home visit "huisbezoek" as a criteria.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#558]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Stichting Leergeld
- Gemeente Westerkwartier

### Change description
- Stichting Leergeld has as one of their criteria that they want to have a personal visit.
- During the application for a fund the applier needs to prove there was a home visit.
- Request is to adapt and optimize the flow of applying for a fund including this step.
- Making sure the volunteer validates the home visit of the citizen.

**Comment by maxvisser** [comment]
probably this should a special criteria which basically you should already have before you can digitally apply.
