### ISSUE TITLE
CR: Update angular

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#559]
Learn more about change requests here: https://bit.ly/39CWeEE

### Change description
Update to the newest version of angular or similar framework (React) or something else

**Comment by GerbenBosschieter** [comment]
<img src="https://user-images.githubusercontent.com/38419514/99324549-d3d1ee00-2874-11eb-9388-28de9c58ad9b.jpg" width='50%'>

**Comment by maxvisser** [comment]
would start with webshop; would probably take two sprints; Scope increases with each webshop we add. I think especially the testing part is alot of work
