### ISSUE TITLE
Change request: Sponser would like to have a "grace period" on vouchers.

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#560]
**Support Ticket ID:** [#2079]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

### Change description
- Sponser would like to have a "grace period" on vouchers.
- for example: first end date on January 1 (communicate to requesters) and second (hard) end date on January 14.

**Comment by maxvisser** [comment]
should decide on timeframe of grace period.
example expire date is 14 january. 
sponsor checks a checkbox on fund config of grace period
januari - grace period is 1 januari

questions
- do we want to hardcode the time frame or should user be able to set an amount of days
- where to show this date; (me-app, e-mails, printables i guess)
- for example end date is 14 of januari. Our system works with expire dates as 'till' so vouchers scanned on 14 of januari are not included. if for example the grace period is 14 days. The new date communicated could become 31 december; We should write some example expire dates and grace periods.

**Comment by maartenfv** [comment]
Make this configurable by Sponsor when creating a fund.
This is not visible for users only the sponsor knows.
Standard can be 3 days.

**Comment by jamalv** [comment]
Added as an insight to productboard: https://app.productboard.com/inbox/notes/18632051
