### ISSUE TITLE
Me records privacy

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#561]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a user I would like to be informed about my privacy in the me app.

Figma: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=1%3A80

**Comment by maxvisser** [comment]
Nice IP. The only change I would make is not hide it behind a little i icon; I would change the i icon to the word 'Privacy'

**Comment by maxvisser** [comment]
I would also suggest adding Privacy aswell as an item to profile page.
