### ISSUE TITLE
Me Actions: Amount paid

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#562]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Max

### Change description
As a provider I would like to understand the pricing structure with actions.

Figma: https://www.figma.com/file/OL6X0AUnpbiP8TX5dq1mU9/?node-id=1%3A2

**Comment by maxvisser** [comment]
proposal can be checked.

**Comment by jamalv** [comment]
Proposal is approved

**Comment by Myshelova** [comment]
What the difference between these tasks? https://github.com/teamforus/me/issues/511 
Can you give a clear context of features data that we need to explore?

**Comment by maxvisser** [comment]
This is the epic which stays open until it released; teamforus/me#511 is your task to design review the proposal 👍 ; not sure why Jamal has assigned you here
