### ISSUE TITLE
Top up: view incoming transactions

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#564]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As a sponsor I would like to see when top up's have been done to the connected bunq account so that I can see when the top-up functionality has been used.

## Current state:
<img width="987" alt="Screenshot 2020-11-03 at 10 39 58" src="https://user-images.githubusercontent.com/30194799/97969896-fb2eb280-1dc0-11eb-9de8-b8e484cf6ba8.png">

## Proposed state:
<img width="573" alt="Screenshot 2020-11-03 at 10 56 16" src="https://user-images.githubusercontent.com/30194799/97971392-39c56c80-1dc3-11eb-847e-394a9a371193.png">

Figma: https://www.figma.com/file/Eu1PsVbVszdj0C5U7gaioe/Top-up-view-incoming-transactions?node-id=1%3A1048

**Comment by maxvisser** [comment]
currently how this works:
user retrieves topup code from modal
send money to BUNQ account
Forus polls transactions list for new transaction with topupcode
add its to topup transactions.

If we just want to show the transaction this needs a proposal / design etc. api routes needs to be exposed to retrieve transactions. Probably scope is small to medium

**Comment by jamalv** [comment]
@maxvisser I added screenshots, what do you think? Maybe this could be a task for @SjoerdHilhorst?

**Comment by maxvisser** [comment]
Topups and voucher transactions are two completely different things. showing it in one table will be pretty hard job; probably not something sjoerd can already do ;)

**Comment by maartenfv** [comment]
I would really like for Sjoerd to try this. If he gets stuck we can help him out?

**Comment by maxvisser** [comment]
I am also not experienced enough to help him with it; he could of course make the proposal easier to build (seperate screens for example)

**Comment by maartenfv** [comment]
Should we ask Dan/Valentin if they are willing to help maybe? for support if Sjoerd gets stuck?

**Comment by maxvisser** [comment]
Lets discuss maybe with Sjoerd/Valentin not sure what the best approach is here.

**Comment by SjoerdHilhorst** [comment]
@maxvisser why wouldn't it be possible to show it in one table? Both transactions affect the same fund right?

**Comment by maxvisser** [comment]
One page shows all voucher_transactions; what this is about its about fund_topup_transactions (or you a completely new entity.

**Comment by maxvisser** [comment]
Its not that its impossible but you need to merge data tables. Aswell as the transaction overview is shown on both provider and sponsor dashboard; so you need to make a seperate pug file for both (split it and stop reusing the same HTML);
