### ISSUE TITLE
Pipeline proposal: Improving the release cycle by depreciating the develop branch

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#569]
## Goal
We want to release features faster to production. 

## Problem
Features have gotten stuck on develop. There’s conflicts in the process, releases have been blocked.

# Proposal
## Branches
There are 4 types of branches:

master
release/xxxx
feature/xxxx
hotfix/xxxx

## Environments
There are 4 environments (no change):

Local
Develop
Staging
Production

## Proces
The new process is as follows:

### Release
After a release, a branch for the new release is created right away.
E.g: right after the branch release/v0.19 is released, release/v.20 is created.

### Development
When a developer starts work, they branch from **master** and create a feature branch.
When the feature branch is ready for review, the developer opens a **draft** pull request.

## Review
The reviewer builds the **feature branch** directly onto the **dev environment** or into a **dev build**.
Work is reviewed, commits are added to the **feature branch** until the feature is ready for release.

To summarise: the dev environment is used to review **separate** feature branches, not one “develop” branch.

## Staging
The current release branch is merged back into the feature branch, and is tested by the developer for compatibility.
When the feature branch is ready for release and includes the merge back release branch, the draft pull request is changed into a normal PR.

## Merging
The reviewer does a final check on the **feature** branch (which includes the current **release** branch).
Final decision is made to include this feature (or fix) into the current release, stakeholders can be informed.

Reviewer merges feature branch into the release branch and closes + deletes the feature branch.
Developer also deletes the feature branch from their system after it is in the release.

## Acceptance and release
When the scope of the release branch is good, a pull request from the release branch to master is made.
Staging is acceptance tested. Review on the release is on the PR: release to master.
If **urgent** fixes are needed, they are done on the release branch (read more about fixes below).

## Release
First a PR is opened from master to the release branch. Any hot fixes will be merged into the release.
The release branch is merged to master, and deployed.
A new release branch is created from master immediately, proces starts from the top.

## Fixes
Fixes are changes that don't influence the scope but are crucial for QA: crashes, typo's, etc..

### Fixes on a release
Fixes on the release, are merged directly to the release branch and deployed to staging.
To create a fix, branch from the release and create: release/v0.x.fix
After the fix is merged, the branch should be deleted.

### Hotfix on production
If there's an issue on production, a hot fix will be made directly from master. 
The hot fix branch is put directly on staging, if the fix works, it is deployed.

**Comment by maxvisser** [comment]
Don't see the benefits of dropping the develop branch; I do see benefits of branch of master more often. If you have big features for example actions or external validators you basically will have a alot of merge conflicts if you start smaller features from master which touch the same files.
