### ISSUE TITLE
CR: Logo Noordoostpolder and GRO looks distorted in IE

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#572]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen en Nop

### Change description

Logo Noordoostpolder looks distorted in IE:
![nop-logo-ie](https://user-images.githubusercontent.com/36952230/98991165-c1ca1580-252b-11eb-9e37-02969411f706.png)

How it should look like:
<img width="368" alt="Schermafbeelding 2020-11-12 om 21 18 54" src="https://user-images.githubusercontent.com/36952230/98991841-b2979780-252c-11eb-94c8-9f8fff8f6f98.png">

**Comment by maartenfv** [comment]
Has an impact on multiple webshops not just NOP

**Comment by maxvisser** [comment]
Correct Stadjerspas aswell. Gerben has commented this in the task; this one should be done this sprint.

**Comment by maartenfv** [comment]
@maxvisser Can you add a release?

**Comment by maartenfv** [comment]
@jamalv can you please add release?
