### ISSUE TITLE
Unlimited availability for an action

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#573]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a sponsor I want to be able to set unlimited actions. For example; if I am not sponsering any amount, I might not care how may times a user uses it.

<img width="702" alt="Screenshot 2020-11-14 at 12 25 28" src="https://user-images.githubusercontent.com/30194799/99146203-4de85400-2676-11eb-9c41-328e03a241ca.png">

**Comment by jamalv** [comment]
suggestion: unlimited should have a checkbox

**Comment by maxvisser** [comment]
Needs backend changes aswell. Currently you need to set a limit for both stock and limit per person. Why is this critical?

**Comment by maxvisser** [comment]
Scope is small/medium

**Comment by jamalv** [comment]
If the cinema says; you can get a ticket for 4 euro's if you have a "stadjerspas" and the sponsor says; cool: I'll approve this action but will contribute nothing. 

Then the action can be used an unlimited amount of times, right? - It would be (too) weird if the sponsor has to think of an arbitrary number, like: you can go to the cinema 10 times?

**Comment by maxvisser** [comment]
Implemented but pretty hacky. If you check the box it  will sent 999999 to the backend. Probably we need backend functionality to fully support this. Depends on the desirability and scope. I think it will increase the complexity. @jamalv what do you think about this?
