### ISSUE TITLE
Sign up for citizen Text is double one needs to be removed.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#574]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen

### Change description

Text is double one needs to be removed.

![image](https://user-images.githubusercontent.com/30211022/99147594-8d1ca200-2682-11eb-812f-4ba4acd99f7b.png)

**Comment by maxvisser** [comment]
This is removed on the same branch were I added the checkbox for privacy. Currently a pr to develop and on staging for acceptance testing
