### ISSUE TITLE
Link from action page to action QR code

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#575]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
User (tester)

### Change description
As a requester i would like to go directly from an actions page to an actions voucher (should be a clear button) - right now I get stuck on the page.

<img width="1352" alt="Screenshot 2020-11-14 at 14 14 45" src="https://user-images.githubusercontent.com/30194799/99147773-e6d19c00-2683-11eb-8b6c-bcc8fc42fceb.png">

**Comment by maxvisser** [comment]
Currently as a PR to develop; I have put in on staging for acceptance testing

**Comment by maxvisser** [comment]
This is only implemented for Groningen. The button opens the first instance of any vouchers you have of that fund. So if you have two stadjerspas (for any reason) you will open the first one.
