### ISSUE TITLE
Add check box and link to privacy statement to sign up page. Adjustable page needs to be made where we can place the statement text.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#576]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen, Gemeente Westerkwartier

### Change description

Goal: Every user that signs up needs to check this box and needs to be able to read the privacy statement.

We should add :

- [ ] an agree to the privacy statement check box.
- [ ] sentence with a link to privacy statement page
- [ ] A stop if someone tries to proceed without checking the box.
- [ ] A reminder if someone tries to proceed without checking the box. "Ga akkoord met de voorwaarden om verder te gaan"
- [ ] develop a privacy statement page
- [ ] Add text to privacy statement page.

Proposal made by Jamal:
![image](https://user-images.githubusercontent.com/30211022/99147776-eb965000-2683-11eb-958a-0b2ebcfa4ea2.png)

- [ ] This change needs a Figma mock-up @jamalv (can we add the link to this prototype)
- [ ] This change needs a better design @Myshelova  (it is cluttered now needs some more spacing)
- [ ] This change needs a text review @linda-90  (please check the wording of the Figma prototype and the text in the statement)
- [ ] This change needs a plan for the setting up the page. @maxvisser (v1 = fix for Groningen, v2 is making sure it works for WK as well and van be re-used for every implementation)
- [ ] Need to communicate this to dev. Who will make this page and link? @maxvisser @danrminds 

If anyone has a question or does not know how to proceed please let me know asap. This is an urgent issue. We can not go live with Groningen without fixing this step.

### Relevant issues:
- https://github.com/teamforus/implementation/issues/583
- https://github.com/teamforus/general/issues/79 

@linda-90 please add the text (privacy statement) that was checked with Groningen.

**Comment by linda-90** [comment]
**Text:**

**Gebruik van mijn gegevens** 

De volgende gegevens worden opgeslagen: 

Jouw e-mailadres 
Om uw jouw account aan te maken en toegang te geven tot jouw Stadjerspas tegoed. 
 
Jouw BSN 
Om te controleren wie je bent en om dubbele toekenningen te voorkomen. 
 
Jouw inkomensgegevens 
Om te kijken controleren of jij recht hebt op de Stadjerspas. 
 
Jouw aantal kinderen 
Om te kijken of jouw kind(eren) recht hebben op de Stadjerspas Jeugd. 
 
Jouw Stadjerspas uitgaven 
Zodat je kunt zien wat je hebt gebruikt van de Stadjerspas. De aanbieders en gemeente zien ook wat er is gebruikt, maar ze zien niet dat jij dit hebt gebruikt. 

Ontvang informatie over jouw Stadjerspas 
Je ontvangt berichten over wat je hebt gebruikt van de Stadjerspas en de acties van aanbieders waar je uit kunt kiezen. Je kunt dit na de aanvraag zelf uitzetten in de notificatie voorkeuren als je inlogt op de website.

De gegevens worden vertrouwelijk verwerkt en niet aan derden verstrekt. 

- [ ] Ik heb gelezen hoe er om wordt gegaan met mijn gegevens

**Comment by jamalv** [comment]
I would suggest to link to the public privacy statement of groningen https://gemeente.groningen.nl/privacyverklaring

I made that mockup in my screenshot tool :P Now also made a figma file: https://www.figma.com/file/LdSjP6FuPCaqM3ioDn56Kx/Privacy-statement?node-id=1%3A90

**Comment by maartenfv** [comment]
@jamalv De generieke privacy statement is niet voldoende. Het gaat juist om de speciefieke data die in het systeem wordt gezet. Ook moeten we iets zeggen over het opslaan van data en dat ze deze kunnen zien in de Me app.

**Comment by maartenfv** [comment]
"**Specifiek en zonder ambiguïteit**

Toestemming tot het verwerken van persoonsgegevens wordt altijd gegeven voor een duidelijk doel. De verantwoordelijke mag de gegevens dan ook niet voor andere doeleinden aanwenden, tenzij de nieuwe doelstelling heel dicht aanleunt bij de oorspronkelijke"

**Comment by jamalv** [comment]
Allright, text and designs for that page can be added here: https://www.figma.com/file/LdSjP6FuPCaqM3ioDn56Kx/Privacy-statement?node-id=4%3A217

**Comment by jamalv** [comment]
We can initially make a custom page and then it should indeed be added to the CMS after that.

What's the status of approval on the content of this page by stakeholders? Also, what are the expectations around when this should be live? 

As this is influencing a core step in the login for the signup for all users, we'll need to do careful acceptance testing before release, it would be a big incident if this breaks the login button in some older browsers or in some mobile browsers, for example 😉 - it could also impact other implementations. So we definitely can't rush this to production. Finally, since there will be no CMS we can't quickly update the page after it's live so having final approval on the content will help speed things up. 👍

**Comment by jamalv** [comment]
And on what places is this needed exactly?

**Comment by maxvisser** [comment]
Mag ik iemands persoonsgegevens verwerken als degene hiervoor toestemming heeft gegeven?

Nee, dat gaat in het sociaal domein vaak niet op. Toestemming is weliswaar een grondslag in de Algemene verordening gegevensbescheming (AVG), maar hiervoor gelden speciale eisen. Daaraan kunt u in het sociaal domein meestal niet voldoen.

Artikel 6 van de AVG noemt toestemming van betrokkene als een grondslag voor de verwerking van persoonsgegevens. De betrokkene is degene van wie u persoonsgegevens verwerkt.

Deze toestemming moet dan wel vrij en ondubbelzinnig zijn. Dat betekent dat betrokkenen in vrijheid hun wil moeten kunnen uiten. Ook mag er geen twijfel zijn of betrokkenen hun toestemming hebben gegeven en voor welke specifieke verwerking zij dit hebben gedaan.

Afhankelijkheidsrelatie
Bij de uitvoering van publiekrechtelijke taken in het sociaal domein is er meestal een afhankelijkheidsrelatie tussen de betrokkenen en u als gemeente. Weigeren mensen toestemming voor het verwerken van hun gegevens, dan kan dat bijvoorbeeld gevolgen hebben voor een gewenste voorziening.

Daarom is er geen sprake van vrije toestemming in de zin van de AVG. Toestemming kan dan dus niet gelden als de grondslag voor de gegevensverwerking.

https://autoriteitpersoonsgegevens.nl/nl/onderwerpen/overheid/sociaal-domein


-- 

Mijn conclusie is dus als mensen afhankelijk zijn van de regeling die ze aanvragen: een toestemming geen grondslag bied voor de verwerking. Je zou dus vooral de grondslag moeten benoemen (uitgifte van de regeling) en geen toestemming moeten vragen

**Comment by jamalv** [comment]
Ik zou de interpretatie overlaten aan (de juristen van) de gemeente, en die hierin de keuze laten maken :) Ik denk overigens niet dat mensen perse afhankelijk zijn van deze regeling, dus dit is ook wel redelijk interpretabel.

@maartenfv @linda-90 hebben we al een definitief besluit van de gemeente hierop? en @maxvisser misschien kan jij helpen door in te schatten hoe snel dit in productie kan zijn vanaf het moment dat er een besluit is?

**Comment by maxvisser** [comment]
Got it. The checkbox below the email field would be on all webshops, aswell as people can just login here. We should decide on how to implement it and after it I can decide the scope :)

**Comment by maartenfv** [comment]
@jamalv Text is door Linda in Teams van gemeente gezet en gechecked door communicatie.

**Comment by linda-90** [comment]
Gemeente wil graag tutoyeren in de communicatie, maar alle basis teksten in het systeem zijn in u-vorm.
Stel voor om u aan te houden en de teksten van de gemeente in u-vorm te zetten. Alleen de uitleg pagina op de website staat nu in je-vorm.

**Comment by maartenfv** [comment]
Opdracht om deze stap toe te voegen is gekomen vanuit gemeente. Gesprek met Menno, Paul en Leonie en Trees. Inhoud hebben ze zelf gecontroleerd.

@linda-90 Moeten er nog meer mensen naar kijken?

v1 prio: De stap moet worden geplaatst bij de aanvraag van de stadjerspas zodat alle gebruikers er langskomen. 

v2 (later) voor WK. Dit kunnen we later doen voor alle gemeenten en dan op de zelfde plek zodat iedereen er een keer langskomt.

Optioneel is om nog toe te voegen in FAQ en misschien noemen op uitleg pagina.

**Comment by jamalv** [comment]
@maartenfv yea sounds clear, so that means the scope is exactly as defined in this figma proposal?  https://www.figma.com/file/LdSjP6FuPCaqM3ioDn56Kx/?node-id=1%3A80

@maxvisser could you check feasibility of that one?

@linda-90 or @maartenfv would need to do the text review. when do you expect the other points you've listed to be done? For example design review? Can we just give these tasks to the rest of the team during sprintplanning on monday at 11 like normal? Or are there other expectations here?

**Comment by jamalv** [comment]
As in; i've seen the other (internal) issue, but initial there wasn't a clear scope so was not really possible to say anything about the timeline; if using a seperate criteria and texts in the CMS would've worked for this usecase, it could be done without design, developent, acceptance testing and release. But now we do need  now we have a scope where that's needed so we can say something about how long it will take to implement.

**Comment by maartenfv** [comment]
Plan now = Make a page, (this means for every webshop also other municipalities). Fill the one of Groningen with the text in the earlier comment. The other pages will be blank. 


Next step (will be separate issue) @linda-90 to do in coming weeks is to get content for these pages as well.

Last step (other issue) Connect those pages to CMS.

@jamalv what is missing in Figma is the text that appears when you try to click but did not check te box.

Something like "Zet een vinkje om verder te gaan"

**Comment by jamalv** [comment]
Something [like this?](https://www.figma.com/file/LdSjP6FuPCaqM3ioDn56Kx/Privacy-statement?node-id=22%3A0)

<img width="574" alt="Screenshot 2020-11-14 at 18 24 53" src="https://user-images.githubusercontent.com/30194799/99153110-b3543900-26a6-11eb-94c0-5f24a250568f.png">

**Comment by maartenfv** [comment]
Generic text for alle the webshops https://docs.google.com/document/d/1kSZM1gnXhE0injmphnArmGtgnIJhPFSoKyBBzNvPeXc/edit

**Comment by maartenfv** [comment]
@jamalv Moeten de text even checken met Linda. Want akkoord gaan mag je niet noemen in deze context hoorde ik.

**Comment by jamalv** [comment]
Have updated it:
<img width="538" alt="Screenshot 2020-11-15 at 08 38 28" src="https://user-images.githubusercontent.com/30194799/99179425-f7365500-271d-11eb-87dd-f9ba79c271b4.png">

figma: https://www.figma.com/file/LdSjP6FuPCaqM3ioDn56Kx/Privacy-statement?node-id=22%3A0

**Comment by jamalv** [comment]
> Generic text for alle the webshops [docs.google.com/document/d/1kSZM1gnXhE0injmphnArmGtgnIJhPFSoKyBBzNvPeXc/edit](https://docs.google.com/document/d/1kSZM1gnXhE0injmphnArmGtgnIJhPFSoKyBBzNvPeXc/edit)

Sweet! For reference; this is the Me app component: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=70%3A300

**Comment by maxvisser** [comment]
Implemented as a MVP for groningen; text is hardcoded and currently only visible on their webshop; Still needs to be reviewed.

**Comment by Myshelova** [comment]
Hi everyone. I've just translated the current version with dutch text on the error and made a suggestion to clarify the error of why the person should accept the privacy policy. And added to the checkmark point that person not only read but also accept our privacy policy. 
<img width="887" alt="Screenshot 2020-11-17 at 16 11 03" src="https://user-images.githubusercontent.com/22478043/99407566-88a8f100-28ef-11eb-9295-acbe36c331d1.png">
