### ISSUE TITLE
Shouldn't need to scroll to view image rights checkbox

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#577]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Probably modal should be wider or something.

<img width="830" alt="Screenshot 2020-11-14 at 14 29 09" src="https://user-images.githubusercontent.com/30194799/99148049-e0dcba80-2685-11eb-93b2-e2b537e2a43e.png">

<img width="838" alt="Screenshot 2020-11-14 at 14 29 13" src="https://user-images.githubusercontent.com/30194799/99148053-ea662280-2685-11eb-86d2-9930b7761f7e.png">

**Comment by maxvisser** [comment]
Created a task for proposal https://github.com/teamforus/forus/issues/1890 @jamalv could you check if you could write the proposal or ask lena

**Comment by jamalv** [comment]
Shouldn't make this too big for now, my only problem here is that the checkbox is not visible. You need to scroll to see it.

**Comment by maxvisser** [comment]
This is not always the case though. Only on smaller laptop screens.

**Comment by jamalv** [comment]
On my 15" macbook it is the case at 100% 🤔

**Comment by maxvisser** [comment]
@jamalv could you recheck this one?

**Comment by jamalv** [comment]
Seems good now on staging!
