### ISSUE TITLE
Remove discount percentages from financial vouchers

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#578]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Multiple stakeholders and end users

### Change description
Remove discount percentages to simplify UX for providers and make the webshop less commercial for citizens

<img width="787" alt="Screenshot 2020-11-14 at 14 32 11" src="https://user-images.githubusercontent.com/30194799/99148164-8abc4700-2686-11eb-8238-269d6d1cecf0.png">

<img width="431" alt="99148174-9dcf1700-2686-11eb-90dd-9d9dceac24fe" src="https://user-images.githubusercontent.com/30194799/99148220-d5d65a00-2686-11eb-96cc-b589546275df.png">

**Comment by maxvisser** [comment]
Does stadjerspas not need this to check if providers give atleast 20% discount?

**Comment by jamalv** [comment]
Hmm, don't think so, not completely sure.

**Comment by maxvisser** [comment]
@maartenfv Could you check this?

**Comment by maxvisser** [comment]
Can this get a project label? @jamalv if multiple stakeholder requested it please indicate which ones

**Comment by maartenfv** [comment]
Problem: This is very unclear: ![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/4b9b1791-c9be-4555-ad2b-0ef317eb364b)

**Comment by maxvisser** [comment]
This is fixed in 18.0
