### ISSUE TITLE
16.1 Minor fixes, texts, links, etc.

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#579]
- [x] done
<img width="706" alt="Screenshot 2020-11-13 at 15 03 31" src="https://user-images.githubusercontent.com/30194799/99238113-a09e4900-27f9-11eb-8e54-c62ea69fc006.png">

- [x] done
<img width="633" alt="Screenshot 2020-11-16 at 10 32 12" src="https://user-images.githubusercontent.com/30194799/99238142-ab58de00-27f9-11eb-9827-efd113ba08c4.png">

**Comment by maxvisser** [comment]
Could we make one big text review issue for 0.16.1 ? (instead of creating seperate once for each one. Lets make a task list in this issue. I / gerben / sjoerd can go through it and fix them all in one go.

**Comment by jamalv** [comment]
- [ ] Change "je" to "u"
![IMG_E1A0F0729ACF-1](https://user-images.githubusercontent.com/30194799/99300098-74f87e80-284c-11eb-9a57-5bcef6c62aa4.jpeg)

**Comment by jamalv** [comment]
<img width="824" alt="Screenshot 2020-11-17 at 11 16 01" src="https://user-images.githubusercontent.com/30194799/99382979-92216180-28cd-11eb-9b80-4e40acf2c974.png">
<img width="902" alt="Screenshot 2020-11-17 at 11 08 28" src="https://user-images.githubusercontent.com/30194799/99382999-98174280-28cd-11eb-8cad-cb65e97655cc.png">
<img width="628" alt="Screenshot 2020-11-17 at 10 52 39" src="https://user-images.githubusercontent.com/30194799/99383014-9baac980-28cd-11eb-8bc5-84cbdba827ad.png">
<img width="916" alt="Screenshot 2020-11-17 at 10 44 05" src="https://user-images.githubusercontent.com/30194799/99383024-9ea5ba00-28cd-11eb-847d-4d50a8c72f59.png">
<img width="859" alt="Screenshot 2020-11-17 at 10 09 47" src="https://user-images.githubusercontent.com/30194799/99383041-a1a0aa80-28cd-11eb-9fc7-eb5e5763a109.png">
<img width="1360" alt="Screenshot 2020-11-17 at 09 58 30" src="https://user-images.githubusercontent.com/30194799/99383045-a4030480-28cd-11eb-9835-cd98b21e6fc3.png">
<img width="423" alt="Screenshot 2020-11-17 at 09 36 26" src="https://user-images.githubusercontent.com/30194799/99383058-a6fdf500-28cd-11eb-99de-fd1c12a59523.png">

**Comment by jamalv** [comment]
@SjoerdHilhorst, zou je een branch vanaf master kunnen maken voor deze textfixes? Als je vragen hebt kunnen we die even bespreken :)

**Comment by jamalv** [comment]
- [ ] Maak van titel en breadcrumb "Privacy Verklaring" https://stadjerspas-acc.gemeente.groningen.nl/privacy

<img width="420" alt="Screenshot 2020-11-17 at 13 13 06" src="https://user-images.githubusercontent.com/30194799/99388968-a4ec6400-28d6-11eb-8271-cde96c613bfc.png">

**Comment by jamalv** [comment]
- [ ] Laatste stap in aanvraag proces: Voeg toe" De aanvraag wordt binnen 10 werkdagen verwerkt. U ontvangt hierover een mail."
<img width="854" alt="Screenshot 2020-11-17 at 13 16 59" src="https://user-images.githubusercontent.com/30194799/99389357-38be3000-28d7-11eb-94a5-702341b64685.png">

**Comment by jamalv** [comment]
- [ ] Als je op de webshop klikt op "Bekijk de kaart" zou de kaart moeten openen (linkje updaten, voor alle webshops)
<img width="1300" alt="Screenshot 2020-11-17 at 13 21 25" src="https://user-images.githubusercontent.com/30194799/99389780-d6196400-28d7-11eb-968e-33afbd097b35.png">

**Comment by jamalv** [comment]
- [ ] @maxvisser hoe werkt het op homepage? is er al uit op productie? moet nog op acceptatie?

**Comment by SjoerdHilhorst** [comment]
> * De aanvraag wordt binnen 10 werkdagen verwerkt. U ontvangt hierover een mail

maar dan met "je" ipv u denk ik ;)

**Comment by GerbenBosschieter** [comment]
> > * De aanvraag wordt binnen 10 werkdagen verwerkt. U ontvangt hierover een mail
> 
> maar dan met "je" ipv u denk ik ;)

Als het consistent is wel ja

**Comment by GerbenBosschieter** [comment]
@jamalv @maxvisser @SjoerdHilhorst hoe zit het met het jij je / u verhaal. Want dat kun je niet zomaar ergens wijzigen zonder dat je weet of het consistent is (webshop, mail, etc etc ). Dus voordat we dit wijzigen, laten we de knoop doorhakken wat betreft hoe wij om willen gaan met generieke / opmaat teksten.

Mijn voorkeur geniet: doen wat de klant wil en een goed proces wat betreft maintanance en beheer,  Dit doen we eigenlijk al met CSS van verschillende implementaties. Als we hetzelfde doen met teksten maar dan beter. Moet lukken en maakt het voor alle partijen makkeijk

**Comment by jamalv** [comment]
Betreft u/jij: Gemeente beleid is tot zover altijd U/Uw. Stadjerspas wijkt af en wil graag in 'je' vorm aanspreken, maar met oog op doorontwikkeling (afvalpas etc) is het beleid van de gemeente wel u/uw. Daarom is de keuze om waar mogelijk (lees: CMS) jij te gebruiken, en om in het systeem (dashboards, mails, vaste teksten in webshop, me app, etc) wel u/uw te blijven gebruiken.

Daarnaast willen we zoveel mogelijk u of jij in zinnetjes er uit laten; zoals bijvoorbeeld:

ipv: Uw e-mailadres. simpelweg E-mailadres :)

**Comment by maxvisser** [comment]
> * [ ]  @maxvisser hoe werkt het op homepage? is er al uit op productie? moet nog op acceptatie?

Aparte development taak aangemaakt; te groot voor maandag https://github.com/teamforus/general/issues/386

**Comment by maxvisser** [comment]
Lijkt me goed dat Groningen zelf het dashboard gebruikt om teksten van de stappen aan te passen.

**Comment by maxvisser** [comment]
> Betreft u/jij: Gemeente beleid is tot zover altijd U/Uw. Spas wijkt af en wil graag in 'je' vorm aanspreken, maar met oog op doorontwikkeling (afvalpas etc) is het beleid van de gemeente wel u/uw. Daarom is de keuze om voor SPas waar mogelijk (lees: CMS) jij te gebruiken, en om in het systeem (dashboards, mails, vaste teksten in webshop, me app, etc) wel u/uw te blijven gebruiken.
> 
> Daarnaast willen we zoveel mogelijk u of jij in zinnetjes er uit laten; zoals bijvoorbeeld:
> 
> ipv: **Uw** _e-mailadres_. simpelweg _E-mailadres_ :)

Wil je betreffende deze issue hier iets mee? Sjoerd heeft alles verder verwerkt.

**Comment by jamalv** [comment]
> Lijkt me goed dat Groningen zelf het dashboard gebruikt om teksten van de stappen aan te passen.

@maxvisser met alleen deze comment en het sluiten van de issue gebeurt het niet. Het gevolg is straks wellicht dat er verkeerde teksten in staan. Het is in scope van deze issue om deze teksten aan te passen; als het volgens jou niet binnen deze issue past dient er een nieuwe issue geopend te worden.

**Comment by maxvisser** [comment]
Ah ok! Not sure why its a development issue any way (why its posted here)

**Comment by maxvisser** [comment]
https://github.com/teamforus/implementation/issues/590

**Comment by jamalv** [comment]
Thx!

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1758

**Comment by maxvisser** [comment]
@SjoerdHilhorst Ik zie dat je tijdens het fixen van de teksten ook Navbar item 'Acties' naar 'Aanbod' hebt veranderd en de titel.
