### ISSUE TITLE
Image uploader: link to image rights explanation

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#581]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
There should be a terms and conditions page that is linked from the image uploader. This page will be a generic external website. 

- [x] @maartenfv could you share the link

Ik beschik over [de rechten]() van de afbeelding.

**Comment by maxvisser** [comment]
Are these custom texts or generic ones?

**Comment by jamalv** [comment]
@maartenfv mentioned that the link can be to an external website, so generic and no extra page needed. 

@maartenfv do you have a link to that site?

**Comment by maartenfv** [comment]
I found this site it is endorsed by governement: www.auteursrecht.nl/ik-wil-jouw-werk-gebruiken

This is another option: https://www.rijksoverheid.nl/onderwerpen/intellectueel-eigendom/vraag-en-antwoord/mag-ik-teksten-muziek-of-foto-s-van-anderen-gebruiken

**Comment by maartenfv** [comment]
The link being down shows the risky-ness

**Comment by jamalv** [comment]
@maxvisser the link is up again; could you make a task for adding the link? https://www.rijksoverheid.nl/onderwerpen/intellectueel-eigendom/vraag-en-antwoord/mag-ik-teksten-muziek-of-foto-s-van-anderen-gebruiken

**Comment by maxvisser** [comment]
planned and open as PR to develop

**Comment by maxvisser** [comment]
Reviewed and merged
