### ISSUE TITLE
Export only data on voucher generator (no pdfs or pngs)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#583]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently you are only able to export all QR-codes

**Comment by maxvisser** [comment]
I think this is aswell nice for anyone who want to export the data @jamalv could you prioritize this.

**Comment by jamalv** [comment]
This will need a design I think? For example a dropdown where you choose "with QR codes/without QR codes?"

**Comment by maxvisser** [comment]
there is already a modal with a choice between PNG and PDF. I would just like to add an option 'Data only'

**Comment by jamalv** [comment]
Sounds good!

**Comment by jamalv** [comment]
@maxvisser could you plan this in?
