### ISSUE TITLE
CSV uploader; add leading zero to BSN if 8 characters

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#585]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
A bsn has 9 digits, sometimes the first digit is a zero. Spreadsheet software sometimes deletes this zero. If the BSN has 8 digits, the zero should be added automatically.

**Comment by jamalv** [comment]
Btw, is this an issue for both generators?

**Comment by maxvisser** [comment]
yes

**Comment by maxvisser** [comment]
Found 0 BSNs less then 9 characters in records (seems that all bsns from digid are 9 characters)
Found 31 BSN without leading zero in prevalidation

**Comment by maxvisser** [comment]
Could also result in unintended assigning if you make a typo it will add a leading zero

**Comment by maxvisser** [comment]
@jamalv check it and close it.
