### ISSUE TITLE
Hide "Jeugd" aanvragen button

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#586]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Knop+weghalen+%22Stadjerpas+jeugd+aanvragen%22+op+aanvragen+pagina+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%228b45wNJ6Y0qanumXB54KX5YAKBGD%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
It is very confusing UX that you can apply to SP: Jeugd. We should add a flag: "aanvraag hidden" which is configurable, to hide a fund from the "aanvraag" pagina, but allow you to activate.

This is the MVP to avoid confusion with a lot of people, later it should become a fund setting (seperate CR) - we need to do the simple thing first here.

**Comment by maxvisser** [comment]
I see the ux problem. I disabled the form for this fund already on staging / production so the user is  not able to request it. The button  still allows you to login with DigiD to check if you can get a voucher through activation codes available

**Comment by maxvisser** [comment]
@jamalv planned a call for monday to see what necassary; I see nothing for this is planned yet.

**Comment by maxvisser** [comment]
Current way its working: user can login with DigiD and check again if he is in minima file; if he is not he gets this message:

![image](https://user-images.githubusercontent.com/10818702/100076124-22692480-2e41-11eb-81a6-be6732f8a999.png)

**Comment by maartenfv** [comment]
Why is this on hold?

**Comment by maartenfv** [comment]
What is needed so this can be planned?

**Comment by jamalv** [comment]
Discussed this with max, in the "normal" ux flow, you only end up at this page when the button "activate" is there, not the option to apply. When creating this issue I was expecting that everyone would come here, but that's not the case. I currently don't expect big issues out of this. 

Next to that, It's quite hard to find something to flag this on, so coming up with a solution to hide it for this case is more difficult than expected.

**Comment by jamalv** [comment]
I'd still like this, but I think there are higher-impact issues right now.

**Comment by maartenfv** [comment]
Wat gebeurt er als we mensen op aanvragen drukken? zijn beide fondsen 1 flow? of heeft dit consequenties

**Comment by jamalv** [comment]
Heeft geen consequenties, vandaar de lagere prio, we willen nu alsnog het aanvragen menu gaan hiden uit het menu, daar wordt het nog minder een probleem van.

**Comment by jamalv** [comment]
Deze pagina wordt nu alleen nog gebruikt om te activeren. Aanvragen gaat via de reguliere aanvraag flow.

**Comment by maartenfv** [comment]
@jamalv Kan je deze afstemmen met de gemeente en akkoord krijgen via comment in MS teams? 

https://teams.microsoft.com/_#/tab::3839bb31-8cb0-4e77-a674-d0f76ecf1ae5/Ontwikkeling?threadId=19:78d8e8b589df4373895fd9676b8ca52b@thread.tacv2&ctx=channel

**Comment by maartenfv** [comment]
Deze staat nu op de backlog in teams met label "Knoop door hakken".

**Comment by maxvisser** [comment]
I see this is part of release for 11 jan. I see there is still no decision made and aswell no code delivered. therefor it can't be released this monday.

**Comment by maartenfv** [comment]
@jamalv Kan je een update geven op deze issue?

**Comment by jamalv** [comment]
We've hidden the page except for where people need it to activate the card, there it says "Activeren" the page is removed in the following places:

- Menu bar when logged out
- Personal menu when logged in

These were the places where you would end up on this button. So in that sense it's "hidden". 

Still we want to improve this part, since if your application is pending, it does not show that, and if you do find and click the button, then you need to login with DigiD and get the error that max shows above. The proposal is to show that the application is "In behandeling" (just like the "stadjerspas" application).

**Comment by jamalv** [comment]
We will discus the proposal that we came up with tomorrow during refinement (with valentin)

**Comment by maxvisser** [comment]
plan:
make another fund config flag to disable the requesting button

**Comment by maxvisser** [comment]
Planned the task

**Comment by maartenfv** [comment]
What is the status?

**Comment by maxvisser** [comment]
Planned it in after refinement of 3 february for @dev-rminds; he is still busy with an epic; probably we can start on this next week if this has higher priority then CMS
