### ISSUE TITLE
Change request: Can't apply for a fund on mobile website if I am logged in because there is no button

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#587]
**Support Ticket ID:** [#2242]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Requester

### Change description
- Can't apply for a fund on mobile website if I am logged in<br>

**Comment by GerbenBosschieter** [comment]
button to apply is missing. Current solution is to log out. Than you do have a button to apply

**Comment by maxvisser** [comment]
you could go to a product and press apply but yeah its pretty stupid UX

**Comment by GerbenBosschieter** [comment]
@maxvisser hahaha. We should defo fix this

**Comment by maxvisser** [comment]
should remove hide-sm class from profile-menu

**Comment by maxvisser** [comment]
should be fixed and staged
