### ISSUE TITLE
IP: Separate login screen without branding and context switcher after logged in

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#589]
### User Story
Right now the problem is that we can't share a login URL to the dashboard to somebody without them landing on our branded landing pages (for provider / sponsor)

#### Acceptance criteria
Proposal is to have a separate page with non-branded login and - if you logged in - show the context switcher

## Prototype
https://www.figma.com/file/ubb2ZdHjOYaAc1wGk3mTCt/Login-met-e-mail---Proposal?node-id=0%3A1

![Screenshot 2020-11-19 at 10 57 23](https://user-images.githubusercontent.com/33207036/99651189-91680700-2a56-11eb-8f83-0ef8d2e1f365.png)
![Screenshot 2020-11-19 at 10 57 29](https://user-images.githubusercontent.com/33207036/99651192-92009d80-2a56-11eb-996c-3f46bfc43374.png)

**Comment by jamalv** [comment]
Yes, I like it! It's also included in this proposal: https://github.com/teamforus/general/issues/492#issuecomment-730253509

Other notes: 

<img width="930" alt="Screenshot 2020-11-19 at 11 09 29" src="https://user-images.githubusercontent.com/30194799/99652110-b3ae5480-2a57-11eb-87a3-fc160893f686.png">

**Comment by maxvisser** [comment]
I would not show the QR-code on the landing page. Should be behind a button (otherwise the frontend start polling the backend)
