### ISSUE TITLE
Change request: Complaints about provider sign-up form

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#590]
**Support Ticket ID:** [#2278]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Provider

### Change description
- There are more organisation using the sign up form the last two week. Sometimes they call for support and most of the time they have the same complaints.

**Complaints**
- The explanation of why you should use the app and dashboard is not clear. (people have the expectation that you can do the same things with it.) https://github.com/teamforus/general/issues/613
- On step 1 we focus a lot on filling in the mobile number to receive a sms. No indication that you fill in the mobile number (no blinking index/pointer) https://github.com/teamforus/general/issues/614
- The focus is 100% on fill in in mobile number. But a lot of times people will use an iPad or a phone of the organisation without a simcard and just a WiFi connection. If there is no possibility for them to enter a SMS, they get stuck. https://github.com/teamforus/general/issues/615
- People are used to search application in the App or Play store. Search "Me" will no result in finding the Me app. No mention on what keywords to choose. and the possibility to download by link or just skip it for now is hidden. https://github.com/teamforus/general/issues/601
- People who sign-up get a felling it on personal level when they have to fill in their mobile phone number https://github.com/teamforus/general/issues/616
- People who installed the app without using phone number get stuck caus we limit them to receive a sms https://github.com/teamforus/general/issues/678

**Comment by GerbenBosschieter** [comment]
This is like the first experience with the platform. The complaints mentioned above deserve their own Change Requests. But  I have the feeling that we already created CR's or added feedback in earlier stage of development about these complaints.

**Comment by maxvisser** [comment]
Could not find alot change request to link. I think those were closed or never created. So if you could split this one up and help to set priority.

**Comment by maxvisser** [comment]
During this sprint we will create seperate change request and check for each what we can do to directly fix them

**Comment by maxvisser** [comment]
I splitted this issue in multiple ones to more easily plan the smaller issues. I will close this one in favor of those. This one is linked to all.

**Comment by maartenfv** [comment]
@maxvisser @GerbenBosschieter I see this one was closed and re-openend. What is the current status? When will this be fixed?

**Comment by maxvisser** [comment]
This is split up into multiple smaller change request

**Comment by maartenfv** [comment]
@jamalv When can this issue be closed?

**Comment by jamalv** [comment]
we have planned all the seperate issues, therefore closing this one.
