### ISSUE TITLE
Canceling DigiD should return you to activate page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#591]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
if you cancel DigiD when applying for a fund you are returned to the homepage. Would be nice to come back where you left. (as the 'start aanvraag' is gone when you are signed in' its pretty hard to get back

**Comment by maxvisser** [comment]
Not sure about difficulty. Seems small

**Comment by maxvisser** [comment]
@jamalv if you want to remove 'aanvragen' from the header. this could maybe be pretty high impact

**Comment by jamalv** [comment]
Yea let's plan this in?
