### ISSUE TITLE
Reason for denying a fund request is not saved

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#594]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
If a validator denies a fund request we do not save what he sents to the citizen; I see a potential issue with not saving this information and showing it to the validator:
1. validator denies citizen on 1 jan, fills in 'U bent geweigerd omdat u een inkomen heeft boven x x"
2. Citizen calls on 7 of jan and asks for the reason
3. Validator can't check anymore why he denied said person.

**Comment by maxvisser** [comment]
Proposal save what validator fills in to a 'note' field in the database.

**Comment by maxvisser** [comment]
estimate points are for the must have.

**Comment by maxvisser** [comment]
Make a seperate field to store it (just a field) on fund request

**Comment by danrminds** [comment]
@maxvisser Can this be closed? I see it had been merged already in teamforus/forus#1977

**Comment by maxvisser** [comment]
All forus issues can be closed. General issues stay open until its released.
