### ISSUE TITLE
Add tags to app stores

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#601]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Add "Groningen" tags to app store to make the app easier to find

- [x] iOS @jamalv 
- [x] Android @maxvisser

**Comment by maxvisser** [comment]
You can only add generic tags to app in google play console;
I added to the description this text:


Het platform bestaat uit drie onderdelen:

- De Me app: Om een account aan te maken, tegoeden te beheren en de QR-Code scanner te gebruiken om je aan te melden op de webshop.

- De webshop: Wordt gebruikt door inwoners als gebruikersomgeving en om losse producten in de vorm van een reservering aan te schaffen.

- Beheeromgeving: De beheeromgevingen worden gebruikt door verschillende rollen. Sponso en aanbieders. In de praktijk zijn dit gemeentes en winkels uit bijv. Groningen en Nijmegen.

**Tegoeden die uitgegeven worden via de app:**

**Gemeente Westerkwartier - Kindpakket
Gemeente Groningen - Stadjerspas
Gemeente Nijmegen - Meedoenregeling
Sociale dienst oost achterhoek namens Gemeente Berkelland, Oost Gelre en Winterswijk - Kindregeling
Gemeente Geertruidenberg - Kindregeling
Gemeente Noordoostpolder - Meedoenregeling**

**Comment by jamalv** [comment]
This is the text we are using for iOS:

> De Me-app is een digitale portemonnee en kassa in één. Aanvragers gebruiken Me om tegoedbonnen te bewaren. Aanbieders gebruiken Me om betalingen te verrichten. Daarnaast kunnen zij zonder wachtwoord inloggen op Forus.
> 
> 
> Beheer tegoedbonnen
> 
> Heb je een tegoedbon ontvangen vanuit Forus? Log dan in op Me om je tegoed veilig mee te nemen, je saldo en transacties in te zien en om de tegoedbon eenvoudig te presenteren aan de aanbieder.
> 
> 
> Accepteer betalingen
> 
> Bied je producten of diensten aan via Forus? Dan heb je Me nodig om de QR-codes van consumenten te scannen en betalingen te ontvangen. Je kunt meerdere (kassa)medewerkers aan je organisatie toevoegen.
> 
> 
> Log zonder wachtwoord in
> 
> Met Me kun je eenvoudig, zonder wachtwoord, inloggen op Forus. Heb je een tegoedbon ontvangen of werk je bij een aanbieder? Scan de QR-code op de website en log veilig in op jouw persoonlijke omgeving

In the app store I'm planning to add stadjerspas and groningen as generic tags as hopefully a solution for now.

**Comment by maxvisser** [comment]
You want to use the same text for android. Do you have an unquoted version (maybe put it in a gdoc in development folder in our google shared drive)

**Comment by jamalv** [comment]
Added to drive: https://docs.google.com/document/d/1ZNKjMTLN7EsdnPTVoBDYCUIlFsXe4HP-Gl-_IZnCufE/edit

For iOS a release is needed to update the tags, will be in 0.4.1

**Comment by GerbenBosschieter** [comment]
Re open, what you guys didn't do the job yet. I a new release is needed than let's what until . As long I am searching on Me, Me-app, or Me Groningen and I can't find anything. Than it's just not good enough.

**Comment by maxvisser** [comment]
On android if I search on Stadjerspas I do get Me as a result

**Comment by maxvisser** [comment]
I think you are talking about iOS?

**Comment by maartenfv** [comment]
@jamalv Do we have an update?

**Comment by jamalv** [comment]
Currently working on the release - hopefully will be released the next few days

**Comment by jamalv** [comment]
Released to production. You can now find it by searching "Stadjerspas", "Me Groningen", or "Stadjerspas Groningen"
