### ISSUE TITLE
Add providers from old fund

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#602]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Customers with existing funds

### Change description
As a sponsor I would like to add all providers from a previous fund, without requiring actions from the providers

**Comment by maxvisser** [comment]
Probably this is not needed; Made an IP which is small and feasible:
https://docs.google.com/document/d/1ITehtSPsviZn8sLRjyhsIfWMGGUUYIR5-28ogr6gd3o/edit#

**Comment by jamalv** [comment]
Figma file: https://www.figma.com/file/DW4Cv9jA6PrRzPyYC5aJfd/Add-providers-from-old-fund?node-id=0%3A1
