### ISSUE TITLE
Add requesters from older fund

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#603]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Sponsors with older funds

### Change description
As a sponsor I would like to renew vouchers if a requester is still eligible in a new year
As a requester I would like to be notified about my new voucher, and receive it without hassle.

**Comment by maxvisser** [comment]
Requester who applied late needs to reapply again in a few months
Allow sponsor to set a time of validity on a criteria (for example kindpakket_eligible = ja should be validated in within the past year or user needs to be validated again) This results in that the criteria could reused.

Brain map it

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/603

**Comment by maxvisser** [comment]
Made an IP to discuss:
https://docs.google.com/document/d/1ITehtSPsviZn8sLRjyhsIfWMGGUUYIR5-28ogr6gd3o/edit#
