### ISSUE TITLE
Have all types of funds in one webshop (financial fund + subsidy fund)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#605]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
In order to have a functional platform and be able to offer our core functionalities without hesitations, we should be able to give out all types of fund in one webshop. 

## Regarding scope:
What is still needed to do this? If scope is medium or smal, I would like to classify this as must-have. If the scope is big I'd like to know how much time is needed to fix this in order to make a decision.

**Comment by maxvisser** [comment]
there are some UX problems that need to be solved first:
- which price to show on frontpage/provider page, product list
- when to show a product (approved/denied, out of stock, limit reached, no budget left etc)
- design needs to be synced

**Comment by maxvisser** [comment]
@jamalv for which project is this a must have?

**Comment by jamalv** [comment]
As mentioned in the original comment if the scope is small or medium I'd see this as an internal must-have (so dobby) - if it's big then it's a should-have and we'll need stakeholder support.

**Comment by jamalv** [comment]
So since it's medium, it's dobby :)

**Comment by maxvisser** [comment]
Discussed it during refinement. @danrminds can look into whats actually still needed for this. Could also help me asses the scope? @danrminds

**Comment by jamalv** [comment]
@danrminds could you still help to check the scope, or plan that in somewhere?
