### ISSUE TITLE
Make forus.io/dl work on tablets

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#606]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Shopkeepers with a tablet

### Change description
Currently you don't have any way to download the app when using a tablet. Forus.io/dl does not redirect. This link should also work on iOS/Android tablets. Should be fixed asap.

**Comment by maxvisser** [comment]
If we fix #281 it will atleast show download buttons.

**Comment by GerbenBosschieter** [comment]
You guys know that people will still get stuck even if you can download the app through sign up form. You can't click to next step in signup flow if you didn't enter phone nummber

**Comment by maxvisser** [comment]
@GerbenBosschieter please check #615

**Comment by maxvisser** [comment]
Currently forus.io/DL is implemented again. Not yet iPad added to the automatic thing
