### ISSUE TITLE
Image size for offers and organization on the Webhop is incorrect.

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#607]
**Support Ticket ID:** [#2316]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Provider

### Change description
- Image size for offers and organization on the Webhop is incorrect.<br>

- With an Offer: You will be asked for a square image (400x400px) during upload, but a 4: 3 image will be shown on the webshop with an offer. If the offer is clicked on the webshop, the photo is many times larger and the height depends on the amount of text in the description. This will pull the image out of context.

- At the Organization / location: A 4:3 image is requested, but a square is shown on the website for providers.

**Comment by maxvisser** [comment]
@SjoerdHilhorst if you have time; this seems as a nice one for a proposal
