### ISSUE TITLE
CSV files to add prevalidations should have more friendly headers

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#608]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- The headers we use in our CSV files to add prevalidations records are unfriendly to use. If there is only one small thing wrong we can't do anything anymore and it's really hard to reproduce what is wrong. The headers are robot/computer things that just doesn't make sense for a normal person.

Would also help with implementation phase of a project, less support about this subject and also a part of our 'first experience' of the system

**Comment by maxvisser** [comment]
most of the headers we can pick ourselves. some have legacy features like children_nth and others depend on functionality like having atleast "_eligible" in it.

As criteria / record_types can be created manually, criteria can be configured manually most of the things can change. Of course for running funds this is difficult to change as a slight error in the migration can have terrible consequences.

**Comment by maxvisser** [comment]
some things to take into account:
- currently the year is necessary in the record type
- _eligible is necessary
