### ISSUE TITLE
CR: Redesign csv upload page

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#609]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @SjoerdHilhorst 

### Change description
- Currently there are 3 upload buttons, with two different functions:
![image](https://user-images.githubusercontent.com/48722300/100621295-c9592f00-331f-11eb-9984-fd2189f9f21f.png)

Improvement proposal:
https://www.figma.com/file/VAVSBCaMLFGl7tS8qkG73x/Upload-.csv?node-id=1%3A80

Proposal is to automatically generate the vouchers when the csv is uploaded, without an extra button.

**Comment by maxvisser** [comment]
@SjoerdHilhorst i see directly uploading the file as a nice feature. Sometimes we do give warnings based on the file though. I think we should still show these warnings (if there is any) and also ofcourse validation errors (a incorrect csv header)

**Comment by jamalv** [comment]
@SjoerdHilhorst I like the proposal in you "play" page! If you want you can rename your "play" page to "review" and move the file in figma to "proposals" - max and I will check the concept and feasibility; if those are good, it can be moved to prototoypes; there linda will check the texts, alex will review the design, and then you can start on development 🥳
