### ISSUE TITLE
Assign vouchers by address 

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#610]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As a sponsor I would like to give out vouchers based on house address. 

Suggestion: to add a new UID based on postal code+house number

**Comment by maxvisser** [comment]
Not sure what does this mean; a address is no person right? If you and me live together on the same address (maybe a student building) who will get the voucher?

**Comment by jamalv** [comment]
Added as insight: https://app.productboard.com/inbox/notes/15569218
