### ISSUE TITLE
Webshop Me page has email again. Please change this to e-mail

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#612]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Please stop using email. In dutch in means something else than in english.
Use different screenshot where email is e-mail.
<img width="279" alt="Screenshot 2020-12-02 at 09 44 11" src="https://user-images.githubusercontent.com/38419514/100849948-5ec10400-3483-11eb-83dc-4227cf55b550.png">

**Wrong**
<img width="1360" alt="Screenshot 2020-12-02 at 09 44 05" src="https://user-images.githubusercontent.com/38419514/100849945-5d8fd700-3483-11eb-988e-f1a7a4896c76.png">

**Alternative screenshot**
![IMG_C32AD9C01774-1](https://user-images.githubusercontent.com/38419514/100849985-6f717a00-3483-11eb-8517-fe0b4e1f4590.jpeg)

**Comment by maxvisser** [comment]
Planned this in for @sashooa change the image

**Comment by GerbenBosschieter** [comment]
Status? I assume a typo should take that long?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/102982575-0d001c80-450b-11eb-9e4a-15e5a2ae5727.png)
its in v0.18.0

**Comment by maxvisser** [comment]
Thanks missed this on on the changelog.
