### ISSUE TITLE
Make it clear what the difference is between dashboard / app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#613]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Support Ticket ID: [#2278]

### Change description
The explanation of why you should use the app and dashboard is not clear. (people have the expectation that you can do the same things with it.)

## proposal

![image](https://user-images.githubusercontent.com/10818702/100857162-a7c98600-348c-11eb-9c9e-02d08172f117.png)

This text could be more clear; currently getting payments and the dashboards is written in one sentence; maybe clearly tell the user App is for doing payments.

**Comment by GerbenBosschieter** [comment]
The step of downloading the app itself should also tell the user more about why they instal the app

**Comment by maxvisser** [comment]
This would be a different issue; could you check #615 figma proposal?

**Comment by jamalv** [comment]
@linda-90 could you have a look at this text and see if you can make a clearer explanation:
- You get acces to the "webomgeving" - there you can xx
- With the app you can make the payments

**Comment by jamalv** [comment]
@maxvisser could you still make a separate issue?
