### ISSUE TITLE
Provider sign-upflow: add blinking indicator that you are filling in phonenumber

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#614]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
On step 1 we focus a lot on filling in the mobile number to receive a sms. No indication that you fill in the mobile number (no blinking index/pointer)

![image](https://user-images.githubusercontent.com/10818702/100857384-ed864e80-348c-11eb-95a4-2ee6879dd1ec.png)

**Comment by maxvisser** [comment]
If we make the screens for phonenumber less prominent; I will put this on blocked by #615

**Comment by GerbenBosschieter** [comment]
@maxvisser why block this issue by #615. the indicator doesn't have to. do anything if gets less prominent or not. it's just a UX thing that we already on other places

**Comment by maxvisser** [comment]
as this input field will be removed in proposal of #615; so it would be weird to add it if you going to remove it afterwards.

**Comment by jamalv** [comment]
@maxvisser i agree with gerben that it should still be done

**Comment by maxvisser** [comment]
there is a pr open which will have conflicts with this.
