### ISSUE TITLE
Provider signupflow: iPad/Phones without simcard UX

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#615]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Support

### Change description
The focus is 100% on fill in in mobile number. But a lot of times people will use an iPad or a phone of the organisation without a simcard and just a WiFi connection. If there is no possibility for them to enter a SMS, they get stuck.

## Proposal
Clearly show download buttons for the app on the page where user can download the Me-app via SMS; user should also be able to scan QR-code and login without needing to fill in phonenumber.

Figma:
https://www.figma.com/file/Jf9evMRyAVEbzy4EDubvTr/?node-id=176%3A138

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/616
![image](https://user-images.githubusercontent.com/10818702/100858303-19560400-348e-11eb-9800-8d60a7053453.png)

**Comment by maxvisser** [comment]
Example of how Whatsapp does it:
![image](https://user-images.githubusercontent.com/10818702/100858480-51f5dd80-348e-11eb-935c-dce2e44cafc6.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/100858744-abf6a300-348e-11eb-8c21-193d52aba85a.png)

**Comment by maxvisser** [comment]
Made an IP: https://www.figma.com/file/Jf9evMRyAVEbzy4EDubvTr/?node-id=176%3A138

**Comment by maxvisser** [comment]
@jamalv Sjoerd is starting development. Did you already look at this for approval of the concept?

**Comment by maxvisser** [comment]
Dan/Sashoa wil do a design review.

**Comment by GerbenBosschieter** [comment]
And what if someone wants to download the App from the stores without this page. So someone with multiple phones. Thats most of the time the case. Are we scared to tell them what keywords to use or something?
