### ISSUE TITLE
Provider signupflow: Make it more clear why we ask phonenumber

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#616]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
People who sign-up get a felling it on personal level when they have to fill in their mobile phone number

**Comment by maxvisser** [comment]
Current page: ![image](https://user-images.githubusercontent.com/10818702/100858209-fd526280-348d-11eb-8ca9-cc56d285c4bc.png)

**Comment by GerbenBosschieter** [comment]
The solution is not focussing that much on phone number but giving them more options pro actively instead hidden options in grey letter

**Comment by GerbenBosschieter** [comment]
Also we should tell them what keywords they should use to search the app in the stores. It's "Me Forus"

**Comment by GerbenBosschieter** [comment]
why is this on hold

**Comment by maxvisser** [comment]
I believe the proposal for #615 fixes this issue; Provider signupflow: iPad/Phones without simcard UX
