### ISSUE TITLE
Change color menu potjeswijzer

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#617]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Westerkwartier

### Change description

Change the color to green (color code like the logo) to make it more visible.
-
![Screenshot menu 2020-12-02 135304](https://user-images.githubusercontent.com/30211022/100875417-457d7f00-34a6-11eb-81e0-ac92581b3461.png)

**Comment by maartenfv** [comment]
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_1257514803?webUrl=https%3a%2f%2ftasks.office.com%2fb4a9ddbe-ddec-41ba-977a-154b31a1847e%2fHome%2fPlanViews%2f-rWQG76nFU-2YfF2jIBD1JgAC-ia%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Geef+de+menubalk+een+groene+kleur+zodat+kan+worden+waargenomen+dat+deze+een+onderdeel+uitmaakt+van+de+site.+in+Planbord&context=%7b%0d%0a++%22subEntityId%22%3a+%22Piuj5Yz_xk-u7UiRBHRMyZgAPZRa%22%2c%0d%0a++%22channelId%22%3a+%2219%3a00622d755b8e4e2b97eb92587835fd07%40thread.tacv2%22%0d%0a%7d&tenantId=b4a9ddbe-ddec-41ba-977a-154b31a1847e

**Comment by maxvisser** [comment]
If a header image is chosen I would like to a design review of both header and menu. As the color of the header can change we properly want to adjust t he color of the menu again

**Comment by maartenfv** [comment]
Dit was feedback van Peter moet worden gedaan.

**Comment by maxvisser** [comment]
Because we were depended on the header foto to be picked. its now picked and we changed the menu color;

**Comment by maxvisser** [comment]
currently in a pr to develop
