### ISSUE TITLE
&nbsp in CMS is not user friendly for customers.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#618]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen

### Change description
- Update CMS from Markdown to WYSIWYG
- Users do not understand markdown and do not what to have to place an &nbsp as an "enter".
- The CMS now requires separate implementation sessions to explain how to use it.

**Comment by linda-90** [comment]
This is also not user friendly. Where do they have to place the image to get such a link?

<img width="1300" alt="Schermafbeelding 2020-12-03 om 18 21 15" src="https://user-images.githubusercontent.com/36952230/101064537-66bc9900-3594-11eb-825c-403b7e2f82cc.png">

- Update CMS with option to upload an image (not by filling in a link to the image)

**Comment by maartenfv** [comment]
@linda-90 Can you make a separate issue for this request?

**Comment by linda-90** [comment]
https://github.com/teamforus/general/issues/666

**Comment by maartenfv** [comment]
This can not be in Icebox it is a problem for the municipality as the CMS is not useable.

**Comment by maxvisser** [comment]
@maartenfv I discussed the CMS a bit with you a few days back. The scope seemed much bigger than this issue. Do we fix the CMS only with changing editors?

**Comment by jamalv** [comment]
> @maartenfv I discussed the CMS a bit with you a few days back. The scope seemed much bigger than this issue. Do we fix the CMS only with changing editors?

I've added this to a CMS epic in order to align on long term strategy

**Comment by maxvisser** [comment]
Discussed this with @maartenfv

**Comment by maartenfv** [comment]
I propose to fix this now. And make a larger interation later.
The CMS needs to be a one stop shop to fix the webshop and related pages. The User sponsor wants to have control.

The situation now is unmaintainable as users can not use markdown. This needs to be fixed asap. Scope is as stated above.

**Comment by maxvisser** [comment]
Native markdown does not support new lines; an extension is needed that for example allows some basic html to be used like ``<br />`` or some 'hack' which creates &nsbp; on the background

**Comment by maartenfv** [comment]
@danrminds @maxvisser Do you have an update on the status this issue?

**Comment by maxvisser** [comment]
it has not been planned in yet; as clear idea yet to fix it.

**Comment by danrminds** [comment]
@maartenfv @maxvisser 

We had some proposal on how to fix this, but no decision made. So, let's try to make a decision here. 
For this - we need an alternative for the Markdown editor (enhancement of it). 

## Proposal 1. Updated version of it.

Build an enhancement on top of Markdown, which will represent a visual editor. For example, something like this:
![Screenshot 2021-01-13 at 16 40 54](https://user-images.githubusercontent.com/33207036/104474294-27835e00-55be-11eb-9025-10f630cb356a.png)

In fact, on the background is the same markdown happening, with same limitations, but we don't really want to give more functionality (like font style, colors, positioning, centring) 

The enhancement will allow us to make a preview directly in the field for the following functionality and text formatting:

 - [ ] Bold text
 - [ ] Italic text
 - [ ] List
 - [ ] Spaces and new lines
 - [ ] Headings (H1, H2, H3, H4, H5)
 - [ ] Images (with uploading directly from the computer)
 - [ ] Links

Estimated implementation time for such a custom layer on top of the markdown editor - 1.5 to 2 weeks. 
https://github.com/teamforus/general/issues/671#issuecomment-759534930

## Proposal 2.

Use a ready library:
https://github.com/sparksuite/simplemde-markdown-editor
https://simplemde.com/
this wrapper for simpleMDE seems to have 15 stars:
https://github.com/hansottowirtz/simplemde-angular
ttps://ui.toast.com/tui-editor 

But, regarding these ones - I am not sure this is what the stakeholders are looking for:
![Screenshot 2021-01-23 at 11.59.05.png](https://images.zenhubusercontent.com/5ea2e8e74754fd7c3ad28537/9b6c1e89-e474-4610-8bc6-40f743ed8ddc)

Still having the `#, **, [links](https://google.com)` etc in the text

**Comment by jamalv** [comment]
second option would take about 2 days

**Comment by jamalv** [comment]
@danrminds would proposal 2 also solve https://github.com/teamforus/general/issues/666?

**Comment by jamalv** [comment]
/ how much extra time would that take?

**Comment by jamalv** [comment]
666; needs library, needs to be connected to either option: does not matter much

**Comment by maartenfv** [comment]
Need to go for proposal 1, not 2. Our users know nothing about markdown and should not need to know. If it takes 2 weeks then that is what we need to do.

Why do we use markdown in the first place?

What about? https://quilljs.com/ or https://www.tiny.cloud/tinymce/ or https://ckeditor.com/

**Comment by maxvisser** [comment]
A fix for this has been released

**Comment by maxvisser** [comment]
Still needs a CSS update to allow headers / images not needing &nbsp;

**Comment by maxvisser** [comment]
@linda-90 can you check this issue again and see what you still find as needed?

**Comment by jamalv** [comment]
was just looking at this with linda - it seems like enter does still not work, and you need to fill &nbsp in order to make a linebreak

**Comment by jamalv** [comment]
@dev-rminds @maxvisser is that correct or are we doing something wrong? the usecase is if we want to add a few extra lines - for example between an image and some text, the extra space doesn't work

**Comment by linda-90** [comment]
Image
![vraagteken](https://user-images.githubusercontent.com/36952230/124132555-3cc34a80-da81-11eb-9903-5a11d794206c.png)

Screenshot website
<img width="470" alt="Schermafbeelding 2021-07-01 om 15 29 36" src="https://user-images.githubusercontent.com/36952230/124132571-42209500-da81-11eb-8f0f-a661381821da.png">

**Comment by maxvisser** [comment]
this is not related to &nbsp ? Maybe create a seperate issue about image width / height; Seems to be that we make them always 100% width; if this is not desired we can not scale them.

**Comment by maxvisser** [comment]
adding white lines into the CMS does not work.
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/5c2805fc-ce8c-4bd3-9997-a7acfbafe521)

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/f15927cd-173f-48a9-84ae-2879f3e5e07a)

you still need to add &nbsp; to create new white lines between texts

**Comment by maartenfv** [comment]
@maxvisser :P let's fix this!

**Comment by maartenfv** [comment]
It is blocking closing the CMS project.

**Comment by maxvisser** [comment]
we talked about it during refinement; we need to plan this in again for valentin

**Comment by maartenfv** [comment]
Waaauw we did it!!!!
