### ISSUE TITLE
Can't do any changes to my product after I've checked the box of: no price or unlimited stock. What if there really is a change or I made a mistake?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#620]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
After a provider adds a product and realises they made a mistake or just want to change something on a later moment they can't always do if the following checkboxes are checked:
- unlimited stock
- no price

Let them be able to change this. Greying it out visually after choosing one is obvious. But limiting them is not really user friendly.

**Comment by GerbenBosschieter** [comment]
What happend with this?

**Comment by maxvisser** [comment]
Nothing yet.

**Comment by maxvisser** [comment]
As it is pretty clear I will plan it in.

**Comment by maxvisser** [comment]
Not sure how difficult this one is to fix though.

**Comment by maxvisser** [comment]
Planned
