### ISSUE TITLE
Use the image that the provider chose somewhere as a placeholder for everywhere if they didn't add a custom image

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#621]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Please make it possible that by default the placeholder images of offices and products are an image a provider already chose. For example their company logo. Some provider only choose one image in the sign up process. Then add an office, then add multiple products.  The action to add the image is so repetitive they just don't do it any more.

This result in our default placeholders. That aren't that nice.

**Comment by jamalv** [comment]
@maxvisser could you plan this in for alex?

**Comment by maxvisser** [comment]
This could result in unintended problems aswell. From a user perspective it is not that logically to it this way. I would or make it an option for the provider to do this; or make somekind of media library to easily reuse images

**Comment by jamalv** [comment]
My expectation is that if we prefill it, then if the provider doesn't like it they will change it, if they like it they won't do anything. IMO this is an improvement in UX. @GerbenBosschieter what do you think?

**Comment by maxvisser** [comment]
You will do this for all providers in the system automatically on release. They do not often go to the webshop and check their images. If you guys don't see any risks with this lets do it. Otherwise I would just wait until there is time to increase scope.

**Comment by jamalv** [comment]
Ah, that's a good point. So then the decision to make is, is the organisation / office image better than the placeholder?

I'm leaning towards yes, but find it a bit hard to oversee. My guestimate is that it should be no problem.

**Comment by jamalv** [comment]
@GerbenBosschieter what do you think?

**Comment by GerbenBosschieter** [comment]
Let's do it

**Comment by maxvisser** [comment]
Planned

**Comment by maxvisser** [comment]
Discussed this during refinement. Its more difficult to fix then assumed.

1. organization / office / products dont have the same dimensions.

Valentin proposes this option: let provider upload a placeholder image for products / offices
migrate placeholder for existing users.

**Comment by maxvisser** [comment]
needs proposal, moved it there for back to be clarified
