### ISSUE TITLE
Adding a product: "aantal" is not clear for provider of Stadjerspas

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#622]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- A lot of providers make mistakes when adding a product if they are being asked for "aantal". They are used to the Stadjerspas scenario where they knew there was a limit of how many times a requester could use the action.

In the old system the sponsor added the product on behalf of them. But now they have to do it themself. They confuse "aantal" with limit per user. 

It needs to be more clear that "aantal" is about how many times the organisation can do the offer and it's not the limit per user.

**Comment by maxvisser** [comment]
Would a tooltip help? Probably add something like
"Aantal van product of dienst dat u in totaal kunt leveren"
