### ISSUE TITLE
As a provider I would like to add a discount of a certain amount (not % but also €) for all my complete assortment

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#623]
## Context/goal: 
Provider can currently add a product and check the checkbox if it's a discount. But they can only give discount in percentages. Would be nice to also do this with a fixed amount. This will really help the use case where the providers wants to give a discount to their complete assortment while the products itself have variable prices. 

### Example
Provider Trivia gives and discount of 20 euro's to everybody with Stadjerspas for all of their contributions: https://stadjerspas.nl/activiteit/2124

The problem is that all their contributions have different prices, so percentages will not do the job. @maxvisser offered a solution for them to add all of their contribution separately to the platform. But thats impossible. This will take years and they are limited to a certain number of products.

The screenshot below wil show you that only one of their menu items already has 12 different contributions. And eery menu item has their contribution list.

See for yourself :) : https://trivia.nl/leszwemmen/contributie/

### important
this issue https://github.com/teamforus/forus/issues/1946 is part of this use case

**Comment by GerbenBosschieter** [comment]
@maxvisser I think the solution is much easier than we think it is. What if we add like an display price option with a dropdown for price, discount or free.

With the onboarding of current providers we notice that most of the offer are like likes. 20 euro discount on whatever they offer. We can manage this if you add a product/offer with price 20 euro. Add it in the title and sponsor will contribute the rest. Only problems is that on the webshop it will say free. But we add a display price to webshop you can say it's a discount. 

We already have checkbox for discount but uses percentages while there is literally no provider that uses percentages for their discount.

**Comment by maxvisser** [comment]
Implemented a fix. 
Example screenshot from staging:
![image](https://user-images.githubusercontent.com/10818702/102258504-4a164e80-3f0e-11eb-927f-7bbd26f864b9.png)

Product which now displays a discount of 12,50 euros was before labeled as 'free'. I see this as a fix for now as product which are becoming free because the municipality contributes are basically still getting that amount of discount.

**Comment by maartenfv** [comment]
@maxvisser What is the status of this issue?

**Comment by GerbenBosschieter** [comment]
@maartenfv for now there is a quickfix that will be released asap
