### ISSUE TITLE
Problem during sign up process of providers: they forget to sign up for a fund

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#624]
## Context/goal: 
Most providers forget to apply a fund during the process of signing up. They create their organisation but don't click apply on any fund and just continue to next step. This is also because we nowadays send a link without organisation id so they have like a list of funds to choose but they just don't know what to choose and think: I will just continue.

This result in a lot of problems. 
1. The sponsor doesn't know a certain provider did create their organisation but just didn't apply.
2. The sponsor can't do anything to influence this
3. Provider doesn't know they forgot something
4. Requester don't know the organization is willing to join
5. Eventually a lot of support
6. Everybody unhappy :( 

I don't have a solution. But this is a big problem during sign up. 

Related to: https://github.com/teamforus/general/issues/584

**Comment by jamalv** [comment]
Not sure if we can technically solve this, at least not without it getting big (allowing providers to add/invite providers to a fund, which is a great feature but probably pretty big)

**Comment by jamalv** [comment]
But clearly a big issue, probably new link should be sent with that instruction as wel.

**Comment by maxvisser** [comment]
If it's get too out of hand we could just do it via a service request. (add the applications to the fund via database). I see this as less priority then features which will allow some use cases that we currently don't support.

**Comment by jamalv** [comment]
Hopefully this can help in the flow of signing up; https://github.com/teamforus/general/issues/628

Applying to the funds afterwards (current issues) can be done trough service requests. Can we be pro-active in this?

**Comment by jamalv** [comment]
We added an overview page (release 18) in order to trigger providers to sign up, also have added a specific provider page.

@maxvisser could you create a task to send providers to the implementation signup flow?

**Comment by GerbenBosschieter** [comment]
What about a feature that allows the sponsor to add (not invite) a provider that already applied for a fund of that sponsor?

**Comment by jamalv** [comment]
Sounds like a good idea to me

**Comment by maxvisser** [comment]
we do have already a CR for inviting providers #78
