### ISSUE TITLE
Openings times when providers isn't closed but doesn't have any specific opening times

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#625]
## Context/goal: 
Some providers don't have specific opening times on certain days. But they are not closed. The way we setup opening times forces the provider to be closed or to add openings hours. What they is not adding any specific opening times while filling in the sign up flow or by creating/editing office, but this will result in: CLOSED.

Would be nice to have an option as: (english wordt left side , dutch wordt right side)
- unknown (onbekend)
- inapplicable (niet van toepassing)
- no data (geen data)

See this video if it's not clear yet: https://drive.google.com/file/d/1V_sygzqlq_YKWtihHPP06GArL4Lgl8ti/view?usp=sharing

**Comment by GerbenBosschieter** [comment]
@maxvisser it gives provider a wrong impression.

As a provider you sign up, then create office, with business hours but leave monday and Tuesday empty, then finish the sign up flow and go to the dashboard. And then you go to your offices and you see a checkmark at closed. So the providers thinks: I am not closed, it just don't have specific opening times

And a screenshot of what show on the webshop doesn't matter and is irrelevant to this issue. This has resulted in complaints!

**Comment by GerbenBosschieter** [comment]
I knew I mentioned this before, it's not exactly the same but it does mention the same complaints

https://github.com/teamforus/forus/issues/1891

**Comment by maxvisser** [comment]
We did fix all the bugs for this aswell as showing the word 'closed' on dashboard.

**Comment by maxvisser** [comment]
This issue is left open as it is about adding more options to specifically describe the situation (so we could show those)

**Comment by maxvisser** [comment]
Ah i see we still have it on edit page...
![image](https://user-images.githubusercontent.com/10818702/102984604-1dfe5d00-450e-11eb-86f4-45e9cda94119.png)

**Comment by maxvisser** [comment]
Probably this can only be fixed with your proposal. there is nothing in between.

**Comment by maxvisser** [comment]
Will plan this in.

**Comment by GerbenBosschieter** [comment]
@maxvisser I didn't propose it for fun or something and I also included the video. I proposed it cause REAL time users complain about iut

**Comment by maxvisser** [comment]
As it is stuck on proposal phase for a while; I put it back into 'to be clarified'
