### ISSUE TITLE
Prevalidations and time-based criteria (Bulkbestand gegevens verloop)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#626]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- SDOA
- Other municipalities

### Change description
- See proposal: https://docs.google.com/document/d/1meid4YqZBQi81PQ26nd7QB8JnHAwjtLb1-eE3iRaoMU/edit#

**Comment by maxvisser** [comment]
added a task for this in forus

**Comment by jamalv** [comment]
@maxvisser that would make this issue an epic? could you convert to epic and link the task(s)?

**Comment by maxvisser** [comment]
epic in a epic?

**Comment by jamalv** [comment]
Epic-ception; it is possible :P (and maybe useful?) But I didn't realize this was already in an epic; maybe link that issue to the top epic?
