### ISSUE TITLE
Tegped!

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#627]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
<img width="682" alt="Screenshot 2020-12-04 at 19 30 43" src="https://user-images.githubusercontent.com/30194799/101201010-5e815e00-3667-11eb-9174-6c999f51a956.png">

**Comment by jamalv** [comment]
Reproduce by manually emailing the QR to yourself (from voucher page in webshop)

**Comment by jamalv** [comment]
@maxvisser I was looking in the codebase to make a pr myself but couldn't find it, could this be planned?

**Comment by maxvisser** [comment]
Adjusted this in release v0.17.1
