### ISSUE TITLE
Actions: Second iteration

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#630]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Current situation
We have delivered the first version of actions. Now that providers and a sponsor start using it, we are finding out things that are not yet clear in the way how users expect how it works, and how it actually works.

## Desired situation
Providers and sponsors should not need training or explanations on how to use actions. It should be self-explanatory.

## Plan
- [ ] Implement figma prototype: https://www.figma.com/file/04lT4mV6Jsl7Ot6SlvqWHz/?node-id=388%3A658

**Comment by jamalv** [comment]
@maxvisser I have some 🧠-breakers for you :P curious to hear your thoughts!

**Comment by maxvisser** [comment]
Well I see our current system as straight forward. You offer a product or service. Fill in title, description and the price which you offer it for. What's not straight forward about that? 

What's messed up is the mindset which provider have when they approach the system 'I Want to apply my product for this specific fund and want to ask the sponsor of this specific fund for a price agreement'. Which results in weird behavior; an example is a provider who already adds the discount he agreed upon with the sponsor. Which results in a too cheap of a product. 

The things I would change is make the product creation simpler. I would remove the discounted price and a selection for adding a discount as product when it has no price. (I find this part completely weird). As well as making an expire date optional. Less options is less confusing functions which are not well thought through. 

What I would add are product 'types'. For example a red iPhone is abit more expensive then a white or black one but they are all the same product. This would solve that a provider would need to add 10 products which are the same.

If we would want the provider to set the action itselve: I would make action/price agreement proposal. Add here the option to show it as a discount and aswell the option for them to set a discount themselves. Workflow would be: First provider creates a product (which is now simpler) and for subsidy funds he applied to he can make action proposals (fill in the amount he wants get from sponsor)

**Comment by jamalv** [comment]
Yea I agree with most of that. This Figma proposal is meant to clarify the direction and have discussions about it, with the goal of being straightforward long-term, regardless of mindset.

Since we have now introduced this new type of fund with subsidies by the sponsor, that means for future implementations using this fund type, that will also be the mindset. (a provider wanting to get a subsidy from the sponsor). So we have to take that into a count when designing UX. The goal of the proposal is to be intuitive for both usecases in the long term. 

The proposed fixes can be implemented incrementally. I agree with removing "aanbiedingsprijs" > There should just be one field "price". I think for financial funds, adding a discount is (and should be) optional, since all funding is coming directly from the sponsor.

I have updated figma a bit this morning, to add the tooltips as hovers in the prototype.

Could you please study this proposal a bit and see if there are increments that can be planned that make the current system better? Sidenote; we've discussed it would be okay to stop showing discount percentages on normal cards; all the feedback we are getting about that is that it makes the webshop too commercial for this type of purpose.

**Comment by maxvisser** [comment]
Not sure which problem you try to fix; I think I miss alot of context; Why is there a 'action checkbox' ? what does it do?

**Comment by maartenfv** [comment]
@jamalv please attach all smaller issues to this issue. This one is not clear.

**Comment by maartenfv** [comment]
@Jamal please add alle issues + release dates

**Comment by jamalv** [comment]
dit is de release met alle issues: https://app.zenhub.com/workspaces/sprint-5f61c6c0a53fb84e755c82f6/reports/release?release=5fe3bf35688d8a0c014ea6fd
