### ISSUE TITLE
Update voucher card: make opening modal links more prominent (buttons need to be visible, not hidden)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#631]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description

- [ ] buttons need to be visible on first sight and not hidden in pop up.
- [ ] Buttons need to have colour
- [ ] buttons need a hover
- [ ] Buttons need to be as large as possible (and still look nice)

It is currently unclear (user testing) what is expected of the user.  User do not see/undestand the current button to be clickable.

MVP is updating the styling to clarify the call to action, we can think about bigger iterations after that.

Figma: This one is outdated (needs update like design Max): https://www.figma.com/file/mWmn4EgY0eh1FDye0dIJWE/?node-id=0%3A1

## Current state:
![image](https://user-images.githubusercontent.com/30194799/101322626-a373e300-3867-11eb-84ac-ed78d29e91cb.png)

## Desired state:
![image](https://user-images.githubusercontent.com/30211022/103012311-b2cb7f80-453b-11eb-9e20-aea780c250b2.png)

Note: font sizes don't need to be updated, that's just a difference between figma and code

**Comment by maxvisser** [comment]
Two questions:
Why two links?
Don't you think the red will feel like something is wrong? maybe make it blue?

**Comment by jamalv** [comment]
Red links are brand identity of municipality. Links and buttons are red everywhere. Doesn't look weird on the page I think.

Two links because during usertesting people didn't understand the QR code, it's important that they make this connection (they don't read the text), pointing them to the modal will undoubtedly help make the concept clear and have them take a next step. (for example getting the app)

**Comment by jamalv** [comment]
If you're in doubt try it in your browser, it doesn't look weird I think. What happened now is the only "call to action" is activate your card, but for a lot of people that's not the one that's most important. They need to make the connection that they can already use the QR code right away. For people with an expectation of a physical card, that's pretty hard to grasp. The modal does the trick.

Anyway, I think it's a small change that improves critical UX, so let's just do it 🚀

**Comment by maxvisser** [comment]
ah i see red / blue text links are not consistent over  the whole site; sometimes they are blue; sometimes red.

**Comment by maxvisser** [comment]
(and in your example black and red) maybe we should create a seperate issue to make them all red / blue / black; so its more consistent

**Comment by maxvisser** [comment]
What kind of hover color will they both have? Should we do a design review?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/101487453-7c4c0d00-395e-11eb-91be-3c7342988dff.png)
this is currently the hover color

**Comment by jamalv** [comment]
Ah I see that URL's are mostly in blue, this is also true for the current SP site and for GG site. Maybe the MVP for this issue is this:

<img width="269" alt="Screenshot 2020-12-08 at 15 33 23" src="https://user-images.githubusercontent.com/30194799/101497078-dd79dd80-396a-11eb-8ca7-e59a45d5a1bd.png">

**Comment by maxvisser** [comment]
Looked at this abit; I think making the links more prominent is maybe not even the fix; I would suggest to maybe even add the actions back direct on the card;

Something like this:
![image](https://user-images.githubusercontent.com/10818702/101501032-84607880-396f-11eb-9201-58b3551cd993.png)

**Comment by jamalv** [comment]
Well I thought about keeping the scope small as an initial fix, but yea, that might be better solution. Still I would like to colorize the buttons in the link color that's used in the implementation.

**Comment by jamalv** [comment]
And let's not forget mobile :D

**Comment by danrminds** [comment]
@maxvisser So - what option should we plan in? The small scope or returning the buttons back?

**Comment by maxvisser** [comment]
Do the smaller scope for now. Make a proposal for the bigger one.

**Comment by jamalv** [comment]
Discussed with @maartenfv and @maxvisser to go with max's proposal;

**Comment by jamalv** [comment]
since they are call's to action; they should be the link color for the implementation (e.g. red for groningen)

**Comment by maartenfv** [comment]
@jamalv and they need a nice mouse hover

**Comment by maartenfv** [comment]
@demylubbers @jamalv @maxvisser Can this issue be planned?

**Comment by maxvisser** [comment]
Its already planned. I finished programming it last week https://github.com/teamforus/forus/issues/1996
