### ISSUE TITLE
Change: "Maak publiek" to "Toon op website"

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#633]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
"Maak publiek" > "Toon op website"

<img width="731" alt="Screenshot 2020-11-29 at 21 39 07" src="https://user-images.githubusercontent.com/30194799/101325717-81c92a80-386c-11eb-9390-09b0a5938e38.png">

**Comment by jamalv** [comment]
@maxvisser can be planned

**Comment by maxvisser** [comment]
You know how this currently works? It still will be shown on the website even if the checkbox is off; We only don't show it publicly for logged out users

**Comment by jamalv** [comment]
Ah, thx for the clarification! In that case I would propose: "Toon openbaar op website"

**Comment by maartenfv** [comment]
Better: "Toon ook aan gebruikers die niet zijn ingelogd"

**Comment by maxvisser** [comment]
already changed to what jamal said.
