### ISSUE TITLE
Role switching in dashboards footer

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#635]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a user who takes on multiple roles I’d like an easy way to switch dashboards.

Figma: https://www.figma.com/file/DqaXCJzRWhLLYFOuhbKPYK/?node-id=0%3A1

<img width="1096" alt="Screenshot 2020-12-07 at 11 23 08" src="https://user-images.githubusercontent.com/30194799/101339403-a75f2f80-387e-11eb-8985-1af772d91c00.png">

**Comment by maartenfv** [comment]
I like this one!!!!

**Comment by maartenfv** [comment]
Very good one

**Comment by maxvisser** [comment]
@SjoerdHilhorst If you have time you can make a figma proposal for this one; You can create a task for yourself in forus: Proposal: role switchtin (assign yourself), after you are done with the proposal; please close that issue and create a design review; Please do mention this CR in both tasks (so they are linked)

**Comment by maartenfv** [comment]
@SjoerdHilhorst Go for it!

**Comment by maartenfv** [comment]
@SjoerdHilhorst Do you have an update?

**Comment by SjoerdHilhorst** [comment]
ill start making a proposal today
