### ISSUE TITLE
Introducing Me: Text and URL on connection modal

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#638]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As an implementation owner I'd like a better introduction to the me app on (probably) the first page where people learn about it (from voucher page)

## Suggestion
Figma: https://www.figma.com/file/UuOGYY6mdunE4lh9MVhN9m/?node-id=1%3A80

<img width="819" alt="Screenshot 2020-12-08 at 13 01 03" src="https://user-images.githubusercontent.com/30194799/101481429-76056300-3955-11eb-9430-bbf5a08cd955.png">

**Comment by maxvisser** [comment]
@danrminds can be planned

**Comment by danrminds** [comment]
https://github.com/teamforus/forus/issues/1983

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/54cb3038-a012-4d0a-aedb-1871a93e62a5)
Seems to be fixed
