### ISSUE TITLE
Ketentest koppeling DCP

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#640]
PVA:
- [x] Contact opnemen met DCP, inlichten over test @jamalv 
- [x] Alles resetten naar "neutrale" staat (DCP FTP server clearen, etc) (staging) @maxvisser @DCP
- [x] Een pas bestellen op het emmahuys, handelingen aan onze kant verichten @jamalv 
- [ ] Pas ontvangen bij emmahuys
- [ ] Pas koppelen
- [ ] Test transactie
- [ ] Champagne 🍾

**Comment by jamalv** [comment]
@maartenfv @maxvisser wie is het aanspreekpunt bij DCP?

PVA:
- [ ] Contact opnemen met DCP, inlichten over test
- [ ] Alles resetten naar "neutrale" staat (DCP FTP server clearen, etc) (staging) @maxvisser @DCP
- [ ] Een pas bestellen op het emmahuys, handelingen aan onze kant verichten @jamalv 
- [ ] Pas ontvangen bij emmahuys
- [ ] Pas koppelen
- [ ] Test transactie
- [ ] Champagne 🍾

**Comment by maartenfv** [comment]
Harald technisch
Erik org

**Comment by maartenfv** [comment]
Test is rond.
