### ISSUE TITLE
Minimum and Maximum voucher amount.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#641]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- DNB, Enigma

### Change description
- We need to have a policy in regards to the minimum and maximum voucher amount. 

What is the minimum amount?
What is the maximum amount?
What are the checks and balances to?

**Comment by maxvisser** [comment]
currently formula is not configurable by users; via generator they can generate a voucher of maximum of 2500 and minimum of 0.10 (i believe)

**Comment by jamalv** [comment]
@maartenfv it's a bit hard for me to prioritise this since i'm missing some context, what do you think? MoSCoW?

**Comment by maartenfv** [comment]
It is a compliance thing. We need to be able to asses risk in our text to DNB.

The system should have a max and a min for a voucher.  So we can combine this issue with making the voucher amount configurable. If someone fills in -10 then it should give an error like "minimum amount is 0,XX cents ". If someone fills in 999999999 then it should state maximum amount is XX,XX.
