### ISSUE TITLE
Show loading progress when uploading files in signupflow

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#642]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a requester I would like to see loading progress when uploading a file in the signupflow.

**Comment by maxvisser** [comment]
Design task:
Design for invidual files upload

Workflow:
Select a file
before you submit
you start uploading it

(Same as gmail when you add an attachment)

Implementing it task (maybe can be done on reviewing needing to upload files pr)

**Comment by danrminds** [comment]
Planned in - https://github.com/teamforus/forus/issues/1980
