### ISSUE TITLE
Change sprint naming

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#646]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
In 2020 we named sprints like: 2020-Q4-S5 | Weeks 49+50

2020-Q4-S5 is not intuitive, therefore weeks are added

The proposal is to simplify it in the new year:

yyyyWwwww

Since the new year starts soon, I think this would be a good time to do it:

<img width="1394" alt="Screenshot 2020-12-11 at 10 39 00" src="https://user-images.githubusercontent.com/30194799/101887391-1600fd80-3b9d-11eb-8da9-808f79643a43.png">

The result is that it's easy to figure out the sprint name based on week numbers.

**Comment by maxvisser** [comment]
propose to add a dash between numbers to make W33-34 more readable

**Comment by jamalv** [comment]
@maxvisser sure!

@maartenfv @TomForus what do you think?

**Comment by maartenfv** [comment]
Why is it not intuitive?

**Comment by jamalv** [comment]
Breaking up the year into "quarters" and "sprint numbers" to come up with the sprint name is a bit of a hassle IMO, and I don't see much added value. Just naming the sprints according to weeks seems a bit easier. Less is more? :)

**Comment by maxvisser** [comment]
@maartenfv just an example:
Called already with external team members a few times cause they labeled their invoices with the wrong sprint code. I find weeknumbers more intuitive and easier to explain.

**Comment by maxvisser** [comment]
As well we had issues with when an quarter stops two times this year where we had in zenhub for example Q2S6 or 7. Which didn't exist
