### ISSUE TITLE
Voucher generator: generate one activation code for each UID

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#648]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
If sponsor creates vouchers and activation codes in bulk. It would be a really nice functionallity to generate one activation code per UID uploaded

**Comment by jamalv** [comment]
@maxvisser I believe this has been planned?

**Comment by jamalv** [comment]
@maxvisser this is released, right?

**Comment by maxvisser** [comment]
Correct in 18.0
