### ISSUE TITLE
Implement digest notification  to sponsor about actions which changed price.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#650]
## Description
A provider can change the price of a product when a sponsor already started an action. In current system the action would stop and a notication would be sent to sponsor.

It would be a nice feature to add these notifications to the digest. Instead of sending a mail per action which got removed from webshop

**Comment by jamalv** [comment]
@maxvisser I think this issue should be moved to forus?

**Comment by maartenfv** [comment]
@jamalv @maxvisser no labels?

**Comment by maxvisser** [comment]
added labels; currently sponsor does not have an easy overview of which actions are stopped because of a price change by provider

**Comment by maxvisser** [comment]
my suggestion here is to add this information to a digest

**Comment by maxvisser** [comment]
duplicate of general#475
