### ISSUE TITLE
Show prices / amount available when you are logged out

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#651]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
GG

### Change description
As a requester I would like to see price and availability in the webshop, even if I'm logged out, so that I can check what I need to pay without having to log in.

<img width="1424" alt="Screenshot 2020-12-14 at 16 25 40" src="https://user-images.githubusercontent.com/30194799/102099858-0c8bc580-3e29-11eb-80f2-cb4230531263.png">

**Comment by jamalv** [comment]
@maxvisser, what do you think? I do understand this feedback :)

**Comment by maxvisser** [comment]
Why we don't show it: The amount available / price is dependend on your voucher. It could differ per fund. (for example the price could be 8 for parents 4 for children.)

I think we could show the price and the maximum amount available for one voucher (we can't guess how many children someone has). Not sure how easy or hard it is.

**Comment by maxvisser** [comment]
I see we have the prices and limit already in the response of the logged out state. Seems pretty easy to add. We should think how we display the information; 'Aantal per persoon' or something

**Comment by maxvisser** [comment]
fixed it on pr to develop

**Comment by maxvisser** [comment]
chose to use the label 'Maximaal per persoon' signed out; the same as they use now on the site.
