### ISSUE TITLE
CR: I can proceed without clicking the checkbox

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#652]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/10ed44e5-8426-41fc-a3dc-f68a71b07d1f)

**Comment by maxvisser** [comment]
Can't reproduce this issue. Could you show me how?

**Comment by maxvisser** [comment]
button is disabled
