### ISSUE TITLE
Page needs more space at the bottom. Can't see phone number

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#653]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groninge

### Change description
- The support tool covers info on the page.
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/00d61cfd-dbab-46e1-8818-22f825ef8bfa)

**Comment by maxvisser** [comment]
maybe move the support tool to bottom left? as there is enough space under the menu list.

**Comment by jamalv** [comment]
I think the location is good, we just need to add some spacing to the bottom of the page.
