### ISSUE TITLE
Clean up labels

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#655]
Remove:
Approval labels
Phase labels
Type labels
Status labels

Keep:
priority labels
scope labels
Status: On hold

type labels:
timetracking
bug
enhancement
epic

**Comment by maxvisser** [comment]
Added all labels to this issue which I think can be removed.

**Comment by maxvisser** [comment]
Project labels:
A project label should be used to indicate which 'demands' there are for a certain projects. Which could be added when a tender is won.

Customer labels:
Add a customer label for each client we have for their feedback points. Which currently are not in a project but we do want to keep track who brought in which issue

**Comment by maxvisser** [comment]
I would use easy to use abbrevations like for customer labels:
wk
nijmgn
sdoa
nop
gro
gtb

**Comment by maartenfv** [comment]
@demylubbers Heb je een idee voor deze issue?

**Comment by maxvisser** [comment]
we did not see your document before creating this issue; Lets write the proposal down and see which are still important and have goals

**Comment by demylubbers** [comment]
@maartenfv Ik denk inderdaad dat alle labels die Max heeft genoemd er uit kunnen en dat er misschien een label moet komen voor een intern budget of funding. Wellicht een klantnr ipv afkortingen, maar het verschil maakt mij niet zo heel veel uit. 

Je document helpt ook heel veel haha. Misschien een sessie met meerderen inplannen om verdere zaken hierover te bespreken?

**Comment by maartenfv** [comment]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/00455c8c-16c8-4663-9b16-9ec4302e76ea)

**Comment by maartenfv** [comment]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/d0e21c0d-0812-4175-a138-b248293eba4b)

**Comment by maartenfv** [comment]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/5c78a226-e47f-4ca7-a1ea-5f24e8b8932d)

**Comment by maartenfv** [comment]
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/faef2bd1-a90a-4cd1-a9ed-ff79b61f9f67)

**Comment by maxvisser** [comment]
Who will add these new labels to the issues?

**Comment by maxvisser** [comment]
I already saw you added them to all. Wil you keep doing that for all new issues coming in?

**Comment by maxvisser** [comment]
I get the usefullness of the labels but I rather have less labels which are well maintained then more usefull labels which are not maintained :sweat_smile:

**Comment by maxvisser** [comment]
removed the phase labels and type labels. As they were not used; Also I did not see them as usefull in anyway or form.

**Comment by maxvisser** [comment]
@jamalv Could you maybe write something about status labels and approval labels; how you see these being used and who and when we should add/update these?

@maartenfv There are two labels which I think you wanted: Request: Support, Request: Meerwerk; do you still see these as usefull (they are barely used)

**Comment by jamalv** [comment]
About approval labels, I use those mainly to show that it is okay to work on the issue (even though it's a **should have** or **could have** for example) for example because it's small and brings enough value to justify the investment of time.

**Comment by jamalv** [comment]
Status labels I think are useful for those who don't have zenhub/understand our pipeline and want to know the status of our development issues, but that's a pretty small audience I guess, and also we'd like to start using productboard for that soon.

**Comment by maxvisser** [comment]
> About approval labels, I use those mainly to show that it is okay to work on the issue (even though it's a **should have** or **could have** for example) for example because it's small and brings enough value to justify the investment of time.

I think both are solved by the intake board; as things are not going to the backlog without being approved right?

**Comment by maxvisser** [comment]
what we wrote about status labels in 'Wijzigingsbeheer' february 2020
![image](https://user-images.githubusercontent.com/10818702/105963868-ce1d3380-6081-11eb-8e74-8ee38fd93e44.png)

**Comment by maxvisser** [comment]
I can see why these are usefull still even with a board; but they need to applied by someone / updated

**Comment by maartenfv** [comment]
@TomForus What is the plan? @demylubbers will pick this one up?

**Comment by demylubbers** [comment]
@maartenfv I have planned a meeting about the different kind of labels. The goal of the meeting is to clearly understand why labels are used and to know which labels need to be added to our policy

**Comment by maxvisser** [comment]
ITSM still needs to be synchronized
