### ISSUE TITLE
Add breadcrumbs: When a sponsor allow a provider to join fund

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#656]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
I want to go back without cliking go back in browser.

Please add breadcrumbs here: ![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/b17c3ed2-3b79-43a8-a902-325946692c08)

**Comment by maxvisser** [comment]
Noticed this one too. I would like to increase the scope on this one abit @SjoerdHilhorst If you have time maybe you can look through the dashboards and add on all 'show' / 'details' pages breadcrumbs.

**Comment by maartenfv** [comment]
This would greatly improve UX. @SjoerdHilhorst

**Comment by SjoerdHilhorst** [comment]
something like 2-3 hours

**Comment by maxvisser** [comment]
released
