### ISSUE TITLE
CR: As a sponsor I would like to send custom mails / messages to the providers and requesters

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#657]
**Support Ticket ID:** [#2529]
**Support Ticket ID:** [#2782]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

### Change description
- As a sponsor I would like to send custom mails to the providers<br>

Edit: added support ticket of sponsor that also requested this.

@jamalv This needs a development proposal. 

We need to get the requirements exactly right before starting this.  I have broken this request up into two development proposals.

**Make System emails adjustable**
Ontwikkelvoorstel:  https://docs.google.com/document/d/1jnFYQ0p9SUCd4jN3YWsnF5_7I37AXp-uY_MgaLhu-vA/edit?usp=sharing
Figma: https://www.figma.com/file/E09uZSki0EQM7J7x5IeUiV/Webshop-%3E-System-e-mails 
Issue: Linked to this Epic (see below)

**Send custom emails to specific target groups**
Ontwikkelvoorstel:  https://docs.google.com/document/d/1-5-ToMKrqRt_2DECFOnFQJeSQbXWtUxwu5ZbJauZ8dQ/edit?usp=sharing
Figma:
Issue: Linked to this Epic (see below)

**Comment by GerbenBosschieter** [comment]
Requested by GTB

**Comment by maxvisser** [comment]
Don't see this as feasible (we are not an e-mailing application); They can export the list of mailadresses and use their own mail services for this?

**Comment by GerbenBosschieter** [comment]
We already have an system to message the providers. And this has been requested long time ago by others also.

**Comment by GerbenBosschieter** [comment]
And we are an e-mail application XD We send like a lot of automatic emails

**Comment by maxvisser** [comment]
Ah you want to adjust the approve and deny notifications or the digest? (like them edit those?)

If we would implement such functionality what I would propose is:
Add to notification; a 'messages' center. Here a sponsor can sent a message to provider (custom)
We sent notifications to provider that they received a new message in their dashboard

We currently already have this kind of functionality but it is on product level.

**Comment by maxvisser** [comment]
How this can look from workflow UX / perspective:
On home page we add some statistics and notification/messages
You can start / create a message:
Select a user type (provider / requester) -> show only providers / requester part of the fund of 
Select organization or requester mailadress
Select product *optional
Select fund request *optional

Fields: 'subject' 'message'

We show in message center all clarification requests and all messages about a product

If you are on a fund application of a provider you can start a converstation directly without filling in all details.

**Comment by maartenfv** [comment]
This is a must-have for Groningen. It was part of the aanbesteding. We will need to make a plan on how to send messages to providers, adjust system mail templates etc.

**Comment by maartenfv** [comment]
See comment above. This issue needs to have a plan and a Figma proposal. We need it to finish the Groningen project. This comes after Aanbod and CMS.

**Comment by maxvisser** [comment]
discussed on 11-02-2021 there is no concrete solution yet; we are stearing towards integration with a mail tool like mailchimp for sending news letters to mailadresses in our system. People can subscribe to the newsletter natively through the platform. Needs abit of resource in the API of mailchimp or we can start with a embedding a signup process.

questions:
is mailchimp privacy compliant? (american company?) @RobinMeles 
what are the integration options? @SjoerdHilhorst 
can we get as Forus a mailchimp account or does this need to be part of implementation?

**Comment by jamalv** [comment]
i should also still discuss this with stakeholders, to check their current situation and if this solves their needs

**Comment by jamalv** [comment]
Did a bit of research: pro of mailchimp is it's a big company and industry standard, con; doesn't seem to be available in dutch, and apearantly the tool is a bit hard to learn. Alternative option is a dutch company: https://www.iwink.nl/producten/mailer

Requirements: the list of e-mailadresses should stay in sync with notification preferences in our platform (GDPR, opt-in) - tool should be usable by municipality.

**Comment by jamalv** [comment]
Possible alternative to mailchimp:
- Zoho campaigns (don't need to update SLA)

**Comment by jamalv** [comment]
er is een plan voor de systeemmails; custom mail integratie moet nog verder besproken worden

beste om in 2 stukken te knippen; zodat custom mails al ingepland kan worden terwijl gewerkt wordt aan de integratie.

plan is voor eind volgende week er een punt achter te kunnen zetten

**Comment by maxvisser** [comment]
custom mails is het laatste idee; Sponsor kleine berichten via webshop naar inwoner te laten sturen in een 'berichten centrum' waarin ook de notificaties staan. Als gemeente een nieuwsbrief wil sturen naar inwoners kunnen ze er voor kiezen om:
- notificatie te sturen naar een website bijv. een blog/nieuwsartikel

dit zou wel een nieuwe werkwijze zijn en past wellicht niet bij de verwachting. Voordelen zijn wel groter dan een integratie met iWink / mailchimp / Zoho. Een berichtencentrum is breder inzetbaar; waar een nieuwsbrief heel statisch is en minder frequent gebruikt kan worden.

**Comment by jamalv** [comment]
donderdag weer meeting tussen max en maarten

**Comment by jamalv** [comment]
max en maarten zijn weer een heel stuk verder

ook relatie mails en notificaties is overwogen

als het klaar is graag feedback van @GerbenBosschieter en @jamalv

**Comment by jamalv** [comment]
vanmiddag tussen 15:00 en 16:00 maarten en jamal gaan er naar kijken

**Comment by maxvisser** [comment]
@maartenfv @jamalv could you give an update? is there any progress on the concept/proposal?
