### ISSUE TITLE
CR: DigiD Recovery option to sign up flow requester

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#659]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Citizens from Nijmegen will apply again next year. They maybe have forgotten their e-mailadres. This cr is about adding a recovery by DigiD to the signupflow.

**Comment by maartenfv** [comment]
@maxvisser Can you give this issue some more context?

**Comment by maxvisser** [comment]
Done

**Comment by maxvisser** [comment]
its planned for next sprint;

**Comment by maxvisser** [comment]
instead of making a figma proposal I just coded it.

**Comment by maxvisser** [comment]
released
