### ISSUE TITLE
CR: Add error when trying to sign in/up without clicking "Ik heb de privacy verklaring gelezen"

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#661]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen, Maarten

### Change description
- It needs to give an error like "Click the box before you proceed" "Click het checkboxje ....."

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/LdSjP6FuPCaqM3ioDn56Kx/Privacy-statement?node-id=53%3A574

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/a7f6fa91-568a-4b11-9f93-562bbd331bd0)

**Comment by maxvisser** [comment]
visual bugs are gone in 0.18.1 if still high priority we can add it to next sprint
