### ISSUE TITLE
Update me app text

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#662]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
-
## Should be:
<img width="812" alt="Screenshot 2020-12-21 at 14 48 32" src="https://user-images.githubusercontent.com/30194799/102784371-99d89800-439c-11eb-8a7b-6f23bd486e45.png">

## Current state:
<img width="854" alt="Screenshot 2020-12-21 at 14 54 41" src="https://user-images.githubusercontent.com/30194799/102784405-a230d300-439c-11eb-9b2d-6ca380bfd913.png">

**Comment by maartenfv** [comment]
Why is this blocked?

**Comment by maartenfv** [comment]
This one is important for first impressions.

**Comment by maartenfv** [comment]
This has gone live. We need to fix this asap.

**Comment by maxvisser** [comment]
released in v0.18.2
