### ISSUE TITLE
Provider signupflow: Add login state

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#663]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
As a provider that is already logged in, when I want to go to my dashboard using "aanmelden als aanbieder" > aanmelden > I would like to have a clear route to go to my dashboard if I have already signed up.

To reproduce use the groningen webshop

**Comment by maartenfv** [comment]
This is an important issue. When I try to log in the button is gone. (I am already logged in but did not know)

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/710a9fd3-aeda-4dc8-81a7-987571db74c4)

This issue breaks the flow and is confusing.

**Comment by jamalv** [comment]
issue is geplanned

**Comment by maxvisser** [comment]
this is not on producton yet
