### ISSUE TITLE
CR: Make download buttons clickable

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#664]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Implemenation

### Change description
 -  Download buttons need to be clickable. Now no link.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/38a875c8-daa1-464e-90ab-fb9acdc749ce)

**Comment by maartenfv** [comment]
@maxvisser Why is this blocked?

**Comment by maxvisser** [comment]
as it still needs to be built. If it isnt blocked any more it can be released
