### ISSUE TITLE
Update CMS: upload for images

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#666]
Update CMS: upload for images. Where do they have to place the image to get such a link?

<img width="1300" alt="Schermafbeelding 2020-12-03 om 18 21 15" src="https://user-images.githubusercontent.com/36952230/101064537-66bc9900-3594-11eb-825c-403b7e2f82cc.png">

- Update CMS with a function to upload an image (not by filling in a link to the image)
Something like a 'drop files' or a 'select files' function with a media library.

**Comment by jamalv** [comment]
Nice one :D @maxvisser could you rate scope? If it can be done with a small scope, I'll give this must-have. Maybe if it's not too big it can be a good one for sjoerd?

**Comment by danrminds** [comment]
This would need: 

1. Media directory with added images (to see the image and it's link)
2. In editor - possibility to add images to the directory
3. In editor - select an image form directory to insert in the text?

**Comment by maartenfv** [comment]
It is a must-have. Needs to be planned. Question is urgency.

**Comment by maartenfv** [comment]
Got a new signal from Groningen. They are running into this problem. Needs to be fixed asap.

**Comment by maartenfv** [comment]
GTB is running into this problem as well.

**Comment by maartenfv** [comment]
We need a preview functionality as well.
