### ISSUE TITLE
Add button for providers to providers page

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#667]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Knop+toevoegen+bovenaan+%22inloggen+voor+aanbieders%22+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%22nYZLtY2rQESuWgokMhYw8ZYADpFc%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
As an implementation holder, I'd like an easy way for providers to sign up. It's a must-have for Groningen.

<img width="590" alt="Screenshot 2021-01-19 at 09 43 27" src="https://user-images.githubusercontent.com/30194799/105009500-d5698f00-5a3a-11eb-81b4-0e59710d0b90.png">

Figma: https://www.figma.com/file/jkwGXZJgjQr37cfEwDWrm4/?node-id=0%3A1

**Comment by maxvisser** [comment]
as in for all webshops?

**Comment by GerbenBosschieter** [comment]
I don't like this idea for all webshops. Also not sure what to expect on mobile?

**Comment by maartenfv** [comment]
@jamalv What will we do with this feedback? 


Also made related issue: https://github.com/teamforus/general/issues/674

**Comment by maartenfv** [comment]
Added link to this issue to MS Teams Groningen Planbord.

**Comment by jamalv** [comment]
First step is a Figma proposal (https://www.figma.com/file/17admjCAaJF6ccIJappiCJ/?node-id=1%3A83), where we need to make sure it is a clear user experience, also considering what max mentioned about confused users.

When we have a good proposal, we can show it to the stakeholders. Then also we can make a decision on if this needs to be custom or if it can be generic. In general of course this button can lead to more provider signups, which is great, but we indeed need to be careful that it doesn't confuse the user. 

If we would want it generic then @maartenfv @linda-90 probably need to be involved for thinking about how/if we can do it for all webshops.

**Comment by jamalv** [comment]
Discussed this with leonie and paul today. The main goal is that people go into the right flow. 

Basically there are four routes we need to support:
- Sign up for providers
- Sign in for providers
- Sign up for requesters
- Sign in for requesters

There's a couple options:
- Add one (or more) buttons that direct to a page with explanation (previous solution for stadjerspas)
- Make the system "smarter" - with the recent updates we did, we might have some options here.

We'll need a figma proposal that solves these userflows, so we can also show groningen and get approval.

**Comment by maxvisser** [comment]
fyi if you guys accept the risk of users going through flow and creating organizations/going to the dashboard etc. lets go and the button to all implementations.

My proposal would be to add links to product / aanbieders pages 
![image](https://user-images.githubusercontent.com/10818702/103661538-21aecc80-4f6f-11eb-919b-ec738349227a.png)

**Comment by danrminds** [comment]
From the figma proposal I like this options:

For all webshops and all main pages - use that as a link in header:
![Screenshot 2021-01-05 at 18.52.56.png](https://images.zenhubusercontent.com/5ea2e8e74754fd7c3ad28537/0e284543-a1e1-495a-bf9f-7998eb73c991)

For the provider page - we can keep the same, or try to replace the button 
![Screenshot 2021-01-05 at 18.53.12.png](https://images.zenhubusercontent.com/5ea2e8e74754fd7c3ad28537/991e22a5-dda7-478c-8d1d-bd3aa0bc3e75)

**Comment by maxvisser** [comment]
Still think adding more options for citizens to click on and get misdirected is a poor design choice; 

I see the problem mostly in that the previous system had this button and the providers of groningen expect the button be there. (they will go to the site and if the button isnt present it will break their flow).

**Comment by jamalv** [comment]
Just discussed this with max, that a call to action in the header will probably cause confusion > proposal is to add the call to action in the providers page.
