### ISSUE TITLE
Requested koop op afstand.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#669]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Westerkwartier

Hi Maarten,
Kan je met Potjeswijzer ook al in webshops betalen? Zo niet, dan lijkt me dat een belangrijke functionaliteit voor de nabije toekomst.
Wat jij?
Groeten,
Erwin

### Change description
- Requested koop op afstand.

**Comment by maxvisser** [comment]
duplicate of #120

**Comment by jamalv** [comment]
voorstel: https://docs.google.com/document/d/1d78GE7HZq1gpbHkf8a5VQZkQy1IQMX_19Clnnx1iaOU/edit#
