### ISSUE TITLE
A validator should see activation codes that are generated within the same organisation.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#67]
**Is your feature request related to a problem? Please describe.**
The validator is part of an organisations who makes the budget for the requesters available.
The validator can't see activation codes that are generated within the same organisation.
Even the sponsor itself can't see these code. This can cause problems on numerous ways:

- The validators don't have a possibility to see others codes, so printing out these codes to send them by letter all in once, is not possible. Not even for the sponsor.
- What if a requester calls the sponsor with the question why the activation code doesn't work or says it's already activated ? It's really hard for the sponsor to figure out whats going on if they can't see the status of the code, they have to figure out who created the code before they can even help these people. And the validators are not the employees who help people, so they probably have to wait a while before they get any help.
- One of the validators already complained about this.

**Describe the solution you'd like**
Give the sponsor the option to display all the activation codes for every validator role.

**Describe alternatives you've considered**
only workarounds, no real solutions. Like using a group mail box as a validator account

**Additional context**:
I'm familiar with most of the arguments why the validations are based on profile and not based on the fund and why the codes are not visible for everyone.

- The idea of validations are more based on personal records than activation codes. You don't want to display all the personal records to every validator if it's not needed.
- Third parties can also be assigned al validator, they shouldn't have acces to al this information.

Most arguments are based on the platform we what to build in the future, because it fits the vision of decentralisation. But these arguments don't fit our current use cases. 

## Improvement proposal
https://github.com/teamforus/general/issues/67#issuecomment-626574827

## User story (?) (edit by jamal)
As a validator I would like to see all activation codes that are generated within my organisation

**Comment by maxvisser** [comment]
@jamalv I think no design for this one is needed. I will put this CR on refinement agenda.

**Comment by maxvisser** [comment]
## Impacted areas:

- [ ] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [x] Processes

## Current situation
The validators don't have a possibility to see each others codes

## Desired situation
Give the sponsor the option to display all the activation codes for every validator role.

## Tasks
- [ ] need to check on code level how much need to be rewritten.

**Comment by jamalv** [comment]
@GerbenBosschieter Is there still a strong desire here? What is the urgency/impact? Otherwise I'd like to move this request to productboard and close this issue. Is that allright?

**Comment by jamalv** [comment]
Added feedback to productboard and closing this issue: https://app.productboard.com/inbox/notes/18631847
