### ISSUE TITLE
Unclear actie price (discount or free?)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#670]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
- As a user I do not understand the following:

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/ca4671c1-58b7-4ae4-9c33-f275e0f1d4d6)

Is it free or is it 20 euro korting?

"Gratis" should state: 20,- euro korting.

**Comment by GerbenBosschieter** [comment]
This will be fixed in next release. We couldn't release it.

**Comment by maxvisser** [comment]
Will close this when next release is on production
