### ISSUE TITLE
CMS Updates and improvements

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#671]
## Context
The platform currently has a basic CMS. The current functionality is inadequate. Issues are being opened with proposals for improving the CMS. 

## Goal of this issue
- Have an overview of what needs to happen to the CMS in order to become adequate. (link CR's to this epic)
- Be able to discus general strategy of CMS; short term quickfixes vs a long term stragegy in the comments of this issue.

Figma: https://www.figma.com/file/TLxmLE6tw9YvigAPF1SPvp/?node-id=63%3A2386

Proposal: https://docs.google.com/document/d/14JLbaZfMjHHuVD12wISsf4Vp5KAAEFS1RDrhO9Dawic/edit

**Comment by jamalv** [comment]
@danrminds @maartenfv you both have a vision on this :) could you please discuss? :)

**Comment by danrminds** [comment]
Discussed with Maarten and Valentin.

Came up to the following proposal:

Build an enhancement on top of Markdown, which will represent a visual editor. For example, something like this:
![Screenshot 2021-01-13 at 16 40 54](https://user-images.githubusercontent.com/33207036/104474294-27835e00-55be-11eb-9025-10f630cb356a.png)

In fact, on the background is the same markdown happening, with same limitations, but we don't really want to give more functionality (like font style, colors, positioning, centring) 

The enhancement will allow us to make a preview directly in the field for the following functionality and text formatting:

 - [ ] Bold text
 - [ ] Italic text
 - [ ] List
 - [ ] Spaces and new lines
 - [ ] Headings (H1, H2, H3, H4, H5)
 - [ ] Images (with uploading directly from the computer)
 - [ ] Links

Any more ideas of what we might need?

Estimated implementation time for such a custom layer on top of the markdown editor - 1.5 to 2 weeks. 
@jamalv @maxvisser @maartenfv

**Comment by maxvisser** [comment]
@danrminds I like this one:
https://github.com/sparksuite/simplemde-markdown-editor

https://simplemde.com/

this one seems to have 15 stars:
https://github.com/hansottowirtz/simplemde-angular

if possible I would not like to build a markdown editor ourselves. Don't see this as a good time investment.

**Comment by danrminds** [comment]
@maxvisser Regarding the ones you proposed - I am not sure this is what the stakeholders are looking for:
![Screenshot 2021-01-23 at 11.59.05.png](https://images.zenhubusercontent.com/5ea2e8e74754fd7c3ad28537/9b6c1e89-e474-4610-8bc6-40f743ed8ddc)

Still having the `#, **, [links](https://google.com)` etc in the text

**Comment by jamalv** [comment]
ontwikkelvoorstel: https://docs.google.com/document/d/14JLbaZfMjHHuVD12wISsf4Vp5KAAEFS1RDrhO9Dawic/edit#

**Comment by jamalv** [comment]
@danrminds please review / finalize the master page: https://www.figma.com/file/TLxmLE6tw9YvigAPF1SPvp/?node-id=145%3A5291 & create seperate tasks for the implementation

**Comment by jamalv** [comment]
Currently the branch only misses the logo / header

**Comment by maartenfv** [comment]
Could we have an update for this issue. Is it possible to release this before 15 of March?

**Comment by jamalv** [comment]
this was discussed yesterday during refinement. valentin is working on this; it was mentioned "basically everything" wil be in scope :) - not sure about the release planning and if it will be before the 15th. @danrminds or @maxvisser do you know more about this?
