### ISSUE TITLE
Change request: Let sponsor set Expiration date for action

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#672]
**Support Ticket ID:** [#2571]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor (support request)

### Change description
- As a sponsor I would like the possibility to make some changes to actions<br>

This change request is related to: Adding action by sponsor but I see some option that could be useful for the sponsor without the scope being too big. The reason a sponsor would like to do some changes is because they want to influence what will be added to the webshop.  Giving the sponsor complete control of an offer is also not desirable because this wil influence other webshops.

1. Add option to sponsor dashboard when starting an action: add another expiration date, so they can set the expiration date to an action/offer in the context of the fund without removing the option to the provider to set an different expiration date for other funds.

2. Give the sponsor an option to change the description for the context of the fund. This way the sponsor doesn't decide the description of a product / action that is also active on different webshops.

**Additional information**
- From this support request I've also created a task: https://github.com/teamforus/forus/issues/2008

**Comment by GerbenBosschieter** [comment]
@maxvisser maybe it's better to spit this? Reason I did this in one CR is because it came from one support request.

**Comment by GerbenBosschieter** [comment]
Not going to split this one

**Comment by maxvisser** [comment]
scope is indeed medium; I think its highly connected to a 'paused' state #476
