### ISSUE TITLE
Me: change "voucher info" to "Aanbod" and link to actions/aanbod

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#675]
Learn more about change requests here: https://bit.ly/39CWeEE

### Change description
As a requester I would like the "voucher info" button in the me app voucher page to be changed to "Bekijk aanbod" (view offers), when I click it I would like to be redirected to the offers for this fund in the webshop.

**Comment by maxvisser** [comment]
@jamalv if you are done with a proposal could add it to this cr?

**Comment by maxvisser** [comment]
there is no proposal yet; implementation is not even planned. So this can't be released on monday. Moved to the next epic.

**Comment by jamalv** [comment]
@maxvisser what's the status of this on android?

**Comment by jamalv** [comment]
I have prepared a release for this on iOS; @maxvisser I heard you were working on an android 0.4.4 release? Could you make sure this is included? And the I think what's left is linking it to the offers (in-page scroll on the vouchers page was proposed by @dev-rminds) can this be done by a backend update? Or do the apps need to be updated as well?
