### ISSUE TITLE
Rename "acties" to "aanbod"

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#677]
@maxvisser commented on [Thu Sep 10 2020](https://github.com/teamforus/forus/issues/1758)

## Context/goal: 
<img width="675" alt="Screenshot 2020-12-30 at 10 45 46" src="https://user-images.githubusercontent.com/30194799/103343397-42b58000-4a8c-11eb-9af6-f8606f8c8984.png">

---

@maxvisser commented on [Mon Sep 21 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-696098909)

Fixed

---

@maxvisser commented on [Wed Nov 25 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-733783579)

@SjoerdHilhorst I see you changed the page subsidies to 'Aanbod' and the navbar item to 'Aanbod'; seems that this was not in the text fix issue as a planned task. Could you revert these changes?

---

@SjoerdHilhorst commented on [Mon Nov 30 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-735639951)

This mentions changing it to "aanbod":
https://docs.google.com/spreadsheets/d/1B1rSQjzejkIMThG2bAIW27Xg6Ol2GLY-hLts7b5vcsI/edit#gid=433994186&range=C26

@jamalv what do you think

---

@maxvisser commented on [Mon Nov 30 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-735670355)

We already reversed the change in release 0.16.3

---

@maxvisser commented on [Mon Nov 30 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-735670565)

Did you implement any other textual fixes from the spreadsheet? 

---

@maartenfv commented on [Tue Dec 22 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-749616268)

@jamalv Can we change it to aanbod? As requested by Groningen?

---

@maxvisser commented on [Wed Dec 23 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-750081915)

Please open a new CR instead of opening old forus tasks.

**Comment by jamalv** [comment]
The preference of groningen is to name this "aanbod", this also fits with how it's named on other webshops. The only thing that could be blocking this name change afaik is the seperation of funds. 

@maxvisser what do you think? is it already feasible to merge subsidies and budgets? The best result would be that we don't need a "split" between subsidies and funds anymore, and that for the requester both can be named "aanbod" - then filters / submenu's can be used to make it easeier to find things.

**Comment by maxvisser** [comment]
not sure what you mean with feasible. lets do a refinement session to see whats needed. I don't see a reason to not change Acties to Aanbod in menu and on pages already.

**Comment by jamalv** [comment]
Okay, in that case let's go :)

**Comment by jamalv** [comment]
@danrminds please plan this in

**Comment by danrminds** [comment]
Planned in
