### ISSUE TITLE
Signup form providers can't click on next step if they don't have a phone number

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#678]
Learn more about change requests here: https://bit.ly/39CWeEE

Related: https://github.com/teamforus/general/issues/590

### Requested by:
- As a provider I would like to not get stuck on signup form if I have don't have a simcard or whatever the reason is I can't receive an sms

### Change description
- Stop limiting the provider that they NEED a way to receive an SMS before they can click to the next step. Even if we would tell the provider a hundred ways to install app besides doing it by phone number. They still can't proceed.

Related issues:
- https://github.com/teamforus/general/issues/615
- https://github.com/teamforus/general/issues/614
- https://github.com/teamforus/general/issues/613
- https://github.com/teamforus/general/issues/616
- https://github.com/teamforus/general/issues/601
- https://github.com/teamforus/general/issues/234

**Comment by maxvisser** [comment]
as we are already in the proces of building this figma proposal:
https://www.figma.com/file/Jf9evMRyAVEbzy4EDubvTr/Download-Me-UX-iPad?node-id=176%3A138&viewport=371%2C112%2C0.10725218057632446

Could you check it?
