### ISSUE TITLE
Privacy verklaring needs an update.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#680]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
- Privacy verklaring needs an update. https://stadjerspas-acc.gemeente.groningen.nl/privacy 

Eerste zin. gegevens worden niet alleen bij de aanvraag opgeslagen, het gaat vooral om ‘bij het gebruik’ . Ik denk ook dat het goed is aan te geven dat de gegevens niet allemaal op de pas worden opgeslagen (zodat men niet bang hoeft te zijn dat men de pas verliest).

Inkomensgegevens vind ik vaag. Gaat het om het (belastbaar) jaarinkomen? Zeg dat dan.

#kinderen. Wordt ‘automatisch bijgeschreven’ Is dat belangrijk om te melden? Inkomen wordt waarschijnlijk ook automatisch bijgeschreven. Ik zou het weglaten. Op het account? Gewoon zeggen: ‘ Thuiswonenden kinderen tot 18 jaar  omdat…..’.

Kan het zijn dat ik de NAW gegevens mis?

**Comment by maartenfv** [comment]
Related to issue: https://github.com/teamforus/general/issues/679 This would save us a lot of time.

**Comment by maartenfv** [comment]
Nieuwe text staat in dit document: https://docs.google.com/document/d/1oDCenX-YEtbX8sXhs7x9bQ60xm3nLMB5oA4fa8wrT1U/edit

**Comment by maxvisser** [comment]
released
