### ISSUE TITLE
CR: Lines need to be gelijk

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#681]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Implementation and Support

### Change description
- Lines need to be equal. Now is messy,

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/eecf32c5-6b17-4e0f-8949-8e19aef61e35)

**Comment by maxvisser** [comment]
Released
