### ISSUE TITLE
CR: Add breadcrumbs and option to go back from provider page.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#682]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
- Needs breadcrumbs/option to go back

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/89a3fb96-4e28-42de-b064-35be7097c7b5)

**Comment by maxvisser** [comment]
duplicate #493 that one was closed by me somehow. thanks for opening this
