### ISSUE TITLE
Make helpcenter call to action more prominent

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#684]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Original dutch CR: verplaats het vraagteken naar de menubalk, of noem het daar “help”

English: People are often missing the helpcenter, it should be made clearer by moving it to the menubar or to "help"

**Comment by maxvisser** [comment]
its already there; its called 'Uitleg'

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/104915856-887dae00-5991-11eb-90db-3cb297749fdf.png)

**Comment by jamalv** [comment]
Are there other ways to link to the helpcenter? Could we also add a direct link on the uitleg page?

**Comment by jamalv** [comment]
Needs helpcenter for requesters.

**Comment by maxvisser** [comment]
@GerbenBosschieter @MichaelForus Helpcenter is nog nergens geimplementeerd; Deze issue komt uit potjeswijzer usertesting. De testers gaven aan dat door dat de helpcenter knop wit op wit is het niet opviel. Vraag:

Wat zijn de opties voor de icon? kunnen wij deze omzetten iets wat wij zelf hebben ontworpen?
