### ISSUE TITLE
CR: Unify export UI

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#69]
## Problem
Export buttons UX feels weird. The way we allow users to export data is with buttons. these buttons are sometimes below the list, sometimes above the list and sometimes within a filter.

I propose to align where we put these buttons

## Context/goal: 

Example I like:
![image](https://user-images.githubusercontent.com/10818702/69551897-c5bcfa80-0f9d-11ea-9cda-4a3d993a203e.png)

Export of a list should always be on filter. If no filter is set button should say 'Exporteer alles";
if a filter selection is set it should display "Exporteer selectie"

**Comment by jamalv** [comment]
@maxvisser I believe this has been done?

**Comment by maxvisser** [comment]
correct can be closed.
