### ISSUE TITLE
CMS | Allow the "aanspreekvorm" Jij / jouw vs U / Uw to be adjustable

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#690]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen

### Change description
- This issue needs to be fixed before the end of Q1 2021.

Every U / Uw needs to be adjustable Jij/ Je. Trough CMS.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/3ce406bc-b7ce-4004-a082-2f02cffac24c)

**Comment by maartenfv** [comment]
@jamalv We need to make a plan on how to index the exact scope on where all the aanspreekvormen should change. needs FIGMA.

**Comment by maxvisser** [comment]
This would make maintaining the system much harder. I would say its better to just rewrite all cases where we do this to not include 'jij or u'

**Comment by maartenfv** [comment]
I think the user story is something like: As a Sponsor I want to be able to choose the "aanspreekvorm" for the webshop inc. all the notifications and modals so the requester is only addressed in the form I prefer.

We should consider the goal of being able to set up a new webshop without any manual actions. I expect that more municipalities will have similar requests. During the next implementation, this should not be an issue.

**Comment by jamalv** [comment]
Should be added to CMS page

@GerbenBosschieter and @maxvisser already had some ideas? 💡

**Comment by jamalv** [comment]
needs a flag on backend, and then implementation on backend
- push notifications
- e-mail
-

**Comment by jamalv** [comment]
@maxvisser could you create a task for the backend stuff and also for the frontend stuff?

- backend flag (hello world)
- in cms have toggle: "aanspreekvorm" [je/u]
- indexing all the places where it's used and adjusting in figma
- implementing it in the frontend

**Comment by jamalv** [comment]
hello world: 
- login mail & login modal

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/TLxmLE6tw9YvigAPF1SPvp/CMS?node-id=63%3A3555

**Comment by jamalv** [comment]
@danrminds please review the design: https://www.figma.com/file/TLxmLE6tw9YvigAPF1SPvp/CMS?node-id=63%3A3555

**Comment by linda-90** [comment]
Can this also be added to the CMS?
Upload for images: https://github.com/teamforus/general/issues/666

**Comment by jamalv** [comment]
@danrminds when doing design review, could you also add #666?

**Comment by jamalv** [comment]
@jamalv todo: akkoord krijgen van gemeente op voorstel

**Comment by linda-90** [comment]
Besproken met Max: teksten DigiD zijn aangeleverd, kunnen niet worden aangepast.

**Comment by jamalv** [comment]
Apps moet gebeuren.

Technische koppeling webshop moet nog: ligt bij Max.

**Comment by jamalv** [comment]
@maxvisser zou jij deze met @SjoerdHilhorst op kunnen pakken?

**Comment by jamalv** [comment]
e-mails zijn vrijdag afgemaakt - fonds gesloten en voucher verloopt konden niet getest worden.

notificaties missen nog; hier hebben we nog wat tijd van Valentin van nodig - vraag willen we de oud verstuurde notificaties ook aanpassen?

**Comment by jamalv** [comment]
eerste reactie oud verstuurde notificaties optioneel

**Comment by jamalv** [comment]
gaat deels mee op de 15e moet uiterlijk eind dit kwartaal opgeleverd worden

**Comment by jamalv** [comment]
voor de me app (iOS) is het gefixeerd

**Comment by jamalv** [comment]
mails zijn gebeurt (nog 2 moeten getest worden)
webshop is behalve misschien hier en daar een modal gefixed
me ios is gefixed

voor android: @SjoerdHilhorst kan je de strings xml doorlopen en alle "u" dingen naar je/jij veranderen?

**Comment by jamalv** [comment]
en op dev doorlopen of alles is aangepast

**Comment by jamalv** [comment]
in afwachting van wanneer valentin het af kan maken:

maarten: volgende week gaat valentin hier mee bezig

**Comment by maxvisser** [comment]
E-mails and most of the texts in the webshop are now changable via formal/informal toggle.

**Comment by jamalv** [comment]
notificaties worden nog gedaan, en dan goede check nodig voor 29ste

**Comment by jamalv** [comment]
voorstel: test backlog voor jij/jou (en ook voor tot en met) - zodat test uren optimaal worden benut.

moet goed _goed_ getest worden anders inconsistency geeft @GerbenBosschieter aan

@GerbenBosschieter maakt overzicht van test backlog

**Comment by jamalv** [comment]
gerben geeft aan: ik verwacht dat duidelijk is wat in de release komt zodat ik weet wat ik moet testen.
maarten vraagt: is er een zenhub test workspace? kunnen we hier naar kijken?

**Comment by maxvisser** [comment]
staged. still needs checking the whole webshop/e-mails
