### ISSUE TITLE
"10 maanden eerder" - what does it mean?

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#691]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Currently on staging:

Better would be: "Laatst actief: xxx"

<img width="498" alt="Screenshot 2020-12-28 at 17 25 38" src="https://user-images.githubusercontent.com/30194799/103228813-f2c2a600-4931-11eb-8fb2-9bc00e95a93a.png">

**Comment by maxvisser** [comment]
as it is not on production yet; I will close this

**Comment by jamalv** [comment]
What's the right place for this feedback? I don't think it should be released like this :)

**Comment by jamalv** [comment]
Also on staging: I think Uid should be changed to ID Nummer:

<img width="641" alt="Screenshot 2020-12-29 at 10 20 11" src="https://user-images.githubusercontent.com/30194799/103273405-855d5680-49bf-11eb-949d-e02ff67eac93.png">

**Comment by maxvisser** [comment]
release pull request
