### ISSUE TITLE
Make digid mandatory, also if used before

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#693]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Nijmegen

### Change description
Currently you can skip DigiD. That should not be possible. Nijmegen is open to it for next year, but does not want it this year.

Change: hide the "overslaan >" button (can be done for all implementations. Then if we make DigiD optional, also discussed with clients, then the whole step can be skipped.

**Comment by jamalv** [comment]
## Hide "overslaan"

<img width="965" alt="Screenshot 2020-12-29 at 13 17 48" src="https://user-images.githubusercontent.com/30194799/103283236-48ea2480-49d8-11eb-8f53-6caa0870049f.png">

**Comment by jamalv** [comment]
@maxvisser why is this medium? seems small?

**Comment by maxvisser** [comment]
Not sure about it. Seems more difficult then just removing the link.
Also: 
Nobody will run into this the first weeks as people will have a meedoenregeling and they can't request a new one.

**Comment by maxvisser** [comment]
will be discussed with @dev-rminds

**Comment by maartenfv** [comment]
@jamalv Kan je tijdens komende overleg hier de release voor afstemmen? is dit 18 jan.?

**Comment by jamalv** [comment]
@maxvisser ik zie geen ontwikkel taak? is deze goed ingepland?

**Comment by maxvisser** [comment]
zit in deze release
