### ISSUE TITLE
Hide "aanvragen" from menu

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#694]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Leonie

### Change description
Currently this page can only cause confusion, when more funds are added we can add it back.

**Comment by maxvisser** [comment]
this can be done with configuration but if #591 is not fixed; this can result in people not begin able to get back to the form

**Comment by maxvisser** [comment]
No development would be needed; this can go to ITSM

**Comment by maxvisser** [comment]
@jamalv maybe it would be better to hide it logged out?

**Comment by jamalv** [comment]
yea that would be okay i.m.o 👍

**Comment by maxvisser** [comment]
Ok will plan this in.

**Comment by maxvisser** [comment]
released
