### ISSUE TITLE
Discounts should not be "free"

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#695]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
Currently discounts are displayed as "free" - this is a showstopper since this can mean that citizens will misinterpret and maybe even try to abuse it, this can cause discomfort to the providers/sponsor

Suggestion: if it's a discount; simply remove the label

<img width="1340" alt="Screenshot 2020-12-29 at 13 08 48" src="https://user-images.githubusercontent.com/30194799/103282740-0247fa80-49d7-11eb-97d3-ac90040c76dd.png">

**Comment by maxvisser** [comment]
could you link an example?

**Comment by maxvisser** [comment]
found it: 
https://stadjerspas-acc.gemeente.groningen.nl/products/1718

**Comment by maxvisser** [comment]
I will plan this is directly as development task. I will do this myself as I also developed the fix for sample/list/grid; Forgot that we also show 'Gratis' here.

**Comment by maxvisser** [comment]
released
