### ISSUE TITLE
Export CSV files should open well in excel

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#698]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Controle+export+lijsten+(algemeen)+in+excel+kolommen+aanpassen+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%22dudTIu5J80-__1Ys-Plg7pYAP10X%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
Currently CSV files are not loaded well into excel. The columns are not displayed. This makes the files unusable for users with less know-how to change excel import settings. The goal of this issue is to make sure our files are loaded well with default settings.

**Comment by maxvisser** [comment]
We need someone with excel to make a proposal. (What is needed); currently can't really estimate the scope.

**Comment by jamalv** [comment]
Comment from @danrminds; the settings are different for each configuration of excel. You'll need to update your configuration. We can change the export, but it will then not open on other systems. 

Could we check what is the default for excel and adjust accordingly?

@demylubbers could you do a bit of googling on what's the default and put the answer here?

**Comment by jamalv** [comment]
@danrminds could you check demy's example and see if a task can be planned?

**Comment by demylubbers** [comment]
If you put a seperator in the front of the file, it works. See the screenshot for the work around.
Open up your csv file in notepad en put in: sep=, 
The seperator depends on the used seperator of course, could also be ";" for example.

![image](https://user-images.githubusercontent.com/70149827/103652853-fe325480-4f63-11eb-9ced-918caa13f516.png)

**Comment by danrminds** [comment]
Seems to work. Basically - this enforces the setting I commented above

**Comment by jamalv** [comment]
@maxvisser could you give a status update?

**Comment by jamalv** [comment]
discussing with dan; conclusion was to add two buttons for export / a modal: Export [.CSV] or [Excel]

**Comment by jamalv** [comment]
@aghimpu needs to go trough all places where we have an export and make it possible to export both, excel and csv, @danrminds could you create the task?

**Comment by jamalv** [comment]
SjoerdHilhorst
commented on Feb 4, 2021
voucher generator, csv
prevalidation, xls
fund requests, xls
voucher transactions, xls
fund provider request list, xls

Discussed with max; the example files can be excluded from the scope. They show the example that is needed.

The proposed fix is to add the XLS option to the voucher generator as that is currently the only place where no XLS is exported yet.

Scope: Voucher generator will have: CSV, PNG + CSV, PDF + CSV, XLS.

**Comment by maartenfv** [comment]
@maxvisser @danrminds Can we release this before 15 of march? What is the status?

**Comment by maxvisser** [comment]
This is on the sprint backlog; currently not done yet; if its still done before wednesday it could make the release.

**Comment by maartenfv** [comment]
@maxvisser Do you have an update here? Has it been released?

**Comment by jamalv** [comment]
@danrminds mentions it's been deployed

**Comment by maxvisser** [comment]
Its not.

**Comment by maxvisser** [comment]
The problem is solved in next release we will add more export options (.csv option to alle exports)
