### ISSUE TITLE
Let sponsor add/update actions

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#699]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Gemeente+wil+zelf+rechtstreeks+aanbod+kunnen+aanpassen+zonder+inspraak+van+aanbieder.+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%2267OY1MAW706Hp-kL6sX8L5YANtaG%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
As a sponsor I would like to add/update actions without provider interference.

**Note:** this issue is very big and quite far from our current architecture. Before we can do development quite some concept development is needed. We should explore possibilities so that we can facilitate an open discussion with the client.

### Ontwikkelvoorstel
https://docs.google.com/document/d/1nauBetwGTl40w5QqNVpv6nPNj0iHLlxDiNNjrOXGYhg/edit

### Figma
Link naar Figma: https://www.figma.com/file/zhX7Ra83QmhftuT93U06E6/?node-id=0%3A1

**Comment by jamalv** [comment]
@maxvisser I believe you had some brainstorm recently about a sponsor being able to start an action?

**Comment by maxvisser** [comment]
No sorry. I did not 👍

**Comment by maartenfv** [comment]
The link to the written proposal and to Figma have been added. Goal is to get this clear before the end of the week.

**Comment by maartenfv** [comment]
After we have an agreement with GRO we need to add a release date and communicate this to GRO.

**Comment by danrminds** [comment]
Planned it in. 

Several questions left @jamalv @maxvisser 

1. We need most probably a new status to an action - in case the provider stopped it. Something like - stopped by provider. Please provide the translation.
2. We need the product page on the provider dashboard
3. We need the funds page on provider dashboard (to show also the link to the terms)
4. Regarding terms - should we oblige the provider to open the link, scroll it down (in a modal) and only after this apply to the fund? Or just like this?

**Comment by jamalv** [comment]
1. Translation: "Stopgezet door aanbieder"
2. It can be the same page i think, using tabs to seperate views (as in figma)
<img width="786" alt="Screenshot 2021-02-10 at 11 00 33" src="https://user-images.githubusercontent.com/30194799/107494537-35150f00-6b8f-11eb-94ce-1de3c08cc0e2.png">

Main thing is to show what sponsor/fund the product is active for, and that you can stop it. You cannot edit it: https://www.figma.com/file/zhX7Ra83QmhftuT93U06E6/699-Let-sponsor-add-update-actions?node-id=307%3A0

3. Added it: https://www.figma.com/file/zhX7Ra83QmhftuT93U06E6/699-Let-sponsor-add-update-actions?node-id=307%3A872

4. I expect the terms and conditions can just link to the provider CMS page, terms can be added there trough the cms: https://stadjerspas.gemeente.groningen.nl/aanbieders/aanmelden

**Comment by jamalv** [comment]
@danrminds when do you expect this to be ready for review?

**Comment by jamalv** [comment]
update from @dev-rminds everyting is running according to planning. release still on 15th
