### ISSUE TITLE
Voucher generator: unassign unused vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#70]
## Description

A sponsor can create a voucher via voucher generator. It is pretty easy to make a mistake in e-mail address which the sponsor wants to assign the voucher to. This is issue is about making it possible to  block unused assigned vouchers. This will help the sponsor to easily undo mistakes.

As a sponsor I would like to block a voucher when it has not been used

## Task

- [ ] Let sponsor set a voucher to blocked when unused (and generated via voucher generator).

**Comment by jamalv** [comment]
maybe this will be superseded by https://github.com/teamforus/general/issues/806?
