### ISSUE TITLE
Add titles to provider dashboard (organisation / personal)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#700]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Provider](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Titels+in+rechter+menu+aanbieders+omgeving+ontbreken+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%222_B1fDSrsUKnOsiAxotilJYANKGO%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
Add menu titles:

Organisatie

Persoonlijk

![Screenshot 2020-11-30 aanbieder titel in menu 120229](https://user-images.githubusercontent.com/30194799/103294586-6fb55480-49f2-11eb-8ffa-f8596225e34a.jpg)

Original dutch CR:
Aanbieder geeft aan dat ze niet duidelijk begrijpt welke onderdelen in het menu over de organisatie gaan en welke over het persoonlijke account. Er is een verschil tussen de tab's. Dit kan mogelijk worden opgelost door in het menu een titel toe te voegen. Er is nu wel een horizontale streep om de menu-items te verdelen. Hier kan nog een titel worden toegevoegd.

Voorbeeld:
"Instellingen organisatie"
"Instellingen persoonlijk"

**Comment by jamalv** [comment]
@danrminds could you plan this in?

**Comment by maxvisser** [comment]
Do we have a figma proposal for this (what font size, colors do we use?)

**Comment by danrminds** [comment]
@maxvisser That is exactly why I planned it for design for @sashooa in forus#2035

**Comment by maxvisser** [comment]
I see haha :)
