### ISSUE TITLE
Product details page: Remove button "aanvragen" for logged out users

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#701]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Knop+%22Aanvragen%22+verbergen+bij+aanbiedingen+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%22tJYiwoN-q0aQ46sPJp9N1pYAKQUw%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
In the context of Groningen, the "aanvragen" button on the product details page is expected to cause confusion to logged out users. Since it seems like you have to apply to each product seperately. 

In order to avoid questions, the client urgently requests for this button to be hidden for logged out users.

<img width="1242" alt="Screenshot 2020-12-29 at 16 55 03" src="https://user-images.githubusercontent.com/30194799/103296605-b016d180-49f6-11eb-953b-ccc4e3aa1ad4.png">

**Comment by maxvisser** [comment]
Why would it not be confusing for other implementations?

**Comment by jamalv** [comment]
Yea agreed, maybe we can remove it for all logged out users, and only show these options if you are logged in.

**Comment by jamalv** [comment]
Or maybe changing the word to "aanmelden" could also help make this less confusing.

**Comment by jamalv** [comment]
For now the preference is to not show it if you are logged out.

**Comment by jamalv** [comment]
@maxvisser why is this closed, the button still is there:

(screenshot from production)

<img width="1680" alt="Screenshot 2021-01-05 at 10 32 10" src="https://user-images.githubusercontent.com/30194799/103629965-45f3b480-4f41-11eb-953e-23f4c476a322.png">

**Comment by maxvisser** [comment]
Created a task for it.
