### ISSUE TITLE
CR: Add euro symbol when scanning actions

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#702]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
Every price needs an euro symbol. Currently the app doesn't show an euro symbol when scanning vouchers with actions on it.

![noprice](https://user-images.githubusercontent.com/38419514/103353586-87034900-4aa9-11eb-9781-2ebea9285744.jpg)

**Comment by jamalv** [comment]
dun
