### ISSUE TITLE
Remove sentence from first screen after scanning action voucher

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#703]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- We inform the provider about that the requester should do a payment at the cashier. This sentence doesn't fit al scenario's. Sometimes there is no price or the action is just free

We should use the sentence after selecting an action or just remove it and inform the provider at the payment screen.

![Kieseenactie](https://user-images.githubusercontent.com/38419514/103354578-35a88900-4aac-11eb-92c1-6ebd7897623f.jpg)

**Comment by maxvisser** [comment]
this is still the case on android on production
