### ISSUE TITLE
Hide: "totaal in omloop" - for subsidy fund

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#704]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description

This variable doesn't seem to make sense for subsidy funds (how would you calculate it?)

<img width="256" alt="Screenshot 2020-12-31 at 12 20 47" src="https://user-images.githubusercontent.com/30194799/103408677-c8f0c580-4b63-11eb-85c7-a14090d854e3.png">

**Comment by maxvisser** [comment]
Subsidy funds *

**Comment by jamalv** [comment]
changed

**Comment by maxvisser** [comment]
superseded by general/740
