### ISSUE TITLE
"Aanbod" on index page of webshop needs to be randomized.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#707]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- 

### Change description 

**Currently,** there are a lot of aanbiedingen from the same provider on the home page. It probably takes the newest ones. 

**Should be** changed to more random aanbiedingen. Would be best that it makes a random selection every time you reload the page. This way all providers get a equal chance.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/45833544-ee9b-4451-8df7-51671859d1a3)

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/51b49edd-3aca-4580-9f8b-daa709706a1c)

**Comment by maxvisser** [comment]
I remember this being the case for other sample. Aswell that products without an image were not part of this selection
