### ISSUE TITLE
Change modal when stopping an action

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#708]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description

The modal says the change is permanent, but that is not the case.

Proposal:
"U verwijderd het aanbod hiermee uit de webshop"

"Informeer inwoners en aanbieders" <- maybe this line can be removed?

<img width="708" alt="Screenshot 2021-01-04 at 11 37 44" src="https://user-images.githubusercontent.com/30194799/103526537-5cd2d200-4e81-11eb-85f7-cab752c90713.png">

**Comment by maxvisser** [comment]
maybe describe better what happens:
- number of times used remains the same after stop / start action
- when stopped, the action is removed from the app and the provider cannot start a transaction

**Comment by jamalv** [comment]
@maxvisser sounds good. I think we'll need a text proposal? @maxvisser could you write a sample line of what you mean so it's easier for linda to do a proposal?

@linda-90 could you have a look at this?

**Comment by maxvisser** [comment]
"u staat op het punt de actie te stoppen. Dit betekent dat de actie niet meer zichtbaar is in de webshop en de aanbieder geen transactie meer kan starten op deze actie. Het tegoed dat de inwoner heeft gebruikt blijft bewaard. Wanneer u later de actie opnieuw start wordt deze afgetrokken van het limiet."

**Comment by jamalv** [comment]
@linda-90 could you please check the text above?

**Comment by linda-90** [comment]
"U staat op het punt de actie te stoppen. Dit betekent dat de actie niet meer zichtbaar is in de webshop en de aanbieder geen transactie meer kan starten op deze actie. Het tegoed dat de inwoner heeft gebruikt blijft bewaard. Wanneer u later de actie opnieuw start wordt deze afgetrokken van het limiet."

Titel: Actie stoppen
Tekst: Let op: de actie is hierna niet meer zichtbaar op de website en inwoners kunnen er geen gebruik meer van maken.

**Comment by linda-90** [comment]
![image](https://user-images.githubusercontent.com/36952230/103945041-db0acf00-5134-11eb-8599-675e2e48b530.png)

**Comment by maxvisser** [comment]
top

**Comment by maxvisser** [comment]
wellicht de beschrijving uit het rode stuk halen;

**Comment by maxvisser** [comment]
@jamalv what do you think; could you adjust linda's proposal; maybe needs design review.

**Comment by jamalv** [comment]
This looks good, I think it can be planned, indeed might need some design review.

**Comment by maxvisser** [comment]
title in the box;
text-align: center;
description could be below the alert box; also aligned center
