### ISSUE TITLE
Tot / tot en met: make this consistent

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#709]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Duidelijkheid+geven+over+vervaldatum+van+een+aanbod.+Is+het+%27tot%27+of+%27tot+en+met%27%3f+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%22Ygu85u4Rl0iJ8HO8H6gZypYAFJN9%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
Sometimes there is confusion about until what date something is. We should have a clear policy on this.

Proposal:

A date is **Always** "tot en met"; meaning if something is until the 15th, this should **include** the 15th

**Comment by jamalv** [comment]
@danrminds please plan this in

**Comment by jamalv** [comment]
@maxvisser who would be good to do this?

**Comment by maxvisser** [comment]
Someone needs to go through the system and look at all the dates and see if these are cosistent:
Me-app
Webshop: budget voucher page, product page, product voucher

Requirements:
All fields we let user set where we ask an expire date it should work as 'Tot en met'/'up to and including'
All fields we show to the user should be shown as 'Tot en met'/'up to and including'

**Comment by maxvisser** [comment]
Lets make an proposal task and ask during refinement if the task is clear and who can do it.

**Comment by admin-forus** [comment]
This is marked as an urgent problem for Gro since December 04 2020. What is the status?

**Comment by jamalv** [comment]
@danrminds @maxvisser could you give a status update?

**Comment by maxvisser** [comment]
@admin-forus the issue Groningen was that we showed an expiration date which was after the end date of the fund.

If there is any concrete smaller issue we can fix now. We can. To fix them all at once we are planning to do this right after adding products as a sponsor.

**Comment by maartenfv** [comment]
This was agreed upon with Groningen to be part of the release of the 15th of March. It was mentioned as point 9 in the Notes send to us by Bas and Danielle. It has been removed from the release and was placed in Icebox. We need to fix this one as soon as possible.

**Comment by maxvisser** [comment]
Ah I see I accidently added it to the icebox while creating a new workspace in Zenhub; probably more issues are moved in the whole team workspace to icebox.

**Comment by jamalv** [comment]
loopt stuk op Valentin moet het doen (planning) - @maxvisser kan jij even met valentin checken of hier nu aan gewerkt kan worden - goed testen is hierin cruciaal geeft max aan.

**Comment by jamalv** [comment]
vraag van maarten: hoeveel tijd kost dit nog zodat dit ingepland kan worden? wat is er voor nodig? @maxvisser @jamalv

**Comment by jamalv** [comment]
zal bovenstaande vraag straks bij refinement stellen

**Comment by jamalv** [comment]
maarten heeft over planning gesproken met dan: valentin kan het oppakken onder aftercare groningen

**Comment by jamalv** [comment]
gister tijdens refinement besproken, valentin is er mee bezig

**Comment by jamalv** [comment]
er is een pull request.

**Comment by maxvisser** [comment]
staged in release 22
