### ISSUE TITLE
remove general landing page; Make first step signupflow the startpage.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#71]
## Context/goal: 

The landing pages can be archived and maybe reused as content on the webshop. We will implement the fist page of the signupflow as the base of the landing page. 

![image](https://user-images.githubusercontent.com/10818702/68406455-2799f980-0182-11ea-9b03-6aba077ddbc5.png)

![image](https://user-images.githubusercontent.com/10818702/93738989-81af7c00-fbe7-11ea-9146-ffee91b9e72a.png)

**Comment by maxvisser** [comment]
@danrminds @maxvisser should plan a seperate refinement call for this issue. Low priority now.

**Comment by jamalv** [comment]
I think this is related: https://github.com/teamforus/general/issues/135

**Comment by maxvisser** [comment]
yes, all information from here moves to the website or to first page of signupflow :)

**Comment by maxvisser** [comment]
We decided to make the first page of the signupflow the landing page after implementing #379

**Comment by maxvisser** [comment]
@jamalv Could this issue get a project? I think it is usefull for multiple projects

**Comment by maartenfv** [comment]
This issue is a must-have for Groningen

**Comment by maartenfv** [comment]
I have marked it for the upcoming sprint. The solution is not perfect as de actual request = https://github.com/teamforus/general/issues/492. So this might get a follow up. For now this is the best solution and needs to be implemented.

**Comment by maxvisser** [comment]
This still need design on how logged out state looks. I would also make a screen before the signupflow which states a question like 'Do you want to login or register?' with big buttons for the two choices.

**Comment by jamalv** [comment]
Why would it need a logged out state? The way it is now it shows login button and link in the text, right?

**Comment by maxvisser** [comment]
Logged in state*

**Comment by maxvisser** [comment]
Sorry

**Comment by maxvisser** [comment]
If you are logged in there is no easy way to open the dashboard

**Comment by jamalv** [comment]
would it be okay to just redirect to the dashboard if you already have an organisation?

**Comment by maxvisser** [comment]
Add a office and a fund application to that list and I am OK with redirecting;

**Comment by jamalv** [comment]
Discussed during refinement:
- Back button should be removed
- Had a general brainstorm about this issue
-
