### ISSUE TITLE
Expiration error: no more funds (geen saldo)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#710]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Check the error you get when funds are expired

Also: check errors with actions: are they descriptive?

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/f10e6b20-2730-42df-8781-0c92ef7d82b0)

Helder
