### ISSUE TITLE
CR: Make seperate page for "uitleg" for providers CMS

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#713]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
- Extra page for providers. Needs to be adjustable in CMS
![image](https://user-images.githubusercontent.com/30211022/103551966-725cf180-4eab-11eb-9a69-83b449774472.png)

**Comment by maxvisser** [comment]
we already have an issue like this planned for this sprint #636

**Comment by maxvisser** [comment]
Will close this one in favor of #636

**Comment by maxvisser** [comment]
Will close this one in favor of #636
