### ISSUE TITLE
Aanbiedingpage is cluttered. Exact amount needs to be korting amount

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#714]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen

### Change description
-
Bedragen zijn onrustig geeft gemeente aan. Er moet staan wat de korting is.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/cd317166-9039-41b8-8b32-8d90c748c5d0)

**Comment by maxvisser** [comment]
this is the exact amount the user needs to pay with at the retail though. Where do you want to put that amount?

**Comment by maxvisser** [comment]
Dit kan met huidige functionaliteit. Hier is het echter ingesteld als een exact bedrag.
