### ISSUE TITLE
Webshop: Align product card height on action funds just like budget funds has

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#717]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Product cards should be same height. This is the case on funds that uses budget. But not for funds that uses actions. Please align this.

**Webshop thats uses action fund (image view)**
<img width="996" alt="Screenshot 2021-01-04 at 15 38 57" src="https://user-images.githubusercontent.com/38419514/103628067-c238c880-4f3e-11eb-8742-8379479eeb42.png">

**Webshop thats uses budget fund (image view)**
<img width="1022" alt="Screenshot 2021-01-05 at 10 14 45" src="https://user-images.githubusercontent.com/38419514/103628357-2b204080-4f3f-11eb-8e09-adebe77afb2a.png">

**Comment by jamalv** [comment]
@danrminds could you check the issue and status?

**Comment by jamalv** [comment]
@danrminds still needs issue :)

**Comment by maxvisser** [comment]
planned this in
