### ISSUE TITLE
Update styling: add "hoefjes" :)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#719]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
This is for Stadjerspas webshop, styling assets:

[wetransfer-c471ae.zip](https://github.com/teamforus/general/files/5769794/wetransfer-c471ae.zip)

**Comment by maxvisser** [comment]
eps files need to be added to figma and maybe converted to svg/png

**Comment by maxvisser** [comment]
Not sure what these are and where to put these; so i labeled it scope big
