### ISSUE TITLE
Remove yourself as employee of an organization

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#72]
## Context/goal: 
This issue is about an user being added to an organization but is quiting his job / does not want to take part of the organization anymore.

He will need to be able to 'Leave' the organization somehow. Maybe show Employees page to all members of organization and have an option on the list to leave.

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/0f64a9f5-fd22-476d-94a7-7739feb09db1)

**Comment by jamalv** [comment]
Added as an insight to productboard: https://app.productboard.com/inbox/notes/17398171

**Comment by jamalv** [comment]
@maxvisser what do you think? Is this something that could be planned for alex?
