### ISSUE TITLE
Aftercare Groningen (feedback) fase 1 (release 11 jan.)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#720]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
- To keep track of all the feedback after release. Please add related issues to this Epic.

Figma: https://www.figma.com/file/OL6X0AUnpbiP8TX5dq1mU9/?node-id=416%3A0
Google docs: https://docs.google.com/document/d/1_Gi8TSZ_zkwJ5i4GNU_ZxTSO_jjXESKddvt49we16e8/edit

**Comment by maartenfv** [comment]
This issue is a continuation of issue: https://github.com/teamforus/implementation/issues/614

**Comment by maxvisser** [comment]
I added client labels; my proposal is to add Client: Groningen to all their issues.

**Comment by maxvisser** [comment]
I like these kind of issues. I would instead propose to add these into the forus repo and add all the tasks to it.

**Comment by maartenfv** [comment]
@maxvisser Are the release dates for the issues correct? Are we going to make the 11th on the issues that are included in this Epic?

**Comment by maxvisser** [comment]
the statuses are correct. three are still not in progress. So not sure if I can stage these tomorrow for acceptance testing.

**Comment by maartenfv** [comment]
@jamalv Voor straks met Paul, Afstemmen planbord in MS teams: kan je deze dingen fixen?: Bas heeft er naar gekeken en noemt dit wel in het projectoverleg als verwachting. Als we dit niet snel rechtzetten groeit dit.

- Sommige punten zijn nog niet duidelijk maar ze staan wel open bij ons op de backlog in zenhub. Voorbeeld: aanvragen knop. In Teams staat deze nu met het label "knoop doorhakken". We moeten zeker weten dat de gemeente akkoord gaat met onze kijk of we moeten de issue oplossen door het uit te werken. Risico is dat dit telkens weer terug komt. Gemeente heeft dit punt al vaak aangekaart.
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/48ef7417-f8aa-4e30-a123-2f6eab3b3ad4)



- Datum titel sprint kolom - kloppen die en kan je die bijwerken? De gemeente verwacht dat alles dat hier onderstaat nu op 8 januari af is.
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/c6b1dcad-4502-4570-a4d4-6d01c2864933)


- Alle items in de sprint kolom moeten weer kloppen met de realiteit. Nu staan er zaken in waar we niet aan werken en niet aan gaan werken dit schept de verkeerde verwachting. Onderstaande dingen staan wel in kolom waar we aan werken maar zijn zeker niet op 8 jan. klaar.

Voorbeeld 1:
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/9b0ca131-c291-41bc-b925-3f8937e435b0)

Voorbeeld 2:
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/154d8014-3532-468a-820a-3c5aa34db11d)

**Comment by maartenfv** [comment]
@jamalv De punten in de sprint klom van MS Teams moeten exact overeenkomen met de dingen die we gaan releasen zoals in deze issue op 11 januari.

**Comment by jamalv** [comment]
@maartenfv teams is vorige week bijgewerkt, release rapport is hier te vinden: https://app.zenhub.com/workspaces/sprint-5f61c6c0a53fb84e755c82f6/reports/release?release=5fe3bf35688d8a0c014ea6fd
