### ISSUE TITLE
Aftercare Groningen (feedback) fase 3

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#721]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description
- Continuation of fase 1 (release 11jan)

**Comment by maartenfv** [comment]
@maxvisser @jamalv Can you please add the issues that are planned to be released on the 25th of jan.

**Comment by maxvisser** [comment]
Seems not to be relevant anymore

**Comment by jamalv** [comment]
@maxvisser @jamalv vraag: kunnen we release rapport bijwerken voor de release van de 15e

**Comment by jamalv** [comment]
release rapport voor .21 (de 15e) is nog niet bijgewerkt door jamal en max; vanmiddag bijwerken

**Comment by jamalv** [comment]
@maxvisser heeft het release rapport bijgewerkt en een nieuwe release aangemaakt voor de 29ste https://app.zenhub.com/workspaces/intake-5fe1b67c5361800022a2646c/reports/release?release=604760767f4555a18239df3a

**Comment by jamalv** [comment]
Sponsor offers release of the 15th was done this morning. Planned a moment this week to do a status check on the other issues @maxvisser I think we're expecting a release the 29th?

**Comment by jamalv** [comment]
gister tijdens refinement alle issues doorgenomen; overal wordt aan gewerkt

**Comment by maxvisser** [comment]
@maxvisser @maartenfv need to update list

**Comment by jamalv** [comment]
zometeen bij refinement wordt de status bijgewerkt

**Comment by jamalv** [comment]
lijkt dat we de release gaan halen, max gaat nog even vragen bij alex over #2133

**Comment by jamalv** [comment]
Update about https://github.com/teamforus/forus/issues/2133 - default zoom state and text fixes will be done.

Research for the zoom out part was also done; this is quite big (will take a couple days) - we therefore decided to take that out of scope and prioritise other issues instead (there were no formal agreements on this issue, we added it as a nice quickfix). 

The insight has been added to productboard though: https://forus.productboard.com/insights/all-notes/notes/15298717

**Comment by maartenfv** [comment]
@jamalv Clear! Thanks for giving context on removal!
