### ISSUE TITLE
Automatically redirect to signupflow if user has no account

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#722]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As a requester i would like to automatically be redirected to the signup-flow if I don't have an account.

Context: currently groningen is experiencing high volume, a lot of users clicking the wrong button.

**Comment by maxvisser** [comment]
Just looked at the logs; alot of people are trying to login with their old mail address. Our system will block their IPs for 10 minutes. so this seems pretty crucial to fix if they are all trying to login on their old accounts.

**Comment by jamalv** [comment]
@danrminds could you plan this in?

**Comment by danrminds** [comment]
@jamalv @maxvisser 

`"As a requester i would like to automatically be redirected to the signup-flow if I don't have an account."` - **redirect from where?**

**Comment by jamalv** [comment]
When logging in, just like in the me app - create an account if you don't have any - people are pressing the wrong button

<img width="689" alt="Screenshot 2021-01-07 at 20 01 58" src="https://user-images.githubusercontent.com/30194799/103933158-38962000-5123-11eb-8430-43d4e29c0619.png">

**Comment by danrminds** [comment]
@jamalv 

Okay. 
But, should he get redirected to which step:

### Option 1: Start (without filled in email)
![Screenshot 2021-01-07 at 20 10 42](https://user-images.githubusercontent.com/33207036/103933994-87908500-5124-11eb-9d77-c0e42f6f229b.png)

## Option 2: Start (with filled in email and pre-checked agreement)
![Screenshot 2021-01-07 at 20 10 53](https://user-images.githubusercontent.com/33207036/103934023-9414dd80-5124-11eb-8fe4-d050f1f32809.png)

## Option 3: Check you email confirmation from signup flow?
![Screenshot 2021-01-07 at 20 10 33](https://user-images.githubusercontent.com/33207036/103934063-a1ca6300-5124-11eb-9396-9e6f8f050d6d.png)

**Note:**
Also - what if in fact -a provider presses on that login button and tries to login, redirecting him to a requester signup flow might not be wise.

**Comment by jamalv** [comment]
I would go for option 3. Regarding providers trying to log in, I would suggest to check if there is an existing organisation. If there is one, redirect to the provider dashboard.

Since this has to do with login, we should be careful with making changes here though. I'm curious to hear @maxvisser and @GerbenBosschieter also, let's not forget mobile for this. I think many people are clicking login because it is a clearer call to action there. Maybe we should think about switching those around.

Right now I'm mostly interested in a fix (if this is still needed) - next, stakeholders would like us to have a look at the login flows for providers and requesters. Right now the flows from start-to-end need some more work. @danrminds

**Comment by danrminds** [comment]
Planned here for now: https://github.com/teamforus/forus/issues/2050 Adjust if necessary.

**Comment by maxvisser** [comment]
done and reviewed
