### ISSUE TITLE
Change of how we use expiration date for products/actions

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#729]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter, providers, sponsors

### Problem Description
If an organization places an offer, they can indicate the date that this offer will expire. Recent update gave the option to indicate that that the expiration date is not applicable/unlimited. This is very useful because otherwise the offers are often taken off the web shop after the calendar year without that being the intention.

Unfortunately, this also presents problems for our newest municipality. They want the Stadjerspas website to only have offers that can be used up to and including 31-12-2021 at the latest. For the municipality, this is even use this as a reason to NOT start an action :( This is annoying for the providers and doesn't help the complaint of not enough actions in the webshop.

### Change request
Develop an option in the sponsor dashboard to set an expiration date no later than a specific date they like (maybe at fund setting or aanbieder section. This wil overwrite what is shown on the webshop of that specific fund) to all the requesters. But will not overwrite the setting of the provider. This way it will not influences products that are also being used on other webshops but wil still give the sponsor the option to give the information on the webshop they like.

**Comment by GerbenBosschieter** [comment]
@jamalv @maxvisser I even see a better an easier solution. Instead of using the variable of the expiration date of the product/offer to show on the webshop. We could also show the variable of the expiration date of the fund! Thats an easy fix, and doesn't negativly influences other webshops.

Only challenge here is webshops with multiple funds and different expiration dates :(

**Comment by maxvisser** [comment]
Seems sensable. We could do this; but an action currently has always the end date of the fund. As nobody will get a new limit; even if you start or stop an action.

**Comment by GerbenBosschieter** [comment]
@maxvisser I know. I've told them. But they really want to have the fund end date on the webshop

**Comment by jamalv** [comment]
I agree this should be done. The combination:

- Provider sets "unlimited"
- Sponsor sets an end date for the action

Makes sense to me.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/104182726-2d880c00-5411-11eb-9f7c-c0a8cac8c0f8.png)

**Comment by maartenfv** [comment]
Do we have an update on this issue?

**Comment by maxvisser** [comment]
its in release v0.19.2 (what I proposed in the screenshot)
