### ISSUE TITLE
Me transactions button: hide it for requesters

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#730]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a requester it is weird to have a transactions button, while I cant have any transactions there. 

We'd better check if the user has an organisation and hide the button if there isn't

**Comment by maxvisser** [comment]
Which button? could you add a screenshot?

**Comment by GerbenBosschieter** [comment]
@maxvisser 

![IMG_1978](https://user-images.githubusercontent.com/38419514/104314985-8b345b00-54da-11eb-91ca-bc484445fa04.jpg)

This was already mentioned during the concept development of this feature. Everybody preferred it to only show information that is related to the specific role. This wasn't an option back then.

**Comment by maxvisser** [comment]
we do have a tooltip on this which is only shown on installation I believe. If we implement this we should check if this still works.

**Comment by maxvisser** [comment]
I would  rather add user transactions to the page but the scope of that is bigger.

**Comment by GerbenBosschieter** [comment]
> we do have a tooltip on this which is only shown on installation I believe. If we implement this we should check if this still works.

it wor
