### ISSUE TITLE
Change request: As a sponsor I would like to send custom mails / messages to the providers and requesters

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#731]
**Support Ticket ID:** [#2782]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

### Change description
- As a sponsor I would like to send custom mails / messages to the providers and requesters<br>

**Comment by GerbenBosschieter** [comment]
Closed, duplicate of: #657 . Created for statistics
