### ISSUE TITLE
Totaal aanbod, what does it mean?

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#732]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
<img width="1125" alt="Screenshot 2021-01-12 at 14 44 45" src="https://user-images.githubusercontent.com/30194799/104322146-db181f80-54e4-11eb-812f-b7970a5e3590.png">

**Comment by GerbenBosschieter** [comment]
It means: total amount of offers that the provider can offer. So max count of products/tickets etc. We should indeed make this more clear.

**Proposal:** _Totale voorraad dat de organisatie kan bieden_?

Maybe it doesn't even matter for the sponsor and we can't just remove it when you try to start an action.

**Comment by jamalv** [comment]
It seems like "totale vooraad" is also visibile on the top left, at beschikbaar: 4.

Let's remove it if it serves no clear purpose.

**Comment by maxvisser** [comment]
its the amount that Groningen wants to give out; not the stock amount

**Comment by jamalv** [comment]
@linda-90 could you do a text suggestion and assign max when you did? He will then implement it :D

**Comment by linda-90** [comment]
Opties:
- Hoe vaak deze actie in totaal beschikbaar is
- Totaal aantal acties waaraan uw organisatie wilt bijdragen

**Comment by maxvisser** [comment]
Tweede lijkt mij duidelijker 👍

**Comment by jamalv** [comment]
Wil bijdragen of wilt bijdragen?

**Comment by linda-90** [comment]
Wilt is gebruikelijker in geschreven taal

> U wilt en u wil zijn allebei correct. In Nederland wordt u wil informeler en in geschreven taal minder verzorgd gevonden dan u wilt.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/104736239-f2544880-5742-11eb-890b-fb24c121be2e.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/104736346-1879e880-5743-11eb-9a63-73b9a83a95d9.png)

**Comment by maxvisser** [comment]
seems pretty long but probably no way to make it smaller?

**Comment by linda-90** [comment]
I agree. Is this an idea?

![image](https://user-images.githubusercontent.com/36952230/104738650-16655900-5746-11eb-9fa5-4951b2e54351.png)
