### ISSUE TITLE
Voucher generator: search by activation_code_ui

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#734]
Learn more about change requests here: https://bit.ly/39CWeEE

**Support ticket** [ #2783 ]

### Requested by:
- Sponsor (SDOA)

### Change description
- We introduced some new features to the voucher generator for SDOA. But this also results in a request to add a new option to search on a certain column. We introduced the column: activation_code_ui . This is used as UID for the citizen they want to grant the voucher to. 

We should add an option to search by activation_code_ui. I added high priority label because not being able to search on an UID has already resulted into an incident.

**Comment by maxvisser** [comment]
planned

**Comment by maxvisser** [comment]
is in release v0.19.2
