### ISSUE TITLE
Logging in and applying for a fund is currently a bit confusing and causes support questions.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#736]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Problem description
Requesters that are informed by the municipality that they can apply for Stadjerspas are somewhat confused on logging in and applying for a fund. The current scenario is like thise:

1. Requester receives messages to apply for Stadjerspas (they already had Stadjerspas, so they assume the can use the same account as before)
2. They will go the website and the first thing they see is text like the image below. This text is confirming the assumption they already had. 
<img width="982" alt="Screenshot 2021-01-13 at 09 33 51" src="https://user-images.githubusercontent.com/38419514/104426664-84f9b980-5582-11eb-9c78-868e787258d0.png">
3. They will click the link to "reactivate" their account
4. They will get redirected to the page to start the application, but there some confusing things over here what causes them to click of the sentences instead of entering their e-mailadres adres. See image below 
<img width="983" alt="Screenshot 2021-01-13 at 09 36 54" src="https://user-images.githubusercontent.com/38419514/104426970-f3d71280-5582-11eb-8503-e8547e0772ca.png">
5. They click on one of these sentences while don't have an account yet. This results in many questions like:
- E-mail is not recognized
- BSN is not recognized
- Why do I have to confirm my e-mailadres? I already have an account.

### Change description
As see two problems over here that should change:
- The welcome text on the website that gives an impression they already have an account. Beter to use the word "EENMALIG OPNIEW AANVRAGEN"
- Put an ng-if statements on these sentences for Stadjerspas. For their scenario it doesn't even make sense to put them their. Because 99% of the people who will land on this page doesn't have an account yet. Stajderpas is just live. People who do have an account wil probably ignore the welcome text and login by using the button: **Inloggen**

I really would like to see a change in this quickly. This causes some unnecessary frustration for the requester and unnecessary high support volume.

**Comment by jamalv** [comment]
IMO the ng-if can be a good hot-fix. For the text in the CMS, we should do a proposal to Groningen. If we have a proposal text I can ask paul. I have a meeting with him at 11:30 today.

**Comment by jamalv** [comment]
What would help is a proposed text, that he could copy-paste:

**Let op, u moet eenmalig opnieuw aanmelden!**
Bestaande leden moeten eenmalig opnieuw een aanvraag doen met DigiD. Klik [hier] om opnieuw een aanvraag te doen.

**Comment by jamalv** [comment]
@GerbenBosschieter @maxvisser what do you think of the text proposal?

**Comment by jamalv** [comment]
I think there are some (subtle) UX issues that cause people to click the wrong links as well:
- The links below the text are the darkest, making them call to action the most; they should be much lighter
- The e-mail filled should probably be active (selected) this will trigger people more to just start typing their e-mail adres

We should fix these issues also for other implementations - people often don't read and just start clicking, the core path we want them to take should be the most prominent.

<img width="825" alt="Screenshot 2021-01-13 at 11 09 22" src="https://user-images.githubusercontent.com/30194799/104438266-17548a00-5590-11eb-9a70-f92866963789.png">

**Comment by maxvisser** [comment]
@jamalv I removed the link we added in v0.19.0 for groningen only;

**Comment by maxvisser** [comment]
Maybe lets plan the styling etc issues for release of monday

**Comment by jamalv** [comment]
Paul also updated the texts on production.

**Comment by GerbenBosschieter** [comment]
Text updated. Frontend fix is released. Closed issue. Great work :)
