### ISSUE TITLE
Clarification request: send "from" sponsor / implementation

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#739]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Currently clearification requests are sent from forus.io, this is not very recognizable. We should change the from address to the implementation if there is an e-mail connection (e.g. stadjerspas@groningen.nl)

**Comment by maxvisser** [comment]
This is in the digest; as Digest can contain multiple funds; you can't really do this for a digest. If you want this probably we should make a seperate mail per implementation for this functionality.

**Comment by maxvisser** [comment]
@jamalv I maybe misunderstood this issue. are these the clarification requests that the validator sent?

**Comment by jamalv** [comment]
Yes, indeed. So those that are sent to the requester.

**Comment by maxvisser** [comment]
check it again and plan it in

**Comment by maxvisser** [comment]
Seems to not work (don't get a e-mail)

**Comment by jamalv** [comment]
@maxvisser that should then be classified as an incident, right? That something is broken on production?

**Comment by maxvisser** [comment]
lets make an ITSM issue to check this clarification request on staging / groningen
