### ISSUE TITLE
Voucher generator: top up / new voucher

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#74]
## Context
Different customers want to use the voucher generator in different ways. A customer wants to be able to use the voucher generator to top up existing vouchers. Another customer wants to be able to create seperate vouchers. e.g. if there is a family they want to create a voucher for each family member seperately: 3 vouchers of 300 euro for a "kindpakket" on the account, instead of 1 voucher of 900.

## Goal
When a voucher is generated, and the user already has a voucher, the sponsor should first get asked if they are sure they want to create the new vouchers https://github.com/teamforus/forus/issues/1386 if they say yes; they should get another choice between top up and creating a new voucher.

## Task
- [ ] Create popup : 
Existing vouchers found:
**Do you want to top up?** (add the budget to the existing voucher) or 
**Do you want to create a new voucher?**

**Comment by maxvisser** [comment]
I would create voucher_amounts or voucher_balances table which has multiple balances for a voucher: fo example if a citizen has 3 children he would get 3x 300 euro's on his voucher instead of how we currently implemented which would be 900.

**Comment by maxvisser** [comment]
Maybe create a new CR for topups?

**Comment by maxvisser** [comment]
Currently a new voucher can be created to generator
