### ISSUE TITLE
CR: Let providers remove/delete their organization

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#742]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Currently there is no way to remove an organization safely without alot of manually checking. There are even alot of provider who still have two organizations on their account as they applied twice.

Being able to remove these organizations would be really nice. Aswell provider who don't want to participate in the system anymore should be able to delete their account.

**Comment by maxvisser** [comment]
Probably wise to start with soft deleting these organizations; afterwards implement a feature to really destroy all data.

**Comment by maartenfv** [comment]
This is a very good issue.

**Comment by maartenfv** [comment]
@RobinMeles Could you help check status?

**Comment by RobinMeles** [comment]
@maxvisser want to close this one? Or what is the status?

**Comment by maxvisser** [comment]
Currently still open as a PR (not yet reviewed)

**Comment by jamalv** [comment]
Valentin says this issue needs refinement.

**Comment by maxvisser** [comment]
Still same as in september, no progress as it has no real priority to work on it.
