### ISSUE TITLE
Rewrite e-mail after fund request approved

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#749]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
The e-mail people get after approval of fund request is to confusing for some users.

1. Title is mentioning the word "tegoed". This results in people expecting a budget. 
**Current:**  Uw aanvraag voor een Stadjerspas-tegoed is goedgekeurd.
**Proposal:** Uw aanvraag voor {fund-name} is goedgekeurd

2. The tip about me-app also confusing. It tells user to download the me-app and show the qr code from their phone. Some users think they have to scan the QR Code with their phone. They don't know they should show it to a provider. Just keep it simple with this sentence and tell them they can manage their {fund-name} in the app.

3. Why use the word: "tegoed"? If we just use the fund name, then everybody is happy.

**Conclusion:** Lets rewrite the complete e-mail

<img width="1149" alt="Screenshot 2021-01-20 at 09 38 11" src="https://user-images.githubusercontent.com/38419514/105148916-38265d80-5b03-11eb-9ea0-5e0c1fe300df.png">

**Comment by GerbenBosschieter** [comment]
Custom e-mails would even be better

**Comment by maxvisser** [comment]
planned for text review
