### ISSUE TITLE
Notifications: add support contact information to all e-mails that are send to the provider

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#75]
## Context/goal: 
*explain why this issue was opened*

**Comment by maxvisser** [comment]
@GerbenBosschieter If you list all e-mail which need this information I will make an issue in Forus.

**Comment by jamalv** [comment]
@GerbenBosschieter is this still something that you want? I think the e-mails can be found here in figma: https://www.figma.com/file/u3KF3hKewS4FA6YzzA7var/?node-id=371%3A0

Maybe by creating a seperate figma file with all the mails that need to be updated can help here?
