### ISSUE TITLE
Voucher generator: remove / change warning about duplicate if there are only expired vouchers

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#750]
**Support Ticket ID:** [#2861]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor

### Change description
- Voucher generator: remove warning about duplicate if there are only expired vouchers<br>
- We should change the text of the button to turn on / off creating a voucher. People get confused (already got three support question about this today xD) because it says "Overslaan / skip" but the button is turned off. So they think skipping is turned off. Just use the same text as when the button is turned. So "Aanmaken voucher" and maybe as an extra add the status to the button like the example below.

<img width="1119" alt="Screenshot 2021-01-21 at 10 56 14" src="https://user-images.githubusercontent.com/38419514/105335371-44301f00-5bd8-11eb-885e-a3d51a03c0c9.png">

<img width="1128" alt="Screenshot 2021-01-21 at 11 06 46" src="https://user-images.githubusercontent.com/38419514/105336158-33cc7400-5bd9-11eb-8217-e8526c959d74.png">

<img width="372" alt="Screenshot 2021-01-21 at 11 08 43" src="https://user-images.githubusercontent.com/38419514/105336191-3c24af00-5bd9-11eb-9bb2-ba7b68faec9a.png">

**Comment by maxvisser** [comment]
I already created a task which is related; to not show it when a voucher is expired.

**Comment by maxvisser** [comment]
Add the issue I was talking about 'as blocking by'

**Comment by maxvisser** [comment]
For this use case maybe the toggles can just be removed;
![image](https://user-images.githubusercontent.com/10818702/105338095-7000d400-5bdb-11eb-899c-26abeebeaef1.png)

**Comment by maxvisser** [comment]
The AAN / UIT in the toggles is a general good idea though. ;)

**Comment by maxvisser** [comment]
created two more task for design review of the toggles; and removing the toggles when there is on only on mailadres or bsn duplicate detected.

**Comment by maxvisser** [comment]
Toggles are designed
Modal is updated to make it more easy to create one duplicate.
