### ISSUE TITLE
Change e-mail icon for login mail for SP implementation

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#752]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Groningen](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_97344372?webUrl=https%3a%2f%2ftasks.office.com%2f8c3b61fd-94af-4533-8307-eb59dbd860b0%2fHome%2fPlanViews%2fCVc1-WjDbUeukZXI_ovhxZYAFzY6%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Aanmeldmail+is+generiek%2c+maar+wil+aanmelden+op+de+Stadjerspas.+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%22ssPyTDyAW0eW0rLxrDbVU5YAHrPi%22%2c%0d%0a++%22channelId%22%3a+%2219%3a78d8e8b589df4373895fd9676b8ca52b%40thread.tacv2%22%0d%0a%7d&tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0)

### Change description
Change the icon for login mails to stadjerspas

@maxvisser I think you had a suggestion? Could you share it here?

**Comment by maartenfv** [comment]
@maxvisser @jamalv Could you please give an update on this issue? It is on the Groningen Backlog in MS Teams.  https://teams.microsoft.com/_?tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0#/tab::3839bb31-8cb0-4e77-a674-d0f76ecf1ae5/Ontwikkeling?groupId=f88a0489-3ae3-4207-89a7-766381327747&threadId=19:78d8e8b589df4373895fd9676b8ca52b@thread.tacv2&ctx=channel

**Comment by maxvisser** [comment]
We worked on this and fixed the issue. While testing it on staging it did not work anymore. Currently the worker loses context of which webshop the e-mail was sent; on local dev environments we do not use a queue and a seperate worker to sent mails. Current state its implemented but only works on dev environments.

**Comment by maxvisser** [comment]
Probably we need to @dev-rminds to check why it only works on dev environments and not on staging. Currently he is busy with a diffrent epic.

**Comment by jamalv** [comment]
@maxvisser allright, could you please check it out with valentin? if this is not too big to fix that's better than waiting till he's done imo.

**Comment by maxvisser** [comment]
@jamalv discussed it; it will take 2 hours; still small scope but probably currently not the priority?

**Comment by maxvisser** [comment]
I will put this on the backlog though

**Comment by maartenfv** [comment]
This is an important issue as it was a major trigger. Needs to keep prio and not disappear

**Comment by maartenfv** [comment]
@maxvisser Is deze gereleased?
