### ISSUE TITLE
Start action modal: shorten input fields

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#753]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
Shorten the input fields, since input can not be so long:

<img width="1012" alt="Screenshot 2021-01-28 at 09 24 34" src="https://user-images.githubusercontent.com/30194799/106110444-050b4c00-614b-11eb-9ff2-485e9083a4eb.png">

**Comment by jamalv** [comment]
plan: do the quickfix and also a design review where we see what info is really needed here

**Comment by maartenfv** [comment]
This issue is on the Groningen MS teams backlog. Can we get an update on the status? Please add a release.

**Comment by maartenfv** [comment]
https://teams.microsoft.com/_?tenantId=8c3b61fd-94af-4533-8307-eb59dbd860b0#/tab::3839bb31-8cb0-4e77-a674-d0f76ecf1ae5/Ontwikkeling?groupId=f88a0489-3ae3-4207-89a7-766381327747&threadId=19:78d8e8b589df4373895fd9676b8ca52b@thread.tacv2&ctx=channel

**Comment by maxvisser** [comment]
This is done and in release v0.20.0
