### ISSUE TITLE
Rate Me-app; 5 stars app store / playstore

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#756]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Show rate Me-app when user hits for example 3 successfull transactions (making transactions or having transactions)

**Comment by maartenfv** [comment]
Currently, we people are giving very low ratings. This is a sad thing. See android playstore. Would be nice to give a reminder to users that are happy with the app to rate as well.

**Comment by maxvisser** [comment]
idea from dan: with next release ask users to rate the app via push notification
