### ISSUE TITLE
Footer on website (map providers) and button aanbieders are bugged

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#757]
On this website https://stadjerspas.gemeente.groningen.nl/providers?show_map=1

1. The button for aanbieders is too wide. 
2. The footer is bugged

Using chrome.

![image](https://user-images.githubusercontent.com/30211022/106568436-9441a680-6533-11eb-8093-7150405c9da0.png)

**Comment by maxvisser** [comment]
fixed in a hotfix
