### ISSUE TITLE
Voucher generator: duplicates warning

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#76]
## Context
Currently with the voucher generator it is possible to assign multiple vouchers to the same email adres. This is good functionality, but a user can create an easy mistake. For example a sponsor could upload the same CSV file twice. Or they are not careful with maintaining their CSV files, and they accidentally have old (already assigned) email addresses in a new CSV file. The risk here is that somebody gets a (duplicate) voucher that they are not supposed to, due to an error by the sponsor.

## Goal
When we detect duplicates we should notify the sponsor that is uploading a CSV file, before creating the vouchers. 

## Task
- [ ] Create popup: 

**{Amount, e.g. 24} Duplicate email adresses detected.** 
Are you sure you want to create extra vouchers for these {Amount, e.g. 24} email addresses that already have a voucher?  
Buttons: Yes to all | Skip duplicates | Cancel

**Comment by danrminds** [comment]
@maxvisser @jamalv 

Please review - https://www.figma.com/file/RolmXCeR5lPfMlnNzDU8lO/Duplicates-on-voucher-generator

**Comment by maxvisser** [comment]
added a comment in the figma prototype; should look at the toggles: now the default is skip and the cta is yes to all. I would make both the less impactfull one so no accidents can happen; TLDR: switch around the Yes to all and Skip duplicates.

**Comment by danrminds** [comment]
@maxvisser @jamalv 

Can this one be planned in?

**Comment by maxvisser** [comment]
needs text review and functional design

**Comment by maxvisser** [comment]
Could you look at these texts:
https://www.figma.com/file/RolmXCeR5lPfMlnNzDU8lO/%F0%9F%93%9D%E2%9A%99%EF%B8%8FDuplicates-on-voucher-generator?node-id=73%3A1521&viewport=963%2C662%2C0.9760416746139526

**Comment by maartenfv** [comment]
We did the language check it has passed and can be developed. Added to dev pipeline.

Dit find a new issue as it need better UX: https://github.com/teamforus/general/issues/296

**Comment by maartenfv** [comment]
@maxvisser This issue is ready for the next step.

**Comment by maxvisser** [comment]
Its in release v0.14.0 and will be online on 17 august
