### ISSUE TITLE
Swap phone number order on our website.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#762]
People keep calling me for support. Some times this is nice. But now it is happening too much. This happens because the order of the contact info.

![image](https://user-images.githubusercontent.com/30211022/107653047-8271a900-6c81-11eb-8904-929cd9257594.png)

Needs to become:

![image](https://user-images.githubusercontent.com/30211022/107653099-8ef60180-6c81-11eb-99a3-2bac33734986.png)

**Comment by maxvisser** [comment]
Done in release 20
