### ISSUE TITLE
Image cropper is not square

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#763]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Everybody using this cropper

### Change description
- We need more space to place the picture.
- Make sure the cropper is actually square.

It says upload square resolution but its not square. 
![image](https://user-images.githubusercontent.com/30211022/107948510-35007f00-6f94-11eb-8889-c4b640fb0e7b.png)

**Comment by jamalv** [comment]
superseded by: https://github.com/teamforus/general/issues/177
