### ISSUE TITLE
Add Privacy Statement and checkbox to each of the citizen sign-up flows.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#764]
The Datawise team has conducted research and concluded that we need to improve our privacy statements.

This means every webshop needs to privacy statement in the sign-up flow for citizens.

- [ ] Stadjerspas
- [ ] Nijmegen
- [ ] Berkelland
- [ ] Oost Gelre
- [ ] Winterswijk
- [ ] Geertruidenberg
- [ ] NOP
- [ ] Wersterkwartier
- [ ] Potjeswijzer

**Comment by maxvisser** [comment]
I wonder why a company like Slack is not doing a checkbox. Did datawise have any research supporting why a checkbox is needed?

Examples from slack:

Sign up (creating an account)
![image](https://user-images.githubusercontent.com/10818702/108495430-11e21200-72a9-11eb-8064-8a1aedfa2e53.png)

Login 
![image](https://user-images.githubusercontent.com/10818702/108495497-26260f00-72a9-11eb-8e59-8a454154aa2d.png)

**Comment by maxvisser** [comment]
Why I am asking:
From user testing we saw alot of confusion on which button they need to press 'Inloggen' or 'Aanmelden'; from these test we thought to remove complexity and make #448 if new users need to check a box to agree to the privacy statements you will never be able to remove this complexity.

If so we could close #448 as it will never happen

**Comment by maartenfv** [comment]
#448 is still on hold. ![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/07deaa15-42f1-4c3d-84c8-da633010554c)

You can read the whole report with reasoning . Het gaat om dedicated moments en niet opt out. 

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/608a0395-043a-4d09-80ed-78f1270ec2ce)

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/95c9d476-ab95-4569-ba38-f6552dc45fc1)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/108973099-462c4880-7684-11eb-9daa-ccc2d667ae6b.png)

Yes I read your comment; I think its worth the time to investigate other options then a checkbox though

**Comment by maxvisser** [comment]
I find asking permission for certain actions like Forus or municipalities sending newsletters, notifications etc. better then 'agreeing' to a policy. Also there is currently no option to not agree; you cant create an account without agreeing with everything.

**Comment by maxvisser** [comment]
also currently: 
- you are still able to create an account in the me-app without agreeing
- you still are able to create an account in provider/validator/sponsor signupflows without agreeing
- you are still able to create an account by pressing login and filling a new e-mail without agreeing

**Comment by maartenfv** [comment]
@RobinMeles could you help with resolving this issue?

**Comment by RobinMeles** [comment]
I think it's wise to add a privacy statement checkbox to the sign-up flow for the provider/sponsor. I will set up this privacy statement and check with Max how we can add this to the flow and in what way.
