### ISSUE TITLE
Print cards (DCP)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#766]
As a maintainer I would like an automated way to send cards to DCP.

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/7076162

**Comment by maxvisser** [comment]
List of tasks:
- have a database column which tells if physical card request is uploaded to ftp
- bundle physical card requests on voucher_id with each export so users who accidently requested two cards receive only one.
- check if voucher of physical card request already has an physical card attached, if so don't export it into the CSV.
- export only requests which did were not exported before. Migrate all previous requests to already be exported
- being able to set a specific subfolder in ftp to upload CSV
- each thursday / friday midnight run a cron job to upload CSV to ftp server

**Comment by maartenfv** [comment]
@RobinMeles Kan je hier een status update over geven?

**Comment by RobinMeles** [comment]
Het uploaden van CSV naar ftp server gebeurt nog steeds handmatig. Misschien met @maxvisser handig om dit een keer te bespreken of dit automatisch kan en of we dit willen.

**Comment by jamalv** [comment]
Wordt op dit moment niet aan gewerkt, kan evt. later weer geopend worden
