### ISSUE TITLE
Update Me screenshot on me page

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#767]
https://stadjerspas.gemeente.groningen.nl/me

![image](https://user-images.githubusercontent.com/30211022/108721874-ca66ba80-7522-11eb-8365-2647fb913475.png)

- [x] The Me screenshots need to be smaller. 
- [x] The screenshot need to be updated to like the ones in the app store.

**Comment by maartenfv** [comment]
@linda-90 Can you add a link to the new screenshots?

**Comment by linda-90** [comment]
New design: https://www.figma.com/file/0cC6cK9JEWpcdcXPwtOkzN/Webshop-Me-page-(Copy)?node-id=189%3A568&viewport=820%2C288%2C0.6963542103767395

**Comment by maartenfv** [comment]
This issue is being tracked on the MS teams bord of Groningen.

**Comment by jamalv** [comment]
Looks absolutely great! But not much I can do here. @maxvisser could you do a separate front end release for this one before Friday morning?

**Comment by maxvisser** [comment]
I think one of the phones should stay an android phone though.

**Comment by maxvisser** [comment]
maybe the left one

**Comment by linda-90** [comment]
Okay, added an Android phone

**Comment by maartenfv** [comment]
Issue is back open. We have gotten feedback. They want to add a third screen with Me logo. 

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/c5503127-a5f5-4fa1-801e-79477d07ea90)

**Comment by linda-90** [comment]
![image.png](https://images.zenhubusercontent.com/5e79fcf1079ee5a57285661f/35ae4119-84ce-40d4-80c5-62dbc6a936e4)

**Comment by maxvisser** [comment]
How would this look on mobile? I think having two screens looks alot better. Also: could we show the municipality the prototype before starting development? (to not have to reopen this issue again..)
