### ISSUE TITLE
Custom emails | Make system generated emails adjustable

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#768]
Proposal: https://docs.google.com/document/d/1jnFYQ0p9SUCd4jN3YWsnF5_7I37AXp-uY_MgaLhu-vA/edit
Figma: https://www.figma.com/file/E09uZSki0EQM7J7x5IeUiV/Webshop-%3E-System-e-mails

As a Sponsor I want to be able to have an overview of all the e-mails the system generates. Some of these emails need to be adjustable. See written proposal for details.

This issue helps with making the emails more recognisable in the webshop context and make them more flexible.

**Comment by jamalv** [comment]
Looked at it yesterday together with the team. Good proposal :) - how are you looking at the scope? Initial reaction of the team is that the scope currently in the _review_ page would take about 2-3 sprints.

The *review* page seems to contain quite some "should have" / "must have" features. Maybe it's an idea to start on a "master" page (duplicate of review") and strip down the scope to what's **must have** initially?

**Comment by jamalv** [comment]
Would also be nice to add some existing pages for context; I see some new ideas in the menu; it would be nice to see how you reach this page? What's the user path?

**Comment by jamalv** [comment]
maarten: vanmiddag wordt planning met dan besproken

morgen even bespreken jamal maarten

**Comment by jamalv** [comment]
maarten stuurt naar groningen, kan over een paar weken aan begonnen worden

**Comment by jamalv** [comment]
@maartenfv kan deze geplanned worden? of wachten we eerst reactie af van de gemeente? en als deze geplanned kan worden, doen @danrminds dat dan?

**Comment by jamalv** [comment]
als ik naar het voorstel kijk, lijkt het wel alsof er nog een definitief design moet komen

**Comment by maxvisser** [comment]
oplevering is na 2 sprints 28 mei; hierna review en acceptatie test. Ik stel voor om deze mee te nemen in de release van 28 juni.

**Comment by maartenfv** [comment]
@maxvisser Hoe staan we er voor?

**Comment by maxvisser** [comment]
deze general issue kan gesloten worden
