### ISSUE TITLE
Generic search

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#770]
# [View on roadmap  >](https://roadmap.forus.io/c/52-algemene-zoekfunctie)

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/6824965

**Comment by maartenfv** [comment]
https://programmablesearchengine.google.com/about/

**Comment by maartenfv** [comment]
https://www.algolia.com/

**Comment by maartenfv** [comment]
Made a schedule with Jamal. (Check everhour)

Jamal will make proposal
Max will review proposal
Linda makes design
Needs to be discussed with Dan to schedule.

**Comment by maxvisser** [comment]
Linda will do a design
Jamal will write proposal (already done)
Max will review the proposal together with valentin and enhance with technical details
-> https://docs.google.com/document/d/19D34FaBAop-47_Nql3nOj1_9KXpsuxli9p6lJOz54eA/edit#
Valentin -> 8h

**Comment by maxvisser** [comment]
@maxvisser create design task for linda

**Comment by jamalv** [comment]
questions:
- search trough pages, how big is the scope?
- back button from details page (remember search result) how big is the scope?
- how to do this technically? especially filtering by relevancy; find a good dependancy?

**Comment by linda-90** [comment]
Design: https://www.figma.com/file/DP3zSdWXVutjc5s81d4s3H/770%3A-Generic-search?node-id=93%3A7691&viewport=2261%2C830%2C0.10300933569669724
