### ISSUE TITLE
Can never be more than 100%

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#771]
![image](https://user-images.githubusercontent.com/30211022/109011319-0b8cd500-76b1-11eb-81f4-5ae0134af05c.png)

Needs an error when higher than 100 and a percentage mark.

**Comment by TomForus** [comment]
![unknown](https://user-images.githubusercontent.com/36765624/109011753-8a820d80-76b1-11eb-9747-50cbc45a1e03.png)

**Comment by maxvisser** [comment]
:joy:

**Comment by jamalv** [comment]
ah, pretty big oversight, @maxvisser let's hotfix this one?

**Comment by maxvisser** [comment]
Agree; pretty big oversight. if needed; it can be hotfixed but I do not see this as highly impactfull. 
As these products are actually free and can't be reserved I do think the damage is pretty small (small impact); as providers who run a legit business probably aswell don't want to fill in any higher number then 100%. 

but lets put it on the top of the sprint backlog and fix the issue from master.
