### ISSUE TITLE
Provider: Improve modal after creating a product

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#773]
![image](https://user-images.githubusercontent.com/30211022/109155015-5f5df380-776f-11eb-97a4-85365d3a3600.png)

This pop-up does not make sense. The flow needs a review and better texts.

**Comment by maxvisser** [comment]
@linda-90 Kun jij een betere tekst schrijven voor deze modal? (deze krijg je nadat je een product aanmaakt.)

**Comment by linda-90** [comment]
Wat voor nut heeft deze modal? Ze klikken op de pagina ook al op bevestig?
