### ISSUE TITLE
Email | Confirmation page needed after verifying mailadress

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#775]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Add a confirmation page or fitting message after a user changes their emailaddress. Would be nice to have an eye candy 
page after verification. For short term we definitely need to have a dutch translation

English: _You successfully verified your email_
Dutch:  _Het is gelukt! Je e-mailadres is bevestigd._

Current page:
<img width="1253" alt="Screenshot 2021-02-26 at 09 11 52" src="https://user-images.githubusercontent.com/38419514/109279273-d6e85d00-7819-11eb-9c65-94ab64a40507.png">

**Comment by maxvisser** [comment]
added a figma page which is already implemented on signupflow: https://www.figma.com/file/DDmzhiepvKFmDAenW8RmBC/E-mail-confirmation?node-id=176%3A137&viewport=477%2C373%2C0.4546875059604645

**Comment by maxvisser** [comment]
Planned for development
