### ISSUE TITLE
Change request: Adjust error message for failed payment

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#777]
**Support Ticket ID:** [#3178]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @Michaelforus

### Change description
If the provider makes a payment and the plastic card is not activated, the provider will get the following error: "No query results for model".
Please adjust the error message. For example: "De pas is niet geactiveerd".

<img width="397" alt="Schermafbeelding 2021-03-03 om 10 06 41" src="https://user-images.githubusercontent.com/66309692/109781390-29ee5580-7c08-11eb-9337-f375cb425ddb.png">

**Comment by maxvisser** [comment]
Released
