### ISSUE TITLE
individual and bulk invite providers

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#78]
For large implementations the system needs to have a feature which allows providers to be invited to register for a fund.

Some sponsors already know which providers they wish to invite for the fund. They have a list of email addresses or phone numbers. During the fund creation proces and when clicking on the provider tab in the sponsor dashboard the option to add providers is needed.

- [x] Generate a link which can be send to providers to invite them for the registration proces.
- [ ] An easy way to copy this link so it can be pasted in emails etc.
- [ ] Add the option to share this link on social media. (twitter, facebook) (optional)
- [ ] Allow to enter the individual email adres of a provider which will receive an email with the link and an invitation text.
- [ ] Allow the sponsor to adjust the invitation text. (this opens a whole new thing in regards to each sponsor setting their own texts for other system communication as well) (optional)
- [ ] Allow to enter multiple email addresses of providers which will receive an email with the link and an invitation text. (This is useful when adding, for example, 5 providers. Enter the email adres, click the add another button so a new field appears, repeat as necessary and press send once.)
- [ ] Allow to upload a list (bulk) of email adres of a provider which will receive an email with the link and an invitation text.
- [ ] Show pending invitations (inc the date/time they have been invited)

**Comment by maxvisser** [comment]
@maartenfv could you help us by splitting this up?

**Comment by jamalv** [comment]
https://roadmap.forus.io/c/27-bestaande-aanbieders-toevoegen
