### ISSUE TITLE
Show funds while not logged in (potjeswijzer)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#782]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
[Erwin](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_1257514803?webUrl=https%3a%2f%2ftasks.office.com%2fb4a9ddbe-ddec-41ba-977a-154b31a1847e%2fHome%2fPlanViews%2f-rWQG76nFU-2YfF2jIBD1JgAC-ia%3fType%3dPlanLink%26Channel%3dTeamsTab&label=Ik+zou+op+de+voorpagina+willen+zien+welke+potjes+er+zijn%2c+evt.+de+belangrijkste+met+een+doorklik+naar+Meer+Potjes+in+Backlog+overzicht&context=%7b%0d%0a++%22subEntityId%22%3a+%22T12wWacv2ku5uvVdeth1kJgADXVD%22%2c%0d%0a++%22channelId%22%3a+%2219%3a00622d755b8e4e2b97eb92587835fd07%40thread.tacv2%22%0d%0a%7d&tenantId=b4a9ddbe-ddec-41ba-977a-154b31a1847e)

### Change description
As a requester I'd like to see the available funds from the homepage

Proposed solution: currently we only show funds (potjes) when logged in: show the funds menu item also when not logged in for potjeswijzer.

**Comment by maxvisser** [comment]
released
