### ISSUE TITLE
As I sponsor I would like to see the card number and connect/disconnect cards

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#783]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As I sponsor I would like to see the card number and connect/disconnect cards

Figma: https://www.figma.com/file/94FYlEOLkCYkkwJKtx5NpJ/Physical-cards-in-dashboard?node-id=0%3A1

**Comment by jamalv** [comment]
Prepared the Figma page for design and technical review: https://www.figma.com/file/94FYlEOLkCYkkwJKtx5NpJ/?node-id=6%3A23380

@maxvisser @linda-90 could you please have a look?

**Comment by maxvisser** [comment]
Requirements:
Use fund config to allow sponsor to connect cards (same as config we use for webshop)

**Comment by jamalv** [comment]
@maxvisser @danrminds  I see text review is done, but this has not been planned for alex. Could you plan this asap? We'd like this to make the next release.

**Comment by danrminds** [comment]
@jamalv This will be planned for next week for Dmitryi. I will take care of planning it soon

**Comment by maxvisser** [comment]
As this will be part of onboarding of Dimitry and can't be finalized before wednesday it will be released on 19 of april

**Comment by maxvisser** [comment]
released
