### ISSUE TITLE
Koppeling / Connection Nijmegen

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#784]
### Requested by:
- Nijmegen
 	
### Change description
Sponsors often have back office system built by Centric or Pink Roccade.

**Automated checks**
In automated checking there are two steps. First step was DigiD and this is now working properly. The second step is to make it possible to carry out checks with the applicant's BSN.

We want to check with the BSN number if a requester is known in the back office system of the sponsor (in the first use case  this will be a Centric application or ESB facility / common ground implementation). We will check in the backoffice if requester already has a current benefit or is entitled to other funds.
This way we retrieve the most up-to-date information (in yes / no form) via SUWI / intelligence agency and thus also be able to assign it automatically for "unknown" residents.

## Proposal
https://docs.google.com/document/d/1CJIzLuhm9Zz_URL4wuT_sed-ddoRZxzYZj7zCQV64MI/edit#

**Comment by maxvisser** [comment]
Hi Maarten this seems to be a duplicated of #435; I will update the issue and move over the comments from there to here; as you planned this issue in

**Comment by maxvisser** [comment]
Updated the API Spec together with @danrminds and  @dev-rminds . wrote down whats needed for implementing the connection. @danrminds and @dev-rminds will look into time/planning. @danrminds could you discuss this with @maartenfv what your idea about it is?

**Comment by maxvisser** [comment]
Max makes a proposal for loading and error pages; dashboard settings pages

**Comment by maxvisser** [comment]
@maxvisser make the issues for the tasks

**Comment by maxvisser** [comment]
https://www.figma.com/file/O3A1gpSSTJ5xoxavB4zOeG/?node-id=66%3A412

**Comment by jamalv** [comment]
@maxvisser as discussed we'd share instructions for the municipality to start building/testing - will we manage that?
