### ISSUE TITLE
Add me logo with downloads

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#785]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Groningen

### Change description
As a requester, I want to have a trustworthy experience when downloading the me app.

Figma: https://www.figma.com/file/5mYDgbgFE4Lz2jg6O0tUHl/?node-id=0%3A1

**Comment by jamalv** [comment]
@linda-90 could you please design review?

**Comment by maxvisser** [comment]
me logo now looks like something you can click

**Comment by maxvisser** [comment]
Most of the scope is released. The only thing which is missing is the screenshots on Me page

**Comment by jamalv** [comment]
comments in figma; @linda-90 kan je de comments in figma checken?

vraag van maarten aan @linda-90 @maxvisser is om het onderling af te stemmen en snel te releasen

**Comment by linda-90** [comment]
Heb design aangepast en besproken met @maxvisser en @maartenfv 

Nog een andere wijziging:

![image](https://user-images.githubusercontent.com/36952230/113136054-2d82f580-9223-11eb-9b4e-d4a6a4071b29.png)

Icon is in voorstel wit ipv blauw.

**Comment by jamalv** [comment]
@maartenfv: het is gelukt! :D - het staat al live!

https://stadjerspas.gemeente.groningen.nl/me
