### ISSUE TITLE
Risk/Damage control migration issue | Using test IBAN/No IBAN for provider

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#787]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Implementation/Groningen

### Change description
Groningen wants us to make an account for about 66 providers without an IBAN. The problem we think will occur is that Groningen will make offers for these accounts and place them on the webshop. When people will start making transactions our system will make API calls to bunq. These can however not be fulfilled because the IBAN is not correct.

Can we adjust the sign-up to make sure that we can create organisations without IBAN? (not urgent but needed. If possible to do within hotfix then would be very nice)
How can we fix this problem with the accounts that use IBAN: GB33BUKB20201555555555? (this is how we create the organisations now)? (when this one is used then scanning should not be possible?)
Can we make some checks so that these calls get special status in relation to bunq/transaction dashboard?

This relates to the problem we had with the staging environment. Here bunq blocked staging API connections when we are doing to many "wrong" calls.

**Comment by maartenfv** [comment]
@danrminds Can you give an update?

**Comment by maxvisser** [comment]
When will we release this? Its impacted pretty core functionality which is hard to test (paying out to providers); should be fixed from master; gerben / max needs atleast a few hours next week to review/accept this

**Comment by danrminds** [comment]
The only thing that was within scope for now - is checking whether the IBAN of the provider is: GB33BUKB20201555555555 - and in this case the transaction would not initiate a BUNQ transaction.

Later scope:
When sponsor trying to add an action (with an amount to be paid to provider) - on a provider with this or no IBAN - show an error message saying that the IBAN of the provider is not valid.

**Comment by maxvisser** [comment]
I would not add more to the scope; building more stuff on this workaround seems like wasted time. I would just start thinking about a long term solution and implement that.

**Comment by maxvisser** [comment]
If the short term solution is also needed for the long term solution lets do it ofcourse.

**Comment by maxvisser** [comment]
a fix for this will hopefully be released tomorrow.

**Comment by maxvisser** [comment]
Fix is released, IBAN to skip is added, it works now like this:
we check if IBAN is in a 'skip list', skip list contains GB33BUKB20201555555555
if IBAN is in skip list we do not sent transaction to BUNQ we add +1 to the attempts and try again for 5 times; If provider changes IBAN within 5 days of the transaction we will still payout the transaction after the 5 days forus needs to add the transaction manual to the queue again.
