### ISSUE TITLE
POT | Provider should agree with terms and conditions

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#79]
## Description

- [ ] Add checkbox and terms and conditions on signupflow

**Comment by MedinaG** [comment]
De AV liggen bij Koen Konings voor een check..

**Comment by maxvisser** [comment]
@maartenfv could you give an update on AV?

**Comment by maxvisser** [comment]
@linda-90 Maarten says you probably should know this?

**Comment by linda-90** [comment]
@maxvisser Er is een opzet voor de algemene voorwaarden van Forus https://github.com/teamforus/implementation/issues/445#issuecomment-683696394. 
De algemene voorwaarden specifiek voor de aanbieder zijn er volgens mij nog niet.

**Comment by jamalv** [comment]
Please re-open this issue when the terms and conditions are available
