### ISSUE TITLE
Logout user after 15 minutes

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#790]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Logius

### Change description
A user needs to be logged out after 15 minutes.

**Dutch:**
Na het inloggen houdt de webapplicatie een sessie met de gebruiker bij. Na maximaal vijftien minuten inactiviteit verloopt de sessie. Bij uitloggen of als alle actieve browserschermen afgesloten worden, vervalt de sessie ook.

**Comment by jamalv** [comment]
@maxvisser can we reproduce this?

**Comment by maxvisser** [comment]
It's similar to the ITSM issues about this topic. Maybe plan those in. Already made some proposal for most of them.

**Comment by jamalv** [comment]
But a user should now still be logged out after 15 minutes, right? Is this functionality currently working? Is there an easy way to test this? Or should we just open a window for 15 minutes?

**Comment by maxvisser** [comment]
I checked the configuration. Seems that the flag ``log_out_time: autoLogOutTime,``is missing at Geertruidenberg implementation. If its not set by default. It could not be working.
