### ISSUE TITLE
As a provider I would like to cancel my application for a fund if it's not accepted yet or rejected

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#795]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- @GerbenBosschieter 

### Change description
- Providers accidentally apply for the wrong fund and forget to apply for the right fund. After accidentally applying for a wrong fund they can't cancel this anymore. As long the application is not procssed yet or the application is rejected we should give the option to cancel the application

**Comment by GerbenBosschieter** [comment]
Related issues:
- https://github.com/teamforus/general/issues/584
- - https://github.com/teamforus/general/issues/794
- https://github.com/teamforus/general/issues/519
- https://github.com/teamforus/general/issues/624
- https://github.com/teamforus/general/issues/78
- https://github.com/teamforus/itsm/issues/449

We already created change requests for similar / related issues. Our users are now asking support for this scenario but we decided no to support because of the reasoning: We should build a feature.  Since we don't, I can't give the support I would like to.

I would like to ask for extra attention for these change request.

**Comment by maxvisser** [comment]
Made a figma file for this issue:
https://www.figma.com/file/g9Uc1iUiGi69nYE3XOjRwv/?node-id=176%3A138

**Comment by maxvisser** [comment]
discussed with gerben; as these are probably some small changes to the templates (no big visual change) he want to try to make the figma proposal.

**Comment by GerbenBosschieter** [comment]
Further worked on [Figma proposal](https://www.figma.com/file/GkEYwSu3oEAezfVVqmPkoj/Provider%3A-cancel-fund-application?node-id=66%3A412). @maxvisser @aghimpu please review if this is feasible

https://www.figma.com/file/GkEYwSu3oEAezfVVqmPkoj/Provider%3A-cancel-fund-application?node-id=66%3A412

**Comment by maxvisser** [comment]
I tested this feature. Seems that the text is too specific. If you cancel for fund where you are accepted its does not make sense anymore.

Can we adjust the text? @GerbenBosschieter
