### ISSUE TITLE
Me-app: Add transaction note to transaction details

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/general#797]
**Support Ticket ID:** [#3281]

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Provider

### Change description
- Add transaction note to transaction list<br>

**Comment by GerbenBosschieter** [comment]
A lot of providers do not use the dashboard and only use the Me-app. For some organizations it would be really usefull to see what note was added during the payment. They use the note to see who the payments belong to so they can use this for their administatrion

**Comment by maxvisser** [comment]
Check if this can be part of 0.5.0

**Comment by maxvisser** [comment]
@jknnr Could you help me plan this in ?

**Comment by maartenfv** [comment]
@maxvisser Can we ask @danieltcacenco to do this?

**Comment by maxvisser** [comment]
Moved to itsm.
