### ISSUE TITLE
Integrate productboard

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#799]
As a user, I would like to give feedback on the product so that the developers know what improvements I would like to see.

<p></p>

**Figma Proposal:** [[https://www.figma.com/file/xzFZGRITMAtMsPFUETtRZU/Feedback-from-dashboard?node-id=3%3A0](https://www.figma.com/file/xzFZGRITMAtMsPFUETtRZU/799---Integrate-productboard?node-id=0%3A1)](https://www.figma.com/file/xzFZGRITMAtMsPFUETtRZU/Feedback-from-dashboard?node-id=3%3A0)

<p></p>

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/7507604

**Comment by jamalv** [comment]
nice one! @maartenfv could you add urgency and priority labels?

max and I discussed this during intake and made a quick figma wireframe here: https://www.figma.com/file/xzFZGRITMAtMsPFUETtRZU/Feedback-from-dashboard?node-id=3%3A0 

The api asks for:

![Screenshot 2021-04-01 at 13.40.50.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/ba46cb86-2958-4ab8-9ad9-d8f5e6205d27)

**Comment by jamalv** [comment]
Proposal: add details to "content",

**Organisation** [organisation name]
**Current page** [link of page that is currently opened] 

etc.

**Comment by jamalv** [comment]
Update: we have now created a new e-mailadres:

feedback@forus.io > which automatically forwards feedback to productboard.

another proposal for addressing this need would be to add contact options along the lines of:

[do you have questions about how to use this product?] : support@forus.io
[do you have ideas on how to make it better?] : feedback@forus.io
[do you want to learn how to use it?] : support.forus.io

We could add a new tab to all environments [support] or similar. > there we could add these options

**Comment by jamalv** [comment]
Feedback from Valentin: is it possible to do this more like an embed?

**Comment by jamalv** [comment]
@jamalv add feedback from sprint demo.

**Comment by lexlog** [comment]
intake note - unasign Alex, Jamal needs to plan it

**Comment by jamalv** [comment]
Updated the proposal with feedback: https://www.figma.com/file/xzFZGRITMAtMsPFUETtRZU/?node-id=501%3A20889 - can be planned for @aghimpu (I couldn't manage to properly align the checkbox with autolayout, but I think you will understand :))

**Comment by jamalv** [comment]
let's discuss during refinement

**Comment by lexlog** [comment]
@jamalv will update proposal after sprint planning discussion ( show email after checkbox is filled)

**Comment by lexlog** [comment]
@aghimpu please add the estimations

**Comment by jamalv** [comment]
> @jamalv will update proposal after sprint planning discussion ( show email after checkbox is filled)

Done

**Comment by lexlog** [comment]
refinement note - @aghimpu clear, 2h est
@jamalv will open figma file for @aghimpu

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-frontend/pull/2085
https://github.com/teamforus/forus-backend/pull/1387

**Comment by lexlog** [comment]
refinement note - no need for demo, small changes that were shown already in previous demo

**Comment by lexlog** [comment]
refinement note - @GerbenBosschieter review (transferred yesterday)

**Comment by lexlog** [comment]
refinement note - should be released soon before laravel
