### ISSUE TITLE
Footer not correctly aligned

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#800]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

### Change description

![image](https://user-images.githubusercontent.com/30211022/113295144-195cf800-92f8-11eb-9c92-364d89cbc14a.png)

**Comment by maxvisser** [comment]
weird. 

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/84d4198e-88c4-4268-ad66-96c86f781207)

**Comment by maxvisser** [comment]
fixed in release v23

**Comment by maxvisser** [comment]
released
