### ISSUE TITLE
CR: Voucher blokeren en verwijderen (deactivate)

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#806]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Gemeente Groningen
- SDOA

### Change description
- Gemeentelijk medewerker wil de pas via de beheeromgeving kunnen blokeren.
- Gemeentelijk mederwerker wil de pas via de beheeromgeving kunnen verwijderen
- Inwoner wil een verzoek kunnen indienen om account te verwijderen.

**Comment by maxvisser** [comment]
We hebben 'state' actief en inactief. Misschien naast voucher activeren ook deactiveren?

**Comment by maxvisser** [comment]
Wat wil de gemeente na blokkade? Blijft de voucher gekoppelt aan bsn en verloopt tie na een jaar wat dan betekend dat de inwoner pas volgend jaar weer aanvraag kan doen?

**Comment by maartenfv** [comment]
Bas geeft dat wij toegang hebben tot het oude systeem en daar kunnen inzien om welke redenen passen werden geblokeerd (mutaties).

**Comment by maartenfv** [comment]
Figma: https://www.figma.com/file/gqlB1qA3B2EyWf9AXFAOHL/Deactivate-voucher?node-id=15%3A22&viewport=-5003%2C371%2C0.8350463509559631

**Comment by maxvisser** [comment]
ook tekst voorstel schrijven wat betekent blokkeren etc; zie je een andere melding in de Me-app? etc.

**Comment by jamalv** [comment]
Ook belangrijk om scherp te zijn op definities en verwachtingen:

**1: Pas:** het plastic pasje dat voor de Stadjerspas wordt uitgegeven - kan geblokkeerd worden door medewerker en inwoner

**2: Tegoed(bon) / voucher:** de daadwerkelijke digitale tegoeden; te gebruiken vanaf de site, mail, app & pas - (bovenstaand Figma voorstel) - o.a. rekening houden met: 
* weergave in de app/site etc
* wat gebeurt er als een aanbieder een pas scant die geblokkeerd is?
* hoe is communicatie naar inwoner/bij gemeente

**3: Account:** identiteit op basis van het e-mailadres - bijvoorbeeld ook voor aanbieders - o.a. rekening houden met:
* wie kan verwijderen en welke reden? - 
  * als inwoner zelf; wat gebeurt er met de data (archiefwet etc) - & technisch voorkomen mogelijkheid dubbele aanvraag
  * als beheerder - is het haalbaar om te bepalen wie welke accounts mag verwijderen? (lijkt me niet?)

Voordat de ontwikkeling start is, om de complexiteit van bovenstaande zaken dat de requirements duidelijk op papier staan.

**Comment by maxvisser** [comment]
@jamalv @danrminds I see that Dimitry built whats inside this figma proposal;
https://www.figma.com/file/gqlB1qA3B2EyWf9AXFAOHL/?node-id=0%3A1

Seems like these things are still missing in figma:
- the mail which the user gets with the reason
- where the reason is shown
- what are the cases that a sponsor can deactivate a voucher (should it be active or can it also deactivate a inactive voucher)

**Comment by maxvisser** [comment]
Also there was no text proposal written. Could we still do this as this is a documentation strategy right?

**Comment by maartenfv** [comment]
@maxvisser Do you have a template of this text proposal written? Or a link to read more about it?

**Comment by maartenfv** [comment]
@linda-90 Kan je het voorstel dat je met Dan hebt gemaakt in Figma verder uitwerken tot een werkbaar stuk? (op basis van text proposal written?)

**Comment by jamalv** [comment]
algemene template: https://github.com/teamforus/general/blob/master/manuals/development/issue-improvement-proposal.md

wellicht ook goed om even naar een paar eerdere voorbeelden te kijken?

**Comment by linda-90** [comment]
@maxvisser @maartenfv Tekstueel voorstel: https://docs.google.com/document/d/1mlmLN37xzJL0LHEeJr0OTwRoYdAnwSABbrvLzhYcE2c/edit#

Mochten er nog zaken missen, please let me know

**Comment by linda-90** [comment]
Seems like these things are still missing in figma:
- the mail which the user gets with the reason > is in Figma
- where the reason is shown > was already in figma
- what are the cases that a sponsor can deactivate a voucher (should it be active or can it also deactivate a inactive voucher) > both
- How would a deactivated voucher look inside Me-app / webshop > is in figma

**Comment by jamalv** [comment]
@maxvisser is the above sufficient to continue?

**Comment by jamalv** [comment]
maarten geeft aan: gemeente vereiste is mailtjes versturen naar overledenen; zijn de requirements duidelijk tussen max en linda? even contact tussen max en linda hier over.

**Comment by maartenfv** [comment]
Max en Linda gaan hier over in gesprek :) en maken een plan hoe we dit kunnen uitwerken en uiteindelijk releasen.

**Comment by jamalv** [comment]
net gebeurt; 3 dingen besproken: overlijden, hoe om te gaan met aanvraag deactiveren, en de meldingen.

**Comment by jamalv** [comment]
linda werkt de tekst even uit, dan kunnen mensen meelezen :D

**Comment by jamalv** [comment]
2 casussen worden afgedekt; voor overlijden is wellicht een nieuwe optie nodig (intern checken en evt. extra vragen stellen aan groningen) voorstel voorleggen aan groningen en evt. andere gemeente.

**Comment by jamalv** [comment]
Goedemorgen Maarten, Jamal,
 
Onderdeel van het project was nog de eis/wens van de medewerker (C4) en de pashouder (B2) om over functionaliteit te beschikken voor het kunnen de-activeren van een Stadjerspas. Enkele weken geleden had ik begrepen dat jullie bezig waren om hier een voorstel voor uit te werken. In bijgevoegd document is door Leonie een aantal situaties (user stories) beschreven waarvoor deze functionaliteit van toepassing is. Zouden jullie deze daarin kunnen meenemen? En wanneer kunnen we de uitwerking verwachten?
 
Groet, Bas

[https://app.zenhub.com/files/123948463/335013f7-443d-413a-9a95-c0b8039d50e6/download](https://app.zenhub.com/files/123948463/335013f7-443d-413a-9a95-c0b8039d50e6/download)

**Comment by maartenfv** [comment]
@linda-90 neemt contact op met Paul

**Comment by jamalv** [comment]
in afwachting van reactie

**Comment by jamalv** [comment]
voorstel lijkt goed - wordt verder uitgewerkt - nog uren inschatting nodig.

**Comment by jamalv** [comment]
straks bij refinement bespreken en ureninschatting vragen van het team.

**Comment by jamalv** [comment]
gister besproken tijdens refinement - team heeft even tijd nodig voor een goede ureninschatting - max herinnert Dan er vandaag even aan - komt vandaag.

**Comment by maartenfv** [comment]
@maxvisser @jamalv Is bovenstaande gelukt?

**Comment by jamalv** [comment]
Yes! Got the estimation this morning. Development will take about 1 or 1.5 sprints.

Note from maarten: Should be implemented systemwide

**Comment by maxvisser** [comment]
Linda gaat er mee aan de slag; vanaf volgende week maandag start ontwikkeling

**Comment by jamalv** [comment]
maandag start is afhankelijk van of het voorstel af komt en 2e deel koop op afstand - of het deze week afgemaakt wordt of deze week nog loopt.

straks na refinement iets beter beeld. - max heeft weinig zicht op 2e deel koop op afstand.

**Comment by maxvisser** [comment]
Koop op afstand loopt uit; dus we starten maandag nog niet met deactiveren passen.

**Comment by jamalv** [comment]
verwachting nu is volgende week maandag (afhankelijk van hoe deze week gaat)

**Comment by linda-90** [comment]
@maxvisser @maartenfv 

Please check: https://github.com/teamforus/implementation/issues/656

**Comment by linda-90** [comment]
Gisteren niet aan toegekomen, bel na de daily!

**Comment by maartenfv** [comment]
https://app.zenhub.com/workspaces/whole-team-5e79d635e969e6cdeeebb411/issues/teamforus/implementation/656

**Comment by jamalv** [comment]
deze is leading voor daily: https://app.zenhub.com/workspaces/whole-team-5e79d635e969e6cdeeebb411/issues/teamforus/implementation/656

**Comment by maxvisser** [comment]
released 30 august in v0.29.0
