### ISSUE TITLE
Proposal: Account recovery

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#81]
# Problem description
The platform doesn't give any possibility to recover your account.
This can be very frustrating if someone can't acces their mail-address anymore.

This has already been a talking point multiple times from support questions.
Right now we are solving this problem by changing the mail-address in the database this results in to other problems:
1. It's really hard for us to verify someone's identity without the help of the sponsor, so we can not just change someone mailadres just because they ask us. 
2. Changing the mail-address in the database is not something we really want.

## Proposal
Add a recovery option when creating a profile.
Options:
- Recovery mail-address
- Recovery by phone number (SMS)
- Recovery sentence
- Username / password

### Additional context
- Solution should be backwards compatible or at least not a have a negative effect on our current users
- Solution should be optional but at least require one recovery option. For example: a recovery mail-address can not be mandatory because a lot of people don't have two mail-adressen

**Comment by GerbenBosschieter** [comment]
@maxvisser why is this in the icebox?
@jamalv priority depends. Do we have another solution if people cannot acces their email so cannot acces our platform?

With our new client we will get a lot of users. If don't have another solution for the problem stated above. The priority is really high and should be fixed until we are going live with our new project.

**Comment by maxvisser** [comment]
For Groningen there will be DigiD

**Comment by jamalv** [comment]
@GerbenBosschieter will DigiD be sufficient?

**Comment by jamalv** [comment]
Has been added to roadmap: https://roadmap.forus.io/c/59-account-herstel

**Comment by maartenfv** [comment]
Still needed

**Comment by jamalv** [comment]
Closing this issue and adding it to stale issues https://github.com/teamforus/general/issues/841 - if we plan this, a project should be opened. In the meantime, productboard can be used for votes/input.
