### ISSUE TITLE
Export translation: granted to 'goedgekeurd'

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#811]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Currently for the export for fund requests (validator dashboard), the translation is still in English, better to also translate this to dutch. Suggestion is 'goedgekeurd'

**Comment by GerbenBosschieter** [comment]
I thinks this counts for all our exports. Better make a list of all needed translations where this is the case and do all of them at once

**Comment by maxvisser** [comment]
This was fixed for Waalwijk
