### ISSUE TITLE
Fund cycles and financial information

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#812]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Valentin/Max

### Change description
Working on the financial dashboard we noticed its pretty difficult to show transactions which are needed for budgetting purposes:

for example:
a fund runs from 1 jan 2020 to 31 december 2020 
and is renewed on 31 december (extended to 31 dec 2021)

Currently the only way to see that voucher was generated for the previous year is its expire date and creation date. This is a loose connection which makes it hard to show financial statistics and can result in inaccurate data.

My proposal is to add fund cycles:
current start and end date are 1 on 1. There can only be one start date and one end date
A fund cycle can be a period in time for example multiple years, a year, half a year; this is the period that the vouchers stay valid. Each voucher you generate in the period are linked to the current cycle; This way even if a voucher is generated manually you can still tell that its transaction are part of a specific year.

Problem we solve:
- We currently don't show vouchers transactions which are expired on the financial overview. After this update we only show voucher transactions which are part of a specific cycle.
- We can register topups based on a cycle, when a new cycle starts we can 'reset' whats already topped up.

**Comment by jamalv** [comment]
I like the idea. Two questions:
* Will this be a choice for the sponsor or mandatory for all funds? Some sponsors really think in calendar years (e.g apply in November, valid until jan 1), others more in a 12 month period from the start date (e.g. apply in November, valid until November)
* Related question: will this impact how vouchers can expire as mentioned above? Are both options possible or only one of the two?

**Comment by maxvisser** [comment]
Conversation with main stakeholder:
Tegoeden: need to calculate last years end saldo and show it in the table; and filter the table on creation date.
Same with top table

**Comment by maxvisser** [comment]
I will plan this in to be worked on in the project overgang-2021

**Comment by maartenfv** [comment]
@maxvisser is dit gelukt? Is er een update?

**Comment by maxvisser** [comment]
Dit is niet gelukt en wordt deel van 't nieuwe overgangsproject
