### ISSUE TITLE
Check all errors: write better ones.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#82]
## Description
Some errors on the platform are not really descriptive of the situation. This issue is about going through each webform and see all the errors and discuss how it looks.

## Task
- [ ] list all errors
- [ ] proposal for improvement

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/176

**Comment by maartenfv** [comment]
@maxvisser @SjoerdHilhorst Is er nog activity in deze issue? Wat is het plan om deze te sluiten?

**Comment by maxvisser** [comment]
Plan is om in kaart te brengen welke slechte errors er zijn en een voorstel te schrijven voor betere errors

**Comment by maxvisser** [comment]
en dan vervolgens in één keer alle errors te verbeteren :)

**Comment by jamalv** [comment]
@maxvisser Could we plan in time for someone to do this? Who could perform this issue? Let's put it in everhour?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/140039380-ef78c593-e8ed-4e39-9370-a1039552c8bf.png)
