### ISSUE TITLE
Add existing funds to potjeswijzer (give sponsor a choice)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#823]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a sponsor I would like a setting where I can choose to show my fund(s) on potjeswijzer, next to my own implementation.

**Context:**
We have a pretty cool website with potjeswijzer now, and already 35 funds are on the platform. Adding all funds at once to potjeswijzer is not feasible. But, if we give sponsors the choice we enable them to fill potjeswijzer with existing funds.

**Acceptance criteria:**
- On the fund settings page there is a toggle: show on potjeswijzer
- If a sponsor toggles this setting, the fund will be shown on potjeswijzer
- No matter what setting the sponsor chooses, the fund is always available on their own webshop, basically it is a duplicate.

@maxvisser my dream is that this issue is not too big :P could you let your thoughts go over it and estimate the scope?

**Comment by maxvisser** [comment]
Currently a fund can only be attached to one webshop at a time. All webshops are currently connected to the general webshop. 

The change would be that a fund can be in multiple implementation webshops at a time.
