### ISSUE TITLE
As a requester, I would like to see which pass number is linked to my physical card

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#826]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Requester

### Change description
- This is currently only possible if they click on **I lost my card** but this isn't something they will click on if they just want to know the card number that is connected to the voucher. Some users have multiple vouchers and plastic cards and they would like to know wich one is connected the voucher

**Comment by maxvisser** [comment]
Yes this is something which is really nice to do actually. Lets see in figma whats a logical place to put it;

Just on top of my mind I would add it here:
- in the breadcrumb
- after the fundname between ()

**Comment by maxvisser** [comment]
https://www.figma.com/file/pPRLF9jHhycsGUTxuCkSJn/?node-id=66%3A412

**Comment by maxvisser** [comment]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/3e83b52e-a26e-448d-ba0e-3b25a25a2bfd)

**Comment by maxvisser** [comment]
Released in v0.28.0
