### ISSUE TITLE
DigiD subdirectory

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#827]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Logius

### Change description

Adapt API to new method (8 hours ) Review
new method / test pre-production (4 hours ) Review
new method / testing production (8 hours)
Implementation with Logius 4 hours (max / jamal)

**Comment by maxvisser** [comment]
Needs a task with a english translation of the document.

**Comment by maxvisser** [comment]
https://docs.google.com/document/d/195EtLtmkiM4hgsDiSIUwSnpoyU7W9kXMg6Mn_04xb3M/edit#
