### ISSUE TITLE
Visual fix: Nijmegen search box CSS

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#828]
![Screenshot 2021-07-06 at 10.06.32.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/0e1061fe-aac3-4881-b904-f1d3b643b57c)

**Comment by maxvisser** [comment]
Task to check all webshops on styles of the search bar
must have: vertical align all texts in the middle of the search bar
