### ISSUE TITLE
KVK Check and apply as office

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#83]
## Context/goal: 
A school community example:
https://www.kvk.nl/zoeken/handelsregister/?handelsnaam=&kvknummer=08117581&straat=&postcode=&huisnummer=&plaats=&hoofdvestiging=1&rechtspersoon=1&nevenvestiging=1&zoekvervallen=0&zoekuitgeschreven=1&start=0

Have a head office and multiple suboffices but these suboffices have all different bankaccounts and access levels.

this issue is about refining an mvp where schools can join without using wrong KVK's and a long term solution where we support larger organizations which use 1 kvk

**Comment by maxvisser** [comment]
Made this prototype for this issue:
https://www.figma.com/file/iDG8cWW5MM0meW2LFbB6PE/KVK-Check-(apply-as-a-office)?node-id=0%3A1

@GerbenBosschieter @jamalv could you leave feedback; I thought about it a bit. I think this could work out great;

Right after the Welcome step we do a quick KVK check (does KVK exist we will do this different flow of adding user to an existing organisation)

**Comment by GerbenBosschieter** [comment]
I can only see an option to add an office if the kvk already exist in your prototype. But adding an office to a kvk number that already exist is not really a solution for the problem. 

How how would this proposal solve the community of schools problem?

**Comment by maxvisser** [comment]
Ah yes forgot to add IBAN field to Office creation step. But if you know which employee works for which office and you have an IBAN of that Office; The system could payout to the IBAN of the Office.

**Comment by GerbenBosschieter** [comment]
https://forus.testquality.com defect [D7](https://forus.testquality.com/project/11140/result/2336879/defect/7583). Do not remove or edit.

**Comment by jamalv** [comment]
Added to productboard as an insight: https://forus.productboard.com/insights/shared-inbox/notes/17398498

Added these user stories as well. Are they accurate? @GerbenBosschieter and @maxvisser?

As an office that is part of a national organisation, I would still like to be able to independently sign up to use forus.

As an office, I would like to be able to use a bank account number that is different from the main organisation.

As an office I would like to see financial flows independant of the organisaiton.

As a national organisation I would like to see the financials of participating offices separately.

**Comment by maxvisser** [comment]
Yes these are the user stories.
