### ISSUE TITLE
Emailadres in address menu bar instead of behind dropdown

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#830]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a requester I would like to see my e-mailadres in the top right address bar to see that I am logged into the right account (this is also useful for support to check if someone is logged in "do you see your e-mailadres in the top right?"

**Comment by maxvisser** [comment]
Task:
Add new navigation structure to figma,
Add e-mailaddress to menu bar

**Comment by maxvisser** [comment]
planned it for Max to work

**Comment by maxvisser** [comment]
Released in v0.29.0
