### ISSUE TITLE
Notification title and body are the same

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#835]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Could notification titles and bodies please be separated? Right now they are exactly the same, which is pretty dumb imo :)

## Current situation:
**Gemeente Groningen heeft een nieuw aanbod toegevoegd aan Entree Familiepark Nienoord.**
_Gemeente Groningen heeft een nieuw aanbod toegevoegd aan Entree Familiepark Nienoord._

<img width="1136" alt="Screenshot 2021-08-10 at 15 58 21" src="https://user-images.githubusercontent.com/30194799/128880517-3ddb8b81-bd32-46ed-bfb7-dcf806adeaff.png">

## Proposal:
**Nieuw aanbod toegevoegd.**
_Gemeente Groningen heeft een nieuw aanbod toegevoegd aan Entree Familiepark Nienoord._

**Comment by jamalv** [comment]
@maxvisser could you point to where these texts are?

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus-backend/blob/master/database/seeds/resources/mail_templates/notification_templates.json
