### ISSUE TITLE
Add notes to reservation (remote payments)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#844]
## User story:

As a provider, I would like to have more context about the user that made a reservation so that I know who made the reservation. For example name, address, etc. This way, when fulfilling the order I know who my customer is.

## Proposed solution:

Add an (optional) note field to the reservation, and show this note to the requester when making a reservation. Show this note to the provider as well.

## 2 possible routes:

**Option 1 (smaller scope):** Show the note field to everybody on all reservations, and add to the description that the user needs to fill this field. The pro of this is that the provider doesn't need to know they need to turn this on. The con of this, is that there's a possibility that users don't fill the note field.

**Option 2 (bigger scope):** Do as gerben suggested and let the provider set if the note is required, and make it mandatory for the end user. In this case probably the provider needs to let the user know what is expected, preferably in the note field itself, since you need to fill something. The pro of this is that all end users will fill the note, the con is that the providers need to understand how this works, this UX can be a bit challenging (add this to the product page? it is already a bit complicated).

**Note from Max:** Probably this user need of the provider will grow as we keep developing this feature; for example when users want to order a package, then the provider will need shipping info, so this note field is a first iteration.

**Figma:**  
<https://www.figma.com/file/UX0pdooeuJZV1Z6YOh0Pcn/Untitled?node-id=2%3A46>

**Comment by maartenfv** [comment]
@maxvisser Er is budget kan je het inplannen?

**Comment by Gerben** [comment]
> 
> 
> I created a 'support development' repo for developing issues like these so we can use the new development template issues.
> 
> I would not like to use general/forus/me repo's anymore for planning in development tasks as this bring to much unclearity of what does have budget and does not and you can't easily split it in different tasks etc.
> 
> Planned in for for @maxvisser: https://github.com/teamforus/support-development/issues/1
> 
> For @Gerben: https://github.com/teamforus/support-development/issues/2
> 
> For @jamal: https://github.com/teamforus/support-development/issues/3
> 
> For @maxvisser https://github.com/teamforus/support-development/issues/4

wat???????????????????????

**Comment by jamalv** [comment]
Proposed solution: add an (optional) note field to the reservation, and show this note to the requester when making a reservation. Show this note to the provider as well.

Note from Max: Probably this user need of the provider will grow as we keep developing this feature; for example when users want to order a package, then the provider will need shipping info.

**Comment by maxvisser** [comment]
In Release v0.31.0 - 27 december
