### ISSUE TITLE
Pie charts

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#852]
As a financial administrator, I would like to see financial data in a pie chart so I can get a quick visual understanding of the current state.

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/10533388

**Comment by maxvisser** [comment]
Would maarten like to show existing data we show currently on the financial statistics (line/barchart?) in a pie chart? That would be a small scope. If he wants to extend (use different data) this would be a medium or big scope.
