### ISSUE TITLE
Set scope of export

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#859]
As an administrator I would like to select the scope of every export so that I don't have to export the entire data set, if I only need a subset of the data.

Requirements: https://docs.google.com/document/d/1CrtWCFHc_6fRc2-Cbq60ignB92fGDNegvPVBK1Ich7k/edit#
Figma: https://www.figma.com/file/CKzXAJLJqp5fOyyQpmarcf/Untitled?node-id=0%3A1

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/10590849

**Comment by maxvisser** [comment]
Assigned michael as he submitted the insight.

**Comment by MichaelForus** [comment]
@maxvisser can you make an estimate? If we can do it within 20 hours, we have the support budget.

**Comment by jamalv** [comment]
FYI:
<img width="200" alt="Screenshot 2021-11-09 at 10 38 33" src="https://user-images.githubusercontent.com/30194799/140899838-3c8b6188-439a-4804-a3e4-a616d76771c0.png">

**Comment by GerbenBosschieter** [comment]
I like this change. This would not only improve the UX of doing exports but also prevents unnecessary dumps of data.

@jamalv we could use the support budget for this if it will cover the hours of development thats needed

**Comment by lexlog** [comment]
intake note - release and should be closed
