### ISSUE TITLE
Set product limit

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#861]
As a sponsor I would like to set a limit per product on a financial fund, so that a requester cannot use an offer more than x amount of times.

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/10591199

**Comment by maxvisser** [comment]
Seems a small issue but is rather complex and needs alot of testing

**Comment by maxvisser** [comment]
If I read the insight it aswell states to only use financial fund to reserve products (all users stories included in using an financial fund in such manner is not included in the scope estimation); I guess  that there would be more complex user stories to fix before the desire written in the insight could be implemented

**Comment by lexlog** [comment]
duplicate https://app.zenhub.com/workspaces/sprint-5f61c6c0a53fb84e755c82f6/issues/gh/teamforus/ede-2022-implementatie-meedoenregeling/69
