### ISSUE TITLE
Enable/disable budget payments

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#869]
As a sponsor I would like to enable/disable a provider to make financial payments so that I can allow a requester to only make specific purchases at a store.

<p></p>

**Criteria:** the option to fill the amount should be removed during checkout when this option is disabled.

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/10899755

**Comment by jamalv** [comment]
@maxvisser please note we already support this user story, but this request is mainly about the criteria.

**Comment by maxvisser** [comment]
I believe these are related:
https://github.com/teamforus/general/issues/845

**Comment by maxvisser** [comment]
We already talked about this during backlog refinement:
1-2 days of backend development + what ever is needed on the me-app (depends on implementation of the feature); our guess is that it definitely needs development on the apps though.

**Comment by maxvisser** [comment]
Reading the user stories there are two more which would maybe put this into the medium scope; Somethings I would say could also be necassary:
- what to do with left over budget on the voucher (for example product is 125 and voucher is 150; user is left with 25 euro's he is not be able to easily spend anymore. 
- more stress on providers creating and adding their products to forus; probably being able to add products as a sponsor needs to be checked again together with financial funds.

**Comment by jamalv** [comment]
@maxvisser this was funded by implementation and support, could you plan this in?

**Comment by lexlog** [comment]
intake note - @jamalv is it part of [this issue](https://app.zenhub.com/workspaces/intake-5fe1b67c5361800022a2646c/issues/teamforus/general/868) ?
then we can add it to the sprint to do them together
