### ISSUE TITLE
CR: Extend the menu with explainer and FAQ

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#87]
## Description

Current menu:
Aanbiedingen | Aanbieders

On smaller screens this just fits:
![image](https://user-images.githubusercontent.com/10818702/80689467-b18da400-8acd-11ea-8cce-2cf796557f32.png)
On larger screen we have no issues

New menu should allow more menu items like: 
Aanbiedingen | Aanbieders | Fondsen  | Uitleg

Figma link to add a proposal for a new menu which allows more links:
https://www.figma.com/file/sEenqvErGSaTEfwqhsGfmQ/Extend-the-menu?node-id=0%3A1

**Comment by maxvisser** [comment]
@jamalv lets use this CR to implement a new menu

**Comment by jamalv** [comment]
@danrminds could you have a look at this? https://github.com/teamforus/general/issues/54 depends on it

**Comment by maxvisser** [comment]
Updated figma. Dan made a proposal for a new frontpage.

**Comment by maxvisser** [comment]
Discussed this with jamal; Most of the webshop improvements will move to a seperate IP and aswell the mobile menu.

**Comment by danrminds** [comment]
@maxvisser 

So - should we just implement now the new menu, or just make some small adjustments for the current menu we have to allocate more space in it?

**Comment by maartenfv** [comment]
Discussed with @maxvisser text has been made smaller. The issue is fixed with a short term solution. Still needs an overhaul. Has become part of Epic webshop improvement.

**Comment by jamalv** [comment]
Yes, that's right, this issue went to https://github.com/teamforus/general/issues/49

Will close this one for now and work on improving that issue / tasks
