### ISSUE TITLE
View validation status information

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#870]
As a validator I want to see the status of a validation request so that I know if action by me or the requester is required or if the request has been finished.

<p></p>

**Statuses:**

1. Pending review (waiting for response by validator)

2. Pending clarification (waiting for response by requester)

3. Approved (information is correct)

4. Denied (information is incorrect)

5. Expired (long response times have passed, requester can start new request)

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/sDODi9Ry5Q1ZELMKYiNhOh/Validation-status-and-lead-times?node-id=3%3A3893

**Comment by lexlog** [comment]
intake note - release and should be closed
