### ISSUE TITLE
View QR code voucher generator

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#873]
As a sponsor I would like to see the QR code of the voucher that I have just created.

<p></p>

Currently it is only possible to view the QR code by exporting it, but this is sensitive for mistakes. The sponsor would like to also be able to view QR's directly in the UI after creating them.

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/11216887

**Comment by maxvisser** [comment]
Seems like a bug you are describing; it is intended that the QR-code is not visible anymore when the voucher is assigned.

**Comment by maxvisser** [comment]
Its pretty easy to add and I have no strong opinion to show the QR-code always. Easiest fix is to remove the frontend flag to hide it. Small if we want to change the way we present the QR-code and make a download button specifically for the QR-code.
