### ISSUE TITLE
Dutch URL's in webshop

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#875]
Change the URL's for dutch webshops:

Proposal: 

<https://paswijzer.waalwijk.nl/aanbieders> (was: providers)
<https://paswijzer.waalwijk.nl/aanbieders/{id}>

<https://paswijzer.waalwijk.nl/acties> (was: actions)
<https://paswijzer.waalwijk.nl/aanbod> (was: products)
<https://paswijzer.waalwijk.nl/aanbod/{id}>

<https://paswijzer.waalwijk.nl/uitleg> (was: explanation)

<https://paswijzer.waalwijk.nl/fondsen> (was: funds)
https://paswijzer.waalwijk.nl/fondsen/2/activeer (was: activate)
https://paswijzer.waalwijk.nl/fondsen/2/aanvraag (was: request)

<https://paswijzer.waalwijk.nl/tegoeden> (was: vouchers)
<https://paswijzer.waalwijk.nl/tegoeden/{address}>

<https://paswijzer.waalwijk.nl/algemene-voorwaarden> (was: terms-and-conditions)

<https://paswijzer.waalwijk.nl/beveiliging/sessies> (was: security/sessions)
<https://paswijzer.waalwijk.nl/reserveringen> (was: reservations)

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/11400401

**Comment by maxvisser** [comment]
I believe scope: small/medium; dependend on if you would include query filters (for ex. https://paswijzer.waalwijk.nl/products?organization_id=18) it could even become big as these are variables defined on the backend.

last time I discussed this one with @dev-rminds I think the conclusion was this would mess with development alot (as for our developers its not really clear anymore which page it is just from the URL); I would suggest a compromis to support both english and dutch routes; only not sure if this is possible.

**Comment by jamalv** [comment]
I don't think filters need to be included, as this is mostly for communication material I expect. So then it would be small?

**Comment by maxvisser** [comment]
Correct. I would suggest discussion it with development team before planning in; As I do not remember clearly why we did not do this already.

**Comment by maxvisser** [comment]
> I don't think filters need to be included, as this is mostly for communication material I expect. So then it would be small?

If everything is dutch and some stuff is still english; I would think people will notice and complain; so I would suggest doing everything at once; if we do 👍

**Comment by maxvisser** [comment]
I thought about it abit more; I would think support English routes would necassary for backwards compatibility (for example people add the site to their bookmarks in Chrome)

**Comment by jamalv** [comment]
Yes, thinking about the use case this is mostly because municipalities wil print the url's on paper flyers and show them in video's for example. And there they want to show dutch urls. If it shows some English filters on visit, that's no big deal IMO.

I agree with @maxvisser that English url's still would also need to be supported for backwards compatibility. So then the user should be able to visit https://paswijzer.waalwijk.nl/providers or https://paswijzer.waalwijk.nl/aanbieders and get the same page.

**Comment by maxvisser** [comment]
I believe this issue is more about maintaince then about initial implementation. if the application uses the english routes, developers use the english routes, we need to really test the dutch routes each acceptance test.

**Comment by jamalv** [comment]
/funds
/funds/{id}

/vouchers
/vouchers/{address}

/providers
/providers/{id}

And fund related? 
/funds/2/activate
/funds/2/request

Any others? Like:
/security/sessions ?
/reservations ?

![image](https://user-images.githubusercontent.com/30194799/155962517-c51d0a8a-db45-42ed-af52-d5e753942ec8.png)


![image](https://user-images.githubusercontent.com/30194799/155962899-54942e46-ecfd-488d-acdd-5d63b56174b7.png)

**Comment by jamalv** [comment]
/funds **Becomes:** fondsen 
/funds/{id}

/vouchers **Becomes:** tegoeden
/vouchers/{address}

/providers **Becomes:**aanbieders
/providers/{id}


**Note from jamal:** I don't think the ones below are needed. Since they will not be directly linked (for example in newsletters or in flyers, @linda-90 what do you think?

Otherwise it would be: 

And fund related?
/funds/2/activate **Becomes:** /fondsen/2/activeer
/funds/2/request **Becomes:** /fondsen/2/aanvraag

Any others? Like:
/security/sessions ? **Becomes:** beveiliging/sessies
/reservations ? **Becomes:** reserveringen

**Comment by jamalv** [comment]
@dev-rminds - I have updated the original issue

**Comment by lexlog** [comment]
refinement - @GerbenBosschieter will close this issue after reviewing PR (and also https://app.zenhub.com/workspace/o/teamforus/forus-frontend/issues/2129 )

**Comment by GerbenBosschieter** [comment]
Issue closed. Released.

https://github.com/teamforus/itsm/issues/751
