### ISSUE TITLE
Sponsor: generic add organisations and products / services

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#88]
## Context
Right now, a sponsor can approve / decline providers from their dashboard. For this, providers have to apply for the appropriate fund first. This issue is about making this flow work the other way around as well. 

## Proposal
Add a page to the dashboard / signup flow, where sponsors can pick which providers / products and services they want to add to the fund.

**This issue needs further refinement and some wireframes**

**Comment by maxvisser** [comment]
I think we could start with inviting existing provider from different funds to your organization.

How I see this change request is a map view around your current location with provider offices which are not connected to your fund.

**Comment by jamalv** [comment]
this issue has been added to product board: https://roadmap.forus.io/c/27-bestaande-aanbieders-toevoegen
