### ISSUE TITLE
Add people to voucher

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#881]
As a **sponsor** I would like to increase the amount of people on a vouchers so that the budget can be increased and it is less confusing for requesters that otherwise would have to get a new voucher.

<p></p>

Figma: <https://www.figma.com/file/aVs4QjOjba8Bw7FxG2QHgr/881-Add-people-to-voucher>

<p></p>

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/11981231

**Comment by jamalv** [comment]
<img width="1085" alt="Screenshot 2022-02-14 at 10 10 28" src="https://user-images.githubusercontent.com/30194799/153844192-7a3b552d-cb4c-4d5b-921f-d766a4f88c04.png">

**Comment by sashooa** [comment]
https://www.figma.com/file/aVs4QjOjba8Bw7FxG2QHgr/?node-id=46%3A7315
