### ISSUE TITLE
Filter by age category

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#883]
As a **requester** I would like to filter by age in the webshop so that I can find products that are in my target audience.

<p></p>

**Criteria:**

- Offers can be categorised into age category

- There's a dropdown filter in the webshop with category

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/6702673

**Comment by jamalv** [comment]
@RobinMeles @GerbenBosschieter I think we already developed this feature, but I can't find it anywhere. Do you know about this?

**Comment by lexlog** [comment]
intake note - still need info about this, do you have any info?
@dev-rminds @GerbenBosschieter @RobinMeles

**Comment by GerbenBosschieter** [comment]
@jamalv we did not develop this. We developed this for funds (EFO). For products we don't have something like this. If we would do this I would suggest to let this be added by the sponsor. This way the category can be managed by the sponsor and prevent pollution of too many categories.

This would need a figma proposal how to handle this in sponsor dashboard

**Comment by jamalv** [comment]
Thx! Looking in product board I see this was requested as part of user-testing result. This makes the priority a 'could-have' right now. Since it needs some time for a proposal, I don't think we have the bandwidth to work on it right now.
