### ISSUE TITLE
Filter by location

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#884]
As a requester, I would like to filter providers by location in the webshop so that I can look for providers that are nearby.

<p></p>

**Technical context:**

When a provider signs up through our platform, the provider is prompted to fill in an address. Based on this address we get a postal code (postcode). When we have a list of postcodes per location/city/municipality we can use this filter accordingly. So for example the postcode 9711 belongs lies in the city Groningen and the postcode 9801 lies in the town Zuidhorn. We could then use these postcodes and assign them to locations which we can show in the filter 'Plaats'.

<p></p>

<p></p>

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/11980612

**Comment by jamalv** [comment]
Related: https://github.com/teamforus/itsm/issues/692

**Comment by jamalv** [comment]
Distance would be easier

**Comment by jamalv** [comment]
Predefined distances: 

<img width="174" alt="Screenshot 2022-02-17 at 10 04 05" src="https://user-images.githubusercontent.com/30194799/154452749-326f4709-7036-4ca8-895d-96ded15d9217.png">

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-backend/pull/1380

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-frontend/pull/2072

**Comment by lexlog** [comment]
intake notes - issue is released, closing
