### ISSUE TITLE
View validations by other employees

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#885]
As a validator I would like to see validation information by other employees so that I know what has been going on if another validator is on a (permanent) leave.

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/9311935

**Comment by jamalv** [comment]
I think some research is needed to figure out how this currently works, and how this should work. Maybe @ateamcms can have a look at how this works now and make a proposal on how to improve this? Possibly with help of @sashooa if designs are needed?

**Comment by jamalv** [comment]
@jamalv will make a separate issue about adding validator supervisor.

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-backend/pull/1388

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-frontend/pull/2086

**Comment by lexlog** [comment]
intake notes - issue is finished and release already

**Comment by lexlog** [comment]
was not in sprint also, added
