### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#886]
As a requester I would like to easily and safely authenticate so that I can create/access my account.

Figma: https://www.figma.com/file/8WwFbq9j2KYccYmwlIiizP/?node-id=0%3A1

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/6714236

**Comment by jamalv** [comment]
Context: this is an existing feature, for which we want to improve the UX.

**Comment by jamalv** [comment]
Figma proposal was updated based on client feedback. Ready for review by @GerbenBosschieter 

https://www.figma.com/file/8WwFbq9j2KYccYmwlIiizP/?node-id=325%3A7306

Still needs:
- Desktop version

**Comment by jamalv** [comment]
Tracking continues in project: https://github.com/teamforus/AUF-2022-Authenticate-And-FundRequest-Userflow/

**Comment by lexlog** [comment]
moved to https://github.com/teamforus/AUF-2022-Authenticate-And-FundRequest-Userflow/issues/8
