### ISSUE TITLE
Webshop menu

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#887]
As a requester I would like to have clear way to navigate the webshop

Figma: https://www.figma.com/file/KVR4NiJY3elZ3Lrq4HgELB/?node-id=0%3A1

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/10591005

**Comment by jamalv** [comment]
The goal is to fix mobile and keep desktop the same (for now) please let us know if this is clear and doable, or if there's any difficulities.

**Comment by jamalv** [comment]
@lexlog please also add scope to the issue

**Comment by lexlog** [comment]
@GerbenBosschieter will write a comment with more details about the issue (especially for logging out status)
and the context of desires of municipalities 

this work shouldn't be done parallel with Authentication (DigiD) issue, decided to do it first

**Comment by lexlog** [comment]
refinement - issues is clear for @aghimpu

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-frontend/pull/2151

**Comment by lexlog** [comment]
refinement note - quite important for review for Valentin ( more than productboard PR)

**Comment by lexlog** [comment]
refinement note - @GerbenBosschieter review

**Comment by lexlog** [comment]
https://github.com/teamforus/forus-frontend/pull/2161

**Comment by lexlog** [comment]
refinement note - also for monday release
