### ISSUE TITLE
Type: Product/service

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#893]
As a provider I want to add a type to my product or service so that it's easier to find for the user.

<p></p>

**Criteria:**

Products / services should be in one list

This should be searchable trough dropdown-search

**Comment by jamalv** [comment]
Link to subfeature: https://forus.productboard.com/feature-board/planning/features/6694849

**Comment by jamalv** [comment]
This is the current situation:

<img width="713" alt="Screenshot 2022-03-28 at 11 15 24" src="https://user-images.githubusercontent.com/30194799/160366576-f78661c4-242d-4c79-af99-dcd4ad891287.png">

Can we combine the 2 lists into one? And allow the user to search using dropdown search?

Question: is 'service' still needed? I remember something about it being a legacy feature. Can we migrate this list into products? And just make it 'catagory' and remove the 'type' selector?

**Comment by jamalv** [comment]
@lexlog could you discuss this during refinement and give an update about the scope?

**Comment by lexlog** [comment]
est-s 6h @dev-rminds

**Comment by lexlog** [comment]
refinement note - @ateamcms clear for current sprint

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-frontend/pull/2154
https://github.com/teamforus/forus-backend/pull/1436
