### ISSUE TITLE
Send fund expiration reminder

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#895]
As a sponsor I would like to send an expiration reminder to people that still have an active voucher when the fund is about to expire so that the amount of people that are too late to spend their voucher is minimised.

<p></p>

**Criteria:**

- Set the target audience
- Set the message body
- Decide when to send it

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/7169241

**Comment by lexlog** [comment]
Intake notes - part of EMC project, should be moved there

approximate estimations:
- 3h for Jamal for Figma proposals
- probably 30h for Alex

scope: covers EMC project fully

**Comment by lexlog** [comment]
Intake notes - part of EMC project, should be moved there

approximate estimations:
- 3h for Jamal for Figma proposals
- probably 30h for Alex

scope: covers EMC project fully

**Comment by lexlog** [comment]
Issue moved to [teamforus/EMC-2022-Nijmegen-Emails-configuration #2](https://github.com/teamforus/EMC-2022-Nijmegen-Emails-configuration/issues/2) via [**ZenHub**](https://www.zenhub.com/)
