### ISSUE TITLE
Reimbursement of invoices

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#905]
![image](https://user-images.githubusercontent.com/30211022/174799245-d4edf13c-ddd1-460e-9dd3-c25d2037af88.png)

**User Stories**

- [ ] As a requester, I want to be able to hand in invoices , so that I receive money for my expense.
- [ ] As a requester, I want to be able to see the invoices that I handed in in my account so that I have a history of things that I submitted
- [ ]  As a requester, I want to be able to see which invoices were paid out to me and when this happened so I have a clear overview of the money I received.
- [ ]  As a requester, I want to be able to see the status of my payment request so that I know what is happening and when I can expect my money.
- [ ]  A a requester I want to know which invoices are eligible to be reimbursed so that I know which things I can upload and which I should not.
- [ ] As a sponsor I want to, be able to process invoices, so that I can send money to the requester.
- [ ] As a sponsor I want to be able to decide if the, money will be paid from a voucher or from the fund itself.
- [ ]  As a sponsor I want to be able to decline invoices when I think people are not submitting the right kind of invoices.
- [ ] As a sponsor I want to inform people if their receipt was approved and will be paid out so that people will know if and when they will receive their money.
- [ ] As a sponsor I want to inform people if their receipt was declined and will not be paid out so that people will know that they are not going to receive their money.
- [ ]  As a sponsor I want to add the reimbursements to the next batch of transactions so that it will be paid out like all the other transactions.
- [ ]  As a sponsor I want to be able to see to which IBAN number I am going to pay out the reimbursement so that I know where the money will go.
- [ ] As a sponsor I want to have a new tab in my account to process these reimbursement so that I have a clear overview.
- [ ] As a sponsor I want to have a  clear overview of which employee paid out the money so that I have a log and can see who initiated the transaction.
- [ ] As a sponsor admin I want to be able to assign this functionality to specific employees (medewerker) (roles and authorisations) so that I can decide who is able to process the invoices.

<p></p>

**Background**

<p></p>

Example: Klippa [https://www.klippa.com/digitaal-declareren/#:~:text=Medewerkers%20kunnen%2024%2F7%20reiskosten,je%20slechts%20in%20drie%20klikken! ](https://www.klippa.com/digitaal-declareren/#:~:text=Medewerkers%20kunnen%2024%2F7%20reiskosten,je%20slechts%20in%20drie%20klikken!)

<p></p>

Notes OCR <https://docs.aws.amazon.com/textract/latest/dg/invoices-receipts.html>

<p></p>

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/13551381

**Comment by maartenfv** [comment]
Link to Figma proposal: https://www.figma.com/file/nPac4T0balinQGEEMjNptn/

**Comment by maartenfv** [comment]
@sashooa Could you please update the Figma proposal so it looks nice again. We need it to have a cover etc. We will work on the proposal later but now just want to have the file ready.

**Comment by maartenfv** [comment]
Worked with @linda-90 to update the Figma file. We added user stories, added the flowchart and made a start with the actual proposal. Later @sashooa will use this proposal to build the new proposal template. This template can be used for all future proposals.
