### ISSUE TITLE
Show fund top-up transaction history

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#908]
Show transaction history because the user can not see it within their system they are unsure when and how much money was added.

![](https://pb-files.s3.amazonaws.com/production/attachments/fb3539730fa8ffae64fcb34c4e6e52b99c45bd33b9ef2d8e0a3ec5093a403603/image.png)

![](https://pb-files.s3.amazonaws.com/production/attachments/66e73caac31e9958906c06a1fc1b05a6c6c74123f5acb0a7295e8af26bc207ba/image.png)

How do we keep track of budget that was added as shown in the screen above?  

Desired situation: Have an overview/list of top-ups which shows atleast: time, date, amount, and code used. (maybe need anything else such as the bank and accountnumber it came from?)  

<p></p>

Currently, there is no way to see the history of top-ups within our system. The sponsor can only see the transfer (top-up) in their own banking system but can not check it on our side.

**Comment by maartenfv** [comment]
Could we maybe add it below this? 
![image](https://user-images.githubusercontent.com/30211022/171595373-d09e6778-20ac-4eff-88d1-3f084a2ac2a0.png)

**Comment by lexlog** [comment]
@dev-rminds we can use a table for information
for table - we need the list of columns to show

we need firstly @sashooa proposal in figma
for @sashooa - ask @maartenfv and @GerbenBosschieter for details

**Comment by maartenfv** [comment]
@sashooa what would you like to know? :)

**Comment by maartenfv** [comment]
The way it currently works is in our knowledge base: https://helpcentrum.forus.io/kb/guide/nl/budget-toevoegen-als-sponsor-OIhD88P127/Steps/1113963?1654687952702&lang=nl Would be nice to have this in English as well but for now we can use google translate in chrome I think.

**Comment by sashooa** [comment]
> @sashooa what would you like to know? :)

I need the exactly information which will be presented on the table :) time, date, amount, code used and etc.

**Comment by sashooa** [comment]
> @sashooa add comment with estimations

@lexlog I didn't made those elements from the screen in new mode, and I don't have them right now so I should make them again from zero, and this will take a little time so... let it be 12-14h

**Comment by lexlog** [comment]
note - for next sprint planning

**Comment by lexlog** [comment]
note - for current sprint for @sashooa

**Comment by maartenfv** [comment]
It needs to be a table with the at least the following columns: fund_id, code, monetary_account_iban, fund_top_up_id, amount, time & date,

**Comment by sashooa** [comment]
The design will appear here: https://www.figma.com/file/T6p9xhf5fSKl8IwRLDGvhb/?node-id=915%3A96296

**Comment by sashooa** [comment]
@lexlog @maartenfv @GerbenBosschieter I think this issue is done

**Comment by lexlog** [comment]
need @GerbenBosschieter and @maartenfv review to finalize result

**Comment by sashooa** [comment]
**Update!** Hope it’s the final version: https://www.figma.com/file/T6p9xhf5fSKl8IwRLDGvhb/?node-id=955%3A52636

**Comment by maartenfv** [comment]
So @GerbenBosschieter @lexlog Please chose what is better the simple one like above, or the one I just suggested. I prefer having one overview of all transactions. Going in and going out.

**Comment by GerbenBosschieter** [comment]
For next time, please asign me if you expect something from me hehe

**Comment by GerbenBosschieter** [comment]
Dont understand what Maarten is proposing because for topups there is no such thing as money going out. So for now I will ignore this proposal and give a go to develop what @sashooa made.

I will ask Maarten about what he meant

**Comment by sashooa** [comment]
> Dont understand what Maarten is proposing because for topups there is no such thing as money going out. So for now I will ignore this proposal and give a go to develop what @sashooa made.
> 
> I will ask Maarten about what he meant

@GerbenBosschieter ohhh yeah!!!)))

**Comment by lexlog** [comment]
refinement note
for Maartens proposal - the problem to do that is that we are not keeping balances of sponsors. so we can't count the current amount of money. 

current figma design - ready and estimated (see above)

**Comment by maartenfv** [comment]
Oke let's go!

**Comment by lexlog** [comment]
issue moved to itsm

**Comment by lexlog** [comment]
delivered in release 0.40.0
