### ISSUE TITLE
Improve the side menu in the user dashboard

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#912]
We need to improve the side menu in the Dashboard. It is becoming filled with to many items and it needs a better structure.

![image](https://user-images.githubusercontent.com/30211022/174073876-52a572bd-2346-4851-88ad-38b8189e811d.png)

**Comment by maartenfv** [comment]
Hi @sashooa could you make a first draft for a proposal and paste the link in this issue?

**Comment by sashooa** [comment]
@maartenfv Yes I can give it to you and your next 2 or 3 days

**Comment by maartenfv** [comment]
@sashooa It just he link the actual design can come later!

**Comment by maartenfv** [comment]
Oke thanks @sashooa I got it! https://www.figma.com/file/bG8kn0xyaPXZVCSijfnzAA/Navigation-Menu-Improvements

**Comment by maartenfv** [comment]
@linda-90 You made a design as well right? to improve the menu? Could you give the link as well?

**Comment by sashooa** [comment]
Link to the Figma file: https://www.figma.com/file/bG8kn0xyaPXZVCSijfnzAA/Improve-the-side-menu-in-the-user-dashboard-912

**Comment by sashooa** [comment]
I think we have to close the issue, because we have this one https://github.com/teamforus/general/issues/909 - here is the same subject but is much global.
