### ISSUE TITLE
Open payments to the requester IBAN

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#914]
## **Userstory**  

- As a requester
- I want to receive money strictly in my bank account after I applied for a fund such as IIT
- So that I will get what was appointed

<p></p>

## How it should work 

The engine of payments should consist of two modules - decision and calculation modules

**The decision module** - based on requirements for citizen
Examples of requirements:  
- You have not received an Individual Income Allowance in the past 12 months
- You live in Nijmegen
- You are 21 years or older, but not yet retired. If you have a partner and one of you receives a pension (AOW), neither of you is entitled to the Individual Income Allowance. 
More - <https://www.nijmegen.nl/diensten/uitkering-schulden-laag-inkomen/individuele-inkomenstoeslag/>

<p></p>

**The calculation module** - calculates how much money to send, based on info from citizen.

Userstory for that - As a sponsor, I want that amount of payment will be based on the submitted information during the application process, so that I will get what i should.

<p></p>

## Side info:

<p></p>

Example of IIT  
<https://www.nijmegen.nl/diensten/uitkering-schulden-laag-inkomen/individuele-inkomenstoeslag/>

**Comment by lexlog** [comment]
Issue moved to [teamforus/OPA-2022-Open-payments #1](https://github.com/teamforus/OPA-2022-Open-payments/issues/1) via [**ZenHub**](https://www.zenhub.com/)
