### ISSUE TITLE
Confirmation for a fund application if already logged in by DigiD

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#915]
## **User story**

<p></p>

- **As** a requester

- **When** applying for a fund I don't want to confirm my DigiD connection again if I'm logged in 

- **So** that applying process will be faster and easier for me.

## **Description**

Part of quotation Nijmegen

**Comment by maartenfv** [comment]
@lexlog Can we clarify this issue?

**Comment by GerbenBosschieter** [comment]
Duplicate: https://github.com/teamforus/itsm/issues/707

Conclussion: Is already possible, but not "sexy" enough and configured. If someone logged in with DigiD and they apply for fund they are able to "skip" this step. But "skipping" this step is the "not sexy" part

**Comment by maartenfv** [comment]
![image](https://user-images.githubusercontent.com/30211022/175949560-93802a13-f60e-4c5f-8797-65a3f0cf3956.png)

**Comment by GerbenBosschieter** [comment]
- [ ] @sashooa needs context to make good UX for this one

**Comment by sashooa** [comment]
**Just for information:** Link to the Figma file: https://www.figma.com/file/KYcnedvXo9CA4OBNSWLw94/Confirmation-for-a-fund-application-%7C-%23915?node-id=36%3A4

**Comment by lexlog** [comment]
@lexlog decide whom @sashooa can ask about this issue

**Comment by lexlog** [comment]
not for refinement today to discuss with sasha
