### ISSUE TITLE
Custom banner on webshop pages to be configured using CMS

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#924]
The CMS has a content element for notifications / announcements / malfunctions which can be easily placed on different pages at the top if necessary.

<p></p>

When something goes wrong they want to be able to add a notification on the pages.

<p></p>

Examples:

![](https://pb-files.s3.amazonaws.com/production/attachments/1d2571ee61d581b0ada4aa9aff7abdbc588d9e1ef19d1dd108a3971aad613b78/image.png)

<p></p>

![](https://pb-files.s3.amazonaws.com/production/attachments/47b67cc290feb1abb840ef0327ac9ae485816fe749e2bfe1370245f8e3b89dd0/image.png)

![](https://pb-files.s3.amazonaws.com/production/attachments/317376632b7a4ecd8239b7e05d747c1754f8a4ba98f96aca6a9cc6cce2ca495b/image.png)

<p></p>

<p></p>

**Comment by jamalv** [comment]
Link to feature: https://forus.productboard.com/feature-board/planning/features/13923416

**Comment by maartenfv** [comment]
@sashooa Do you have a figma file/proposal for this? Could you add the link?

**Comment by GerbenBosschieter** [comment]
Related issue is this one: https://github.com/teamforus/itsm/issues/824 so we already developed a foundation for this.

Tasks to get it to next status:
- [ ] Use the page for system notifications (its called /implementation-notifications) where the user can add a announcement. The design of the option to add announcement should be a bit different than the list we currently have. It needs to "pop out". (see image)
- [ ] The following things should be editable by the sponsor. I've based this on what is already build

  $table->enum('type', ['warning', 'danger', 'success', 'primary', 'default'])->default('danger') -> should be included
  $table->string('title', 2000) -> should be included
  $table->text('description')->nullable(); - >should be included
  $table->dateTime('expire_at')->nullable(); -> should be included
  $table->enum('scope', ['provider', 'webshop'])->default('sponsor');; -> should be included
  $table->boolean('active')->default(true); -> should be included

**Comment by sashooa** [comment]
**Just for information:** Link to the Figma file: https://www.figma.com/file/VPDqNnRnOPESQ6DnheMA8G/Custom-banner-on-webshop-pages-to-be-configured-using-CMS-%7C-924?node-id=36%3A4

**Comment by lexlog** [comment]
we need design for a webshop

we need a design for dashboard - design not needed 
frontend feature needed to be branched from CMS block feature

backend part will be nice to start soon
