### ISSUE TITLE
Estimation request | Add start date for products

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#930]
## Question
Currently you can set the end date of a product, but there is no functionality for adding a start date. This is desirable because you can already create products that are valid in a certain period in advance and will be visible on the webshop on this date.

https://forus.productboard.com/insights/notes/all-notes/notes/15569195

## Goal
Add start date for products

![Schermafbeelding 2022-08-24 om 09 54 28](https://user-images.githubusercontent.com/36952230/186363207-ea090623-68af-4f94-8598-bdcc5d66757a.png)

## Ideas

1. Add the 'Start date' field in the provider dashboard. Make the product visible on the webshop (after sponsor approval) on the start date.

2. Add the 'Start date' field in the provider dashboard. Make the product after sponsor approval visible on the webshop, but without the option to click on the product or with the announcement that the offer is available from date X. In this way the citizen can see which products will become available and may then be able to save budget to purchase this products.

**Comment by lexlog** [comment]
**refinement note**

need some research to know what it will impact
rought est. - up to 3 days

**Comment by EmielForus** [comment]
Issue moved to [teamforus/EDE-2022-Implementatie-Meedoenregeling #51](https://github.com/teamforus/EDE-2022-Implementatie-Meedoenregeling/issues/51) via [**Zenhub**](https://www.zenhub.com/)
