### ISSUE TITLE
CMS update: Give option to choose for image or extra text block.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#933]
# Description

We currently have the option to add textual content to certain pages (see image 1). And we also have the option to add blocks to the homepage (see image 2).

**Image 1**
<img width="1557" alt="image1" src="https://user-images.githubusercontent.com/38419514/187655752-2e206348-e07b-47d7-9be1-4943f5859185.png">

**Image 2**
<img width="1555" alt="image2" src="https://user-images.githubusercontent.com/38419514/187655808-21ff4526-cff7-4f55-9b24-d6c699bd4e07.png">

But both options do not exactly give the solution I am looking for. Visually it would be nice if we can choose to add text or an image (or whatever should be the solution) This way we can add two blocks of information instead of one 100% width block with text or two blocks where one block has to have an image.

Desires solution (see image 3)
**image 3**
<img width="1613" alt="image3" src="https://user-images.githubusercontent.com/38419514/187655720-7fdda336-2471-4862-94fe-ce621ea1f953.png">

**Comment by lexlog** [comment]
refinement note:
not clear how to scale, for @GerbenBosschieter to decide what to do next with this issue

**Comment by GerbenBosschieter** [comment]
Too big, if we want to do this properly we need to refactor cms. Until then will do some custom html/cms things :( closed
