### ISSUE TITLE
Estimation request | View provider text in sponsor dashboard

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#935]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
Currently there is no option to check the provider information text in the sponsor dashboard when you approve a provider.
It is necessary to show this text as part of the sponsor's policy and misspellings.

## Desired situation
The provider information text is visible with the provider information in the sponsor dashboard.
<img width="827" alt="Schermafbeelding 2022-10-27 om 15 38 51" src="https://user-images.githubusercontent.com/36952230/198300745-8d024cde-1d40-4f6f-a0ba-729ea2a445bf.png">

## Plan
- [ ] Add information text provider
- [ ] if possible: option to adjust text or make change request.

**Comment by EmielForus** [comment]
Issue moved to [teamforus/DevOps #98](https://github.com/teamforus/DevOps/issues/98) via [**Zenhub**](https://www.zenhub.com/)
