### ISSUE TITLE
Estimation request | Add titles (headings) to FAQ list in CMS

### ISSUE THREAD

**Issue by linda-90** [teamforus/general#937]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [ ] Design
- [x] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
It is not possible to add headings in the FAQ list. This makes it a long list with questions and you can't quickly find the question you are looking for (divided by topic/category for example).

## Desired situation
Make it possible to divide questions by topic. Being able to add a title between the questions in the CMS.

## Plan
- [ ] Add titles (headings) to FAQ list in CMS

**Comment by EmielForus** [comment]
Issue moved to [teamforus/DevOps #99](https://github.com/teamforus/DevOps/issues/99) via [**Zenhub**](https://www.zenhub.com/)
