### ISSUE TITLE
Toesturen of Toekennen is unclear need more information and better UX.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#99]
@maartenfv commented on [Mon Dec 02 2019](https://github.com/teamforus/development/issues/229)

In the pop-up as in the image below more info needs to be added about how to use this feature. The problem is that it is unclear what Toekennen and versturen means. 

![image](https://user-images.githubusercontent.com/30211022/69960602-2605ec00-150a-11ea-99c5-99d4c7e3f64f.png)

All three options need to be presented in the same way.

- Print
- Toekennen
- Versturen

All with a short description and presented with a similar layout the prevent confusion.

---

@maxvisser commented on [Tue Dec 03 2019](https://github.com/teamforus/development/issues/229#issuecomment-561052329)

Yes good issue; we also found this UX weird. As 'toekennen' is permanent; it needs explicit user consent.
a different option could be to add a checkbox behind e-mail field.

**Comment by jamalv** [comment]
just checked, this was overhauled - so I don't think this is relevant anymore
